### ISSUE TITLE
When trying to view clips in firefox, firefox reports typeerror: network error when attempting to fetch resource

### ISSUE THREAD

**Issue by rhatguy** [dermotduffy/frigate-hass-card#10]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
0.14

**Last working release (if known):**
First attempt to use the card

**Browser and Operating System:**
Firefox 91.0.1 on Windows 10

**Description of problem:**
My card is configured as shown below. When I click the clips icon in lovelace firefox replaces the video with a grey box with a small black exclamation point in the middle.  When I hover over the exclamation point it says "TypeError: NetworkError when attempting to fetch resource."  If I click on the "View Frigate UI" button it opens a new tab in firefox and successfully connects to frigate as it .should.  I am able to ping 10.1.1.52 (my frigate server) successfully from within the terminal on hass.io/
type: custom:frigate-card
frigate_url: http://10.1.1.52:5000
webrtc: {}
camera_entity: camera.front_door_cam
motion_entity: binary_sensor.front_door_cam_person_motion
view_default: live
menu_mode: below
autoplay_clip: false

**Javascript errors shown in the web inspector (if applicable):**
I have 2  reported in my browser console.  Not sure if it is related:
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Thanks for the report @rhatguy . Two questions:
* Are you accessing HA itself over http or https?
* What happens when you try a different browser, do you get the same issue?

**Comment by rhatguy** [comment]
I'm accessing HA over https locally through my lan.
Accessing with different browsers gives the same behavior but with a slightly different message.  Edge and Chrome both say "TypeError: Failed to fetch".

Interestingly when I tail the nginx log on my frigate machine (which runs on a separate RPi 4) I see home assistant connecting to it for various other things (mostly grabbing /api/stats to update other lovelace cards), but when I load up this card, I don't see any connections to frigates nginx instance.  For some reason its not connecting to frigate at all.

**Comment by rhatguy** [comment]
Just found a new issue in my console.  (Sorry not adept at the right place to look for these javascript errors).  

Blocked loading mixed active content “http://10.1.1.52:5000/api/events?camera=front_door_cam&has_clip=1&limit=100”

**Comment by dermotduffy** [comment]
Since you're accessing HA over http**s** and pointing the card at Frigate over http (no 's'), the browser likely won't allow you to access mixed content. Give the browser a http*s* means of reaching Frigate. If you have Home Assistant behind a reverse proxy (and that's how you're getting ssl), you'd just need to configure Frigate in a similar way (this is my own setup).

**Comment by rhatguy** [comment]
Understood. I have a nginx proxy setup for other stuff internally but haven't moved hass.io behind it yet.  I'll give a go at getting both HA and frigate on either http or https and see if that fixes things.  Thanks!

**Comment by dermotduffy** [comment]
Rather than unhelpfully render just an icon, [from the next release] the card will show the error message in the card and link to the troubleshooting documentation, which now includes the specific issue that went wrong for you.

Good luck with the setup! Please re-open a new issue if the solution you're working on does not resolve it (pretty optimistic it will!).

**Comment by rhatguy** [comment]
Just waned to confirm that I got my setup working after getting frigate accessible through https.  Thanks for your help.  The addon looks great!
