### ISSUE TITLE
No Clips, No snapshots

### ISSUE THREAD

**Issue by boehser-enkel** [dermotduffy/frigate-hass-card#100]
The card shows "no clips" & "no snapshots"
All newest version and different browser. Can view clips and snapshots via frigate and media browser but not via this card

greetz
boehser enkel

**Comment by dermotduffy** [comment]
Thanks for the issue filling! I'll need much more information to help you though (the new issue template tries to get that information).

Which version specifically? (You say latest, but release or pre-release, please just include the exact version number).

Which version number of home assistant?

Please include your card config.

To start with please review similar issues such as 
https://github.com/dermotduffy/frigate-hass-card/issues/87 to see if the advice given there help you.

**Comment by boehser-enkel** [comment]
I'm sorry. I thought newest would be clear (non beta)
frigate_camera_name did the trick
