### ISSUE TITLE
Video recordings playing from snapshot menu rather than video clips and playing from incorrect timeline

### ISSUE THREAD

**Issue by limitless-code** [dermotduffy/frigate-hass-card#1009]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
4.0.0
**Last working release (if known):**
not known
**Browser and Operating System:**
home assistant companion app and firefox 111.0 (64 bit) pop OS

**Description of problem:**
Video clips playing from incorrect timeline from snapshots via snapshot menu? (snapshot  taken @ 11:15am but when clicking on the snapshot to play the video, it plays a clip from 8:50am the same day 15/03/2023). seems to be random as to which video clip it picks.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Maybe something awry with the back-end maybe?

**Comment by limitless-code** [comment]
Thank you for replying. 

I have uploaded a video hopefully it gives the gist of the problem. It seems the video it chooses to play when i click a snapshot changes depending on if there are newer "video associated" snapshots since the last one that played. The clip that is played is always the same clip no matter which snapshot i choose. Only person object snapshots are played within a certain zone called "main drive" which is correct , the rest of the snapshots are of car objects  or person objects outside of this zone and do not have a video associated, this is also correct.

Unfortunately due to privacy I have had to mask out most of the video hopefully this is acceptable in order to troubleshoot this problem

In the video i go to the menu > snapshot , chose a snapshot at ~11:16, snapshot chosen is correct at 11:16:25 but when I click this image video that starts is from ~10:31. if another clip is added the video that plays is the a different clip, but again the same clip will play no matter which snapshot I choose in the timeline of that day.

I hope this makes some sense. It's almost like an indexing problem? And perhaps only pertinent to my frigate install on HASSIO as an add on?

https://user-images.githubusercontent.com/49276185/225390788-8d12fa58-abb1-4634-b9f3-f9f9925c9949.mp4

**Comment by limitless-code** [comment]
the bit where I say it plays the same clip no matter which snapshot i chose is not strictly true it seems to be be hit or miss. Sometimes 

1. the same clip on some snapshots but wrong clip for the time.
2. the correct clip initially for the snapshot but for subsequent different snapshots in the timeline it plays the same clip.
3. it plays the correct clip for a snapshot and subsequent snapshots but after a few snapshots it does either 1. or 2. above

**Comment by limitless-code** [comment]
In the HASSIO frigate addon under events i can see the snapshot and corresponding video clip.

I can browse to this snapshot and the corresponding video clip and both are correct.

1.  https://hassio.localdomain:8123/api/hassio_ingress/ziQWjtQhpRzzLLrQqSJhi4QjVZhWkU4PLinL_ViZ9fc//api/events/1678801852.863592-335txy/snapshot.jpg
2. https://hassio.localdomain:8123/api/hassio_ingress/ziQWjtQhpRzzLLrQqSJhi4QjVZhWkU4PLinL_ViZ9fc//api/events/1678801852.863592-335txy/clip.mp4

where as in the frigate card when i click on the snapshot that displays as above:

https://hassio.localdomain:8123/api/hassio_ingress/ziQWjtQhpRzzLLrQqSJhi4QjVZhWkU4PLinL_ViZ9fc//api/events/1678801852.863592-335txy/snapshot.jpg

but it plays a different clip and not 

 https://hassio.localdomain:8123/api/hassio_ingress/ziQWjtQhpRzzLLrQqSJhi4QjVZhWkU4PLinL_ViZ9fc//api/events/1678801852.863592-335txy/clip.mp4

so the backend seems ok?

**Comment by felipecrs** [comment]
The first thing that triggers my attention is why `hassio_ingress` is being used... in my understanding, the URL should actually be pointing to the integration proxy. /cc @dermotduffy

**Comment by dermotduffy** [comment]
> The first thing that triggers my attention is why hassio_ingress is being used... in my understanding, the URL should actually be pointing to the integration proxy, right @dermotduffy?

I think that's just the URL they are manually using to view the clips in the addon, rather than suggesting the card is using that URL. The card definitely should not be using that URL.

More generally, in the "old" (v4) codebase the code has a heuristic that attempts to match a snapshot, with the clip it should play with that snapshot is clicked. [The code](https://github.com/dermotduffy/frigate-hass-card/blob/main/src/components/viewer.ts#L388). This is because all media comes from the HA media browser, so the card cannot know which clip is related to which snapshot, so it tries to "guess". Perhaps this guessing is going wrong here for some reason.

In the new code (v4.1 -- not yet released), this is entirely gone, since the events stream directly from Frigate (via the integration), and we know exactly the clip that is related to each snapshot.

@limitless-code If you are comfortable doing so, one thing you could do is build your own version of the card from the `v4.1.0` branch and see if you will still have the issue, or just use the [Javascript from the last github build](https://github.com/dermotduffy/frigate-hass-card/actions/runs/4412418200).

**Comment by limitless-code** [comment]
@dermotduffy You are correct those are URLs I am using to view the snapshot and corresponding clip manually  to check that it's not the back end.

this is what i see as a request  when i select a snapshot in the frigate card. 

https://hassio.localdomain:8123/api/frigate/frigate/snapshot/1678801852.863592-335txy?authSig=<redacted string>

I will give v4.10 a try and let you know how I get on.

**Comment by limitless-code** [comment]
@dermotduffy I tried the following JS but still get similar symptoms.
[frigate-hass-card.zip](https://github.com/dermotduffy/frigate-hass-card/files/10985185/frigate-hass-card.zip)

**Comment by dermotduffy** [comment]
@limitless-code That's still the old v4.0.0 codebase, you need the code from the `v4.1.0` branch. The simplest way to tell is that the end result will build to multiple Javascript files, not a single file.

[Here's the direct link to the build output from the v4.1.0 branch](https://github.com/dermotduffy/frigate-hass-card/suites/11541659310/artifacts/597284880).

**Comment by limitless-code** [comment]
@dermotduffy I have downloaded and put file in the following path. 

![frigate-hass-card](https://user-images.githubusercontent.com/49276185/225548386-fc612746-4d42-45ac-a1c5-8dbaa68d07b9.png)

restarted HASSIO and cleared my browser cache. but getting the following error in HASSIO log:

`140450673869776] Error handling message: extra keys not allowed @ data['cameras']. Got [] (invalid_format) Owner from <ip redacted> (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0)

```
Failed to receive response from Home Assistant for request.[ Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).

adding card shows the following:

{
  "request": {
    "type": "frigate/events/get",
    "instance_id": "frigate",
    "cameras": [],
    "limit": 50,
    "id": 93
  },
  "response": {
    "code": "invalid_format",
    "message": "extra keys not allowed @ data['cameras']. Got []"
  }
}
```

**Comment by dermotduffy** [comment]
**The good news**: You got the new card codebase working!
**The bad news**: You're on an older version of Frigate itself.

I understand if you don't want to go further down the rabbithole here, but you'd need to upgrade:

 * Your Frigate integration to the latest beta: https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-beta4
 * Your Frigate backend to the latest beta: https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0-beta9

(There's lots of new goodies anyway, so it might be worth it!)

**Comment by limitless-code** [comment]
**The good news:** I have a new backend and front and the integration is working. And I so far have not needed to change my frigate.yaml.

**The bad new:** I still have the same random problem with the snapshot gallery.

**but there's more good-ish news:** I found that if I use the 'Main Drive' filter in the snapshot gallery view i get consistent **correct** results. 

However. the `default snapshot view` (filter) has a problem where it will play the same clip and then other clips in seamless succession, i.e it will play a clip from 13:39 and the clip will last 6 min 20sec and end with a clip at 15:39 and will keep playing this with the 3 other different snapshot i chose in this view.

If I chose `person view` (filter), it will play random clips, there's no appending of clips (if that is what it is doing in the `default snapshot view`?)

`Main Drive` view works perfectly so far. not sure if this worked in the old version, never used this filter.

The other date filters under ' This Month' and other date filters do not show the full list of videos it should.

The only option that works is `Main Drive` including when clicking on the date filter `This month` etc. Person or no filter (default snapshot view) have the above issues.

![frigate-filters](https://user-images.githubusercontent.com/49276185/225704756-84f8f9d2-80b6-49ad-a64c-29001b845b82.png)

**Comment by dermotduffy** [comment]
Whilst I still have no clue why you're seeing this, lets make sure you're on the right codebase first. That screenshot is definitely from the *old* card codebase -- that "folder" type view is gone entirely from the `v4.1.0` codebase.

Is it possible you did not correctly install the card, or that it's being cached? (Try in an incognito window).

**Comment by limitless-code** [comment]
@dermotduffy Thank you for your replies. Yes you are correct, I had copied the 2 old frigate-hass-card.js(.gz) temporarily and completely forgot. Working well now after deleting those 2 files, placing the new `4.1.0` frigate-hass-card.js in the folder and clearing the cache.

It is showing the correct `tooltip` date and time of the clip and plays the corresponding clip correctly. Some of the thumbnails (not many) shows an incorrect corresponding  snapshot I don't think it's the cache but I'll double check that.

**Comment by limitless-code** [comment]
> It is showing the correct `tooltip` date and time of the clip and plays the corresponding clip correctly. Some of the thumbnails (not many) shows an incorrect corresponding snapshot I don't think it's the cache but I'll double check that.

After checking this again. the frigate card is fine. Snapshots that "look wrong" in `4.1.0` are "I think" because these video clips are ones that were potentially stuck `in progress`. So the snapshot corresponds to the last clip where it has appended numerous clips to the first clip in the same event, so the `tool tip` date and time is from the time it started to record but the snapshot is from the last clip within the same event. This is all pulling correctly from `Frigate` as I have checked in `events` and  see the same behaviour.

Thank you for helping me resolve this issue it is much appreciated. I really like the evolution of `Frigate` and the `frigate-hass-card`. :+1:

**Comment by dermotduffy** [comment]
> Thank you for helping me resolve this issue it is much appreciated. 

Thank goodness for that, was afraid it might all have been a wild goose chase. Enjoy!
