### ISSUE TITLE
Release beta of the `v5.0.0` codebase

### ISSUE THREAD

**Issue by Delta1977** [dermotduffy/frigate-hass-card#1021]
Hi can you publish a alpha or betarelease for v4.1 so we can test is as beta in hacs ?

I thank you.

**Comment by dermotduffy** [comment]
Once the [issues for v4.1.0 are resolved](https://github.com/dermotduffy/frigate-hass-card/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.1) I will publish a beta release.

**Comment by dermotduffy** [comment]
Since there are very significant underlying changes, I am going to number the new release `v5.0.0`. Expect the release will be imminent.

**Comment by dermotduffy** [comment]
@felipecrs If you have time, and the inclination, the [pt-BR data](https://github.com/dermotduffy/frigate-hass-card/blob/release-5.0.0/src/localize/languages/pt-BR.json) on the `v5.0.0` branch would benefit from a refresh to include new/changed strings for the new features.

@elax46 If you have time, and the inclination, the [it data](https://github.com/dermotduffy/frigate-hass-card/blob/release-5.0.0/src/localize/languages/it.json) on the `v5.0.0` branch would benefit from a refresh to include new/changed strings for the new features.

Thank you in advance if you have the time, and no worries if not (it falls back to English translations).

**Comment by dermotduffy** [comment]
[v5.0.0-beta.1](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v5.0.0-beta.1) is now released.
