### ISSUE TITLE
JSMPEG rendering may not work with Frigate release 0.9.1

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#103]
As reported by @alexdelprete in https://github.com/dermotduffy/frigate-hass-card/issues/92 .

**Comment by Backslashh** [comment]
> @dermotduffy
> 
> No errors in the console but my HA server logs are full of invalid login attempts. These stop after I switch from `frigate-jsmpeg` back to `frigate` and happen on both Chrome and Safari
> 
> ```
> 2021-10-07 14:16:53 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from mbp2015.localdomain (192.168.4.197). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15)
> 2021-10-07 14:16:57 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from mbp2015.localdomain (192.168.4.197). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36)
> 2021-10-07 14:16:58 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from mbp2015.localdomain (192.168.4.197). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15)
> 2021-10-07 14:17:03 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from mbp2015.localdomain (192.168.4.197). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15)
> 2021-10-07 14:17:04 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from mbp2015.localdomain (192.168.4.197). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36)
> 2021-10-07 14:17:08 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from mbp2015.localdomain (192.168.4.197). (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15)
> ```


I have this same issue. HA logs full of auth issues when using `frigate-jsmpeg`

**Comment by dermotduffy** [comment]
I don't think there is much easy improvement likely here because of how JSMPEG works, combined with the requirement for Home Assistant to sign the request, and to proxy the traffic through to the backend. 

Maybe some kind of 'continual streaming' option is possible (i.e. stream all the time -- wasting network bandwidth but cutting  render lag), but I'm not sure it's worth it. I'll explore improvements on  #106 .
