### ISSUE TITLE
Ability to use other go2rtc instance then frigate building

### ISSUE THREAD

**Issue by Delta1977** [dermotduffy/frigate-hass-card#1035]
At the moment I can use only the frigate  building go2rtc in Hass-Card 4.1. 
frigate support external go2rtc as source. 

For example: I use Alexit go2rtc addon in Hass and configure it as Source it works fine for frigate. 
Then I select go2rtc as liveprovider in card it can't connect to frigate because ports are closed. 

It would be perfect if I can overwrite the go2rtc source in card and point it to go2rtc addon from Alex.

**Comment by felipecrs** [comment]
Just to mention you can use webrtc_card as live provider which allows you to use different go2rtc's.

**Comment by Delta1977** [comment]
You are right, but I want to get rid from webrtc card because it has an building go2rtc 😃. That is then the third go2rtc instance.

**Comment by dermotduffy** [comment]
Can you give me an example of what this would look like in the configuration?

**Comment by felipecrs** [comment]
> it has an building go2rtc 😃. That is then the third go2rtc instance.

Only if you want. During the installation of the WebRTC integration, it gives you the choice of starting or not its own go2rtc binary.

**Comment by Delta1977** [comment]
> > it has an building go2rtc 😃. That is then the third go2rtc instance.
> 
> 
> 
> Only if you want. During the installation of the WebRTC integration, it gives you the choice of starting or not its own go2rtc binary.

 Ah, ok. I didn't know it.

**Comment by dermotduffy** [comment]
@Delta1977 I want to make sure I understand -- success here would be that you can configure the card to talk to a different endpoint for a different go2rtc, is that right? i.e. something like this is what you want:

```yaml
cameras:
  - camera_entity: camera.office
    live_provider: go2rtc
    go2rtc:
      endpoint: <URL GOES HERE>
```

Is that right?

One issue is that the integration only proxies to the go2rtc that is running on the Frigate backend. I don't think it's tenable/advisable to have the integration proxy arbitrary endpoints. So I think we'd have to do it without the proxying, which means we'll probably run into mixed content warnings or access problems unless the user knows what they're doing. Example: if their HA instance is behind `https`, they would have to also put the go2rtc instance behind a `https` reverse proxy, and remote access (off local network) would not work unless they've specifically configured that go2rtc instance to be accessible externally).

**Comment by Delta1977** [comment]
> @Delta1977 I want to make sure I understand -- success here would be that you can configure the card to talk to a different endpoint for a different go2rtc, is that right? i.e. something like this is what you want:
> 
> ```yaml
> cameras:
>   - camera_entity: camera.office
>     live_provider: go2rtc
>     go2rtc:
>       endpoint: <URL GOES HERE>
> ```
> 
> Is that right?
> 
> One issue is that the integration only proxies to the go2rtc that is running on the Frigate backend. I don't think it's tenable/advisable to have the integration proxy arbitrary endpoints. So I think we'd have to do it without the proxying, which means we'll probably run into mixed content warnings or access problems unless the user knows what they're doing. Example: if their HA instance is behind `https`, they would have to also put the go2rtc instance behind a `https` reverse proxy, and remote access (off local network) would not work unless they've specifically configured that go2rtc instance to be accessible externally).

Yes you are right.

I think the card didnt need to proxy as the go2rtc instance run on the same host. The card should  connect to the "Alexit-go2rtc addon" Slug instead to rthe frigate-Container-Slug

**Comment by felipecrs** [comment]
The difference is that Frigate has the Frigate integration which proxies the access to the Frigate container through Home Assistant (which is accessible through the front-end).

Add-ons can't be accessed directly through the front-end.

**Comment by Delta1977** [comment]
great explained.  now i understand the difference.  Thanks very much.
