### ISSUE TITLE
Add support for a custom_url parameter

### ISSUE THREAD

**Issue by mcsquared88** [dermotduffy/frigate-hass-card#105]
This custom card has been fantastic. But the 0.9.x release of Frigate released 2 days ago broke the ability to view clips using this card. I figured an easy work-around would be to edit the frigate_url parameter in the card to point directly to the Events page in the Frigate webUI for each of my cameras. That way, when I want to view clips, instead of clicking on the clips icon in the menu, I'd just click on the Frigate icon. Yes, it would open in a new browser window, but that's OK.

Unfortunately, this idea didn't work. The Frigate URL for the event page for a specific camera is something like http://frigate_server:5000/events?camera=camera_name. I entered that as the frigate_url in the card configuration, but then realized that the card is appending "cameras/camera_name" to the URL provided in the configuration, which doesn't resolve to the correct page.

I've thought of two ways to address this:

1. Stop appending "cameras/camera_name" to the URL provided by the user.
2. Add support for a custom_url parameter in the card configuration. If specified, a new icon will appear in the menu bar that links to the custom URL without anything being appended to the URL.

I'm not sure what else besides the link in the menu bar the frigate_url is used for. If nothing, then the first option might be best. But if it is, or you don't want to change how things are currently working, the second option would be better.

**Comment by dermotduffy** [comment]
Need more information to debug, closing for now. I can only say that clips should work just fine with 0.9.1+ (and do for me). Please re-open if that's not the case for you and/or you'd like help to debug it together.
