### ISSUE TITLE
Create a zip containing all JS files on release

### ISSUE THREAD

**Issue by BBaoVanC** [dermotduffy/frigate-hass-card#1056]
**Is your feature request related to a problem? Please describe.**

On the latest v5.0.0-beta.1, there's like 20 files to download instead of it being bundled now. This is fine, but it's really annoying to download because I have to go copy every single link and paste it into a wget command.

**Describe the solution you'd like**

Put all the JS files into a single zip file that I can download and unzip on server easily.

**Additional context**

For reference, I got all the URLs this time by adding a `id="blah"` to the release artifact list in the developer console and running this:

```js
Array.from(document.querySelectorAll("#blah a")).map(a => a.href)
```

**Comment by dermotduffy** [comment]
> On the latest v5.0.0-beta.1, there's like 20 files to download instead of it being bundled now. This is fine, but it's really annoying to download because I have to go copy every single link and paste it into a wget command.

Thanks for the idea. Presumably there is a reason you're not using HACS to manage the release?

**Comment by felipecrs** [comment]
And by the way, since you are not using HACS to install it, you can get the zip from the GitHub Actions artifacts:

https://github.com/dermotduffy/frigate-hass-card/tree/release-5.0.0#advanced-users-installing-unreleased-versions

https://github.com/dermotduffy/frigate-hass-card/tree/v5.0.0-beta.1

**Comment by BBaoVanC** [comment]
> Thanks for the idea. Presumably there is a reason you're not using HACS to manage the release?

HACS seems to be too much for my pi, it makes home assistant take 10+ minutes to start up for some reason, so I ended up having to just install stuff manually

**Comment by dermotduffy** [comment]
The next release will have a ZIP.

**Comment by BBaoVanC** [comment]
There wasn't a zip in v5.0.0-beta.2, was that a mistake or is it only going to happen at the full release of v5.0.0?

**Comment by dermotduffy** [comment]
There is a zip in it. https://github.com/dermotduffy/frigate-hass-card/releases/download/v5.0.0-beta.2/frigate-hass-card.zip
