### ISSUE TITLE
Custom (camera) switches

### ISSUE THREAD

**Issue by PovilasID** [dermotduffy/frigate-hass-card#1057]
**Is your feature request related to a problem? Please describe.**
I have cameras that have integrated floodlights that have HA integration and has switch. 
There are also cams that support ONVIF for switching IR/moving etc. Speakers that can double as sirens etc.

**Describe the solution you'd like**
Adding a an option for adding custom '(camera) buttons'. Users would have to reference some switch for example: flood lights/siren toggle; camera move to left/right by 5deg etc.
Custom buttons could be appended to an existing menu or could be put in a secondary one. 
Global things like turning on an alarm would make more sense over every cam and things like motion/light control for individual camera would make more sense as a secondary menu that is in a different location to primary. 
However, I will take any ability to add custom switch no matter the location.

**Describe alternatives you've considered**
Frigate has ONVIF support planned out but it does not cover over devices that HA has already integrated integrated and that would be wildly out of scope for frigate.

**Additional context**
Frigate and HA enables notifications as soon as something is still happening, so you can do something to prevent/reduce damage those are dependent on 3rd party tools and you do not have the time to navigate to a different to lock the door.

**Comment by felipecrs** [comment]
This is totally possible already.

https://github.com/dermotduffy/frigate-hass-card#:~:text=This%20example%20shows%20submenus%20conditional%20on%20the%20camera%20selected.

**Comment by PovilasID** [comment]
> This is totally possible already.
> 
> https://github.com/dermotduffy/frigate-hass-card#:~:text=This%20example%20shows%20submenus%20conditional%20on%20the%20camera%20selected.

Awesome!
You will rightfully not going to believe me but I was coming back to close it after finding in documentation.
Still need to figure out where does that YAML conf go... but I think I will manage :)
