### ISSUE TITLE
Clicking recordings in the "background" of the timeline does not play them

### ISSUE THREAD

**Issue by jbms** [dermotduffy/frigate-hass-card#1073]
I've been very much enjoying the timeline scrubbing feature --- thanks very much!

As noted in https://github.com/dermotduffy/frigate-hass-card/issues/1055#issue-1651075641 it would be great if clicking on a spot in the timeline without an event would play recordings if they are available.

Currently I'm not aware of any way to access recordings from the timeline view.

**Comment by dermotduffy** [comment]
Actually, what you describe is already implemented! However, I confirm it does not seem to work in the `v5.0.0-beta.1` so let me look into it ...
