### ISSUE TITLE
Linking to a specific view/event/time

### ISSUE THREAD

**Issue by jbms** [dermotduffy/frigate-hass-card#1078]
Would it be possible to create a URL that opens the card at a specific view/event/time?

For example, when sending a camera event notification, I would like to include a link so that the user can jump directly to the event in the timeline view.

I don't know enough about the home assistant lovelace card framework to know whether this is possible.

**Comment by dermotduffy** [comment]
There is some support for this kind of thing, see: https://github.com/dermotduffy/frigate-hass-card/tree/release-5.0.0#query-string-actions

So you can have it take you to the most recent event / snapshot, for example. Key limitation: It currently can not take you to a _specific_ event / snapshot (e.g. by an id).

**Comment by dermotduffy** [comment]
Please re-open if not sufficient. Thanks!
