### ISSUE TITLE
Cant play recordings

### ISSUE THREAD

**Issue by TelepathicWalrus** [dermotduffy/frigate-hass-card#1088]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.0.0-beta.1

**Last working release (if known):**
Not known

**Browser and Operating System:**
Chrome 112.0.5615.121
Windows 10

**Description of problem:**
Cant play recordings from the lovelace card. I can playback recordings using the media section in hass. The frigate integration card is on version 4.0.0. There does not seem to be any errors in the web inspector. I have added a screenshot of the player with a blank screen which is all i get when i try and play recordings. Snapshots however do still work.

![Frigate lovelace not loading recordings](https://user-images.githubusercontent.com/48514138/232224923-9ef1bfde-2d8f-4aff-90d8-3e86a196890d.png)

**Comment by dermotduffy** [comment]
Thanks for the report @TelepathicWalrus , this is a rather glaring issue with the current beta. It's already fixed in code, and will be in the next beta (that I hope to do shortly).
