### ISSUE TITLE
Not working after v4 upgrade - Error with media stream contents. Check troubleshooting.

### ISSUE THREAD

**Issue by andrewhack** [dermotduffy/frigate-hass-card#1099]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
4.0.0.

**Last working release (if known):**
3.0.1
**Browser and Operating System:**
Firefox 112.0/Windows 10

**Description of problem:**
After v4 upgrade no streams are available. Error shown in the card: Error with media stream contents. Check troubleshooting.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Suggest trying the v5 series which includes some hardening for this issue: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v5.0.0-beta.2

**Comment by andrewhack** [comment]
@dermotduffy is this downloadable from the UI? I see v3, v4 and master. Tried master - same issue

**Comment by dermotduffy** [comment]
How to test a pre-release:

```
HACS -> Frontend -> Frigate Card -> (three dots menu) -> Redownload -> Show beta-versions -> (Select latest)
```

**Comment by wilcomir** [comment]
I am on v5.0.0.-beta.2 and I still have the issue. Happy to help w/ logs or debug if needed.

**Comment by dermotduffy** [comment]
Do the clips play reliably in the HA media browser? i.e. not using the card at all?

**Comment by dermotduffy** [comment]
@andrewhack Sorry, I don't know what to tell you. Try the 'Update Information' open in the card "three-dots" menu. Failing that perhaps restart your HA instance (I think HACS refreshes periodically).

**Comment by andrewhack** [comment]
@dermotduffy please accept my apology - I am looking the integration, not the card... silly me
now is working very well!

**Comment by andrewhack** [comment]
@dermotduffy many thanks!

**Comment by wilcomir** [comment]
FWIW, it seem to work reliably for me as well. I still have to get around understanding the new options now available with go2rtc, but the media problem mentioned in this issue was fixed by latest beta.
