### ISSUE TITLE
Support last snapshot view default with click to play video

### ISSUE THREAD

**Issue by blakeblackshear** [dermotduffy/frigate-hass-card#110]
It would be great to show the default view as the latest snapshot, and playback the associated video when tapped. At the moment, tapping on the latest snapshot renders a broken video player.

Using v1.1.0

**Comment by dermotduffy** [comment]
This was fixed in https://github.com/dermotduffy/frigate-hass-card/pull/98 , but not released yet. With the default view as 'snapshot' it should otherwise behave as you describe.

**Comment by blakeblackshear** [comment]
Awesome. Thanks for all the work on this. It takes things to another level.
