### ISSUE TITLE
Player brightness config entry

### ISSUE THREAD

**Issue by Bobbik1** [dermotduffy/frigate-hass-card#1102]
4.0version  uses different Player than  webt2RTC card and stream is a little bit darker so it'll be nice to have a function to adjust the brightness

**Comment by Bobbik1** [comment]
![Screenshot_2023-04-20-20-14-28-067_io homeassistant companion android-edit](https://user-images.githubusercontent.com/48585522/233452707-0f35c3c3-f7d4-44db-8924-01bb3cfdd283.jpg)

**Comment by Bobbik1** [comment]
![Screenshot_2023-04-20-20-18-31-798_io homeassistant companion android](https://user-images.githubusercontent.com/48585522/233453468-66e3f600-b1a8-4f5a-9d67-7b5e0e9cd971.jpg)

**Comment by dermotduffy** [comment]
Weird. Did you try the latest beta? Also would you mind holding down the Frigate card menu button for a few seconds and post the resulting diagnostic information?

**Comment by Bobbik1** [comment]
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.4.2",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (Linux; Android 13; M2101K6G Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.101 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; M2101K6G)",
  "date": "2023-04-20T20:34:20.577Z",
  "frigate_version": {},
  "lang": "pl",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "webrtc_card": {
          "entity": "camera.taras_hd"
        },
        "title": "Taras",
        "icon": "mdi:balcony",
        "live_provider": "webrtc-card",
        "id": "1"
      },
      {
        "webrtc_card": {
          "entity": "camera.tapo_camera_8431_hd"
        },
        "title": "Wejście",
        "live_provider": "webrtc-card",
        "id": "2"
      },
      {
        "webrtc_card": {
          "entity": "camera.tapo_camera_d888_hd"
        },
        "title": "Trawnik",
        "id": "3"
      }
    ],
    "menu": {
      "position": "top",
      "alignment": "right",
      "buttons": {
        "cameras": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "live": {
          "enabled": false
        },
        "download": {
          "enabled": false
        }
      }
    },
    "view": {
      "default": "live",
      "dark_mode": "auto"
    },
    "live": {
      "controls": {
        "next_previous": {
          "style": "chevrons",
          "size": 20
        },
        "title": {
          "mode": "popup-top-right",
          "duration_seconds": 2
        }
      }
    },
    "elements": [
      {
        "type": "custom:frigate-card-conditional",
        "conditions": {
          "camera": [
            "2"
          ]
        },
        "elements": [
          {
            "type": "custom:frigate-card-menu-state-icon",
            "entity": "automation.discord_snapshot",
            "icon": "mdi:motion-sensor",
            "tap_action": {
              "action": "toggle"
            }
          },
          {
            "type": "custom:frigate-card-menu-icon",
            "icon": "mdi:content-save",
            "tap_action": {
              "action": "call-service",
              "service": "script.delete_last_tapo1"
            }
          },
          {
            "type": "custom:frigate-card-menu-icon",
            "icon": "mdi:home-floor-1",
            "tap_action": {
              "action": "call-service",
              "service": "script.setcam_first"
            }
          },
          {
            "type": "custom:frigate-card-menu-icon",
            "icon": "mdi:home-floor-2",
            "tap_action": {
              "action": "call-service",
              "service": "script.setcam_last"
            }
          },
          {
            "type": "custom:frigate-card-ptz",
            "orientation": "horizontal",
            "style": {
              "transform": "none",
              "left": "20px",
              "bottom": "20px"
            },
            "service": "button.press",
            "data_left": {
              "entity_id": "button.tapo_camera_8431_move_left"
            },
            "data_right": {
              "entity_id": "button.tapo_camera_8431_move_right"
            },
            "data_up": {
              "entity_id": "button.tapo_camera_8431_move_up"
            },
            "data_down": {
              "entity_id": "button.tapo_camera_8431_move_down"
            }
          }
        ]
      },
      {
        "type": "custom:frigate-card-conditional",
        "conditions": {
          "camera": [
            "1"
          ]
        },
        "elements": [
          {
            "type": "custom:frigate-card-menu-state-icon",
            "entity": "automation.taras_discord_snapshot",
            "icon": "mdi:motion-sensor",
            "tap_action": {
              "action": "toggle"
            }
          }
        ]
      },
      {
        "type": "custom:frigate-card-conditional",
        "conditions": {
          "camera": [
            "3"
          ]
        },
        "elements": [
          {
            "type": "custom:frigate-card-menu-state-icon",
            "entity": "automation.discord_snapshot_trawnik",
            "icon": "mdi:motion-sensor",
            "tap_action": {
              "action": "toggle"
            }
          }
        ]
      }
    ],
    "dimensions": {
      "aspect_ratio_mode": "unconstrained"
    },
    "media_viewer": {
      "layout": {
        "fit": "fill"
      }
    }
  }
}

**Comment by Bobbik1** [comment]
And i did try v5beta2, however u couldn't handle myself to force the config work for me

**Comment by dermotduffy** [comment]
> And i did try v5beta2, however u couldn't handle myself to force the config work for me

Sorry I don't know what this sentence means -- can you clarify? I'd rather only debug the v5 beta release, since it will imminently be the latest release (v4 is quite old at this stage).

**Comment by dermotduffy** [comment]
Also I notice you have dark mode set to auto, which will intentionally darken the card if your Home Assistant is in dark mode. Try turning that to `off` (which is the default).

**Comment by Bobbik1** [comment]
> 

Sorry, it was late night and my English isn't my best skill.
It just means, that beta didn't work with my old config, it somehow couldn't connect to go2rtc , error was something like:  "couldn't determine engine"

**Comment by Bobbik1** [comment]
> Also I notice you have dark mode set to auto, which will intentionally darken the card if your Home Assistant is in dark mode. Try turning that to `off` (which is the default).

I think it helped . It's sunny day now, but looks like streams are identical now. Thanks. I'll consider to debug a beta.

**Comment by dermotduffy** [comment]
Excellent. Closing for now -- thank you.
