### ISSUE TITLE
Update documentation for manual installers with `v5.0.0`

### ISSUE THREAD

**Issue by TheQue42** [dermotduffy/frigate-hass-card#1108]
**Checklist:**

**Release with the issue:**
v.5-isch

**Last working release (if known):**
4isch

**Browser and Operating System:**

I'm just trying to install, **without* hacs, manually. Yes, I now its recommended. But....because :-/.

**Description of problem:**
I appologize for my stupidity, but ever since the 5.000x (betas) have come out, I dont understand how I am supposed to get hold of the actual frigate-hass-card.js file?? The download under releases just contains a short 28byte .js with an include?
During the betas I managed to build my own, but now, i get the same include after yarn build.
Isnt manuall install with the single frigate-hass-card.js supported anymore?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Hi @TheQue42 , thanks for the report. There is no "actual" single `frigate-hass-card.js` anymore, it was been removed for performance reasons (the card will now dynamically load only what it needs). So you need to download all the Javascript files from the release and place them all in a directory, if you want to install manually. There is also a ZIP file included for convenience for people who are doing this ([here is the ZIP from the v5.0.0 release](https://github.com/dermotduffy/frigate-hass-card/releases/download/v5.0.0/frigate-hass-card.zip)).

**Comment by dermotduffy** [comment]
Please re-open if unclear! Thanks.

**Comment by TheQue42** [comment]
Understood, and thanks for a quick reply! I suppose the readme needs a bit of update?

![bild](https://user-images.githubusercontent.com/38688906/233837089-d637c5f8-fa0a-49b8-9986-c2af2ce13a1b.png)

**Comment by TheQue42** [comment]
My own feeling for "tidyness" wouldn't mind if if all the "sub-files" that are included from the main card.js, where in a subdirectory. If I for any reason wanted to remove this plugin from HA, its a bit messy to figure out which of the associated .js files that have been added under www/plugins, that belong to frigate-hass-card.js.

**Comment by dermotduffy** [comment]
> My own feeling for "tidyness" wouldn't mind if if all the "sub-files" that are included from the main card.js, were in a subdirectory. If I for any reason wanted to remove this plugin from HA, its a bit messy to figure out which of the associated .js files that have been added under www/plugins, that belong to frigate-hass-card.js.

Just to be clear -- you can put the files wherever you want. It doesn't have to be at the top-level, etc -- that's just an example in the docs. You're right that they need a refresh for manual installs -- I'll re-open this bug to track that.

**Comment by TheQue42** [comment]
> > My own feeling for "tidyness" wouldn't mind if if all the "sub-files" that are included from the main card.js, were in a subdirectory. If I for any reason wanted to remove this plugin from HA, its a bit messy to figure out which of the associated .js files that have been added under www/plugins, that belong to frigate-hass-card.js.
> 
> Just to be clear -- you can put the files wherever you want. It doesn't have to be at the top-level, etc -- that's just an example in the docs. You're right that they need a refresh for manual installs -- I'll re-open this bug to track that.

🤦 Of course...I supposed I _could_ have realised myself, that I don't _have_ to have all plugins directly in the plugins/ directory.... :-)
