### ISSUE TITLE
Card should fallback to `generic` on camera that has unregistered entity

### ISSUE THREAD

**Issue by remoteassist** [dermotduffy/frigate-hass-card#1116]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
V5
**Last working release (if known):**
V4
**Browser and Operating System:**

**Description of problem:**
Getting error "Could not find camera entity. Check troubleshooting." after upgrading to V5. Going back to V4 will work again. The card settings are default, no extra setting except the camera entity
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.fake_front_door
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

```
Could not find camera entity. Check troubleshooting.
{
  "hide": false,
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  },
  "engine": "auto",
  "frigate": {
    "client_id": "frigate"
  },
  "motioneye": {
    "images": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    },
    "movies": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    }
  },
  "live_provider": "auto",
  "image": {
    "refresh_seconds": 1
  },
  "camera_entity": "camera.fake_front_door"
}
```

**Comment by remoteassist** [comment]
V4 information
```
Card diagnostics. Please review for confidential information prior to sharing

{
  "ha_version": "2023.4.6",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0",
  "date": "2023-04-24T20:18:26.846Z",
  "frigate_version": {
    "95bb50f12295de1e4b86de3216985f71": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.fake_front_door"
      }
    ]
  }
}
```

**Comment by dermotduffy** [comment]
Some of the autodetection logic changed. The v5 card reads from the HA entity registry to attempt to autodetect the kind of camera that is. Given that the name is `camera.fake_front_door`, I'm suspecting this may be some unusual or fake kind of camera ;-) 

What kind of entity is it?

You may be able to work around this by manually specifying the camera engine type, something like this:

```yaml
type: custom:frigate-card
cameras:
- camera_entity: camera.fake_front_door
  engine: generic
```

Does that work by any chance?

**Suggestion to myself**: If an entity is not found in the entity registry, but _is_ found in the HomeAssistant state object, fallback to assume it's a generic camera. Otherwise, show this error (as this will be what happens when someone typos the entity).

**Comment by remoteassist** [comment]
Thanks, for looking into this. The real camera is re stream from the go2rtc addon, not from the one that came with Frigate, but the actual addon. The entity is created in the camera.yaml with the new url from go2rtc.

 It's not working with the new configuration, same error. Here is more information

Go2rtc 
===========
```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.1.107/live/",
      "remote_addr": "192.168.1.107:554",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 8 PCMA/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1"
      ],
      "recv": 29876383
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://192.168.1.82:8554/camera.porch?mp4",
      "remote_addr": "192.168.1.82:48026",
      "user_agent": "Lavf59.16.100",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 0 MPEG4-GENERIC/0"
      ],
      "tracks": [
        "96 H264/90000, sinks=1"
      ],
      "send": 29870975
    }
  ]
}
```

Camera.yaml
===========
```
Camera.yaml

- platform: ffmpeg
  input: rtsp://192.168.1.82:8554/camera.porch?mp4
  name: Fake_front_door
```

**Comment by remoteassist** [comment]
Ok, looking at your document, the camera entity need to be created by Frigate, weird that it was working with V4 with the old setting. I found the entity that Frigate created for the camera and got it working with configuration below.
   The reason I wasn't using it was one of my old device was not compatible with the Frigate camera entity.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_door
    dependencies:
      all_cameras: false
    live_provider: go2rtc
```

**Comment by dermotduffy** [comment]
Glad you got it working. I think I'll keep this bug open to implement the [hardening I describe above](https://github.com/dermotduffy/frigate-hass-card/issues/1116#issuecomment-1521072835). At the very least the card should be able to fallback to treating unregistered camera entities as `generic`.
