### ISSUE TITLE
Timeline not working with a mix of Frigate and Generic Cameras

### ISSUE THREAD

**Issue by Remko76** [dermotduffy/frigate-hass-card#1119]
I have set up the V5 card completely and it is working nice. One issue I found is the timeline... I use the Generic Camera integration for a low res stream using go2rtc. The high res stream comes from the Frigate integration. It all works fine, I have defined the substreams and in the card I can switch between the 2. All works really nice. The thing which does not work is the "Timeline" tab. When I click that it is completely empty. I guess it has to do with the generic cameras defined as "main" cameras and these of course do not have the timeline info.
When I use the "mini timeline" it does work though, even when it is displaying the low res stream, the mini timeline shows all the events for that camera. The card diagnostics/configuration and some screenshots below:

So the generic cameras are the "camera.xxx_sub" the ones from frigate "camera.xxx"
```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.4.6",
  "card_version": "5.0.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
  "date": "2023-04-26T07:13:17.291Z",
  "frigate_version": {
    "2f7b619244e861e8d2c372c193f91597": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en",
  "timezone": "Europe/Berlin",
  "git": {
    "build_version": "5.0.0-HEAD+gd7b150a",
    "build_date": "Sat, 22 Apr 2023 17:18:25 GMT",
    "commit_date": "Sat, 22 Apr 2023 10:10:23 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "live_provider": "auto",
        "frigate": {
          "camera_name": "birdseye"
        },
        "dependencies": {
          "all_cameras": true
        }
      },
      {
        "camera_entity": "camera.eingang_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "eingang_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.eingang",
        "title": "Eingang HD",
        "live_provider": "auto",
        "id": "eingang_hd",
        "hide": true
      },
      {
        "camera_entity": "camera.carport_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "carport_hd"
          ],
          "all_cameras": false
        }
      },
      {
        "camera_entity": "camera.carport",
        "title": "Carport HD",
        "live_provider": "auto",
        "id": "carport_hd",
        "hide": true
      },
      {
        "camera_entity": "camera.garten_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "garten_hd"
          ],
          "all_cameras": false
        }
      },
      {
        "camera_entity": "camera.garten",
        "title": "Garten HD",
        "live_provider": "auto",
        "id": "garten_hd",
        "hide": true
      },
      {
        "camera_entity": "camera.esszimmer_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "esszimmer_hd"
          ],
          "all_cameras": false
        }
      },
      {
        "camera_entity": "camera.esszimmer",
        "title": "Esszimmer HD",
        "live_provider": "auto",
        "id": "esszimmer_hd",
        "hide": true
      },
      {
        "camera_entity": "camera.werkstatt_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "werkstatt_hd"
          ],
          "all_cameras": false
        }
      },
      {
        "camera_entity": "camera.werkstatt",
        "title": "Werkstatt HD",
        "live_provider": "auto",
        "id": "werkstatt_hd",
        "hide": true
      },
      {
        "camera_entity": "camera.garage_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "garage_hd"
          ],
          "all_cameras": false
        }
      },
      {
        "camera_entity": "camera.garage",
        "title": "Garage HD",
        "live_provider": "auto",
        "id": "garage_hd",
        "hide": true
      }
    ],
    "menu": {
      "buttons": {
        "substreams": {
          "icon": "mdi:high-definition"
        }
      },
      "style": "outside"
    },
    "view": {
      "dark_mode": "auto"
    },
    "live": {
      "auto_mute": "all",
      "controls": {
        "timeline": {
          "mode": "below",
          "style": "ribbon",
          "media": "clips"
        }
      }
    },
    "timeline": {
      "style": "stack",
      "show_recordings": true,
      "media": "all"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/75678314/234497574-e21965b0-8079-4e9b-afb8-d49448dea745.png)

![image](https://user-images.githubusercontent.com/75678314/234497688-6f422aaf-8638-4f3a-8f39-d38cc9006b90.png)

![image](https://user-images.githubusercontent.com/75678314/234497810-9e8e9c67-6da2-49f5-ac3f-6e7709e90f4b.png)

**Comment by dermotduffy** [comment]
Thanks for the report @Remko76 ! I just wanted to take a very quick look, does it work when some cameras are selected in the camera select menu (e.g. your `birdseye` camera), but not others (e.g. your `camera.eingang_sub`) camera?

My theory, in the following example is that if `camera.eingang_sub` is not a Frigate camera, and it's dependency is marked as `hide: true` then there's just nothing for the timeline to show. Generic cameras don't support timeline, and the `hide` parameter intentionally hides the camera from the UI completely except as a substream -- i.e. it is not its own camera. In a scenario like this I can replicate it showing blank.

I agree showing blank is not what it should do, but I don't think an error message is what you're looking for. Maybe what's needed (if this is your problem) is allowing cameras to be hidden from the camera selectors, but _not_ from the timeline. Probably this would require a change in the `hide` parameter.

```json
      {
        "camera_entity": "camera.eingang_sub",
        "live_provider": "auto",
        "dependencies": {
          "cameras": [
            "eingang_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.eingang",
        "title": "Eingang HD",
        "live_provider": "auto",
        "id": "eingang_hd",
        "hide": true
      },
```

**Comment by Remko76** [comment]
Thanks for looking at it and your explanation makes perfect sense. Basically I am hiding all my frigate cans from the UI, hence.. No timeline.

to answer your question, no, with this setup I cannot get the timeline to show anything.

What I find “strange” Is that the mini timeline does work, so that shows the information from the sub stream. I did expect the normal timeline to behave the same, but with your explanation I understand it.

The other way of solving it would be if I change the low abs high res stream, so habe the high res (frigate cam) as default and the low res stream (generic cam) as substream. But this basically defeats the purpose. I want low res, low bandwidth as default and high pinky on demand.

I have not found a way of getting frigate to give me the low res stream as default stream in the camera entity, otherwise that would be the way to go.

**Comment by Remko76** [comment]
BTW. Snapshots and recordings are all available under the respective tabs, so these do work.

**Comment by dermotduffy** [comment]
Code just merged (but not released), will let us to things like this:

```
  - camera_entity: camera.living_room
    capabilities:
      disable_except:
        - substream
        - snapshots
        - clips
```

That supports the "substream" having both snapshots/clips which can be shown on a timeline, even if the selected camera is a generic camera.
