### ISSUE TITLE
The microphone menu button should support `toggle` and `momentary` options

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1129]
Hold/push to talk is nice. But, personally, I would prefer to toggle the microphone icon on or off to have a seamless conversation (so that I don't need to keep holding my finger to talk, or pressing the mouse button).

For example, the Tuya Smart app has both methods, and you can select which one you prefer in the settings.

Therefore, I suggest adding this alternative way of controlling the microphone.

It would be nice as well, for example, if there was some kind of safeguard in this case. Example:

- If user does not disable microphone in X seconds, the microphone automatically disables.

I would set it to something like 90s for example.

**Comment by felipecrs** [comment]
Another thing to consider in a toggle microphone situation:

_Automatically unmute microphone after connecting microphone_

**Comment by dermotduffy** [comment]
> I would set it to something like 90s for example.

This bit is kind of already done (defaults to 60s). If the microphone is not muted/unmuted in the last 60s, the microphone is automatically disconnected from the stream.

So I think this feature request amounts to: "Allow the microphone menu button to be either toggle or momentary".

**Comment by felipecrs** [comment]
Cool then, that's right.
