### ISSUE TITLE
Incompatibility with Frigate event structure

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#1136]
Hi! I was following this issue because it's happening something similar since last week. The card was working perfect (great job, thanks!) for months, but now I'm facing this error:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/12398295/235763996-35bf8c86-ca5d-44c7-83e5-1cf14583795e.png">
The error ends with an invalid keys message. I've add the debug part to a dashboard containing only 1 card, I didn't see the CameraManager request part in the javascript console, this is my output:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/12398295/235765315-ee4e786f-6167-4536-bd64-3a2a1ec18292.png">
I'm not sure if it's the same error, I'll like to getting this back to work. Maybe you can shed some light on this.
Thanks!

_Originally posted by @raelbsd in https://github.com/dermotduffy/frigate-hass-card/issues/1132#issuecomment-1532028631_

**Comment by dermotduffy** [comment]
Looks like something may have changed in the structure of the events, or at least there's a difference in the event protocol between what the card expects and what Home Assistant is returning.

@raelbsd are you using a very cutting edge Frigate version? I notice @NickM-27 filed https://github.com/blakeblackshear/frigate-hass-integration/issues/481 which sounds like it could be related.

**Comment by NickM-27** [comment]
this doesn't look like the same issue, not seeing the new fields that were added, unless those wouldn't be included in what the card gets for some reason

**Comment by dermotduffy** [comment]
From the screenshot it is possible the `sub_label` key is missing. The card currently expects it to exist and be either a string or `null`, but not missing entirely. Did anything change with that?

**Comment by NickM-27** [comment]
> From the screenshot it is possible the `sub_label` key is missing. The card currently expects it to exist and be either a string or `null`, but not missing entirely. Did anything change with that?

No, if anything perhaps the user is running an older version of frigate which doesn't send this field

**Comment by dermotduffy** [comment]
> No, if anything perhaps the user is running an older version of frigate which doesn't send this field

That would also do it. @raelbsd are you using the [latest Frigate version](https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0)?

**Comment by raelbsd** [comment]
Hi, maybe this is the problem, I'm running Frigate version 0.10.1-83481AF. It's running on Truenas Scale, and that took me a lot of effort so I didn`t update the version (and also it was running fine). I'll try to update then to see if this gets fixed.
Thanks!

**Comment by raelbsd** [comment]
I can confirm that the issue was the old version. I managed to update to the last stable and the error is gone, I have my frigate card working again. Thank you guys for the help!

**Comment by dermotduffy** [comment]
Excellent. Enjoy!
