### ISSUE TITLE
Another stream on full screen

### ISSUE THREAD

**Issue by mishoboss** [dermotduffy/frigate-hass-card#1155]
**Is your feature request related to a problem? Please describe.**
Usually for each camera we have a hight-res (with audio) stream and a low-res (may be without audio) stream. The low-res stream is good for object detection and as well for live streams, especially when there are multiple cameras on a single page (personally I have 12). However it would be really nice to have the option to stream the high-res one when we hit full-screen mode.

**Describe the solution you'd like**
On full-screen button click, play an optional second stream instead of the defined live stream.
<img width="44" alt="image" src="https://github.com/dermotduffy/frigate-hass-card/assets/1629929/5b68ca1b-5bf0-4df8-a67a-944168e3ed49">

**Comment by dermotduffy** [comment]
Funnily enough I implemented this a few days ago, take a look at this: https://github.com/dermotduffy/frigate-hass-card/pull/1141

It'll be in the next build. I think it's what you're looking for.

**Comment by mishoboss** [comment]
Looks like it's exactly that, though I'm not entirely sure how it does it. How we set which stream we want? I'm using go2rtc streams.

**Comment by dermotduffy** [comment]
@mishoboss The card already supports "substreams", multiple versions of the same live camera. The new (unreleased) code is simply the automation to activate those substreams when certain conditions are met. You'd configure the substreams as in these examples (see 'Having an SD and HD substream' specifically):

https://github.com/dermotduffy/frigate-hass-card#using-live-substreams

**Comment by dermotduffy** [comment]
Going to close this as I believe it's already done, and will be in the next release.
