### ISSUE TITLE
Zoom function does not work on Firefox & Safari

### ISSUE THREAD

**Issue by scooper1** [dermotduffy/frigate-hass-card#1174]
zoom features do not seem to be supported in desktop chrome 
pinch to zoom works ok in android chrome 
function not mapped to the mouse wheel on desktop 

is it possible to link the mouse wheel to Zoom or box select etc to Zoom on PC Chrome

**Comment by dermotduffy** [comment]
Try: Hold down control and use the mousewheel (the mousewheel on its own is used to scroll the carousel).

**Comment by EricKerby** [comment]
I have the same question for Firefox on a Mac OS laptop. Ctrl or Cmd + two-finger scroll (same as scroll wheel) doesn't have the effect of zooming the video.

**Comment by dermotduffy** [comment]
I can confirm there is an issue on at least Firefox. Chrome should work fine.

**Comment by dermotduffy** [comment]
For the immediate issue, I traced it down to `TouchEvent` apparently not existing at all in Firefox or Safari, when used on non-touch devices (whereas it does in Chrome).

Also found another issue with zooming (in any browser) on a snapshot, the click to pan around is interpreted as a click to take the matching video.

**Comment by scooper1** [comment]
Tried all shifts with middle button nothing worked with normal pc chrome.  Got either pam pull,  video pull with no entry sign or auto scroll

**Comment by dermotduffy** [comment]
> Tried all shifts with middle button nothing worked with normal pc chrome. Got either pam pull, video pull with no entry sign or auto scroll

@scooper1 I don't understand that last sentence, can you clarify? All the development was done on Chrome in a browser -- is it possible you're not running the new build? Please hold down the Frigate menu button and paste the resulting diagnostics and I'll try to reproduce with your config.

**Comment by scooper1** [comment]
I have fully cleared the  cache  not just shift refresh on windows 11

The function works fine using chrome  on Android 12

But I don't have a PC with touch screen    so can not do a pinch type action.   I would expect that either click hold and draw box to select area to zoom   

I not sure what is the correct action to trigger zoom on non touch screen so hard to show not working....  

I also currently do not have correct software to record this not working as a video   and can't really do this using standard screen capture   just tried unsuccessfully to describe actions I tried to trigger zoom 



⁣Get BlueMail for Android ​

**Comment by dermotduffy** [comment]
> I have fully cleared the  cache  not just shift refresh on windows 11

Can you hold down the Frigate menu button in the card and paste what shows up into this issue?

> But I don't have a PC with touch screen    so can not do a pinch type action.   I would expect that either click hold and draw box to select area to zoom  

PC + Chrome: Hold `Ctrl` + use mouse wheel. There's no other action that will do it.

**Comment by scooper1** [comment]
type: custom:frigate-card
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:9'
view:
  update_cycle_camera: true
  update_force: false
  timeout_seconds: 60
  update_seconds: 4
  camera_select: live
  default: live
live:
  preload: true
  draggable: false
  lazy_load: true
  controls:
    title:
      duration_seconds: 5
      mode: none
    thumbnails:
      mode: below
      media: clips
    next_previous:
      style: none
  transition_effect: none
  lazy_unload: all
menu:
  buttons:
    frigate:
      enabled: true
    live:
      enabled: true
    clips:
      enabled: true
    snapshots:
      enabled: true
    image:
      enabled: true
    download:
      enabled: true
    fullscreen:
      enabled: true
    camera_ui:
      enabled: true
  style: outside
  alignment: bottom
  position: bottom
image:
  refresh_seconds: 5
  mode: camera
media_viewer:
  controls:
    thumbnails:
      mode: below
      size: 75
      show_timeline_control: true
      show_favorite_control: true
      show_details: true
    title:
      duration_seconds: 5
      mode: popup-top-left
    next_previous:
      style: thumbnails
  draggable: true
  lazy_load: true
  transition_effect: none
  auto_play: all
  auto_unmute: all
  layout:
    fit: cover
timeline:
  media: all
  show_recordings: true
  controls:
    thumbnails:
      show_details: true
      size: 75
      show_favorite_control: true
      show_timeline_control: true
  clustering_threshold: 1
cameras:
  - camera_entity: camera.f_front
    live_provider: ha
    webrtc_card:
      entity: camera.f_back
    frigate:
      camera_name: f_front
      url: http://172.16.10.98:5000/
    dependencies:
      all_cameras: true
    triggers:
      motion: true
media_gallery:
  controls:
    thumbnails:
      show_details: true
      show_timeline_control: false
      size: 75
      show_favorite_control: false

**Comment by scooper1** [comment]
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.5.3",
  "card_version": "5.0.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "date": "2023-05-21T22:32:03.873Z",
  "frigate_version": {
    "87416c1f1f4442466f1eb8b7ea29aa1a": "4.0.0/0.12.0-bc16ad1"
  },
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.0.0-HEAD+gd7b150a",
    "build_date": "Sat, 22 Apr 2023 17:18:25 GMT",
    "commit_date": "Sat, 22 Apr 2023 10:10:23 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "dimensions": {
      "aspect_ratio_mode": "static",
      "aspect_ratio": "16:9"
    },
    "view": {
      "update_cycle_camera": true,
      "update_force": false,
      "timeout_seconds": 60,
      "update_seconds": 4,
      "camera_select": "live",
      "default": "live"
    },
    "live": {
      "preload": true,
      "draggable": false,
      "lazy_load": true,
      "controls": {
        "title": {
          "duration_seconds": 5,
          "mode": "none"
        },
        "thumbnails": {
          "mode": "below",
          "media": "clips"
        },
        "next_previous": {
          "style": "none"
        }
      },
      "transition_effect": "none",
      "lazy_unload": "all"
    },
    "menu": {
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "live": {
          "enabled": true
        },
        "clips": {
          "enabled": true
        },
        "snapshots": {
          "enabled": true
        },
        "image": {
          "enabled": true
        },
        "download": {
          "enabled": true
        },
        "fullscreen": {
          "enabled": true
        },
        "camera_ui": {
          "enabled": true
        }
      },
      "style": "outside",
      "alignment": "bottom",
      "position": "bottom"
    },
    "image": {
      "refresh_seconds": 5,
      "mode": "camera"
    },
    "media_viewer": {
      "controls": {
        "thumbnails": {
          "mode": "below",
          "size": 75,
          "show_timeline_control": true,
          "show_favorite_control": true,
          "show_details": true
        },
        "title": {
          "duration_seconds": 5,
          "mode": "popup-top-left"
        },
        "next_previous": {
          "style": "thumbnails"
        }
      },
      "draggable": true,
      "lazy_load": true,
      "transition_effect": "none",
      "auto_play": "all",
      "auto_unmute": "all",
      "layout": {
        "fit": "cover"
      }
    },
    "timeline": {
      "media": "all",
      "show_recordings": true,
      "controls": {
        "thumbnails": {
          "show_details": true,
          "size": 75,
          "show_favorite_control": true,
          "show_timeline_control": true
        }
      },
      "clustering_threshold": 1
    },
    "cameras": [
      {
        "camera_entity": "camera.f_front",
        "live_provider": "ha",
        "webrtc_card": {
          "entity": "camera.f_back"
        },
        "frigate": {
          "camera_name": "f_front",
          "url": "http://172.16.10.98:5000/"
        },
        "dependencies": {
          "all_cameras": true
        },
        "triggers": {
          "motion": true
        }
      }
    ],
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_details": true,
          "show_timeline_control": false,
          "size": 75,
          "show_favorite_control": false
        }
      }
    }
  }
}

Live: doorbell_f_go2rtc

**Comment by dermotduffy** [comment]
> "card_version": "5.0.0",

You are not using the right version of the card.

**Comment by scooper1** [comment]
very strange - i had downloaded the latest version  and done hard reload
I now re downloaded in hacs and hard reload  now have latest version ....  strange it was working on Android 
still no luck in getting it working PC 
`
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.5.3",
  "card_version": "5.1.1",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "date": "2023-05-21T22:38:00.164Z",
  "frigate_version": {
    "87416c1f1f4442466f1eb8b7ea29aa1a": "4.0.0/0.12.0-bc16ad1"
  },
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.1.1-HEAD+g2d977be",
    "build_date": "Sat, 20 May 2023 20:35:29 GMT",
    "commit_date": "Sat, 20 May 2023 13:32:32 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "dimensions": {
      "aspect_ratio_mode": "static",
      "aspect_ratio": "16:9"
    },
    "view": {
      "update_cycle_camera": true,
      "update_force": false,
      "timeout_seconds": 60,
      "update_seconds": 4,
      "camera_select": "live",
      "default": "live"
    },
    "live": {
      "preload": true,
      "draggable": false,
      "lazy_load": true,
      "controls": {
        "title": {
          "duration_seconds": 5,
          "mode": "none"
        },
        "thumbnails": {
          "mode": "below",
          "media": "clips"
        },
        "next_previous": {
          "style": "none"
        }
      },
      "transition_effect": "none",
      "lazy_unload": "all"
    },
    "menu": {
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "live": {
          "enabled": true
        },
        "clips": {
          "enabled": true
        },
        "snapshots": {
          "enabled": true
        },
        "image": {
          "enabled": true
        },
        "download": {
          "enabled": true
        },
        "fullscreen": {
          "enabled": true
        },
        "camera_ui": {
          "enabled": true
        }
      },
      "style": "outside",
      "alignment": "bottom",
      "position": "bottom"
    },
    "image": {
      "refresh_seconds": 5,
      "mode": "camera"
    },
    "media_viewer": {
      "controls": {
        "thumbnails": {
          "mode": "below",
          "size": 75,
          "show_timeline_control": true,
          "show_favorite_control": true,
          "show_details": true
        },
        "title": {
          "duration_seconds": 5,
          "mode": "popup-top-left"
        },
        "next_previous": {
          "style": "thumbnails"
        }
      },
      "draggable": true,
      "lazy_load": true,
      "transition_effect": "none",
      "auto_play": "all",
      "auto_unmute": "all",
      "layout": {
        "fit": "cover"
      }
    },
    "timeline": {
      "media": "all",
      "show_recordings": true,
      "controls": {
        "thumbnails": {
          "show_details": true,
          "size": 75,
          "show_favorite_control": true,
          "show_timeline_control": true
        }
      },
      "clustering_threshold": 1
    },
    "cameras": [
      {
        "camera_entity": "camera.f_front",
        "live_provider": "ha",
        "webrtc_card": {
          "entity": "camera.f_back"
        },
        "frigate": {
          "camera_name": "f_front",
          "url": "http://172.16.10.98:5000/"
        },
        "dependencies": {
          "all_cameras": true
        },
        "triggers": {
          "motion": true
        }
      }
    ],
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_details": true,
          "show_timeline_control": false,
          "size": 75,
          "show_favorite_control": false
        }
      }
    }
  }
}`

**Comment by scooper1** [comment]
thanks for help  working ok now    
was not helping I was ctrl and clicking mouse wheel then rolling the wheel   duh

**Comment by dermotduffy** [comment]
Glad you got it working. There's a legitimate bug with Firefox & Safari, I'm going to keep this up until I've resolved that.

**Comment by Hukuma1** [comment]
Has anyone tested it on iOS? Zooming in works, but the screen goes black about 3 seconds after. If I zoom back out the video recovers again. Using RTC, if it matters.
