### ISSUE TITLE
Add ability to video capture single frame as a "screenshot"

### ISSUE THREAD

**Issue by EricKerby** [dermotduffy/frigate-hass-card#1178]
Apologies if this already exists, but is it possible to add a quick snap / screenshot button to save the current live camera frame to the local device? I would like to be able to grab a frame to save locally or quickly share, and taking a screenshot through the mobile or desktop OS would include overlays or card buttons.

**Comment by dermotduffy** [comment]
@EricKerby There's already a download option to download static media (e.g. snapshots, clips, recordings). But I think you're looking for a way to capture a single frame of the live video, is that correct? There's no way to do that today.

**Comment by EricKerby** [comment]
Yes, that is correct. I agree with the updated title.

**Comment by dermotduffy** [comment]
Will be in the next build.
