### ISSUE TITLE
Can't scroll dashboard on mobile when swiping up/down on video

### ISSUE THREAD

**Issue by stplatt** [dermotduffy/frigate-hass-card#1181]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 5.1.1

**Last working release (if known):** 5.0

**Browser and Operating System:** Android companion app, android webview, chrome (mobile)

**Description of problem:**

You can't scroll up/down on a dashboard page by swiping up/down on the frigate hass card with video playing. It only works if you press and drag over a menu button 

**Frigate card diagnostic information**

```
{
  "ha_version": "2023.5.3",
  "card_version": "5.1.1",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "date": "2023-05-23T14:32:21.170Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.1.1-HEAD+g2d977be",
    "build_date": "Sat, 20 May 2023 20:35:29 GMT",
    "commit_date": "Sat, 20 May 2023 13:32:32 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.octoprint",
        "live_provider": "webrtc-card",
        "webrtc_card": {
          "url": "camera.octoprint",
          "ui": true
        }
      }
    ],
    "menu": {
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "live": {
          "enabled": false
        },
        "clips": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "download": {
          "enabled": false
        },
        "camera_ui": {
          "enabled": false
        },
        "expand": {
          "enabled": true
        },
        "timeline": {
          "enabled": false
        },
        "fullscreen": {
          "alignment": "opposing"
        }
      },
      "style": "overlay",
      "position": "bottom",
      "button_size": 35
    },
    "elements": [
      {
        "type": "state-icon",
        "tap_action": {
          "action": "toggle"
        },
        "entity": "switch.basement_workbench_light",
        "style": {
          "top": "20px",
          "left": "20px"
        }
      }
    ],
    "live": {
      "draggable": false
    }
  }
}

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Burbacottero** [comment]
Same problem

**Comment by dermotduffy** [comment]
This is almost certainly because the card now supports zoom (didn't in `v5.0.0` and does in `v5.1.1`). A temporary workaround would be to disable zoom on which view you are using, e.g:

```yaml
live:
  zoomable: false
```

Let me know if that helps. I'll see if there's a better solution, though, that keeps zoom working.

**Comment by stplatt** [comment]
Disabling zoom does fix the issue, but it would be nice to do both (scroll and zoom) if possible. Thanks.

**Comment by arigit** [comment]
I can confirm this problem, on Android 13, Samsung S23. There is no way to scroll up/down unless you touch the buttons in the overlay UI, which forced me to disable zooming from live view. 

The zoom feature is awesome (I upgraded the card just for it), if the dashboard scrolling issue can't be solved, the next best thing would be to make the feature work in live view "Full Screen" mode only

**Comment by dermotduffy** [comment]
OK -- made some progress on this. You won't be able to scroll when you're zoomed in -- but this is working as intended, since you'll be panning around instead. When you're not zoomed in, it should scroll as usual. It'll be in the next build for you all to try out!

**Comment by timknowlden** [comment]
Also have this issue, when will update be live?

**Comment by dermotduffy** [comment]
It already is, v5.2.0 .
