### ISSUE TITLE
panning to view a cut off part of a feed  on mobile portrait screen 

### ISSUE THREAD

**Issue by scooper1** [dermotduffy/frigate-hass-card#1189]
when viewing on a small mobile screen only a limited part of the main feed is showing and it not possible to pan this view to see missing parts even if zoomed only the narrow portion of the screen that is shown on full screen is available for panning.

am I missing an option to be able to pan to see the cut-off edges of pictures?

**Comment by scooper1** [comment]
Don't have problem on PC chrome but android chrome is setting higth of card as the restraint and cuts off the edges . 

Once this happens you can still pinch zoom card and use panning but picture is limited to original u zoomed edges not the full width of picture

⁣Get BlueMail for Android ​

**Comment by dermotduffy** [comment]
> Don't have problem on PC chrome but android chrome is setting higth of card as the restraint and cuts off the edges .
> Once this happens you can still pinch zoom card and use panning but picture is limited to original un zoomed edges not the full width of picture

Sorry, I'm still not following. Would it be possible to provide a video capture or screenshot of the issue? A picture is 1000 words. I use the card on Android Chrome all the time. I can pinch to zoom (multi-finger) and pan the full image (single-finger drag) to the full extent of the image.

**Comment by dermotduffy** [comment]
Please re-open with a screenshot/screencap of the issue so I can see what the issue is. Thanks!

**Comment by scooper1** [comment]
Ment to close  with fixed by using constraints to keep all the image on phone screen by reducing height
