### ISSUE TITLE
Ever since updating to the new release I now get an error when trying to load a camera

### ISSUE THREAD

**Issue by zacharyd3** [dermotduffy/frigate-hass-card#1190]
Previously I had everything setup and working great, however once I've updated my frigate cameras all give me an error saying "invalid keys" limit=50 I'd=126

**Comment by dermotduffy** [comment]
Update your Frigate.

**Comment by dermotduffy** [comment]
Confident this is related to versions not being up to date, as I've seen this issue many times. If you think I'm wrong, please re-open!
