### ISSUE TITLE
unknown_command after updating Home Assistant to 2023.6.0

### ISSUE THREAD

**Issue by rea-ducks** [dermotduffy/frigate-hass-card#1193]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
Home Assistant 2023.6.0
Frigate 0.12.0-da3e197 in Docker
Frigate Home Assistant Integration 4.0
Frigate Hass Card 5.1.1

**Last working release (if known):**
Home Assistant 2023.5.4
Frigate 0.12.0-da3e197 in Docker
Frigate Home Assistant Integration 4.0
Frigate Hass Card 5.1.1

**Browser and Operating System:**
Firefox 113.0.2 on Windows 10 22H2, Microsoft Edge 114.0.1823.41 on Windows 10 22H2, Home Assistant Companion App on Android 13

**Description of problem:**
Up until Home Assistant to 2023.5.4 the card worked, now after updating to Home Assistant 2023.6.0 it gives me an error. The Home Assistant integration does work flawless and showes all streams.

Instead of a stream it only shows the following text:
````
Failed to receive response from Home Assistant for request. Check troubleshooting.

{
  "request": {
    "type": "frigate/events/get",
    "instance_id": "frigate",
    "cameras": [
      "eyethree"
    ],
    "limit": 50,
    "id": 163
  },
  "response": {
    "code": "unknown_command",
    "message": "Unknown command."
  }
}
````

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.6.0",
  "card_version": "5.1.1",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0",
  "date": "2023-06-08T11:29:56.003Z",
  "frigate_version": {
    "7185845307e0582a9f6dd68dc0d4f6a0": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en_GB",
  "timezone": "Europe/Berlin",
  "git": {
    "build_version": "5.1.1-HEAD+g2d977be",
    "build_date": "Sat, 20 May 2023 20:35:29 GMT",
    "commit_date": "Sat, 20 May 2023 13:32:32 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.eyethree",
        "live_provider": "auto"
      }
    ],
    "menu": {
      "position": "bottom",
      "buttons": {
        "substreams": {
          "enabled": false
        }
      }
    }
  }
}
```

**Additional information:**
I already removed Hass card from the dashboard, readded it, uninstalled the Addon, redownloaded it, tried different live providers, result is always the same.

**Comment by dermotduffy** [comment]
@rea-ducks Is your Frigate integration working correctly? When you visit `Settings -> Devices & Services -> Frigate` are you seeing your Frigate devices as you expect?

**Comment by rea-ducks** [comment]
> @rea-ducks Is your Frigate integration working correctly? When you visit `Settings -> Devices & Services -> Frigate` are you seeing your Frigate devices as you expect?

Erm, no, it didn't. Had to shut down the whole computer and restart and then the integration came up. I guess I still don't grasp how the whole stuff is interconnected.
After going through it all I know that what I thought is the integration is Frigate Proxy …
