### ISSUE TITLE
Live views are still on Android HA Companion app

### ISSUE THREAD

**Issue by lordbah** [dermotduffy/frigate-hass-card#1194]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
frigate-hass-card v5.1.1

**Last working release (if known):**
Unknown

**Browser and Operating System:**
HA App
Android 13

**Description of problem:**
I have 2 cameras. On desktop in Firefox both cards have the expected moving live view. On Android phone in Chrome, ditto. On Android phone in HA Companion app 2023.3.0-full both views are a still image rendered at the time the page was viewed. If I switch to timeline or screenshots and then back to camera, I see a fresh image, but again it is still and does not update.

Similar to other reported issues but I couldn't find one which matched exactly. I suppose there is a good chance this turns out to be an HA app issue instead of a card issue but I thought I'd begin here.

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.5.4",
  "card_version": "5.1.1",
  "browser": "Mozilla/5.0 (Linux; Android 13; Pixel 4 XL Build/TP1A.221005.002.B2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; Pixel 4 XL)",
  "date": "2023-06-08T16:22:47.231Z",
  "frigate_version": {
    "7316a3a775208e5832c2291abe3284d9": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.1.1-HEAD+g2d977be",
    "build_date": "Sat, 20 May 2023 20:35:29 GMT",
    "commit_date": "Sat, 20 May 2023 13:32:32 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "frigate_url": "http://homeassistant.local:5000/",
    "view_default": "live",
    "cameras_global": {
      "engine": "frigate",
      "live_provider": "go2rtc",
      "go2rtc": {
        "modes": [
          "webrtc"
        ]
      }
    },
    "cameras": [
      {
        "camera_entity": "camera.front_door",
        "id": "front"
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true
        }
      }
    }
  }
```
Aside: the microphone button does not appear, apparently I have to get into certificates for HA to setup HTTPS access. I had been using my web server to handle that with a reverse proxy to HA so I didn't have to worry about it yet.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
I don't know why this would happen in the Companion app. Have you tried other live providers to see if you can narrow the problem down?

**Comment by lordbah** [comment]
jsmpeg, image, ha (default) all behave properly. Am I understanding correctly that ha (native webrtc) requires a separate server to be installed, RTSPtoWebRTC? Is it worth trying webrtc-card?

**Comment by lordbah** [comment]
Since every other provider was working I switched back to go2rtc and it's working now too. I don't know why it wasn't before.
