### ISSUE TITLE
Jump to a certain camera given by URL parameter

### ISSUE THREAD

**Issue by t0ny-peng** [dermotduffy/frigate-hass-card#1205]
**Is your feature request related to a problem? Please describe.**

I'm using `live` as the default view, with 4 cameras. I have an automation that turns on the tablet screen when person is detected. Everytime the camera page is loaded, it always shows the first camera. Just wonder if there's a way to slide to a certain camera using URL parameter. 

**Describe the solution you'd like**

E.g., opening `https://<my-ha-domain>.com/lovelace/frigate?camera=living_room` will automatically open the living room camera. 

**Describe alternatives you've considered**

Having multiple pages, each having only one camera? Seems not scalable. 

**Additional context**

None

**Comment by dermotduffy** [comment]
Try:

```
https://<my-ha-domain>.com/lovelace/frigate?frigate-card-action:camera_select=camera.living_room
```

Note:
 - Assumes `camera.living_room` is the id for one your cameras.
 - Will cause this action to occur on all Frigate cards on the dashboard.

Reference:
 - [Relevant docs](https://github.com/dermotduffy/frigate-hass-card#query-string-actions) 
 - [Known issue with some actions](https://github.com/dermotduffy/frigate-hass-card/issues/1200)

**Comment by t0ny-peng** [comment]
@dermotduffy Nice! Thanks a lot. Closing this ticket.
