### ISSUE TITLE
go2rtc external access not working within the card

### ISSUE THREAD

**Issue by cooltings** [dermotduffy/frigate-hass-card#1219]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
iPhone 

**Description of problem:**

I cannot get external access of go2rtc with duckdns

**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
The card exclusively communicates with Home Assistant (whether you use go2rtc or not), so it is very unlikely (impossible?) the card is responsible for any networking issues you are having. Put another way: If Home Assistant itself works remotely, the card should work "just as much". If it doesn't, that is an issue somewhere with HA or the Frigate backend, and not with the card.

**Comment by cooltings** [comment]
Ok
