### ISSUE TITLE
Putting birdseye in fullscreen

### ISSUE THREAD

**Issue by atv2016** [dermotduffy/frigate-hass-card#1220]
I would like one camera view of the frigate card with birdseye, but use all of the screen estate in the view.
Is this possible ? Currently it shows as a default card, which is not very big.

Thanks

**Comment by dermotduffy** [comment]
> I would like one camera view of the frigate card with birdseye, but use all of the screen estate in the view.
Is this possible ? Currently it shows as a default card, which is not very big.

You have a few options:

* Use the fullscreen menu button to convert the card into fullscreen.
* Use the expand menu button to open up a "dialog box".
* Use a HA [panel](https://www.home-assistant.io/dashboards/panel/) [view](https://www.home-assistant.io/dashboards/views/) to just render the card "fullscreen" in the dashboard.

**Comment by atv2016** [comment]
Lovely! Panel view did the trick wonderfully.
Thanks,
