### ISSUE TITLE
Panel Mode: Fit: Fill - No longer works as expected

### ISSUE THREAD

**Issue by cweakland** [dermotduffy/frigate-hass-card#1221]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
5.2.0
**Last working release (if known):**
Not sure, but it was a few releases ago.
**Browser and Operating System:**
Firefox or Chrome

**Description of problem:**

I have the frigate card in use on a dashboard using panel mode. I have it configured such that the video fills the screen. In prior releases it would work properly and there would not be scroll bar on the right hand side. Recently I noticed that the scroll bar is back. The odd thing is, on the first load of the page in a fresh browser session (it can be Firefox or Chrome), it will load properly filling the screen without a scroll bar, then the "Live: <Camera Name>" notification pops up in the lower right hand corner, and the scroll bar appears. 

Thank you for your help, this is such an amazing project! 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/25326695/2cb21d26-6201-4af9-adfe-aedc57f3685b)

**Frigate card diagnostic information**

```json
Card diagnostics. Please review for confidential information prior to sharing

{
  "ha_version": "2023.7.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0",
  "date": "2023-07-11T14:18:46.966Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.driveway",
        "title": "Driveway",
        "frigate": {
          "camera_name": "driveway"
        },
        "live_provider": "jsmpeg"
      },
      {
        "camera_entity": "camera.frontyard",
        "title": "Front Yard",
        "frigate": {
          "camera_name": "frontyard"
        },
        "live_provider": "jsmpeg"
      },
      {
        "camera_entity": "camera.basement",
        "title": "Basement",
        "frigate": {
          "camera_name": "basement"
        },
        "live_provider": "jsmpeg"
      },
      {
        "camera_entity": "camera.basement_inside",
        "title": "Basement - Inside",
        "frigate": {
          "camera_name": "basement_inside"
        },
        "live_provider": "jsmpeg"
      },
      {
        "camera_entity": "camera.backyard",
        "title": "Back Yard",
        "frigate": {
          "camera_name": "backyard"
        },
        "live_provider": "jsmpeg"
      },
      {
        "camera_entity": "camera.backyard_shed",
        "title": "Back Yard - Shed",
        "frigate": {
          "camera_name": "backyard_shed"
        },
        "live_provider": "jsmpeg"
      }
    ],
    "live": {
      "controls": {
        "next_previous": {
          "style": "chevrons"
        },
        "thumbnails": {
          "mode": "right",
          "show_details": true,
          "show_timeline_control": true
        },
        "timeline": {
          "mode": "none"
        }
      },
      "transition_effect": "none",
      "draggable": false,
      "layout": {
        "fit": "fill"
      }
    },
    "timeline": {
      "show_recordings": true,
      "controls": {
        "thumbnails": {
          "mode": "below"
        }
      }
    },
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_details": true
        }
      }
    },
    "media_viewer": {
      "layout": {
        "fit": "fill"
      },
      "controls": {
        "timeline": {
          "mode": "none"
        }
      }
    },
    "image": {
      "layout": {
        "fit": "fill"
      }
    },
    "dimensions": {
      "aspect_ratio_mode": "dynamic"
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Hi @cweakland , I agree with what you expect. I wonder if this isn't a HA problem -- I can make a new panel dashboard, with a simple picture element card (not a frigate card), and it will spill slightly over the full "screen" the same way. It appears to spillover the same amount as the Frigate card does.

Do you see the same thing?

**Comment by cweakland** [comment]
A picture card spills over at the initial screen load. The frigate card spills over once it fully loads the content. Its not a big deal, its just a cosmetic thing that changed at some point.

**Comment by dermotduffy** [comment]
> A picture card spills over at the initial screen load. The frigate card spills over once it fully loads the content. Its not a big deal, its just a cosmetic thing that changed at some point.

Understood -- my point is I think it changed in Home Assistant, not the Frigate card! It might be good to open a bug over there with a Picture Element example (since that is stock and should work out of the box).

**Comment by dermotduffy** [comment]
I'm going to close this as I can't see any behavior difference between the Frigate card and stock HA cards in panel mode. If you think there's something else to do here, please re-open and we can discuss! Thanks.
