### ISSUE TITLE
Split timeline and live view

### ISSUE THREAD

**Issue by dnestico** [dermotduffy/frigate-hass-card#1223]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to redesign my camera dashboard for mobile and I see that your card is very good, it has a live view, timeline and clips which is perfect for me. 

The way the timeline works now though is it looks like you have to click a separate button on the card to bring it up rather then always being shown underneath the card during live view.

**Describe the solution you'd like**
A I guess it is called "split view" option perfect for mobile, live view at the top and timeline below with the recent events:

Here is an example, **I am not suggesting making it look like that picture below**, the timeline right now you made is great I just want an option to keep it visible below the live view for easier access rather than having inexperienced family members with HA clicking random buttons or trying to figure out how to pull it up, especially after coming from the nest / google home app which is different.

<img width="429" alt="Screenshot 2023-07-13 at 5 21 11 PM" src="https://github.com/dermotduffy/frigate-hass-card/assets/3034555/b37c4cdd-05ee-4f59-b49c-5fe81672f998">

**Describe alternatives you've considered**
Frigates experimental view, it's decent but just a website that you can't access externally embedded in the iframe HA card.

<img width="446" alt="Screenshot 2023-07-13 at 5 31 17 PM" src="https://github.com/dermotduffy/frigate-hass-card/assets/3034555/2f15b0de-4edf-4bf8-9385-943ade74efc5">

Another one is using your card of course and as you see the timeline below is what I want here, but it only shows when viewing clips, not all the timeline or on live view easily accessible.

<img width="490" alt="Screenshot 2023-07-13 at 6 01 52 PM" src="https://github.com/dermotduffy/frigate-hass-card/assets/3034555/97688b3a-9d51-45c5-bd79-444c18fe9788">

**Additional context**

**Comment by dermotduffy** [comment]
It's possible I misunderstand the request, but is this not what you're asking for:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.kitchen
live:
  controls:
    timeline:
      mode: below
media_viewer:
  controls:
    timeline:
      mode: below
```

**Comment by dnestico** [comment]
Holy shit that's exactly what I was asking for! I'm sorry I did not realize it was possible to work with the live view! 

Btw if I add multiple cameras will it work still and show all events from each camera on one timeline?

I still like the more mobile app look like above but this will work for now, thanks!

**Comment by dnestico** [comment]
Holy shit that's exactly what I was asking for! I'm sorry I did not realize it was possible to work with the live view!

Btw if I add multiple cameras will it work still and show all events from each camera on one timeline?

I still like the more mobile app look like above but this will work for now, thanks!

**Comment by dermotduffy** [comment]
> Holy shit that's exactly what I was asking for! I'm sorry I did not realize it was possible to work with the live view!

Heh. Excellent!

> Btw if I add multiple cameras will it work still and show all events from each camera on one timeline?

When you view the live for camera X, the timeline will show the events for camera X and any camera marked as a dependency of camera X.

**Comment by dermotduffy** [comment]
@dnestico Probably. I made some tweaks to allow `card_mod`, although do not use it myself.

**Comment by dnestico** [comment]
Alright cool, any example specifically for the timeline so I can figure out how to modify different parts of the card?

**Comment by dermotduffy** [comment]
> Alright cool, any example specifically for the timeline so I can figure out how to modify different parts of the card?

Afraid not -- you're a trail blazer! There's one [example](https://github.com/dermotduffy/frigate-hass-card/blob/main/README.md#using-card-mod-to-style-the-card) in the docs on using card-mod, but as this is unsupported you're kind of on your own here. Good luck!

**Comment by dnestico** [comment]
So far this doesn't do anything so tryna figure out how the whole CSS thing works rn...

```
card_mod:
  style:
    frigate-card-timeline-core $: |
      div.timeline {
        background: red !important;
      }
```
