### ISSUE TITLE
Media gallery should offer custom date/time support

### ISSUE THREAD

**Issue by dominikjas** [dermotduffy/frigate-hass-card#1224]
Hello,

I found this feature in the dev version of frigate and thought this would be a nice feature for the hass-card too:

https://github.com/blakeblackshear/frigate/pull/5183#issuecomment-1634950671

When you got many events on a day the datepicker does not really help one to not end up in endless scrolling and the timeline view was a bit laggy with many events. 

Maybe it's also because of my setup that it's partially laggy:
1. Frigate docker container on a dedicated server (16 cores, 96GB RAM, 32GB cache SSD RAID1, USB Coral / 1G cache, 8G shm)
2. The storage is on an iscsi-target 
3. Home Assistant runs on RPI4-4GB

**Comment by dermotduffy** [comment]
Thanks for the idea! Just to make sure I understand, the idea is to add a time picker, as well as a date picker that is already on the timeline?

I guess I didn't think people would have so many events that this would be necessary, but I guess I was wrong!

**Comment by dominikjas** [comment]
Hey I think it would especially help in the clips gallery section:

![Screenshot_20230714_074355_Microsoft Remote Desktop.jpg](https://github.com/dermotduffy/frigate-hass-card/assets/83553492/5b0e8608-4a07-4083-ad6d-a31092228a32)

Simply to get a better overview what happened for example yesterday between 6:30 and 6:45. Now I have to scroll through the whole day to see this.

But to have it at both sections would be probably the best.

**Comment by dermotduffy** [comment]
Oh! That's pretty different than I was imagining thanks for clarifying. So the primary use is in the gallery filter, and in your 
 example when you use the "Yesterday" time selector, there's just too much scrolling / imprecision?

**Comment by dominikjas** [comment]
Yes exactly!

**Comment by dermotduffy** [comment]
This is now implemented and will be in the next release.
