### ISSUE TITLE
Integration of card seems to be broken

### ISSUE THREAD

**Issue by jurispucekts** [dermotduffy/frigate-hass-card#1225]
Removing the and renewing doesn't seem to help. After upgrade to latest Frigate version on card get this error:

  "response": {
    "code": "invalid_format",
    "message": "extra keys not allowed @ data['cameras']. Got ['entrance']"

Other types of cards work just fine and there doesn't seem to be visible error in Frigate logs

**Comment by dermotduffy** [comment]
Your Frigate integration, or Frigate backend are out of date. Update them both to latest.

**Comment by jurispucekts** [comment]
Found the component missing update! Thanks
