### ISSUE TITLE
Stream flips upside down when using WebRTC

### ISSUE THREAD

**Issue by justinwoodland** [dermotduffy/frigate-hass-card#1229]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v5.2.0

**Last working release (if known):** Unknwon

**Browser and Operating System:** (Chrome, Firefox), (Linux, MacOS, Android)

**Description of problem:**
I recently switched my frigate instance over to use go2rtc.  Everything is working fine in Frigate. I can use the webrtc and mse streams and they appear correctly in the Frigate webapp.

When trying to use these streams in the frigate-hass-card (the 'Auto' Live view provider defaults to the `Home Assistant video stream (i.e. HLS, LL-HLS, WebRTC via HA)` stream) the live view appears for a moment (varies from nearly instant to ~1.5 seconds) in the correct orientation. The live view then flips upside down and stays that way until the page is reloaded.

Here is a screenshot of the same stream in frigate on the left and the frigate-hass-card on the right. 

![Screenshot from 2023-07-19 17-08-55](https://github.com/dermotduffy/frigate-hass-card/assets/85194572/e423371f-298a-4d1f-b159-492a64ef4fa6)

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.7.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
  "date": "2023-07-19T23:13:37.698Z",
  "frigate_version": {
    "9b2ad4783bae62024fe8f72458b17ca2": "4.0.0/0.12.0-66881eb"
  },
  "lang": "en",
  "timezone": "America/Boise",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front",
        "live_provider": "auto"
      }
    ]
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```
None found
```

**Additional information:**

**Comment by dermotduffy** [comment]
Hah. What on Earth. I doubt this is related to the card -- if you check that same camera entity in Home Assistant, is it also upside down? If yes, your issue is not the card but something on the Frigate side.

**Comment by justinwoodland** [comment]
You are correct. The camera entity is showing upside down too. I'll close this case and take a look at my frigate config. Thanks for your work on this card!
