### ISSUE TITLE
Amcrest Door bell 2-way audio not working

### ISSUE THREAD

**Issue by SusithAbeythunga** [dermotduffy/frigate-hass-card#1234]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
Latest
**Last working release (if known):**
None
**Browser and Operating System:**
Chrom/ Windows 10

**Description of problem:**
I tried to set up the 2-way audio with Amcrest doorbell. It works perfectly when I don't have #backchannel=0 added to go2rtc. But this will block the button function on the bell. So I added #backchannel=0, but then the Frigate card microphone not work. I can see it refresh the stream the first time I press, I assume this is to get stream link without backchannel=0, but cannot hear anything on the doorbell

**Frigate card diagnostic information**
Couldn't get one

```json

```

**Javascript errors shown in the web inspector (if applicable):**
NA
```

```

**Additional information:**

**Comment by dermotduffy** [comment]
> I tried to set up the 2-way audio with Amcrest doorbell. It works perfectly when I don't have #backchannel=0 added to go2rtc. But this will block the button function on the bell. So I added #backchannel=0, but then the Frigate card microphone not work. I can see it refresh the stream the first time I press, I assume this is to get stream link without backchannel=0, but cannot hear anything on the doorbell

This sounds like more of a go2rtc issue than a card one. If the 2-way audio works in go2rtc, it should work in the card just fine -- the card is simply using the webrtc stream that go2rtc provides (i.e. it doesn't know anything, nor do I (!), about the backchannel argument to which you are referring).

Recommend getting 2-way audio working correctly as you want it in go2rtc (you can test via the `2-way-aud` line on the go2rtc UI, but you'll need to access over `https`), then come back to the card once it's working there and it should "just work".

**Comment by SusithAbeythunga** [comment]
I have Amcrest AD410 door bell. According to go2rtc I have to add #backchannel=0 at the end of the rtsp stream to avoid 2-way channel open all the time. When this happens, the door bell button doesn't work. 
I guess your frigate card need a stream with two-way audio to work properly. So, I ended up removing the backchannel=0 at the end of rtsp stream. Is there a way to have the live view with a different go2rtc stream and change the go2trc stream when the mic button pressed? This way I can set up a different go2rtc streams, one with 2 way audio and one without 2 way audio.

**Comment by dermotduffy** [comment]
> I guess your frigate card need a stream with two-way audio to work properly. 

It needs only a single WebRTC stream. If that stream supports 2-way audio, 2-way audio should work. If it doesn't, you'll get video only. 

> Is there a way to have the live view with a different go2rtc stream and change the go2trc stream when the mic button pressed? This way I can set up a different go2rtc streams, one with 2 way audio and one without 2 way audio.

As above, this is not unnecessary. The stream either supports 2-way audio or it doesn't -- if the right thing is not happening with the stream, the issue is with `go2rtc` which creates and presents the stream and not with the card.

**Comment by SusithAbeythunga** [comment]
Thanks for the information. Looks like it's an issue with AD410 doorbell go2rtc integration.

**Comment by dermotduffy** [comment]
This is very likely the same or similar issue as #1235 , so lets track it there.
