### ISSUE TITLE
Android Screen (Android 11) 5.5 Inch screen - Frigate Card doesnt work

### ISSUE THREAD

**Issue by robotsmarthomes** [dermotduffy/frigate-hass-card#1238]
Using Android 11 - 5.5 Inch Android Screen - Frigate card "not-found"
           Android 11 - 10.1 Inch Android Screen - Frigate card working correctly

I have a few screens from the same manufacturer. Frigate card only works on 10.1 inch screen, not 5.5 inch screen. I was trying to adjust dimensions and aspect ratio, but no luck.  

Any ideas?

Thanks

**Comment by dermotduffy** [comment]
Very likely due to Android OS version, or webview version differences. I would guess the devices that say "not found" are running a slightly too-old version of Android/Webview, and so the browser cannot understand the Javascript. Check the exact Android version, and see if the smaller devices are older?

**Comment by dermotduffy** [comment]
Similar: https://github.com/dermotduffy/frigate-hass-card/issues/1204

**Comment by robotsmarthomes** [comment]
Yes, this was one of our employees who asked the question. Both are running "Android 11" - and seems to be same age. you are probably correct that they might be a 'slightly' older version. There's also no update available for the 5.5 inch tablet

AHHH

**Comment by dermotduffy** [comment]
> There's also no update available for the 5.5 inch tablet

Also check whether or not the latest "Android System WebView" has been installed from the Play store.

**Comment by robotsmarthomes** [comment]
Hey thanks for getting back to me. Yes the latest android system webview has been installed

**Comment by dermotduffy** [comment]
> Yes the latest android system webview has been installed

Then I'm afraid you're out of luck :-(

**Comment by dermotduffy** [comment]
Conclusion: Unsupported device.
