### ISSUE TITLE
Page refreshes mid-scroll or when watching longer video

### ISSUE THREAD

**Issue by scottjjr** [dermotduffy/frigate-hass-card#1239]
**Checklist:**

- [ x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
have noticed for almost entire time using it (year+)

**Last working release (if known):**

**Browser and Operating System:**
Home assistant app on iOS

**Description of problem:**

If I’m using the card in the home assistant to scroll and view videos for a while, or watch a  video longer than a few seconds, the card will refresh on me and kick me back to the top. Has been happening for some time.

even just happened while I was trying to copy out the dish below. Almost seems like there’s a force hard refresh happening after a certain time no later if you’re using it or not

**Frigate card diagnostic information**

```json

Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.8.0",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.4 (io.robbie.HomeAssistant; build:2023.460; iOS 16.5.1) Mobile/HomeAssistant, like Safari",
  "date": "2023-08-03T09:19:15.691Z",
  "frigate_version": {
    "011c4ce06f74e21dc4bf9081f5aa6e2e": "4.0.0/0.12.1-367d724"
  },
  "lang": "en",
  "timezone": "Pacific/Auckland",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.garage",
        "frigate": {
          "url": "http://frigate.home:5000"
        },
        "live_provider": "go2rtc"
      }
    ],
    "dimensions": {
      "aspect_ratio_mode": "unconstrained"
    },
    "live": {
      "controls": {
        "thumbnails": {
          "mode": "below",
          "size": 75
        },
        "next_previous": {
          "style": "none"
        },
        "timeline": {
          "mode": "below",
          "window_seconds": 10800
        }
      }
    },
    "menu": {
      "style": "outside"
    },
    "media_viewer": {
      "controls": {
        "next_previous": {
          "style": "none"
        },
        "thumbnails": {
          "mode": "below",
          "size": 75
        },
        "timeline": {
          "mode": "below"
        }
      }
    },
    "timeline": {
      "controls": {
        "thumbnails": {
          "mode": "below"
        }
      },
      "media": "all",
      "show_recordings": true
    },
    "view": {
      "update_force": false,
      "update_seconds": 0,
      "timeout_seconds": 0,
      "default": "live"
    },
    "image": {
      "refresh_seconds": 0
    },
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_details": true,
          "size": 100
        }
      }
    }
  }
}

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
A few questions:

* Does it only happen in the Home Assistant app on iOS?
* What about a browser on a PC, or Safari on iOS?
* Does the whole page refresh including all the Home Assistant surround, or is it just the card itself?
* Does it refresh once and then it's fine, or keep refreshing over and over?
* Do you notice any pattern in what you're doing when it refreshes?

Some sort of video capture works be really helpful, if that was possible and you can reproduce it.

Thanks for the issue report!

**Comment by scottjjr** [comment]
Hello, only noticed it on iOS iPhone 13 (only device I watch them on).

Appears to just be the card itself, refreshes back to live feed as if the page was just opened, bit painful if you’re mid video or scrolling down a list as have to start all over again.

Managed to screen record one, link here https://youtube.com/shorts/NpHJ0NgdSPk?feature=share

**Comment by dermotduffy** [comment]
Thanks for the video. It's like it is temporarily losing connection to Home Assistant (you can see the momentary 'Reconnecting...').

You missed these questions:

* Does it only happen in the Home Assistant app on iOS or a browser in iOS also?
* Does it refresh once and then it's fine, or keep refreshing over and over?
* Do you notice any pattern in what you're doing when it refreshes?

**Comment by scottjjr** [comment]
Does it only happen in the Home Assistant app on iOS or a browser in iOS also?
only noticed on the iPhone, but that’s all I use it on.

Does it refresh once and then it's fine, or keep refreshing over and over?
does not get into a refresh loop, but it does happen again after a while

Do you notice any pattern in what you're doing when it refreshes?
Either watching a video or scrolling. If it does happen once, it’s likely to happen again within the same usage session

**Comment by dermotduffy** [comment]
OK -- thanks @scottjjr . Note that as I do not own an iOS device, this may be quite difficult for me to make progress on. Best I can do is try to reproduce it on Safari in MacOS somehow.

**Comment by scottjjr** [comment]
Confirming this is an issue in the web browser on PC as well, had it happen when using the other night. Experience the same as above.

wonder if it’s to do with the size/ bitrate of the video, I’m trying to review 4K video with a reasonably high bitrate

**Comment by dermotduffy** [comment]
@scottjjr What OS and browser were you using?

**Comment by scottjjr** [comment]
Apologies for delay have been travelling . Windows 11 with the new Microsoft Edge (which is based on Chromium)

**Comment by dermotduffy** [comment]
> Apologies for delay have been travelling . Windows 11 with the new Microsoft Edge (which is based on Chromium)

NP. OK. I do all my testing in Chrome so it's a little surprising you're seeing this even in a Chromium browser. If you ever figure out a pattern in when this happens, please update this issue...

**Comment by scottjjr** [comment]
I’m wondering if it’s not a fan of the 4K video. Anyway I can track/monitor memory usage?

**Comment by dermotduffy** [comment]
Chrome has a task manager that shows a running  memory total per tab.

`Three dots menu` -> `More Tools` ->  `Task Manager`

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!
