### ISSUE TITLE
Instalation manual unclear

### ISSUE THREAD

**Issue by Forsskieken** [dermotduffy/frigate-hass-card#1249]
Hi There,

I have a Proxmox environment running and of course Frigate. In Home Assistance OS I integrated Frigate via HACS.
I was reading about the optional Lovelace Frigate Card but I'm stuck at this line in the manual.
**Lovelace YAML users**
If Lovelace is in yaml mode. I don't understand what is this Lovelace yaml mode? where can one check this...Isn't Lovelace the default view/template nowadays?
Why is the card not automatically added?

**Comment by dermotduffy** [comment]
If you don't understand it, you're not using it ;-) Is there a reason you cannot just use the [HACS install](https://github.com/dermotduffy/frigate-hass-card#installation) .

> Why is the card not automatically added?

Home Assistant does not automatically add custom cards to a dashboard (and in my experience, automatically generated HA dashboards are never especially useful -- people always want to select what is shown).

**Comment by Forsskieken** [comment]
> If you don't understand it, you're not using it ;-) Is there a reason you cannot just use the [HACS install](https://github.com/dermotduffy/frigate-hass-card#installation) .
I used the HACS install but learned via Youtube that you sometimes need to clear cache.
I had to manually add a resource for the card.

> Why is the card not automatically added?
I was talking about the resource adding inside Home Assistance OS
This could be added inside the manual.
I love the card it's very nice, and the manual is very good. It's just a pity that I was stuck in the very beginning of the install process
Thanks for reading.

**Comment by dermotduffy** [comment]
> I was talking about the resource adding inside Home Assistance OS
> This could be added inside the manual.

Ah, I don't use Home Assistant OS. Can you clarify what you needed to do?

**Comment by Forsskieken** [comment]
I had to add manually this line:
/hacfiles/frigate-hass-card/frigate-hass-card.js
![image](https://github.com/dermotduffy/frigate-hass-card/assets/3041025/1798b33c-19d9-4c88-9e3b-9841d8d5fe33)

**Comment by dermotduffy** [comment]
> I had to add manually this line:

HACS adds a line like this automatically, I'm not sure why it didn't do that for you. I just verified this behavior on a fresh install, with no manual addition:

![hacs](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/261decb5-0529-4a08-94d9-271cf11916b7)

**Comment by Forsskieken** [comment]
I don't know either...
I'm using Promox where frigate is running in a separate LXC and Home Assistant is on a VM. Both have of course different IP addresses.
So maybe a dding a warning that if after install the card can't be added, That one should  add the above line.
I find this important, because if it doesn't work out of the box, people will continue with the manual and change to yaml configuration.
