### ISSUE TITLE
Querystring navigation not operating when parameters in certain order

### ISSUE THREAD

**Issue by kirsch33** [dermotduffy/frigate-hass-card#1253]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

5.2

**Browser and Operating System:**

All devices (iOS/Windows/Debian) and Safari/Chrome

**Description of problem:**

when attempting to navigate to my TLD and include card actions via query string, per the current docs, nothing happens. Card just loads the default view each time, not the requested camera/view in the query string.

example of attempted query string navigation, where my default dashboard has a tab called "frigate":
```
https://example.com/lovelace/frigate?frigate-card-action:camera_select=back&frigate-card-action:live
````

And below in the diagnostic info you can see I have added an `id` parameter of `back` for that camera, so I think it should work?

At first I thought this could be a Cloudflare issue and/or Caddy issue, but I've verified with Chrome's developer tools that the proper URI is being passed to HA, so honestly I am not sure if this is a frigate-hass-card issue or something else, but I'd love some pointers on how to narrow it down

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.8.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
  "date": "2023-08-24T23:12:19.061Z",
  "frigate_version": {
    "5db7149f926abc9b72a9114bd58ba62c": "4.0.0/0.13.0-9857641"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "front"
        },
        "id": "front",
        "frigate": {
          "camera_name": "front",
          "url": "192.168.42.12"
        },
        "triggers": {
          "occupancy": false
        }
      },
      {
        "camera_entity": "camera.back",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "back"
        },
        "id": "back",
        "frigate": {
          "camera_name": "back",
          "url": "192.168.42.12"
        },
        "triggers": {
          "occupancy": false
        }
      },
      {
        "camera_entity": "camera.garage",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "garage"
        },
        "id": "garage",
        "frigate": {
          "camera_name": "garage",
          "url": "192.168.42.12"
        },
        "triggers": {
          "occupancy": false
        }
      }
    ],
    "live": {
      "draggable": false,
      "lazy_load": true,
      "preload": true,
      "controls": {
        "timeline": {
          "mode": "above",
          "style": "ribbon",
          "media": "all",
          "show_recordings": true
        },
        "thumbnails": {
          "mode": "none"
        },
        "builtin": true
      },
      "transition_effect": "none"
    },
    "view": {
      "dark_mode": "off",
      "default": "live"
    },
    "dimensions": {
      "aspect_ratio_mode": "unconstrained",
      "aspect_ratio": "4:3"
    },
    "performance": {
      "profile": "high"
    },
    "menu": {
      "position": "bottom",
      "buttons": {
        "download": {
          "enabled": false
        },
        "camera_ui": {
          "enabled": false
        },
        "expand": {
          "enabled": true
        },
        "media_player": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "microphone": {
          "enabled": true
        },
        "timeline": {
          "enabled": false
        },
        "fullscreen": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        }
      },
      "style": "outside"
    },
    "elements": [
      {
        "type": "custom:frigate-card-conditional",
        "conditions": {
          "camera": [
            "cam-garage"
          ],
          "media_loaded": true,
          "view": [
            "live",
            "image"
          ]
        },
        "elements": [
          {
            "type": "custom:frigate-card-ptz",
            "orientation": "horizontal",
            "style": {
              "transform": "none",
              "right": "20px",
              "top": "70px"
            },
            "service": "amcrest.ptz_control",
            "data_left": {
              "entity_id": "camera.garage_amcrest",
              "movement": "left"
            },
            "data_right": {
              "entity_id": "camera.garage_amcrest",
              "movement": "right"
            },
            "data_up": {
              "entity_id": "camera.garage_amcrest",
              "movement": "up"
            },
            "data_down": {
              "entity_id": "camera.garage_amcrest",
              "movement": "down"
            }
          }
        ]
      }
    ],
    "timeline": {
      "style": "ribbon",
      "media": "snapshots",
      "show_recordings": false
    },
    "media_viewer": {
      "auto_play": "all",
      "snapshot_click_plays_clip": false,
      "controls": {
        "thumbnails": {
          "show_download_control": false,
          "show_favorite_control": false,
          "mode": "none",
          "show_details": false,
          "show_timeline_control": false
        },
        "timeline": {
          "show_recordings": true,
          "media": "all",
          "style": "ribbon",
          "mode": "above"
        },
        "next_previous": {
          "style": "chevrons"
        },
        "builtin": true
      },
      "draggable": false,
      "transition_effect": "none"
    },
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_download_control": false,
          "show_favorite_control": false,
          "show_timeline_control": false
        },
        "filter": {
          "mode": "none"
        }
      }
    }
  }
}
````

**Comment by dermotduffy** [comment]
I can reproduce this. Does it work if you reverse the order (it does for me):

`https://example.com/lovelace/frigate?frigate-card-action:live&frigate-card-action:camera_select=back`

**Comment by kirsch33** [comment]
yes if i reverse the order it does work, never would've thought to try that!

**Comment by kirsch33** [comment]
@dermotduffy quick update, after some additional testing I have realized that while this functionality works fine with a browser (when order is reversed as mentioned), the use of query strings doesnt work well with the HA companion app on iOS. 

as I mentioned in https://github.com/dermotduffy/frigate-hass-card/issues/1246, the use of a subdirectory in the URI should open that exact URI in the HA app, but it does not in this case.

I will open an issue on the appropriate Home Assistant repo to inquire into this as I believe this is not the result of anything frigate-hass-card but something with either iOS or the iOS implementation of HA companion app.

**Comment by dermotduffy** [comment]
> @dermotduffy quick update, after some additional testing I have realized that while this functionality works fine with a browser (when order is reversed as mentioned), the use of query strings doesnt work well with the HA companion app on iOS.

Sounds good. I will keep this issue open to fix the "order" problem.

> I will open an issue on the appropriate Home Assistant repo to inquire into this as I believe this is not the result of anything frigate-hass-card but something with either iOS or the iOS implementation of HA companion app.

Please do, thank you for the update!

**Comment by kirsch33** [comment]
@dermotduffy I _think_ I figured out the issue. its how iOS companion app/Swift encodes the query parameters. I'm not a developer at all, so bear with me, but basically the companion app can't tolerate the colons used in passing the card actions thru.

this can be verified on iOS companion app by using developer tools on HASS to send test notifications to the app:
```yaml
service: notify.mobile_app_austins_iphone
data:
  message: testing
  data:
    push:
      interruption-level: active
    actions:
      - action: URI
        title: View Live
        uri: >-
          homeassistant://navigate/lovelace/frigate?frigate-card-action:live&frigate-card-action:camera_select=back
        destructive: false
```

the above will not work and will fall back to the default dashboard view. however, if you change the URI to escape the colons, it works:

```yaml
homeassistant://navigate/lovelace/frigate?frigate-card-action%3Alive&frigate-card-action%3Acamera_select=back
```

anyways, curious to hear your thoughts on this matter and if it could/should be addressed by you or the iOS app devs, or if it should just remain as-is with this little tidbit of info noted in the docs.

**Comment by kirsch33** [comment]
if anyone is interested to the relevant iOS app code section, I think it’s this:

https://github.com/home-assistant/iOS/blob/e065d9bfe05bf1a179a729c3f63ec7745f5b3446/Sources/App/WebView/IncomingURLHandler.swift#L33C15-L33C15

**Comment by dermotduffy** [comment]
@kirsch33 Good find! Glad to hear it works when escaped.

Sounds like it comes down to my choice of delimiter. I did specifically hunt for whether or not this was a problem, but couldn't find any platform where it didn't "just work". From [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.3) the unreserved characters (ones that can be used without encoding) are the follow -- although others (such as `:` appear to work to varying degrees):

```
      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

So perhaps a fix is to support both `:` and another character (from the above) as the delimiter, e.g.

**Before:**
```
homeassistant://navigate/lovelace/frigate?frigate-card-action:cardID:live&frigate-card-action:cardID:camera_select=back
```

**Other choices:**
```
homeassistant://navigate/lovelace/frigate?frigate-card-action-cardID-live&frigate-card-action-cardID-camera_select=back
homeassistant://navigate/lovelace/frigate?frigate-card-action.cardID.live&frigate-card-action.cardID.camera_select=back
homeassistant://navigate/lovelace/frigate?frigate-card-action_cardID_live&frigate-card-action_cardID_camera_select=back
homeassistant://navigate/lovelace/frigate?frigate-card-action~cardID~live&frigate-card-action~cardID~camera_select=back
```

Of the above, I think `.` probably looks the best.

**Comment by kirsch33** [comment]
i agree, `.` looks the best. do you want me to open a separate issue/request to address this? or keep it with this one?

**Comment by dermotduffy** [comment]
Created a separate one!

**Comment by dermotduffy** [comment]
This weird ordering issue is now fixed in code and will be in the next build.
