### ISSUE TITLE
Thumbnails should not be greyed out in `live` view

### ISSUE THREAD

**Issue by Twiistz** [dermotduffy/frigate-hass-card#1254]
Hi guys,

Hope some of you can help me understand if this is problem or not.

Looking at the picture below, only the latest thumbnail is highlighted. What is the reason for that?

![image](https://github.com/dermotduffy/frigate-hass-card/assets/77859166/6bf7cb63-0ba8-4888-95d6-a285a85e495d)

**Comment by dermotduffy** [comment]
In the media viewer, greyed out thumbnails are those that are not selected / not being viewed. This doesn't make sense in the `live` view and isn't supposed to happen, i.e. is a bug.

**Comment by dermotduffy** [comment]
(Fixed this while I was merging a much larger change, will be in the next release)
