### ISSUE TITLE
Support `.` as an alternative query string delimiter

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#1259]
i agree, `.` looks the best. do you want me to open a separate issue/request to address this? or keep it with this one?

_Originally posted by @kirsch33 in https://github.com/dermotduffy/frigate-hass-card/issues/1253#issuecomment-1701184560_

**Comment by kirsch33** [comment]
@dermotduffy not sure whats going on exactly, but even running the latest dev build if I navigate to (assuming domain is ```https://example.com``` and dashboard is named ```frigate```):

```https://example.com/lovelace/frigate?frigate-card-action.live&frigate-card-action.camera_select=back```

it is not navigating to the correct camera. any ideas?

**Comment by dermotduffy** [comment]
> it is not navigating to the correct camera. any ideas?

I'm reworking this whole section of code as part of #1253 -- please hold that thought, I'm on it (and will test a variety of different combinations).
