### ISSUE TITLE
Cannot autodetect Frigate camera name

### ISSUE THREAD

**Issue by dlWhitaker** [dermotduffy/frigate-hass-card#126]
Hello,

I have completed setting up Frigate as Docker on Unraid with Frigate NVR Proxy and so far things are working. I am now trying to add in the Lovelace card. I am  getting an error that the card cannot bring in the camera entity. I am unsure if this is a Frigate issue that I should raise there or if the configuration I am using with Docker on Unraid with the Frigate Proxy to HA is an issue. I have not yet tried to use the HA Frigate add-on directly. I am looking for some input here where I might go next to resolve my issue. Any help guidance is appreciated. Let me know if more info is needed than below. Thanks in advance!

Error Message on Card Configuration:
“Cannot autodetect Frigate camera name, you need to either set camera_entity and / or frigate_camera_name. “
 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73088968/137233888-733cfdd5-4187-41cf-a9fe-b87789060d8a.png">

Configuration:
Frigate installed as Docker on Unraid. Home Assistant CORE as VM with Frigate NVR Proxy.
 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/73088968/137233902-23ee5a65-700e-4d63-a094-9335e5c8afb0.png">

I have setup one camera for my pilot. Camera works in Frigate from the Docker Web UI and also comes through to HA via the NVR Proxy. 

Config.yml:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/73088968/137234512-27b6efb6-5d74-4f60-b147-9f49ddc7e3fa.png">

  Frigate viewer. I am able to access events, clips, and recordings within the NVR. 
<img width="650" alt="image" src="https://user-images.githubusercontent.com/73088968/137234641-5605ef0f-7d13-4da2-9b38-879279961fce.png">

**Comment by dlWhitaker** [comment]
Hello once again,

The last issue with the spinning save button was my own doing when I had also been playing with my yaml mode settings on Lovelace. When moving that back to UI mode I was able to save the card fine.

From my perspective this resolves my issue. 

If you at all are looking to work on the proxy NVR config at some point I would be happy to help with any testing there. For now I will work with the configuration you have provided. For now I will close my question and thanks again so much for your help!

**Comment by dermotduffy** [comment]
Hi @dlWhitaker -- filed a separate bug to track the work for the NVR proxy.

I still don't understand how you somehow didn't have any camera entities (neither in the card editor dropdown, nor in Home Assistant itself). That suggests the integration may not  have been correctly installed.

Nevertheless, glad you got it to work out. Follow along on that other bug to track progress on the NVR proxy work when I, or someone else, gets around to it in the backlog!
