### ISSUE TITLE
Playback of recordings doesn't work when HA timezone `!=` Browser timezone

### ISSUE THREAD

**Issue by Kenajcrap** [dermotduffy/frigate-hass-card#1267]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.2.0
**Last working release (if known):**
unknown
**Browser and Operating System:**
**Doesn't work on** Firefox for Arch Linux (117.0) 
**Works on** Firefox for Android 107.0 
**Works on** Home Assistant App for Android (2023.8.2-minimal.10992)

**Description of problem:**

card yaml:
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.saladeespera
    live_provider: go2rtc
    icon: mdi:sofa-single
menu:
  buttons:
    recordings:
      enabled: true
    clips:
      enabled: true
    snapshots:
      enabled: false
timeline:
  style: ribbon
  media: all
  show_recordings: true
```
the yaml is processed as valid and doesn't error out.
However, if you navigate to the recordings tab and click on a recording, the playback never starts, and the same goes for if you click on the thick light blue stripe that highlights the position of a recording in the timeline
![image](https://github.com/dermotduffy/frigate-hass-card/assets/25385928/41d2c448-191e-4b65-a7f0-507f06ed47f1)
If instead navigate to the "clips" tab and click on a clip that is associated with that same recording, then the clip plays normally. Same goes for clicking on the thin colored stripe in the timeline that signals an event.

These recordings and clips can both be accessed through Home Assistant's media tab and through Frigade's equivalent.

I noticed 3 identical 502s followed by this error in my browser's console when the playback fails:
the 502:
```
XHRGET
http://[REDACTED]:8123/api/frigate/frigate/vod/2023-09/13/04/saladeespera/utc/index.m3u8?authSig=[REDACTED]
[HTTP/1.1 502 Bad Gateway 19ms]

	
GET
	http://[REDACTED]:8123/api/frigate/frigate/vod/2023-09/13/04/saladeespera/utc/index.m3u8?authSig=[REDACTED]
Status
502
Bad Gateway
VersionHTTP/1.1
Transferred314 B (157 B size)
Referrer Policysame-origin
DNS ResolutionSystem

    	
    Connection
    	keep-alive
    Content-Length
    	157
    Content-Type
    	text/html
    Date
    	Wed, 13 Sep 2023 01:15:17 GMT
    Server
    	nginx/1.22.1
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    DNT
    	1
    Host
    	10.170.15.3:8123
    Referer
    	http://[REDACTED]:8123/lovelace/0
    Sec-GPC
    	1
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/117.0
```
the error
```
Error starting stream, see logs for details (Server failure) ha-hls-player-aef987da.js:11:1284
    render ha-hls-player-aef987da.js:11
    update lit-element.ts:160
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value ha-hls-player.ts:319
    value ha-hls-player.ts:265
    emit index.js:203
    emit hls.ts:287
    trigger hls.ts:298
    handleNetworkError playlist-loader.ts:605
    onError playlist-loader.ts:326
    readystatechange xhr-loader.ts:240
    (Async: EventHandlerNonNull)
    openAndSendXhr xhr-loader.ts:145
    loadInternal xhr-loader.ts:117
    (Async: setTimeout handler)
    retry xhr-loader.ts:283
    readystatechange xhr-loader.ts:237
    (Async: EventHandlerNonNull)
    openAndSendXhr xhr-loader.ts:145
    loadInternal xhr-loader.ts:117
    load xhr-loader.ts:76
    load playlist-loader.ts:347
    onManifestLoading playlist-loader.ts:154
    emit index.js:203
    emit hls.ts:287
    trigger hls.ts:298
    loadSource hls.ts:389
    value ha-hls-player.ts:237
    emit index.js:203
    emit hls.ts:287
    trigger hls.ts:298
    _onMediaSourceOpen buffer-controller.ts:804
    (Async: EventListener.handleEvent)
    onMediaAttaching buffer-controller.ts:161
    emit index.js:203
    emit hls.ts:287
    trigger hls.ts:298
    attachMedia hls.ts:353
    value ha-hls-player.ts:234
    value ha-hls-player.ts:162
    value ha-hls-player.ts:106
    _$AE reactive-element.ts:1378
    performUpdate reactive-element.ts:1343
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
```
I noticed that it was searching the API in UTC, while I was supposed to be using UTC -03:00. This made me review my timezone settings on the containers and on HASS and I noticed that Frigate's container was UTC -03:00, HASS container was UTC, HASS configuration was UTC -03:00 and the main host system was UTC -03:00. 
I tried setting everything to UTC -03:00 but the problem didn't change.
Then I noticed that the particular system was using to to browse the interface had it's timezone set to UTC and **by changing it to UTC -03:00, i was able to solve the problem**

**Frigate card diagnostic information**

I was not able to find this information, will update if I do find out

**Javascript errors shown in the web inspector (if applicable):**
see above

**Additional information:**
Frigate is at the latest stable release

Thank you for your work and for this amazing software

**Comment by dermotduffy** [comment]
> These recordings and clips can both be accessed through Home Assistant's media tab and through Frigade's equivalent.

To clarify, the same recording works correct in HA media browser, and in Frigate -- but not in the card?

And to reproduce I should set my browser timezone to be different from my Home Assistant timezone?

**Comment by Kenajcrap** [comment]
> > These recordings and clips can both be accessed through Home Assistant's media tab and through Frigade's equivalent.
> 
> To clarify, the same recording works correct in HA media browser, and in Frigate -- but not in the card?
> 
> And to reproduce I should set my browser timezone to be different from my Home Assistant timezone?

yes, that's correct. I was experiencing the issue, and when I set the timezone of the device I was using to view Home Assistant to be the same as the one from the Home Assistant host the issue was solved. I will try to reproduce the issue in other browsers in a few hours.

**Comment by Kenajcrap** [comment]
@dermotduffy I'm so sorry if I wasn't able to make this clear because English is not my first language, here are the 3 configurations that were tested:

**Configuration 1:**
Frigate Container ->UTC -3:00
HASS Container -> UTC
HASS Config -> UTC -3:00
Device used to access the HASS interface -> UTC
**Result**: Bug as described

**Configuration 2:**
Frigate Container ->UTC -3:00
HASS Container -> UTC -3:00
HASS Config -> UTC -3:00
Device used to access the HASS interface -> UTC
**Result**: Bug as described

**Configuration 3:**
Frigate Container ->UTC -3:00
HASS Container -> UTC -3:00
HASS Config -> UTC -3:00
Device used to access the HASS interface -> UTC -3:00
**Result**: Fixed

Therefore, I think that the accurate title would be **"Playback of recordings doesn't work when HA timezone != Browser timezone"**
