### ISSUE TITLE
Camera unavailable should not print configuration

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1273]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

Latest

**Last working release (if known):**

If I remember well this was not always like that.

**Browser and Operating System:**

N/A

**Description of problem:**

When my camera becomes unavailable for whatever reason (like bad Wi-Fi for example), the card should only show that the camera is unavailable and not print the entire configuration.

This is an error that is expected to happen, and not something that would require fixing the configuration.

![image](https://github.com/dermotduffy/frigate-hass-card/assets/29582865/d154a435-b4f2-48e2-8153-d4a84413c59d)

**Frigate card diagnostic information**

N/A

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

Déjà vu? No:

- https://github.com/dermotduffy/frigate-hass-card/issues/759

Also, this is especially worse now that the Frigate integration itself reports unavailability:

- https://github.com/blakeblackshear/frigate-hass-integration/issues/406

**Comment by dermotduffy** [comment]
I figured this was coming after the frames/unavailable change :-)

I think I need to treat camera unavailability entirely differently, i.e. not render a top-level error at all, but perhaps render an error message in place of the camera feed. The distinction is that a top-level error will really stop the usability of the card (e.g. a carousel with 10 loaded cameras, if 1 goes unavailable it shouldn't prevent usage of the carousel for the other 9). This will be even worse with the new (unreleased) grid functionality.

**Comment by dermotduffy** [comment]
> Déjà vu? No:

BTW: One of the reasons my development is slow right now is because I'm investing a lot of time in refactoring and adding unittests as I go, specifically to raise the quality bar and prevent regressions. I hope this results in fewer bugs over time (and thus less time fixing them).

**Comment by felipecrs** [comment]
Just to be clear it wasn't my intention at all to pinpoint a regression. I am extremely grateful for your hard work on the card and I know how hard it can be to remember all the small details when doing some refactor without tests to help you catch them (and I know you did major refactors to the card since then).

My intention was only to remind you, and to cross reference the issues.

**Comment by dermotduffy** [comment]
> My intention was only to remind you, and to cross reference the issues.

Of course, I didn't for a moment suspect otherwise!
