### ISSUE TITLE
Missing buttons for recordings and clips 

### ISSUE THREAD

**Issue by harambe88** [dermotduffy/frigate-hass-card#1274]
**Checklist:**

- [x] I updated to the latest version available   ==> not sure. Is this card updated automatically? Is there a button for that?
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

 Win10, MS Edge

**Description of problem:**

 Can't get buttons for clips and recordings to appear anymore when clicking on frigate button. In card coinfiguration all buttons are enabled.

**Frigate card diagnostic information**

Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2023.9.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31",
  "date": "2023-09-19T15:39:05.638Z",
  "frigate_version": {
    "486a6be987fb8a4e8e0cb4b6d6c133e5": "5.0.0-beta.1/0.12.1-367d724"
  },
  "lang": "en",
  "timezone": "Europe/Berlin",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.cam_7links1"
      }
    ],
    "view": {
      "update_force": true,
      "scan": {
        "enabled": false
      }
    },
    "menu": {
      "buttons": {
        "clips": {
          "alignment": "matching",
          "enabled": true
        },
        "snapshots": {
          "alignment": "matching",
          "enabled": false
        },
        "recordings": {
          "enabled": true
        },
        "media_player": {
          "enabled": false
        }
      }
    },
    "live": {
      "show_image_during_load": false
    },
    "image": {
      "mode": "camera"
    },
    "timeline": {
      "style": "ribbon",
      "controls": {
        "thumbnails": {
          "mode": "right"
        }
      }
    }
  }
}
```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
The buttons were working on a supervised installation on a Raspberry 4 32-bit prior to the new frigate version. With the new version of frigate NVR I got "numpy version difference errors" and therefore couldn't use frigate anymore. So I switched to Home Assistant OS/64 bit and restored my backup from the supervised installation.

**Comment by harambe88** [comment]
I'm not sure what "functioning Frigate camera" means. But this camera used to work in my old installation and is working now with life video. I can also watch event videos via web view.

**Comment by dermotduffy** [comment]
`Settings` -> `Devices & Services` -> `Frigate` -> `XX entities` (in the sidebar)

... do you see the exact Entity ID in that list?

**Comment by harambe88** [comment]
![noname-cutout](https://github.com/dermotduffy/frigate-hass-card/assets/45999722/c653efc8-969a-439a-9b0c-cb89190851bc)

**Comment by dermotduffy** [comment]
As you can see, the camera you have configured the card with is not in that list of Frigate cameras :-) I am guessing there are "dead" or misconfigured entities consuming the original names. I see a `camera.cam_7links1_2` (notice the `_2`), this might be your real Frigate camera. Try configuring the card with that camera.

**Comment by harambe88** [comment]
Ouch! What an easy solution. Thank you very much for your help. And congrats to the best NVR addon I know!
