### ISSUE TITLE
Invalid configuration incorrectly reported for title popup controls in refactored code

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#1280]
Built and trying the refactor PR and I am seeing this error

![Screen Shot 2023-10-03 at 13 16 34 PM](https://github.com/dermotduffy/frigate-hass-card/assets/14866235/48dbfe46-cc54-4e3a-b838-d89578299990)

however I don't have that defined in the yaml anywhere

**Comment by dermotduffy** [comment]
Thanks! Real bug, fix added to the PR.
