### ISSUE TITLE
Can you use Frigate love lace card without Frigate backend in HA?

### ISSUE THREAD

**Issue by badnbusy** [dermotduffy/frigate-hass-card#1288]
This is not a bug but more of a question...

I use Frigate and the Lovelace card on my main HA installation, however I have a secondary system which is using the go2rtc addon and the webrtc lovelace card in order to show some non-Frigate RTSP streams from Hikvision cameras.

Is it possible to use the Frigate lovelace card with these without using Frigate integration / backend?

The lovelace card is so ace and I like how you can use left/right to flick between cameras, go full screen and just the general layout compared to the simple webrtc custom card.

If not, and I know this isn't a Frigate lovelace problem, what is the next best card for viewing live camera feeds?

Thank you

**Comment by dermotduffy** [comment]
> Is it possible to use the Frigate lovelace card with these without using Frigate integration / backend?

Absolutely, although features will be much more limited. As a matter of principle, the card will always work for non-Frigate cameras -- and I've been vaguely considering whether we should rename the card.

See here for the functionality differences between camera "engines": https://github.com/dermotduffy/frigate-hass-card#available-camera-engines

Likely of significant relevance to you is [this PR](https://github.com/dermotduffy/frigate-hass-card/pull/1291) which I just literally merged today. As such, it is not yet available in any build. It enables `go2rtc` support for non-Frigate cameras, which it sounds like you need.

**Comment by badnbusy** [comment]
Thanks! How is the engine: generic set in yaml?

**Comment by dermotduffy** [comment]
> Thanks! How is the engine: generic set in yaml?

It'll be autodetected if you use a non-Frigate provided camera. It could be manually set with this in a camera configuration:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.sitting_room
    engine: generic
```

**Comment by badnbusy** [comment]
I don't have any camera entities defined in Home Assistant as I was using the webrtc card which just requires the go2rtc stream name... do I need to create a generic camera entity and will that make it not be efficient if not using go2rtc then?On 8 Oct 2023 20:43, Dermot Duffy ***@***.***> wrote:

Thanks! How is the engine: generic set in yaml?

It'll be autodetected if you use a non-Frigate provided camera. It could be manually set with this in a camera configuration:
type: custom:frigate-card
cameras:
  - camera_entity: camera.sitting_room
    engine: generic

**Comment by dermotduffy** [comment]
> I don't have any camera entities defined in Home Assistant as I was using the webrtc card which just requires the go2rtc stream name... do I need to create a generic camera entity and will that make it not be efficient if not using go2rtc then

No entities required at all. Here is a live working config from my dev setup, note the absence of anything home assistant or Frigate related:

```yaml
type: custom:frigate-card
cameras:
  - live_provider: go2rtc
    go2rtc:
      stream: office
      url: http://nuc:1984
```

**Comment by badnbusy** [comment]
Will this work at present or only with your recent PR to support go2rtc streams?

**Comment by dermotduffy** [comment]
> Will this work at present or only with your recent PR to support go2rtc streams?

You'll need to wait for the `v6` release. If you cannot wait, and are prepared to experiment unsupported, you can also [install an unreleased version](https://github.com/dermotduffy/frigate-hass-card#advanced-users-installing-unreleased-versions) or build your own.

**Comment by dermotduffy** [comment]
Closing, as I don't think there's anything else to do here!
