### ISSUE TITLE
Timeline "choose date" not popping on iOS devices

### ISSUE THREAD

**Issue by ronluna** [dermotduffy/frigate-hass-card#1289]
When trying to get the "Choose date" popup to pop by tapping on it from an iOS device the calendar simply won't come out... However the Pan button does seems to work... Wondering if anyone else having this issue?

<img width="203" alt="image" src="https://github.com/dermotduffy/frigate-hass-card/assets/9822111/95d2a185-3f15-42da-9747-39c54c99fd99">

FRIGATE-HASS-CARD  Version 5.2.0

**Comment by kirsch33** [comment]
I can confirm this as well

**Comment by kirsch33** [comment]
i think it may be related to this:
https://github.com/flatpickr/flatpickr/issues/1928

maybe setting disablemobile to true will fix?

https://flatpickr.js.org/mobile-support/

**Comment by dermotduffy** [comment]
Fixed, will be in the next release.
