### ISSUE TITLE
Issues with the Frigate HA Add On

### ISSUE THREAD

**Issue by sharpopotamus** [dermotduffy/frigate-hass-card#13]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v0.1.4

**Last working release (if known):**
N/A

**Browser and Operating System:**
I'm running the Frigate add on for Hassio behind a reverse proxy, and I've tried accessing from both Chrome and Edge running on Windows 11.

**Description of problem:**
While the live camera view works great, I don't think the card is successfully communicating with the Frigate HA addon. For example, when I try to bring up the clips view on a camera, the card goes grey and shows a small exclamation point icon. The developer console gives this error message: "SyntaxError: Unexpected token < in JSON at position 0"

And when I click "view frigate UI," it takes me to a blank screen with the home assistant wrapper. The card pulls up "https://homeassistant.[mydomain].org/ccab4aaf_frigate/cameras/doorbellCam," but that url doesn't go anywhere. But if I change the Frigate URL to "http://[internal IP address]:5000," it happily appends "/cameras/doorbellCam" and takes me to the right screen.

**Javascript errors shown in the web inspector (if applicable):**

```
frigate-hass-card.js?hacstag=394082552014:406 SyntaxError: Unexpected token < in JSON at position 0
_getEvents @ frigate-hass-card.js?hacstag=394082552014:406
async function (async)
_getEvents @ frigate-hass-card.js?hacstag=394082552014:406
_renderEvents @ frigate-hass-card.js?hacstag=394082552014:409
render @ frigate-hass-card.js?hacstag=394082552014:457
update @ frigate-hass-card.js?hacstag=394082552014:185
performUpdate @ frigate-hass-card.js?hacstag=394082552014:148
_enqueueUpdate @ frigate-hass-card.js?hacstag=394082552014:148
async function (async)
_enqueueUpdate @ frigate-hass-card.js?hacstag=394082552014:148
requestUpdateInternal @ frigate-hass-card.js?hacstag=394082552014:148
set @ frigate-hass-card.js?hacstag=394082552014:148
_changeView @ frigate-hass-card.js?hacstag=394082552014:406
_menuActionHandler @ frigate-hass-card.js?hacstag=394082552014:423
_callAction @ frigate-hass-card.js?hacstag=394082552014:365
V.menuMode.expand.V.expand @ frigate-hass-card.js?hacstag=394082552014:381
handleEvent @ frigate-hass-card.js?hacstag=394082552014:82
I.__boundHandleEvent @ frigate-hass-card.js?hacstag=394082552014:82

```

**Additional information:**

**Comment by dermotduffy** [comment]
That certainly appears like the card cannot talk to the Frigate backend (actually reads like it is talking to something  that is not the Frigate backend!).

What URL have you configured it to talk to? (In the options for the card, see [screenshot](https://github.com/dermotduffy/frigate-hass-card#card-editing)).

Whatever URL you configure it with, you should be able to just visit that same URL manually in your browser and reach the Frigate backend. If you can't, the card won't be able to use that URL either.

**Comment by noorbertt** [comment]
I have a same issue.
If I use the ccab4aaf-frigate:5000 address is working fine and nice, but when I am not in my local network I can not see anything except my webrtc feed. 
I cant and wont forwarding the 5000 port :(

**Comment by dermotduffy** [comment]
Hi all, I have a fairly complete fix for this ready. I hope to have a pre-release in the next few days.

**Comment by dermotduffy** [comment]
FYI: [The new pre-release is available for testing](https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1283669)

[Please open new bugs/requests as appropriate](https://github.com/dermotduffy/frigate-hass-card/issues/new/choose)
