### ISSUE TITLE
Camera card became small for seconds when switching to live view

### ISSUE THREAD

**Issue by Regressor** [dermotduffy/frigate-hass-card#1302]
**Release with the issue:**
I'm using Frigate lovelace card v5.2.0

**Browser and Operating System:**
I got this problem on Windows10/Chrome, Windows10/Firefox, Linux/Chrome

**Description of problem:**
I added a grid card to home assistant panel and two Frigate camera cards into it. Default view - image snapshot. All works fine, but when I'm trying to switch one of the cameras to live view it shrinks and became small. After 2-3 seconds of loading video it returns to its original size. I don't want to preload live view in background (enabling it solve problem!) because live view rarely used and background preload use server cpu every time I open panel.

This is default view with snapshots images:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/17557802/92c5c3cc-af51-40ac-b393-3cb0599bcb94)

This is after swtching to live view:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/17557802/f522bbd2-3bb9-44d9-adab-9aedfc7ef1ac)

**Frigate card diagnostic information**
{
  "ha_version": "2023.10.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
  "date": "2023-10-19T01:24:21.069Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "Asia/Vladivostok",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.10_10_105_8",
        "live_provider": "auto"
      }
    ],
    "view": {
      "default": "image",
      "camera_select": "image",
      "dark_mode": "off",
      "timeout_seconds": 240
    },
    "image": {
      "mode": "camera"
    },
    "menu": {
      "buttons": {
        "image": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        }
      }
    },
    "live": {
      "preload": false,
      "lazy_unload": "hidden",
      "auto_play": "all",
      "auto_pause": "all",
      "auto_mute": "all",
      "auto_unmute": "never",
      "lazy_load": false,
      "zoomable": false,
      "layout": {
        "position": {
          "x": 100,
          "y": 100
        }
      },
      "draggable": false,
      "show_image_during_load": true
    },
    "media_viewer": {
      "auto_play": "all",
      "auto_pause": "all",
      "auto_mute": "all",
      "auto_unmute": "selected",
      "draggable": false,
      "zoomable": false,
      "transition_effect": "none"
    }
  }
}
```json

```

**Javascript errors shown in the web inspector (if applicable):**
No js errors during switching

```

```

**Additional information:**
Changing browser window size brings camera card size to original before live view starts.

**Comment by dermotduffy** [comment]
To be clear: The issue is that the live view video is momentarily "small" within the Frigate card, before the card resizes it to the correct size within 2-3s? Does this always happen?

**Comment by Regressor** [comment]
> To be clear: The issue is that the live view video is momentarily "small" within the Frigate card, before the card resizes it to the correct size within 2-3s? Does this always happen?

Yes. It became small just after click live video icon and stay small 2-3 seconds until video starts playing. It happen always on chrome and firefox. I didn't checked on other browsers.

**Comment by dermotduffy** [comment]
What happens if you include this in your config:

```yaml
live:
  show_image_during_load: false
```

This should not attempt to show a still image of the video feel while it's loading. So it should perhaps take longer to load something useful, but I'm curious if there is anything being rendered "small". If not, the issue is with the still image (not the video feed).

**Comment by Regressor** [comment]
> What happens if you include this in your config:
> 
> ```yaml
> live:
>   show_image_during_load: false
> ```
> 
> This should not attempt to show a still image of the video feel while it's loading. So it should perhaps take longer to load something useful, but I'm curious if there is anything being rendered "small". If not, the issue is with the still image (not the video feed).

This helps a little - after switching to live black player appears and after some delay just before playing it quickly changes size to small and back.

**Comment by clearwave1** [comment]
I also have the small image sometimes. However, all the time, the live video is first some other resolution (either really small or bigger than it should be) and it is video (not still) but the frame rate is really low.

It takes between 2 - 5 seconds to show the proper resolution at the proper frame rate.

**Comment by clearwave1** [comment]
Any update on when this might be fixed?

Thanks for the great work.

**Comment by dermotduffy** [comment]
> Any update on when this might be fixed?

So far I haven't been able to reproduce this at all, but I haven't spent much time on it. It also sounds like a minor issue so not really a particularly high priority. It's in the `v6.0.0` milestone, so I do plan to investigate this properly before the next release. There are currently 16 open issues attached to that milestone, which I'm slowly working through. Can't give an ETA I'm afraid. If you're a developer, [help would very much be appreciated](https://github.com/dermotduffy/frigate-hass-card/issues/1248).

**Comment by GarethBlain** [comment]
I get this issue all the time and weirdly it SEEMS for me to be the first window in the list (don't think I've EVER seen it in the second cam and I only have two so not sure about more).

I thought it was a specific camera but recently re-ordered the cameras on the screen and it started happening with the new top one which is a completely different camera (ESPHome cam instead of ReoLink).

Also for me this issue occures and doesn't resolve it's self. A page reload(F5) in Chrome sometimes fixes it but not all the time. If I switch to another page and back it DOES almost always resolve it!

**Comment by dermotduffy** [comment]
@GarethBlain Mind holding down your Frigate menu button in the card and pasting the diagnostics in here?  This might help me find the pattern between you and the original poster to understand why it's happening to only some people...

**Comment by clearwave1** [comment]
I didn't know you could do this. I don't know if this is helpful but I have this card in its own view and it is only when I switch to that view, that the first camera shows up strange (either small or wrong resolution too big) for 3 - 5 seconds and then corrects itself. At that point, if I cycle through the cameras, all are fine until I leave and return to the view.

Here is the output from mine:

Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.2.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "date": "2024-02-28T13:29:39.000Z",
  "frigate_version": {
    "61947a4ca7648483911805135d1f5f04": "5.0.1/0.13.2-6476f8a"
  },
  "lang": "en",
  "timezone": "America/Toronto",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front_db",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [],
          "stream": "front_db_main"
        }
      },
      {
        "camera_entity": "camera.front_hall",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "mse"
          ],
          "stream": "front_hall"
        }
      },
      {
        "camera_entity": "camera.office",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "mse"
          ],
          "stream": "office"
        }
      },
      {
        "camera_entity": "camera.office2",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": []
        }
      },
      {
        "camera_entity": "camera.office3",
        "live_provider": "go2rtc"
      }
    ],
    "menu": {
      "style": "overlay",
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "snapshots": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        },
        "download": {
          "enabled": false
        }
      },
      "alignment": "right",
      "position": "top"
    },
    "live": {
      "auto_mute": "all",
      "preload": false,
      "lazy_load": true
    }
  }
}

**Comment by GarethBlain** [comment]
> @GarethBlain Mind holding down your Frigate menu button in the card and pasting the diagnostics in here? This might help me find the pattern between you and the original poster to understand why it's happening to only some people...

Sorry for the slow reply. I've been experimenting trying to see if splitting the cards out into two seperate cards instead of both in the same Grid card helps. It's inconclusive as I've not had it happen on ether page (the original page with them in the same Grid Card and the one with them as two seperate issolated cards) since! 🙈 

Here is my output from the first one:

Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.3.0",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "date": "2024-03-07T09:33:27.866Z",
  "frigate_version": {
    "fdfe12239a770baae7679d747ba75f26": "5.0.1/0.13.2-6476f8a"
  },
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.kitchen1",
        "title": "Kitchen"
      }
    ]
  }
}

**Comment by dermotduffy** [comment]
If anyone is testing the `dev` branch, I'd love to know if this still happens as [I've fixed the issue I found that could cause this](https://github.com/dermotduffy/frigate-hass-card/issues/1302#issuecomment-1982519770). For now, I'm going to wait on this until we see if people still experience it in the new build.

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!
