### ISSUE TITLE
motioneye clips

### ISSUE THREAD

**Issue by trevorstuart24** [dermotduffy/frigate-hass-card#1308]
I cannot get clips to play from motioneye using the frigate card. I can add the camera and I can see the clips without a thumbnail image(timestamp is correct), but whenever I click any clips it fails to load. I've tried adding the formatting for the motioneye camera engine options but nothing seems to have any effect.

Current Release, home assistant OS, motioneye add on.

**Comment by dermotduffy** [comment]
> I cannot get clips to play from motioneye using the frigate card. I can add the camera and I can see the clips without a thumbnail image(timestamp is correct), but whenever I click any clips it fails to load. I've tried adding the formatting for the motioneye camera engine options but nothing seems to have any effect.

I am going to guess you have a networking issue. MotionEye integration doesn't proxy clips/snapshots through to the browser like Frigate does -- so in order for it to work you must:

* Have your motionEye integration configured with an address that is both accessible by HA and by your browser
* You must not mix `https` and `http`, i.e. if you access your HA instance over `https` you need to configure your motionEye integration with a `https` URL, which may include you needing to setup a reverse proxy in front of it.

Simple way to test: Can you view motionEye media in the Home Assistant Media browser (on the left menu)? If this doesn't work, your issue is not (directly) the card.

**Comment by trevorstuart24** [comment]
> > I cannot get clips to play from motioneye using the frigate card. I can add the camera and I can see the clips without a thumbnail image(timestamp is correct), but whenever I click any clips it fails to load. I've tried adding the formatting for the motioneye camera engine options but nothing seems to have any effect.
> 
> I am going to guess you have a networking issue. MotionEye integration doesn't proxy clips/snapshots through to the browser like Frigate does -- so in order for it to work you must:
> 
> * Have your motionEye integration configured with an address that is both accessible by HA and by your browser
> * You must not mix `https` and `http`, i.e. if you access your HA instance over `https` you need to configure your motionEye integration with a `https` URL, which may include you needing to setup a reverse proxy in front of it.
> 
> Simple way to test: Can you view motionEye media in the Home Assistant Media browser (on the left menu)? If this doesn't work, your issue is not (directly) the card.

Seems you are correct. Media tab similarly shows the clips but won’t let me watch them.

I was just reading into how to allow Motioneye to play in a browser but I’m not figuring it out yet. I already have cloud flared setup. Can I use that?

**Comment by dermotduffy** [comment]
> I was just reading into how to allow Motioneye to play in a browser but I’m not figuring it out yet. I already have cloud flared setup. Can I use that?

Probably, although I think you'd need to expose your motionEye instance to the internet if you did that which is a bad idea for other reasons. The usual approach is to install Apache, nginx, Traefik or any other reverse proxy locally, and put both your HA instance and motionEye server behind it. This is not for the feint of heart...

**Comment by trevorstuart24** [comment]
> > I was just reading into how to allow Motioneye to play in a browser but I’m not figuring it out yet. I already have cloud flared setup. Can I use that?
> 
> Probably, although I think you'd need to expose your motionEye instance to the internet if you did that which is a bad idea for other reasons. The usual approach is to install Apache, nginx, Traefik or any other reverse proxy locally, and put both your HA instance and motionEye server behind it. This is not for the feint of heart...

damn I wish it was possible to just use frigate for esp32 cams. Doesn’t seem to be possible. Spent many hours trying. Should have just spent more money and less time with those cameras

**Comment by dermotduffy** [comment]
> damn I wish it was possible to just use frigate for esp32 cams. Doesn’t seem to be possible. Spent many hours trying. Should have just spent more money and less time with those cameras

Sorry, I have no specific advice for you other than that _should_ be possible, although I think CPU expensive. In case you haven't, you could raise and discuss here and perhaps get some help: https://github.com/blakeblackshear/frigate/discussions/7532

**Comment by diamant-x** [comment]
> * Have your motionEye integration configured with an address that is both accessible by HA and by your browser

Sorry to hijack this topic, but I'm facing same issue as OP.
I'm using the official motioneye integration, which uses ingress to access its clips. Media Browser from HA is able to browse and see the files, but the card says 'no media'.
I'm wondering:

- would ingress-only motioneye NOT be supported by any chance (as it is not a open-browser accesible URL, but only through HA)?

If so, and given most people may initiate themselves to motioneye through the official addons, any chance to support ingress-enabled connections? 
Or as a work around, a way to tell the file/folder path in the OS system to browse for files?

Thanks!

**Comment by dermotduffy** [comment]
> If so, and given most people may initiate themselves to motioneye through the official addons, any chance to support ingress-enabled connections?

I don't have motionEye installed as an addon (or installed at all!), so I have never tested this -- but if media works via the Home Assistant browser, I would have expected it to "just work" as the card is using the same APIs, or perhaps there is some small change required. I'd welcome a PR from someone if you can figure it out. If this issue gets enough thumbs up, I can explore myself, but there's a non-trivial backlog already so might be a while...

**Comment by diamant-x** [comment]
>  the card is using the same APIs, or perhaps there is some small change required. 

I'm happy to troubleshoot it. Is there any way to see what API query or path the card is trying to resolve, or how can I check it?

**Comment by dermotduffy** [comment]
[Issue cleanup] I'm going to close this issue as I don't think there is anything for the card to do per se. PRs are always welcome to improve camera coverage!

**Comment by diamant-x** [comment]
> > the card is using the same APIs, or perhaps there is some small change required.
> 
> I'm happy to troubleshoot it. Is there any way to see what API query or path the card is trying to resolve, or how can I check it?
> 
> Thanks!

I left this proposal in the past to try to see why the clips from motioneye are not loading. It was shared that only being able to see the media from the media tab is not enough. 
Otherwise the card can remove the motioneye part to clean up the code.

Had any one successfully used the card with motioneye in one of the latest releases of home assistant? (maybe it broke along the way)

**Comment by dermotduffy** [comment]
> I left this proposal in the past to try to see why the clips from motioneye are not loading. It was shared that only being able to see the media from the media tab is not enough.

If the a user can see motionEye media in the media browser, they should be able to see them in the card. If that is not the case, I'll re-open this issue. It won't be that much work to reinstall motionEye to test ...
