### ISSUE TITLE
Mini timeline not showing "Built-in video controls" on events loaded from timeline clicks.

### ISSUE THREAD

**Issue by ronluna** [dermotduffy/frigate-hass-card#1310]
When clicking on a timeline event the recorded event will start playing just fine but the built-in video control won't show. Click the chevrons to load previous or next event will show the "Built-in video control" but not for the event that was loaded from the timeline.

I have tried many different configurations but the loaded event that was selected by clicking on the timeline simply won't show the built-in video controls. 

any ideas ?

**Comment by dermotduffy** [comment]
Hmm, that's surprising, I can't imagine why that would happen only with timeline events. A quick play around and I'm afraid I can't reproduce it.

Would it be possible to take a recording / screen capture of the issue happening? And include your config?

Thank you!

**Comment by ronluna** [comment]
Here it is:

https://github.com/dermotduffy/frigate-hass-card/assets/9822111/b43b7b85-39e9-4599-9203-3925cec01310

`
type: custom:frigate-card
card_id: main_nvr_1
cameras:
  - camera_entity: camera.birdseye
    title: Birdseye
    dependencies:
      all_cameras: true
  - camera_entity: camera.driveway_front_10_1_8_92
    title: Driveway
    live_provider: go2rtc
  - camera_entity: camera.front_door_intercom_hikvision_nvr_proxy_10_1_8_15
    title: Front Intercom
    live_provider: go2rtc
  - camera_entity: camera.service_entrance_north_corner_10_1_8_91
    title: Service Entrance
    live_provider: go2rtc
  - camera_entity: camera.driveway_north_side_to_front_10_1_8_82
    title: Driveway Nort to Front
    live_provider: go2rtc
  - camera_entity: camera.front_south_corner_10_1_8_90
    title: South Corner
    live_provider: go2rtc
  - camera_entity: camera.front_south_corner_to_north_10_1_8_83
    title: Front South Corner to North
    live_provider: go2rtc
  - camera_entity: camera.sideyard_south_corner_10_1_8_93
    title: Southyard South
    live_provider: go2rtc
  - camera_entity: camera.sideyard_north_10_1_8_86
    title: Sideyard North
    live_provider: go2rtc
  - camera_entity: camera.sideyard_rear_north_corner_10_1_8_87
    title: Sideyard North Corner
    live_provider: go2rtc
  - camera_entity: camera.pool_rear_south_corner_10_1_8_85
    title: Pool South Corner
    live_provider: go2rtc
  - camera_entity: camera.pool_rear_west_corner_10_1_8_81
    title: Pool West Corner
    live_provider: go2rtc
  - camera_entity: camera.backyard_rear_north_corner_10_1_8_84
    title: Backyard North Corner
    live_provider: go2rtc
  - camera_entity: camera.backyard_east_corner_10_1_8_89
    title: Backyard East Corner
    live_provider: go2rtc
view:
  scan:
    enabled: false
menu:
  style: outside
  buttons:
    frigate:
      enabled: false
    timeline:
      enabled: true
    screenshot:
      enabled: false
    mute:
      enabled: true
    expand:
      enabled: true
    recordings:
      enabled: true
    substreams:
      enabled: false
    image:
      enabled: false
    play:
      enabled: true
    microphone:
      enabled: true
timeline:
  style: ribbon
  controls:
    thumbnails:
      mode: below
  show_recordings: false
  media: all
live:
  controls:
    thumbnails:
      mode: below
    next_previous:
      style: chevrons
    title: {}
    builtin: true
    timeline:
      show_recordings: false
  layout:
    fit: contain
    position:
      x: 50
      'y': 50
  lazy_load: true
  draggable: false
media_viewer:
  controls:
    next_previous:
      style: chevrons
    thumbnails:
      mode: below
    title:
      duration_seconds: 3
      mode: none
    timeline:
      mode: below
      media: all
      show_recordings: false
    builtin: true
  draggable: false
  layout:
    position:
      x: 50
      'y': 50
    fit: contain
  snapshot_click_plays_clip: true
media_gallery:
  controls:
    thumbnails:
      show_details: true
    filter:
      mode: left
performance:
  features:
    animated_progress_indicator: true
    media_chunk_size: 25
  style:
    border_radius: true
    box_shadow: true
dimensions:
  min_height: '4500'
  aspect_ratio_mode: unconstrained
image:
  mode: camera


`

**Comment by dermotduffy** [comment]
Thank you. Great video. I agree that is broken and very strange!

**Comment by ronluna** [comment]
What I think it’s happening is that the built-in controls are falling on to the incorrect position of the carrousel. Take a closer look around second 35 of the video. It seems like the built-in control layer shows briefly while sliding into the selected video.

**Comment by bedbug1226** [comment]
Yeah this seems to be happening to me as well where the play buttons sometimes show up on the first camera loaded until I switch off and back to it.

**Comment by dermotduffy** [comment]
I have submitted a PR that may address this issue, although since I have not been able to reproduce it it's a bit of a guess. I'll keep this open for now until the next release comes out and can be tested...

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!
