### ISSUE TITLE
Allow the PTZ to be controlled by keyboard

### ISSUE THREAD

**Issue by t0ny-peng** [dermotduffy/frigate-hass-card#1315]
**Is your feature request related to a problem? Please describe.**

One of my cameras supports PTZ, and can be controlled by a Home assistant `button` entity. I've been using the `custom:frigate-card-ptz` element and it worked fine. Just wonder if there's a way to control the camera using keyboard. I'm not a JS developer, but I assume the arrow keys can be definitely captured. 

**Describe the solution you'd like**

The `custom:frigate-card-ptz` element supports controlling the camera via arrow key.

**Describe alternatives you've considered**

Write a Python script and run it locally?

---

Thanks!

**Comment by dermotduffy** [comment]
Fixed in code, will be in the next release.
