### ISSUE TITLE
Problem loading Frigate Card on 13 Beta 4

### ISSUE THREAD

**Issue by LordNex** [dermotduffy/frigate-hass-card#1320]
See below 
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
0.13.0beta4
**Last working release (if known):**
12.1
**Browser and Operating System:**
Mostly iOS Home Assistant App but also Windows with any browser
any browser

**Description of problem:**

Every time since I've loaded and upgraded to Frigate 13beta4 everything works that should work, except the frigate card itself. If I goto the proxy addon, as my frigate server is a separate Linux server with a Google Coral TPU, the card fails. I can roll it back and rebuild the database but that's the best I can do and I'd prefer to use the latest if possible

Don't know if this is related or not but ever since upgrading to the latest card "Birdseye" no longer showed up as a camera and cannot be selected
**Frigate card diagnostic information**
See below

Na
```

  "ha_version": "2023.11.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.1.0) Mobile/HomeAssistant, like Safari",
  "date": "2023-11-06T22:48:55.542Z",
  "frigate_version": {
    "cc5094b175583f1890de1995aa5d3d82": "5.0.0-beta.2/0.13.0-65e3e67"
  },
  "lang": "en",
  "timezone": "America/Chicago",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "input_name": "",
    "input_entity": "camera.side_doorbell_main",
    "cameras": [
      {
        "camera_entity": "camera.sidedoorbell",
        "frigate": {
          "url": "http://192.168.1.155:5000/"
        },

```
Na
**Javascript errors shown in the web inspector (if applicable):**
Ma
```
na
```

**Additional information:**
Na

**Comment by dermotduffy** [comment]
Try upgrading your integration to https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3

**Comment by LordNex** [comment]
When I show all betas under HACS the closest I see is 5.0.0 beta2. I had been using 5.2.0 which I assumed was the correct version. What’s the best way to download this card? Sorry if it’s a simple answer, I’m just not seeing it.

Benjamin T Powers

On Nov 6, 2023, at 5:04 PM, Dermot Duffy ***@***.***> wrote:

﻿

Try upgrading your integration to https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3

**Comment by dermotduffy** [comment]
Just to reiterate: I'm guessing the problem may not be the card at all, but rather an outdated Frigate integration. If you installed there integration via HACS, find the Frigate integration there and chose 'Update Information', make sure 'Show beta versions' is ticked and you did see v5. 0.0-beta.3 .

(Not at my computer now, above best I can do from memory!)

**Comment by LordNex** [comment]
Here’s what I get with that card


Benjamin T Powers

On Nov 6, 2023, at 5:04 PM, Dermot Duffy ***@***.***> wrote:

﻿

Try upgrading your integration to https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3

**Comment by LordNex** [comment]
No my install of Frigate is on a separate server all together. The card just reflects what the proxy integrations brings into HA. Which I can see on a normal card so I know it’s not frigate. It’s has to be the version 5.2.0 card which is the latest I can find here

<https://github.com/dermotduffy/frigate-hass-card/releases>
Releases · dermotduffy/frigate-hass-card<https://github.com/dermotduffy/frigate-hass-card/releases>
github.com<https://github.com/dermotduffy/frigate-hass-card/releases>
[apple-touch-icon-180x180-a80b8e11abe2.png]<https://github.com/dermotduffy/frigate-hass-card/releases>


I don’t even see a 5.0.0beta4. Which would still be a step back from what I have for not in just going to point the card at the direct stream until I can get frigate to proxy the correct stream.

Benjamin T Powers

On Nov 6, 2023, at 5:18 PM, Dermot Duffy ***@***.***> wrote:

﻿

Just to reiterate: I'm guessing the problem may not be the card at all, but rather an outdated Frigate integration. If you installed there integration via HACS, find the Frigate integration there and chose 'Update Information', make sure 'Show beta versions' is ticked and you did see v5. 0.0-beta.3 .

(Not at my computer now, above best I can do from memory!)

**Comment by dermotduffy** [comment]
The card and the integration are different things. You are running an older version of the integration. Please update it. I'm not certain this will fix your issue, but I need to rule it out. I can't support you further until you do this. v5.0.0-beta.3 is the latest integration version (do not confuse this with the card, which coincidentally is v5.2.0 latest).

**Comment by LordNex** [comment]
I know the difference. I’ve been running this system for 5 years. I upgraded my docker-compose build to the latest version on Linux Server with the latest docker version. This should be the belownbersion based on the below link. Now if you've taken over care of the card, cool. But explain that and how we're supposed to replace the one he had listed which only goes up to 5.2.0 in HACS. I can take a web browser and point it at my frigate server and it's pulling in streams just like it should. I go look at the Frigate “Integration” not “add on”   , which I'm only using the proxy part of in home assistant. It has working fine under frigate:stable which is version 0.12.1 but since Inseem the beta and have heavy hardware behind it, is give it a try. But I can get to the Proxy Addon that adds the cameras in the side bar. Looks thhr Same as it does I just go to it by a web page. The reason for the card is all the other add one it brings sd fat as being able to view and scrub old media directly from home assistant. Let me know if that wasn't clear enough but the issue has to be with the csrd

The one mother thing that might be causing an issue is the fact that I'm using Dwains Dashboard with the card on the main page. Now DD Issues aside, and there are many, in was able to view realtime or past events directly from the card. So I think it's something with the card attempts to load the entity from the error.

Frigate Current Version
0.13.0-65E3E67.


<https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0-beta4>
Release 0.13.0 Beta 4 · blakeblackshear/frigate<https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0-beta4>
github.com<https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0-beta4>
[apple-touch-icon-180x180-a80b8e11abe2.png]<https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0-beta4>


Benjamin T Powers

On Nov 6, 2023, at 5:36 PM, Dermot Duffy ***@***.***> wrote:

﻿

The card and the integration are different things. You are running an older version of the integration. Please update it. I'm not certain this will fix your issue, but I need to rule it out. I can't support you further until you do this. v5.0.0-beta.3 is the latest integration version (do not confuse this with the card, which coincidentally is v5.2.0 latest).

**Comment by LordNex** [comment]
Sorry was in email

When intey and add the repository this is what I get 

When I try and goto HACS and try to add a custom repository, then add 

https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3

As either an integration or Lovelace. I get this

![image](https://github.com/dermotduffy/frigate-hass-card/assets/9270948/11c3f283-b77d-4979-9465-c54c014b31d1)

**Comment by LordNex** [comment]
If I try and add 

https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3

To add on optional repositories I get this

![image](https://github.com/dermotduffy/frigate-hass-card/assets/9270948/1490b68f-005f-4442-a002-368d46ff75d3)

**Comment by LordNex** [comment]
Hopefully that explains what its doing when trying to import it. Not in an delete that one that there. But again I though that was seprate from the card itself.

**Comment by LordNex** [comment]
Maybe it's something for some of us only use the proxy instead of the entire add on? Like I said my frigate is separate from my Home Assistsnt. But is closely tied to it with DoubleTake, CompreFace, and Deep Stack. But those are not the issue here

**Comment by LordNex** [comment]
Here's what the card produces

![image](https://github.com/dermotduffy/frigate-hass-card/assets/9270948/83691e46-f772-4500-8ff9-67fde3693b2e)

**Comment by LordNex** [comment]
> The card and the integration are different things. You are running an older version of the integration. Please update it. I'm not certain this will fix your issue, but I need to rule it out. I can't support you further until you do this. v5.0.0-beta.3 is the latest integration version (do not confuse this with the card, which coincidentally is v5.2.0 latest).

No I see what your saying. What I'm saying is I have the latest version. I could spin up a whole other Frigate server directly on my HA if wanted. But I don't. I have a separate frigate server and use the add ins proxy service. Now weather that loads the card or not I have no idea. The proxy add on works fine. Just not the card. I'm also on iOS 17.1 if that makes a difference. Other than that everything is at it's latest version.

**Comment by dermotduffy** [comment]
> No I see what your saying. What I'm saying is I have the latest version. 

That is not what the diagnostics at the start of the issue show:

```
    "cc5094b175583f1890de1995aa5d3d82": "5.0.0-beta.2/0.13.0-65e3e67"
                                         ^^^^^^^^^^^^
```

> If I try and add https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.3

You shouldn't need to do this, if you've already added the integration you do not need to add it again. Can you clarify why [these steps](https://github.com/dermotduffy/frigate-hass-card/issues/1320#issuecomment-1797015742) do not work?

**Comment by LordNex** [comment]
No no you were right. My bad. Case of the way too late night coding, and not seeing the forest for the trees. 

I'm fixed for the most part. Still can't get birds eye to come in and instill have a few old crappy Wyze pan cams around. They don't always stay connected sndnice noticed if one drops. The code on the card scrambles until it comes back or I hide it from the UI.
