### ISSUE TITLE
Birdseye Not Working on 13 Beta 4

### ISSUE THREAD

**Issue by LordNex** [dermotduffy/frigate-hass-card#1321]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
13beta4
**Last working release (if known):**
12.1 I think?
**Browser and Operating System:**
Home Assistant iOS App but it appears under Chrome and Edge on Windows 11 Pro as well. 

**Description of problem:**
Everytime I try to add the Birdseye view I get an error. Prior to I think version 11, a camera entity was never made but if you names it birdseye and had the right URL it would display. Then they actually made Birdseye a camera entity inside Home Assistant with I think version 11 or 12. But ever since I upgraded my server, the HA Add on, and the card all to the latest version. It hasn't created an entity and when I try to manually enter it I get the below error in the card

**Frigate card diagnostic information**

```json

troubleshooting.
{
  "hide": false,
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  },
  "engine": "auto",
  "frigate": {
    "client_id": "frigate",
    "url": "HTTP://192.168.1.155:5000/birdseye",
    "camera_name": "Birdseye"
  },
  "motioneye": {
    "images": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    },
    "movies": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    }
  },
  "live_provider": "auto",
  "image": {
    "refresh_seconds": 1
  },
  "camera_entity": "birdseye",
  "title": "Birdseye"
}

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
You need to EITHER specify the camera_entity or the camera_name.

## Entity

You have:

```
  "camera_entity": "birdseye",
```

... entities always start with 'camera.' so this is malformed.

## Camera Name

I'm not sure if this is case sensitive, but this should probably  be `birdseye` not `Birdseye` (i.e. without a capital 'B').

**Comment by LordNex** [comment]
I've tried it all of those ways and every combination in between and still a no go. I could use camera.birdseye for example IF it made an entity. The only way I see that happening is if delete the integration and try and readd it. But that will most likely cause me to have to recode a lot of automations and other things in the chain. If that's what HAS to be done you might want to put that in the notes. If not and you can recode it great. I wasn't quite sure if I should post this here or over in the main Frigate Integration, but since it's an adopted integration, wouldn't I have to post this under HA Core?

**Comment by dermotduffy** [comment]
> I could use camera.birdseye for example IF it made an entity. 

What does this mean?

> The only way I see that happening is if delete the integration and try and readd it. 

Did you manually delete the entity? Why would re-adding it make any difference?

>  If that's what HAS to be done you might want to put that in the notes.

Birdseye will work without any entity at all.

> I wasn't quite sure if I should post this here or over in the main Frigate Integration, but since it's an adopted integration, wouldn't I have to post this under HA Core?

It's not yet clear there is a problem here at all.

Can you hold down your Frigate  button for a few seconds, let it go and paste the diagnostics here?

**Comment by dermotduffy** [comment]
Please also include a screenshot of the error you receive.

**Comment by dermotduffy** [comment]
Can you hold down the Frigate  menu button _in the card_ and paste the diagnostics?

**Comment by LordNex** [comment]
> Can you hold down the Frigate  menu button _in the card_ and paste the diagnostics?

As you can see in the screenshot there is no frigate button. Only when I exclude or remove the birdseye view will it show up

![image](https://github.com/dermotduffy/frigate-hass-card/assets/9270948/f94324b1-8b2f-432c-90e6-f5a7febf5f11)

Also, I tried removing the integration completely from Devices and Services, rebooted, went to readd it and was given this screen. Just had to change the URL to point to my actual server. 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/9270948/d74310fc-3f4d-4a63-8617-7c531e00e56b)

But as you can see below, it didn't add a bird eye camera which it used too. 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/9270948/e7887845-47c1-4a8e-926a-7d67245df746)

So still no luck.

**Comment by dermotduffy** [comment]
OK -- lets just go with the basic YAML config for the card, then?

**Comment by LordNex** [comment]
> OK -- lets just go with the basic YAML config for the card, then?

What like a normal card pointing to the birdeye address?

I think it's just http://192.168.1.155:5000/birdseye

**Comment by dermotduffy** [comment]
No, I'm asking you to just copy and paste the YAML config for the broken Frigate card into this issue so I can see how you are configuring it.

**Comment by LordNex** [comment]
> No, I'm asking you to just copy and paste the YAML config for the broken Frigate card into this issue so I can see how you are configuring it.

I can try. I'm using Dwain's Dashboard which looks nice but is a pain in the ass. I wish I would have never started using it. Because now I've spent so much time building it, it would take forever to rebuild that nice of a dashboard with Lovelace. 

Let me create a new dashboard that does have his shit in it and try adding it there. I'll just add one camera I know that works and the birdseye. BTW that link above works fine for me but gave a security warning like it was under https. Weird

**Comment by LordNex** [comment]
> No, I'm asking you to just copy and paste the YAML config for the broken Frigate card into this issue so I can see how you are configuring it.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.side_doorbell_main
  - camera_entity: birdseye
    live_provider: auto
    frigate:
      camera_name: birdseye
      url: Http://192.168.1.155:5000
```

Fresh brand new card

**Comment by dermotduffy** [comment]
Please try this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.side_doorbell_main
  - frigate:
      camera_name: birdseye
      url: Http://192.168.1.155:5000
```

**Comment by LordNex** [comment]
> Please try this:
> 
> 
> 
> ```yaml
> 
> type: custom:frigate-card
> 
> cameras:
> 
>   - camera_entity: camera.side_doorbell_main
> 
>   - frigate:
> 
>       camera_name: birdseye
> 
>       url: Http://192.168.1.155:5000
> 
> ```

Now that worked. What is it the live provider?

**Comment by dermotduffy** [comment]
> What is it the live provider?

The card supports a variety of different ways of viewing live images, each with different performance characteristics (different latencies, different technologies). The selection is here:

https://github.com/dermotduffy/frigate-hass-card#live-providers

I removed that as you were setting the default value unnecessarily.

**Comment by LordNex** [comment]
Hmm still not working on my main page. But let me wipe that out and start over. The only difference between your code and mine was I had live provider set to automatic. 

I went and shut that off on all my cameras on my main card but it still didn't take. So let me try with a new card. Still sounds like a bug. I should be able to make those selections and they never caused an issue until I upgraded and the Birdseye camera went away. Anyway, thanks for the help. I'll let you know if this does or doesn't work.

**Comment by dermotduffy** [comment]
> Hmm still not working on my main page. But let me wipe that out and start over. The only difference between your code and mine was I had live provider set to automatic.

No. You also specified an invalid/non-existent camera entity, which I removed.

**Comment by LordNex** [comment]
> > Hmm still not working on my main page. But let me wipe that out and start over. The only difference between your code and mine was I had live provider set to automatic.
> 
> 
> 
> No. You also specified an invalid/non-existent camera entity, which I removed.

Is there a way to do that through the UI. All I can set is the name "birdseye". I don't have a camera element inside Home Assistant for birdseye. 

One of the bad things about This Dashboard is that you loose the ability to view certain things in code. If not I'll have to dig around his config files to locate that entry

**Comment by dermotduffy** [comment]
> Is there a way to do that through the UI

From the editor UI? Just delete the text in the camera entity box and save.

**Comment by LordNex** [comment]
Gotcha. I thought that field was required. Thanks for all your help. It's much appreciated!
