### ISSUE TITLE
Configuration documentation suggestion 

### ISSUE THREAD

**Issue by nickdos** [dermotduffy/frigate-hass-card#1322]
This is obviously a complicated Lovelace card with lots and lots of options, so making it simple for a first-time user is a very difficult task. 

I have been using HA for over 5 years and have installed dozens of HACS customisations. They mostly follow a convention in documenting their config, which is to provide a minimal example straight-up and to describe the top-level elements first. Then for each top-level element that has its own options, there is a section further down, that covers each of these. These can all be accessed from the first "screen" of the README by their clickable links to the sections. [Apexcharts cards](https://github.com/RomRider/apexcharts-card) is a good example.

The config docs for this repo go straight into detailed explanation of (just) the `cameras` top-level setting. Sprinkled further down appears a few other top-level settings, like `menu` but you have to scroll and seek to find these. There is no clickable table of contents for the sections, so scrolling is the only way to get there. 

My suggestion is to add a table of contents at the top the README and to document all the top-level config vars first and then go into details for each one below that. 

Lastly, is it possible to add a title to appear at the top of the card, independent of the `cameras`?

**Comment by dermotduffy** [comment]
Thanks @nickdos. A few notes:

 * Github already offers table of contents feature  that can be used to move around vs scrolling:

<img width="873" alt="Screenshot 2023-11-10 at 20 57 57" src="https://github.com/dermotduffy/frigate-hass-card/assets/1136829/f9ddc496-fc82-4645-acba-4577ecf38714">

* There's no special treatment for `cameras` really, all options are listed in order. There is just a lot of them, and `cameras` is the only required argument.

Overall, the main README is just much too long now and I think a multi-page setup might need to considered. For now, perhaps this issue could be to add:

 * A small (not exactly minimal, but basic) example config.
 * A table that contains the main sections (e.g. `cameras`, `menu`, `dimensions`, etc) and links to each of their detailed sections.

Sound right?

> Lastly, is it possible to add a title to appear at the top of the card, independent of the cameras?

i.e. a static title that is always shown above the card? No, this is not currently possible, although you could presumably do it with a markup card outside of the frigate card.

**Comment by nickdos** [comment]
Thanks for the thoughtful reply.

Dang, I never noticed that builtin table of contents (been too long on GH so don't notice new features) - thanks for pointing out. That was my main frustrating as I was scrolling up and down and up and down the page, which got old quickly.

I'm probably not an exception in not noticing the builtin ToC so adding a small inline ToC for the main sections, as you suggested, is a good idea. 

And yes, a minimal config example would've helped me too. I didn't push that in my original comment, as you provide a very good UI mode for config and I mostly used that to good effect. 

I did get stumped when trying to configure WebRTC and/or go2trc (via Frigate) and gave up. The examples were numerous and complete but had the warning "don't copy them verbatim as not all options are required" (or words to that effect). But I just couldn't work out which options I did need vs I didn't need. I also couldn't work out the values I needed in some cases, so a real example would've helped.

I think many people will be coming from a few common setups, so having a few preferred/opinionated config examples for those groups would be useful. In my case, give me an example for Frigate using the webrtc card and associated webrtc settings and indicate which options I need to have set in Frigate (go2rtc with webrtc, etc) to match that.

Lastly, I found the "overridable" green ticks very confusing - is the user overriding a default value with "this" option or is there another option further down that might override "this" setting? E.g. the very first option "camera-entity" is overridable and not marked as required, so I'd assume I could leave that empty (i.e. I can choose **not** to override with a value of my own?). But it errors, so this assumption appears to be wrong. So if it is the other interpretation, then what other options might be able to override the current setting? Without knowing this, marking it as overridable is kind-of pointless (my opinion). There might be many other options that do override it but I feel you should link to all of them - or not bother to have the overridable flag at all. 

I did a quick scan and every option for the first 14 screen lengths (hitting page down) had overridable set as true. I got to thinking that it should be assumed any setting might be overridable and maybe it should be the other way around - only indicate when a setting overrides another setting and link back to that "higher" setting in those cases. That would seem to be a more useful way of doing it, assuming I have guessed correctly on how to interpret "overridable" (I'm still not sure).

An example:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/532845/d90c589c-09c4-4713-8dd8-582b807001bc)

Why is one overridable and the other not? How does that flag change the way I interpret these settings? What action or check do I need to follow-up with, when it set vs not set? 

Apologies if this comes across as over critical, it's not my intention. I think this is a fantastic card and was hoping my observations might help improve access for other users. As a software developer I struggled with some aspects, so I'm guessing people from a non-technical background would struggle even more.

**Comment by dermotduffy** [comment]
> I'm probably not an exception in not noticing the builtin ToC so adding a small inline ToC for the main sections, as you suggested, is a good idea.

Sounds good.

> And yes, a minimal config example would've helped me too.

Sounds good.

> I did get stumped when trying to configure WebRTC and/or go2trc (via Frigate) and gave up. The examples were numerous and complete but had the warning "don't copy them verbatim as not all options are required" (or words to that effect). But I just couldn't work out which options I did need vs I didn't need. I also couldn't work out the values I needed in some cases, so a real example would've helped.

> I think many people will be coming from a few common setups, so having a few preferred/opinionated config examples for those groups would be useful. In my case, give me an example for Frigate using the webrtc card and associated webrtc settings and indicate which options I need to have set in Frigate (go2rtc with webrtc, etc) to match that.

I interpret this as: Please add a simple example that uses the go2rtc live provider, and separately the webrtc_card live provider. The latter is already [provided here](https://github.com/dermotduffy/frigate-hass-card/tree/dev#webrtc-card-provider), but I think really the minimal config (mentioned above) could feature early in the documentation, and could provide a few "common scenarios".

> Why is one overridable and the other not? How does that flag change the way I interpret these settings? What action or check do I need to follow-up with, when it set vs not set?

I struggle a little with this one. Draggable is a property of the entire carousel, so cannot reasonably change depending on a "slide" within the carousel, whereas Zoomable is a property of an individual slide. I don't expect the user to understand the "why" behind these distinctions, but without some sort of indicator it could be quite confusing why the override is not working. Realistically though, most people are not going to be using overrides, so stripping out the checks/xs entirely is always a possibility if we think it improves clarity for the majority (vs occasional head-scratching for the minority).

> Apologies if this comes across as over critical, it's not my intention. I think this is a fantastic card and was hoping my observations might help improve access for other users. As a software developer I struggled with some aspects, so I'm guessing people from a non-technical background would struggle even more.

Not at all, I understand and appreciate very much. When one is in the trenches, it's very hard to see what is readable vs not. I'll go one step further, if you fancied putting together a PR with some of the ideas here, that would be fantastic -- if not the contribution of the ideas is still very much appreciated and I can work on a PR at some point in the future.

**Comment by dermotduffy** [comment]
I'm going to consider this closed. I've completely overhauled the documentation into something approaching usable:

https://dermotduffy.github.io/frigate-hass-card

I hope you'll find the new documentation significantly improved, with a bunch of your tips/advice incorporated. Thanks for the quality issue report -- knowing that a HA-experienced developer was struggling to use it was a significant motivator.
