### ISSUE TITLE
view->update_seconds interferes with card actions

### ISSUE THREAD

**Issue by miguelangel-nubla** [dermotduffy/frigate-hass-card#1324]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Current main branch, post 5.2.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome on Windows and Linux, Android FullyKiosk.

**Description of problem:**
```yaml
view:
  update_seconds:
```
interferes with navigate actions `camera_select`

------

I understand the way to refresh for new events is
```yaml
view:
  update_seconds: 30
```
When I call the navigate action `?frigate-card-action:camera_select=camera.cam_patio` the live view goes back to the default camera (cam_driveway) as soon as the `update_seconds` timer expires.
I expected to continue to update the thumbnails and keep the last selected camera view.

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.11.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
  "date": "2023-11-27T02:37:24.462Z",
  "frigate_version": {
    "fb049a4db4f992ddec703a758face4f8": "5.0.0-beta.3/0.13.0-614a36a"
  },
  "lang": "en",
  "timezone": "Europe/Paris",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.cam_driveway"
      },
      {
        "camera_entity": "camera.cam_patio"
      }
    ],
    "view": {
      "update_seconds": 3
    },
    "debug": {
      "logging": true
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```
card-555679fd.js:5 Frigate Card CameraManager request [Input queries: 1 , Cached output queries: 1 , Total output queries: 1 , Duration: 0.008s, , Queries: [{…}] , Results: Map(1) {{…} => {…}} ]
card-555679fd.js:5 Frigate Card view change:  Oy {view: 'live', camera: 'camera.cam_driveway', query: Ay, queryResults: Uy, context: {…}}
card-555679fd.js:5 Frigate Card view change:  Oy {view: 'live', camera: 'camera.cam_driveway', query: Ay, queryResults: Uy, context: {…}}
card-555679fd.js:5 Frigate Card view change:  [default]
card-555679fd.js:5 Frigate Card CameraManager request [Input queries: 1 , Cached output queries: 1 , Total output queries: 1 , Duration: 0.006s, , Queries: [{…}] , Results: Map(1) {{…} => {…}} ]
card-555679fd.js:5 Frigate Card view change:  Oy {view: 'live', camera: 'camera.cam_driveway', query: Ay, queryResults: Uy, context: {…}}
card-555679fd.js:5 Frigate Card view change:  [default]
card-555679fd.js:5 Frigate Card CameraManager request [Input queries: 1 , Cached output queries: 1 , Total output queries: 1 , Duration: 0.006s, , Queries: [{…}] , Results: Map(1) {{…} => {…}} ]
card-555679fd.js:5 Frigate Card view change:  Oy {view: 'live', camera: 'camera.cam_driveway', query: Ay, queryResults: Uy, context: {…}}
card-555679fd.js:5 Frigate Card view change:  [default]
card-555679fd.js:5 Frigate Card CameraManager request [Input queries: 1 , Cached output queries: 1 , Total output queries: 1 , Duration: 0.006s, , Queries: [{…}] , Results: Map(1) {{…} => {…}} ]
....repeating...
```

**Additional information:**

**Comment by dermotduffy** [comment]
> When I call the navigate action ?frigate-card-action:camera_select=camera.cam_patio the live view goes back to the default camera (cam_driveway) as soon as the update_seconds timer expires.

I've rewritten this code entirely since the last release, so let me play around with this to see if this is still an issue ...

**Comment by miguelangel-nubla** [comment]
I still see this in main branch head.

**Comment by dermotduffy** [comment]
> I still see this in main branch head.

Try the `dev` branch.

**Comment by dermotduffy** [comment]
> When I call the navigate action ?frigate-card-action:camera_select=camera.cam_patio the live view goes back to the default camera (cam_driveway) as soon as the update_seconds timer expires.

Re-reading this now, I'm wondering if actually there's a misunderstanding since what you describe is how it's _designed_ to work. From the [documentation](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#view-options)...

![image](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/17320456-a30b-4777-8bc3-dd40fa6ffab6)

... as you can see `update_seconds` intentionally updates with the default view. 

Perhaps you can describe what you're trying to achieve in more detail, and I can see what the best way to achieve that is (I don't understand why you have `update_seconds` set at all).

**Comment by miguelangel-nubla** [comment]
I use an always on display with the frigate card to show a particular camera and its events.
Initially, I expected the events to update in real time (via websocket or something) for the current camera being displayed, but soon realized that was not the case?
The solution I found at the time (maybe incorrectly) was to use `update_seconds` to achieve something like that.

Later I added video to a doorbell, and I automated to change the displayed camera for 60s when called, and go back to the default one after with another ha automation.

I expected `update_seconds` to update the events for the newly selected camera while the 60s, then when I manually select the default camera again, keep updating the events for the default camera.

**Comment by dermotduffy** [comment]
I think I understand the situation better now, please correct me if I go wrong here, this is what you want:

1. To have a card that shows `live` for camera A (and so events for camera A, and these should update).
2. When your doorbell is pressed, the card changes to camera B for 60s (and so events for camera B, and these should update).
3. After 60s, go back to step 1.

=> **Is this correct?**

In general, I don't like using arbitrary "refresh every N seconds" type approaches, when we _do_ have richer information on when new events are available (at least in the `dev` branch we do). So I think this might be the best approach:

* Configure the cameras to trigger on new events (`dev` branch supports this already).
* [New] Add a new action for that trigger  that effectively means "update current view, regardless of what that is"
* [New] Hygiene: Possibly rename `update_seconds` to `reset_to_default_seconds`.

This would let you use the query string based automation you're doing today, but also let you use an `automations` block entry that detects the doorbell press and takes action, without you needing the `navigate` stuff you're doing today. I think the card should support both.

Let me know if anything sounds wrong here...

**Comment by miguelangel-nubla** [comment]
> => **Is this correct?**

Yes, that is the idea.

> * [New] Add a new action for that trigger  that effectively means "update current view, regardless of what that is"

Why have an action to do that? Why not by default?
Especially since there is richer information available as you say, the only logic needed would be to push to current views where it makes sense (media gallery, media viewer, etc) the new media element when received.
I would complement that with a `freeze` action to allow users to pause the "live" update where needed which should be the exception.
Example: browsing the media gallery of a camera with too frequent new events would move the elements on the grid making it unusable.

> * [New] Hygiene: Possibly rename `update_seconds` to `reset_to_default_seconds`.

I understand now the same behavior can already be accomplished with `automations` with way more flexibility.
Just use a home assistant automation entity as trigger (leveraging the existing ha automation trigger flexibility).
```
automations:
  - conditions:
      - condition: state
        entity: automation.frigate_card_interval
    actions:
      - action: custom:frigate-card-action
        frigate_card_action: default
```
So maybe deprecate `update_seconds`?
Same argument can be made for `view.update_entities`.
