### ISSUE TITLE
Camera Carousel Display

### ISSUE THREAD

**Issue by GregoryWest501** [dermotduffy/frigate-hass-card#1325]
Not sure if this exists already, if it has I can not find how to configure it.

What I am looking for is a way for the Frigate HA Card to automatically switch between each camera.   What would be ideal is if HA displayed Camera-1 for say 10 seconds, then Camera-2 for 10 seconds.......    and so on threw each camera, then loop back to Camera-1.

Is this possible?

Greg

**Comment by dermotduffy** [comment]
> Is this possible?

Yes. You want the `update_cycle_camera` option, see [documentation](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#view-options). It will change the camera on each update of the card, and then you can use the `update_seconds` option to decide how frequently you would like that to happen.

Try it out?
