### ISSUE TITLE
Latest snapshots only cycles per camera not the list of cameras given

### ISSUE THREAD

**Issue by dopeytree** [dermotduffy/frigate-hass-card#1328]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

Latest snapshots only cycles per camera not the list of cameras. Video works fine and cycles all latest clips

**Last working release (if known):**

**Browser and Operating System:**
safari Version 17.1 (19616.2.9.11.7) - macOS sanoma 14.1.1 (23B81)

**Description of problem:**

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.11.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15",
  "date": "2023-11-30T05:11:10.776Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.barn_catflap"
      },
      {
        "camera_entity": "camera.porch_cam"
      },
      {
        "camera_entity": "camera.barn",
        "labels": "cat"
      }
    ],
    "view": {
      "default": "recording"
    },
    "menu": {
      "style": "hover"
    },
    "live": {```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

```
type: vertical-stack
cards:
  - type: custom:mushroom-template-card
    primary: Introducing Catflix
    secondary: Lastest movies
    icon: mdi:video
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.barn_catflap
      - camera_entity: camera.porch_cam
      - camera_entity: camera.barn
        labels: cat
    view:
      default: recording
    menu:
      style: hover
    live:
      draggable: false
      zoomable: false
    media_viewer:
      auto_pause: hidden
      draggable: false
      zoomable: false
      auto_play: never
  - type: tile
    entity: sensor.sun_next_rising
    hide_state: false
    show_entity_picture: false
    vertical: false
    color: deep-orange
```

**Comment by dermotduffy** [comment]
The config appears to have gotten cut off in the report, would you mind including the full config?

> Latest snapshots only cycles per camera not the list of cameras. Video works fine and cycles all latest clips

I'm trying to understand this sentence, can you say it another way including what you see and what you expect to see?

Thanks!

**Comment by robwaldhauser** [comment]
I'm having the same issue, but with clips. If you set the View to "Clips gallery" and have 4 camera's listed in the card, when you refresh the page it always filters to only the first camera instead of displaying the clips for all of the cameras. So every time you need to pull open the filter menu and select the rest of the cameras.

**Comment by dermotduffy** [comment]
> I'm having the same issue, but with clips. If you set the View to "Clips gallery" and have 4 camera's listed in the card, when you refresh the page it always filters to only the first camera instead of displaying the clips for all of the cameras. So every time you need to pull open the filter menu and select the rest of the cameras.

That is working as intended. If you want it to load the clips for all cameras, configure the cameras to depend on one another. Example:

https://github.com/dermotduffy/frigate-hass-card/issues/1357#issuecomment-1925028378
