### ISSUE TITLE
The Speaker and Mic Icons do not appear when using Chrome on a Amazon Fire Tab

### ISSUE THREAD

**Issue by def1149** [dermotduffy/frigate-hass-card#1329]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
5.2

**Last working release (if known):**
N/A

**Browser and Operating System:**
Chrome on Amazon Fire OS v 5.7.1.0

**Description of problem:**

I'm using an Amazon Fire tablet for HA wall-mounted use. The frigate card does not show the Speaker, Microphone, or Pause icons.

**Frigate card diagnostic information**

```json
{
  "ha_version": "2023.12.0b2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
  "date": "2023-12-05T15:39:26.918Z",
  "frigate_version": {
    "cf264c8c4e585535f4c048eeb234805d": "5.0.0-beta.3/0.13.0-614a36a"
  },
  "lang": "en",
  "timezone": "America/Chicago",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "doorbell_stream"
        }
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true,
          "icon": "mdi:microphone",
          "type": "momentary",
          "alignment": "matching"
        },
        "mute": {
          "enabled": true
        },
        "expand": {
          "enabled": false
        },
        "play": {
          "enabled": true
        }
      },
      "style": "overlay",
      "position": "top"
    },
    "live": {
      "microphone": {
        "always_connected": false,
        "disconnect_seconds": 0
      }
    },
    "view": {
      "default": "live"
    },
    "performance": {
      "profile": "high"
    }
  }
}

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by zachlovescoffee** [comment]
I have the same issue but it's just with default frigate-card in Home Assistant. Even though my HA instance is running over HTTPS and go2rtc is enabled on cameras (in Frigate on Unraid > MQTT > HA), the mic will not show on the frigate-card.

**Comment by dermotduffy** [comment]
In both cases, if you cannot visit the go2rtc interface and successfully use your microphone (i.e. not using the card at all), the issue is less likely to be the card and more something is wrong with your setup. 

For both of you, if you set the `show_image_during_load` under `live` ([documentation](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#live-options)) does the stream still load? If webrtc connection was overall failing, you'd see this behavior (and it might be masked by having HomeAssistant images refreshing every 1s, so perhaps you don't notice).

**Comment by def1149** [comment]
Mic, speaker, and pause icons appear on Android Phone, IOS and PC and work. Mic, speaker, and pause icons do not appear on Fire tablet. Please explain again slowly, in detail, for us slow learners how that's a setup problem.

**Comment by dermotduffy** [comment]
My previous statement remains accurate (your setup includes limitations associated with your device), and previous debugging instructions/questions remain valid and unanswered.

> Mic, speaker, and pause icons appear on Android Phone, IOS and PC and work. Mic, speaker, and pause icons do not appear on Fire tablet. Please explain again slowly, in detail, for us slow learners how that's a setup problem.

This is Open Source! You get the benefit of (in the case of this card) hundreds of hours of development, for no cost to you. The flip side of that, is that it's often -- as is the case here -- provided in precious limited "hobby" time. There is zero obligation for support, and users who ask for support are entirely dependent on goodwill. In that light, lack of civility and poor choice of tone in communicating are very unlikely to get users the support they may wish to receive.

I hope you figure out your issue. Good luck.
