### ISSUE TITLE
Clips view preset filtering

### ISSUE THREAD

**Issue by kei81131** [dermotduffy/frigate-hass-card#1333]
Would like to know if it is possible to set some preset filter, thank you

such as when I open this card, it will show (when: today) (what: bark) by default
no need to choose every time
![image](https://github.com/dermotduffy/frigate-hass-card/assets/111072203/b95111f0-628a-46ed-94b6-c9c790b71945)

**Comment by dermotduffy** [comment]
Yes, you can should be able to use the `labels` parameter for the camera or cameras in question, see [documentation](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#camera-frigate-configuration).

**Comment by kei81131** [comment]
thank you so much, it works perfectly ^_^
