### ISSUE TITLE
Custom element doesn´t exists: frigate-card

### ISSUE THREAD

**Issue by lokomoti** [dermotduffy/frigate-hass-card#1335]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.2.0

**Last working release (if known):**
N/A

**Browser and Operating System:**
Chrome 81.0.1011.138
Fully Kiosk Browser 1.54.1-play
Companion App 2023.12.4-full
on
Android 10

**Description of problem:**
On my Lenovo M10 Plus I get error message when loading a Frigate card.
Error is as follows: "Custom element doesn't exist: frigate-card."

**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
- I encountered same issue with older Ipad. 
- The card loads up properly in Firefox on the same tablet.
- Card loads up properly on Iphone 13 and 14 (Companion App).
- Frigate Proxy Addon also does not work where the card doesn´t load.

**Comment by dermotduffy** [comment]
As this appears to work for you on some devices / browsers, it is not an installation issue and likely an old unsupported (by me) version of webview being used by Android 10.  I have no particular workarounds other than use a more modern device / webview.

**Comment by TinkeringB** [comment]
Title not fully correct; it should read "Custom element doesn't exist: frigate-card." 
- I am having the same problem for a brand new installation when trying to create a dashboard with the code on https://pastecode.io/s/kmzktckc 
- not working on Firefox nor Chrome; as those are my only real options, it is currently a no-go for me

**Comment by lokomoti** [comment]
I was able to flash android 12 on my tablet and now it is working.
