### ISSUE TITLE
2 way communication mic problems

### ISSUE THREAD

**Issue by penguinpatrol** [dermotduffy/frigate-hass-card#1338]
**Checklist:**

- [x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

i am trying to set up t way communication but am having an issue where the mic doesn't send sound out the camera i can hear from the outside, in but i cant talk to the outside

**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by nosar77** [comment]
I'm having the same issue did you find a way to fix this?

**Comment by dermotduffy** [comment]
This can be quite tricky to setup, and comes with a bunch of requirements, this is the place to start: https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#using-2-way-audio

Have you followed these steps? Do you have a compatible camera?
