### ISSUE TITLE
Only one video can play at a time

### ISSUE THREAD

**Issue by mogim0gi** [dermotduffy/frigate-hass-card#1340]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

Fully kiosk browser + fireHD + frigate card (4 cameras), im getting this popup from time to time, has anyone experienced this?

![image](https://github.com/dermotduffy/frigate-hass-card/assets/64898710/a5f82dc8-1e8f-4651-850f-55d3f9b9ae01)

**Comment by mogim0gi** [comment]
I know its fireHD issue, however a lot of people are using them for wall tablets, and I sisnt have this problem in WebRTC card

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!

I would recommend trying the `lazy_unload` option, as it will ask the card to unload live streams more aggressively, which may help in this case: https://card.camera/#/configuration/live
