### ISSUE TITLE
UX: Change Default TimelinePanBehavior = 'seek' to 'pan'

### ISSUE THREAD

**Issue by suredesigntshirts** [dermotduffy/frigate-hass-card#1343]
**Is your feature request related to a problem? Please describe.**
My problem is on mobile, in the Home Assistant App, it's hard to use the mini-timeline when added to live view cards to pan around the timeline (when the default is set to seek). When the default is set to seek, most any clicks link you over to watch the clips. When the default is in pan mode, you can actually navigate around the timeline, then select & view the clip you'd like to watch.

**Describe the solution you'd like**
[frigate-hass-card/src/components/timeline-core.ts : line 209](https://github.com/dermotduffy/frigate-hass-card/blob/3b82dd6843d9a619d8e35151489dd90066a9b746/src/components/timeline-core.ts#L209)
```
...
  public itemClickAction?: TimelineItemClickAction;

  @state()
  protected _panBehavior: TimelinePanBehavior = 'seek';

  protected _targetBarVisible = false;
...
```

Change this from 'seek' to 'pan'

**Describe alternatives you've considered**
I've played around with seek & seek-in-media and those don't allow clicking on timeline with out the hass-card navigating away from live-view. I think pan is better.

I know you should be able to change this via the small icon next to the calendar in the bottom right corner of the timeline...problem is the click event handler seems to overlay on top of those icons when using mobile and it's hard to click (seems impossible actually)

Also even if I set this icon to 'pan' instead of one of the 'seek's...I don't believe this change would survive a reload of the page or app. 

Alternatively, this could be a setting in the hass-card options...but I still think default 'pan' is the best default behavior and thus should simply just be changed to the default for UX reasons.

**Comment by dermotduffy** [comment]
>  When the default is set to seek, most any clicks link you over to watch the clips. 

Isn't that what is most useful, though? Don't quite follow why `pan` is be a better UX by default -- can you expand a little?

> I know you should be able to change this via the small icon next to the calendar in the bottom right corner of the timeline...problem is the click event handler seems to overlay on top of those icons when using mobile and it's hard to click (seems impossible actually)

I don't understand this -- I can click this icon just fine on mobile (Android), you cannot?

> Alternatively, this could be a setting in the hass-card options...but I still think default 'pan' is the best default behavior and thus should simply just be changed to the default for UX reasons.

Adding it to be configurable is certainly doable, and you're right that whatever you set will be lost if you reload the page.

**Comment by dermotduffy** [comment]
Implemented. Will be in the next release.
