### ISSUE TITLE
Latest Person Snapshot Not Refreshing

### ISSUE THREAD

**Issue by rogerquake** [dermotduffy/frigate-hass-card#1344]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
Frigate card: 5.2.0
Frigate Integration: 5.0.0-rc1
Frigate: 0.13.0-614A36A

**Last working release (if known):**
Unknown

**Browser and Operating System:**

Seeing issue everywhere: Chrome, Firefox (Windows), Android Tablet w/ Fully Kiosk Browser

**Description of problem:**

I'm experiencing an issue where the "Latest Snapshot" of person on a  Frigate camera is not automatically updating on the card. I always see the card information popup appear indicating the trigger was seen, but it's very sporadic if the latest snapshot appears on the card. If I refresh the browser (either on my desktop or Android tablet), the latest snapshot image is always there.

I've tried a bunch of different settings, using the default occupancy triggers and explicitly specifying the person sensor for the camera. 

Normally I use with a camera at my frontdoor and have the latest person snapshot appear on Android tablets around my house. They have been off for the past few months so I just started noticing the issue now. To test the issue, I placed a camera inside my house to observe the sporadic snapshot refresh issue.

It almost seems as if there is a cooldown period occurring since it's more common for a new snapshot to appear if there is a longer time difference between a person being detected.

**Frigate card diagnostic information**

```json
{
  "ha_version": "2024.1.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "date": "2024-01-19T02:50:29.775Z",
  "frigate_version": {
    "99eb8c5245aa5d034f0be3cad78d58f6": "5.0.0-beta.3/0.13.0-614a36a"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.office"
      }
    ],
    "view": {
      "default": "snapshot"
    }
  }
}

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Can you clarify what you are trying to achieve? Perhaps it's for the card to continually update with the latest snapshot (without the user needing to refresh anything)?

**Comment by rogerquake** [comment]
Sure. Every time a person is detected on the camera, I want the snapshot image to be automatically refreshed with the latest image of the person. I'm using the card to see the last person who appeared on my frontdoor camera.

**Comment by dermotduffy** [comment]
A few ideas:

- Use the most recent camera entity (e.g. `camera.office_person`, renamed to `image.` entities in bleeding edge Frigate integration code) to tell the card to update its view with something like:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
view:
  default: snapshot
  update_entities:
    - image.office_person
```

- Automatically refresh the card every 60s seconds with something like this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
view:
  default: snapshot
  update_seconds: 60
```

Now a warning I'll attach is that the card does cache the latest event information for `60s`, so it's possible this is causing some of the behavior you've seen, e.g. the first solution should work, but if another snapshot arrives within `60s` I could imagine that will not work for your case. Allowing user control over the cache time/use would help, although is not supported / no-one asked for that yet.

**Comment by rogerquake** [comment]
Appreciate the ideas, but the image still does not consistently refresh without a full page load. I'm honestly surprised there isn't more posts with others mentioning this. To be sure it wasn't an issue with the latest Frigate and HA, I tested our an older HA, Frigate 12 build with the associated integration and cards and noticed the same issue.

I love the Frigate card and I'll still be using it for live video and watching clips, however for this specific use case (image of the last person at my front door), I'm going to have to use something else until the required functionality is integrated.

It's not the best solution, but I've decided to use the "refreshable-picture-card" and point it to the URL of the Frigate API that has a snapshot of the latest person on the camera. This card automatically appends data to the end of the URL so the browser won't cache the image. It also doesn't flicker during refreshes like the Frigate card does.

I think it would be awesome to build in a similar feature into the Frigate card so the latest snapshot image isn't cached.

**Comment by dermotduffy** [comment]
> Appreciate the ideas, but the image still does not consistently refresh without a full page load. I'm honestly surprised there isn't more posts with others mentioning this. 

Me too :-)

> I think it would be awesome to build in a similar feature into the Frigate card so the latest snapshot image isn't cached.

Well, it's supposed to already be built in. Let me keep this bug open until I have the time to either find the issue and fix it, or conclusively prove that it does work (for me at least).

**Comment by dermotduffy** [comment]
Mind sharing how you're testing it on your end? I'll re-use the same methodology.

**Comment by rogerquake** [comment]
Sure. I have a dashboard with multiple cards on it that should all theoretically auto refresh and show the last person detected on the camera. I setup a camera in my office so I could easily test without going outside. I walk in front of the camera, Frigate detects me, and  I see if the image on the cards update.

From left to right:

- Picture Glance Card: Hitting the Frigate API to get the latest snapshot with the URL appending a timestamp to bypass the cache. By default this only updates every 10 seconds.

- Refresh Card. It's set to update every 4 seconds. The card automatically appends a timestamp to bypass the cache.

- Frigate Card: Set to the latest snapshot of the camera and the trigger is set to the occupancy sensor for the camera.

I also added a card to show that a person was detected and the time between detections. You can check out a sample video below of the setup:


https://github.com/dermotduffy/frigate-hass-card/assets/28624502/1e131f4c-1df2-48f1-95f9-369da8036ec0

**Comment by dermotduffy** [comment]
Amazing! Thank you. Mind providing the Frigate API endpoint you're using?

**Comment by rogerquake** [comment]
Good question on the occupancy sensor. The card usually has a popup when the sensor is triggered but I didn't see that appear. Below is the frigate card settings used in the test:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    triggers:
      occupancy: true
view:
  default: snapshot
performance:
  profile: high
```

**Comment by dermotduffy** [comment]
Try putting this on your nice dashboard and repeat the experiment?

```yaml
type: entity
entity: binary_sensor.office_all_occupancy  <---------- Replace with name of your occupancy sensor
```

If the occupancy sensor updates when the room goes from unoccupied to occupied, but the card does not, it's a card problem. If the occupancy sensor also doesn't update, it's at least _also_ an integration problem.

**Comment by rogerquake** [comment]
I originally had the occupancy entity on the page set to just person, but I switched it over to all_occupency. It triggers alright but the Frigate card isn't updating:


https://github.com/dermotduffy/frigate-hass-card/assets/28624502/393e6340-2931-48b3-8dde-9ae986ef6d15

**Comment by grasstoshi** [comment]
I am right there with you, updated to HOAS Core 2024.1.6,  Frigate 0.13.1, and Frigate Lovelace Card 5.2.0

Everything was working perfectly before updates, dashboard showed latest snapshot, instantly updated with the newest image every time motion was captured. 

Now the card on the dashboard says 'Entity not available: camera.frontdoorcamera_person

I didn't change any configurations or yaml.

**Comment by dermotduffy** [comment]
> Now the card on the dashboard says 'Entity not available: camera.frontdoorcamera_person

@grasstoshi This sounds like a different problem. My guess is you need to update your config to the new `image` entity, in your case it might be called `image.frontdoorcamera_person`. The latest version of the Frigate integration changed from using `camera` entities for latest snapshots to `image` entities.

You still might experience the same problem as this issue, but sounds like you didn't get that far yet.

**Comment by dermotduffy** [comment]
The excellent testing work and videos from @rogerquake have spurred me to look into this and reproduce the test setup. There are *at least* two problems:

1. The cards default behavior of caching is a real problem if the new snapshot shows up within 60 seconds. Caching should just be disabled when the user wants the most recent snapshot/clip.
2. More fundamentally: Using the entity update information for `binary_sensor`s is not a reliable means of knowing when there's a new snapshot available. I believe it works okay when the state is toggling from "person not occupying room" to "person now occupying room". But when there's _already_ a person occupying the room (but there's a new snapshot), the MQTT topic that the binary sensor uses does not / cannot flip value, so the binary sensor doesn't update, so the card doesn't know.

Fixing 1 is easy, fixing 2 is more involved (requires integration changes). @NickM-27 was suggesting that using the raw Frigate events stream is the best way to trigger this, so I'm going to look into exposing that via Home Assistant events (that the card could subscribe to).

**Comment by dermotduffy** [comment]
Option 2 is now implemented, and will be in the next card release.

**Comment by rogerquake** [comment]
Very cool, thanks @dermotduffy for all your hard work and following up on this!
