### ISSUE TITLE
Playback controls not available after selecting video from Timeline view

### ISSUE THREAD

**Issue by heisenberg2980** [dermotduffy/frigate-hass-card#1349]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v5.2.0

**Last working release (if known):**
None

**Browser and Operating System:**
Google Chrome in Windows 11 and Home Assistant app in Android

**Description of problem:**

After opening the Timeline view in Home Assistant and selecting a moment in time when there is no events, the playback controls (i.e. pause, play, mute and jump to a different moment of the video) are not available

**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
> After opening the Timeline view in Home Assistant and selecting a moment in time when there is no events, the playback controls (i.e. pause, play, mute and jump to a different moment of the video) are not available

You mean the native video controls in the video player itself? Can you take a screenshot / video capture to show what you mean?

**Comment by heisenberg2980** [comment]
Yes, the native video controls are not available so the video cannot be paused or jump. This is an screenshot of the normal video with the controls available:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/58039006/61976038-9d92-4819-b49b-9a208d7e8b66)

After selecting a moment in time in the timeline, for example this one marked with a blue X in this screenshot:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/58039006/7d541dd9-a3cf-4555-b686-b724dfa458c1)

Controls are not available anymore:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/58039006/0b2555e1-194b-4712-abdf-16056fb464d7)

**Comment by dermotduffy** [comment]
Weird! Thanks for the screenshots. Mind including your card config so I can attempt to reproduce?

**Comment by heisenberg2980** [comment]
Don´t you have the same issue? I thought it would happen to everyone

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!

(A quick check by clicking on a random spot on the timeline does not show the issue for me, at least with the new builds)
