### ISSUE TITLE
Still image placeholder, slows loading of web-rtc stream

### ISSUE THREAD

**Issue by Morphy99** [dermotduffy/frigate-hass-card#1367]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
5.2.0
**Last working release (if known):**

**Browser and Operating System:**
Chrome x64 Win 10

**Description of problem:**
I've been experimenting with changing the image during the loading of the streams as I keep getting the Frigate default image every now and then.
I added the local image url under cameras which displays correctly however, now it seems to display all the time, delaying the loading of the stream. Is this expected and is there a way to just replace the default image from being displayed when I'm assuming, the stream is taking too long to load?

**Frigate card diagnostic information**

```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.1.6",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "date": "2024-02-11T14:11:49.669Z",
  "frigate_version": {
    "41842a280c048a85ae74c1feea2817e4": "5.0.1/0.13.1-34fb1c2"
  },
  "lang": "en",
  "timezone": "Europe/London",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front",
        "live_provider": "go2rtc",
        "go2rtc": {
          "stream": "front_sub"
        },
        "triggers": {
          "occupancy": false
        },
        "image": {
          "url": "/local/images/loading.gif"
        }
      }
    ],
    "menu": {
      "buttons": {
        "media_player": {
          "enabled": true
        },
        "frigate": {
          "enabled": true,
          "icon": "mdi:arrow-u-left-top-bold"
        },
        "cameras": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "live": {
          "enabled": false
        },
        "clips": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "camera_ui": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        },
        "screenshot": {
          "enabled": true
        },
        "download": {
          "enabled": true
        }
      },
      "style": "outside",
      "position": "bottom"
    },
    "live": {
      "controls": {
        "title": {
          "mode": "popup-top-right"
        },
        "thumbnails": {
          "show_timeline_control": false
        }
      },
      "show_image_during_load": true
    },
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_timeline_control": false
        }
      }
    },
    "media_viewer": {
      "controls": {
        "thumbnails": {
          "show_timeline_control": false,
          "mode": "right"
        },
        "next_previous": {
          "style": "none"
        },
        "title": {
          "mode": "popup-top-right"
        }
      }
    },
    "image": {
      "mode": "camera"
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
> is there a way to just replace the default image from being displayed when I'm assuming, the stream is taking too long to load?

When you say the default image, do you mean the Home Assistant snapshot of the stream? If yes, that is disabled if you set `show_image_during_load` to `false`, in that case you'll just see a blank loading window. But I suspect I'm not properly understanding what you're trying to do.

**Comment by Morphy99** [comment]
I had no configuration at all for loading an image and I kept seeing this: https://raw.githubusercontent.com/dermotduffy/frigate-hass-card/main/images/image-view.png

But I didn't see ` show_image_during_load: false,` sorry! There are soo many. I'll try with that and see how I get on.

**Comment by dermotduffy** [comment]
> I had no configuration at all for loading an image and I kept seeing this: https://raw.githubusercontent.com/dermotduffy/frigate-hass-card/main/images/image-view.png

If the above is the "problem", the `show_image_during_load` is not relevant, but I guess I still don't really know what the problem being reported is. Perhaps take a video clip of what you mean and describe what you'd expect to see?

**Comment by Morphy99** [comment]
> If the above is the "problem", the `show_image_during_load` is not relevant,

Strange, as enabling that has fixed the issue. I'll try describing it. I have four frigate cards on my HA page which are set to web-rtc and when switching onto the page all cards would display the frigate bird for a second before loading the camera feeds. This wouldn't always happen as I'm guessing the browser or server was more responsive at some times more than others.

**Comment by Morphy99** [comment]
I've tried removing that line now to see if I can recreate it but typically, they load with no frigate bird now! I'll leave it out to see if it happens again and I'll try and get a video.

The other issue, as I guess there is two, if I define an image it slows the loading of the stream. 
[This is with an image defined under camera ](https://drive.google.com/open?id=1VqL0Qmp4bVj8UJW9TD7eSN7G8rA0xufz&usp=drive_fs)
[This is without an image defined](https://drive.google.com/open?id=1Vv1Jd_i_fUVrKAIv5MkMk62LBbW5kBw1&usp=drive_fs)

**Comment by Morphy99** [comment]
Hi Dermot. [I finally managed to get a screencap of the issue](https://drive.google.com/file/d/1lcUr6jcn2Dcr1bZsK-pz8IRrqintkZt6/view?usp=sharing)
