### ISSUE TITLE
Snapshots not reliably loading at start

### ISSUE THREAD

**Issue by Daniel-dev22** [dermotduffy/frigate-hass-card#1378]
**Checklist:**

- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
v5.2.0
**Last working release (if known):**

**Browser and Operating System:**
Android 14 Galaxy S24 ultra home assistant companion app 

**Description of problem:**
Often I load home assistant and all frigate cards look like this on the page. The only way to fix it sometimes is to reload the page. Sometimes they eventually load other times it's stuck this way.
![Screenshot_20240224_133811_Home Assistant](https://github.com/dermotduffy/frigate-hass-card/assets/47092714/9cf473b8-f673-464e-9cea-a22db44450a9)

Snapshots should load asap.

Home assistant picture entity cards were much more reliable at loading the snapshot and they loaded much faster.
**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```
{
  "ha_version": "2024.2.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Linux; Android 14; SM-S928U1 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36 Home Assistant/2024.1.5-12102 (Android 14; SM-S928U1)",
  "date": "2024-02-24T20:21:47.500Z",
  "frigate_version": {
    "121894675fc2447d4c58c7cbe23d8009": "5.0.1/0.14.0-74a8fee"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.garage"
      }
    ]
  }
}
```

**Additional information:**

**Comment by dermotduffy** [comment]
Sounds like this could be: https://github.com/dermotduffy/frigate-hass-card/issues/1368

Did this work on prior HA versions? Is this also broken in the HA media browser (outside of the card)?

**Comment by dermotduffy** [comment]
[Issue cleanup] If you still have issues with this, please try the latest release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) first and re-open this. Thanks and good luck!
