### ISSUE TITLE
Support Frigate Native PTZ control

### ISSUE THREAD

**Issue by itispip** [dermotduffy/frigate-hass-card#1379]
**Is your feature request related to a problem? Please describe.**
Request feature to support Frigate native PTZ control

**Describe the solution you'd like**
Now Frigate 0.13 has natively support PTZ, however frigate-card-ptz can only call a HomeAssist service to get the control. Is that possible to directly leverage frigate native feature

**Describe alternatives you've considered**
no

**Additional context**
Frigate 0.13 UI auto display the PTZ pannel which include Pan/Tilt, Zoom control and Preset list. Ideally frigate-card-ptz can leverage them.

**Comment by dermotduffy** [comment]
This is already implemented, but not yet released. Will be in the next release.

**Comment by AdamPflug** [comment]
Is there something major holding back the new release? It'd be cool to have access to this feature if it's already implemented...

**Comment by dermotduffy** [comment]
Hi @AdamPflug, release will be when [this backlog](https://github.com/dermotduffy/frigate-hass-card/milestone/6) is complete. In the meantime, you can always build your own or use github artifacts as shown in this video:

https://dermotduffy.github.io/frigate-hass-card/#/advanced-installation?id=unreleased-versions
