### ISSUE TITLE
Interest in paid short term consulting help with frigate and frigate card?

### ISSUE THREAD

**Issue by mitchell-pioneer** [dermotduffy/frigate-hass-card#1385]
**Is your feature request related to a problem? Please describe.**
I'm considering using frigate and Frigate card to build a low bandwidth video monitoring application. It will be deployed remotely and intermittently accessed via 4G.

**Describe the solution you'd like**
Looking for some short-term consulting help to answer questions by email or Zoom on getting Frigate card configured and working. Already have the basics of HA and frigate working, but I'm struggling with frigate card. Also looking for best practices and suggestions for existing projects to save. If we select the home assistant platform, this could translate into longer-term consulting.

**Describe alternatives you've considered**
we've used VideoLoft and other solutions that don't scale for use by 4G.

**Additional context**
Willing to pay via, credit-card, PayPal or venmo.

**Comment by dermotduffy** [comment]
Sorry, no.

I can only speak for this repo, but this is a hobby in limited free time. You are welcome to use the card for any purpose, request support as a github issue, and in an extreme case if you enjoy the card or get value out of it [buy me](https://github.com/sponsors/dermotduffy) a beer/coffee as a token. But the other side that is that I do not want to be beholden for any particular support requests under any circumstances. I invest best effort to support users, but I already cannot keep up with the demand, so can't ever promise anything. Thank you for understanding!

**Comment by mitchell-pioneer** [comment]
Thanks for the reply.  I get it.  It is a hobby. It's a great project and a lot of fun. 

I'm just struggling to get it running.  All I want is to get the card fully running so I can see what it's capable of. 

If you run across anyone who wants to has some free time and want to get $50 an hour let me know.
