### ISSUE TITLE
Timeline choose date not working on Firefox Android

### ISSUE THREAD

**Issue by marcel263** [dermotduffy/frigate-hass-card#1397]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
5.2.0

**Last working release (if known):**

**Browser and Operating System:**
Android 11
Firefox for Android Beta 124.0b9

**Description of problem:**

Blue date time picker icon not working. Nothing happens when tapping it. FF android should support its own native picker. Desktop no problem.

This possibly related bug in the library used was found: https://github.com/flatpickr/flatpickr/issues/2726

**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
I've already completely removed that library due to issues like this. I just verified the already committed code works fine on FF Android -- so this will be available/fixed in the next release (`v6.0.0`).
