### ISSUE TITLE
Lower res streams with high res upon click

### ISSUE THREAD

**Issue by rhatguy** [dermotduffy/frigate-hass-card#14]
**Is your feature request related to a problem? Please describe.**
Unable to stream full bandwidth streams on mobile

**Describe the solution you'd like**
I'd like to be able to see the lower resolution "detect" streams when I first land on the lovelave page with the card, but then be able to access the high resolution streams by clicking on them, or by clicking on a button.  When I try on my lan, home assistant is pushing upwards of 70mb/s at some points since I have multiple full resolution streams.

**Describe alternatives you've considered**
I could create rtsp based "cameras" in home assistant that bypass frigate altogether and pull the low res streams directly from the cameras, but that somewhat defeats the purpose of frigate.

**Additional context**
Maybe I'm misunderstanding the way I should be using the card.  I initially setup the card using the cameras that are automatically setup by the frigate hass addon.  These pull whichever streams I have tagged for the rtmp feed inside frigate, which I normally have tagged as my high resolution streams.  It also seems I'm not able to leverage webrtc without creating the separate rtsp bases camera entities in HA first.  Perhaps I'm not understanding the intended use of the addon?

**Comment by dermotduffy** [comment]
Right now, the card uses only these video sources:
* The camera entity Frigate exposes in Home Assistant (for the 'Frigate' live source).
* Clips fetched directly from the Frigate server.
* Or, if configured, just renders a [WebRTC](https://github.com/AlexxIT/WebRTC) card underneath, which you can configure any way you want (e.g. via a separate RTSP camera entity, or just configuring the URL directly in the [configuration](https://github.com/AlexxIT/WebRTC#configuration)).

Are you proposing a different video source that is already available somewhere?

[WRT webrtc the behavior you describe is expected. This card is intentionally not re-implementing the WebRTC card, just rendering it and allowing easy access to events/snapshots 'over it']

**Comment by dermotduffy** [comment]
Slightly improving the WebRTC documentation with https://github.com/dermotduffy/frigate-hass-card/pull/15 .

**Comment by rhatguy** [comment]
I've got the cards setup now so that they pull the low res RTSP stream directly from the cameras and display using WebRTC.  That works great.  When I would love to be able to do is to specify a second RTSP stream (the high res one this time) that would be opened up larger or full screen when clicking on the camera.  I don't always want the high res streams chewing up bandwidth every time I load the page, but I would like to be able to click on a camera to pull that stream if I wanted it.

**Comment by dermotduffy** [comment]
It's a fair bit of extra technical complexity to have a whole separate mode for this. However, with #42 now merged, you can add an arbitrary entity to the menu. So this would now work:

- Configure a camera in HA with your high-res feed.
- Configure the card with your low res stream.
- Add the high-res camera entity to your card menu.

Net result: When you click on the camera entity in the menu, the more-info HA dialog will pop up, which for cameras is the video feed (i.e. your high-res video feed in this scenario).

Pretty close to what you want I think? [This is live in the v1.0.0 pre-release so you could experiment there]

**Comment by dermotduffy** [comment]
[Going to close this out, let me know if the solution I've described is not sufficient what you're seeking]

**Comment by rhatguy** [comment]
Just wanted to update that I finally got this implemented last night.  The additions you've made facilitated exactly what I was looking for.  Thanks for this awesome card!
