### ISSUE TITLE
Unauthorized Access for Users Not Admin

### ISSUE THREAD

**Issue by kirsch33** [dermotduffy/frigate-hass-card#1403]
**Checklist:**

- [x] I cleared the cache of my browser

**Release with the issue:**
dev

**Last working release (if known):**
not sure

**Browser and Operating System:**
HAOS/iOS Companion App

**Description of problem:**

My wife's companion app lately has not been loading frigate-card, but doesnt have any issues at all loading the other cards I've configured on the same dashboard.

In inspecting the logs I see this message:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:300
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:26:07 PM (12 occurrences)
Last logged: 2:26:17 PM

[140024757137984] Error handling message: Unauthorized (unauthorized) WIFE_NAME from WIFE_INTERNAL_IP (Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.2 (io.robbie.HomeAssistant; build:2024.561; iOS 17.4.0) Mobile/HomeAssistant, like Safari)
```

The issue goes away if I change my wife's account to Administrator.

I saw some commits to the dev branch lately dealing with support of users/etc so I tried a different dev build (2498--before the user support commit) and the issue remains. So now I'm thinking this may not actually be an issue with frigate-card but maybe with some recent HAOS changes? I wanted to start this issue to see if you or any other users have dealt with this issue before spamming my entire config file and downgrading to v5.2--but if those are needed to help i can provide.

**Comment by dermotduffy** [comment]
[Issue cleanup] Please update to the latest build and let me know if you still have this issue:
  
  https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.3
