### ISSUE TITLE
"Menu>Button: Download" shows download button even when viewing live

### ISSUE THREAD

**Issue by reef-actor** [dermotduffy/frigate-hass-card#1404]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 5.2.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome (Windows/Android)

**Description of problem:**
Enabling the Download button in the Menu section displays the download button always.
The Download button should only be displayed when viewing something that can be downloaded, not when viewing live.

**Comment by dermotduffy** [comment]
If you click it, it's downloading the media from the thumbnail carousel (usually the latest clip or snapshot). I agree that's unintuitive and the thumbnails can optionally have their own download icons anyway.

**Comment by reef-actor** [comment]
I found with the download button on the thumbnails I was accidentally pressing it often when browsing the thumbnails, which is why I changed to the Menu button.

Perhaps it makes sense to move the download button from Menu to Media Viewer?

**Comment by dermotduffy** [comment]
I'll just remove the download button from the live view.
