### ISSUE TITLE
Speaker/Microphone Button don't show/work in Android Companion App

### ISSUE THREAD

**Issue by memattyg** [dermotduffy/frigate-hass-card#1410]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

Android Companion App 
Fire HD 10

**Description of problem:**
I have loaded the frigate card but, when accessed through the android companion app the sound button and microphone button never appear.  These buttons do appear in a web browser on PC and my iOS app.  Sound comes through the camera in the Android App on a regular picture card.

**Frigate card diagnostic information**
I can't seem to copy the whole thing over from the tablet, can you query what is the important part related to the microphone and I will type it in.

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by jsapede** [comment]
access to microphone is usually limited by chrome to https. Chrome is the basis of the companion app.  it could explain you dont have access on your tablety if you're on local LAN network.

you should check this setting on your tablet, worked for me.

https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https#:~:text=Navigate%20to%20chrome%3A%2F%2Fflags,number%20too%20(if%20required).

**Comment by dermotduffy** [comment]
[Issue cleanup] Please update to the latest build and let me know if you still have this issue:

https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.3
