### ISSUE TITLE
annoying banners

### ISSUE THREAD

**Issue by mikki8** [dermotduffy/frigate-hass-card#1413]
Hi,

why is popping up all the time and how to prevent it ?
https://github.com/dermotduffy/frigate-hass-card/assets/76606753/a512a95b-97ef-4663-90d5-2ced347bd0c0

**Comment by dermotduffy** [comment]
https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#title-popups-are-annoying--continually-popping-up

**Comment by dermotduffy** [comment]
Please let me know if this does not resolve the issue, good luck!
