### ISSUE TITLE
Downloaded the lovelace card, but I don't see it in dashboard management 

### ISSUE THREAD

**Issue by raspman** [dermotduffy/frigate-hass-card#1416]
I am fairly new here, so any help or guides on the exact steps to have it show up would be great.  I found a Youtube video indicating sometimes the browser cache needs to be refreshed before you'll see the lovelace card to add to the dashboard, did it and still can't find it to add it.  I installed it via HACS.

Appreciate your help.

**Comment by dermotduffy** [comment]
Have you followed the [installation instructions](https://github.com/dermotduffy/frigate-hass-card/tree/dev?tab=readme-ov-file#installation)?

**Comment by raspman** [comment]
I found the issue.  I didn’t do the follow-up where you discuss the manual resource management, where you need to add a URL, per the instructions.  I do see it now.  I’ll have to do some more reading, but it is saying “Could not determine suitable engine for camera.  Check Troubleshooting.” I’m using a Reolink WiFi Doorbell cam. 

Btw, thank you very much for this software, I am moving away from an older DVR and I am really enjoying this.  A learning curve for me, but the video quality of the recording is great and the near instant notifications in the HA app is awesome.  The only other thing I can’t figure out is how to play the live view with HA and have it show the high-qualify feed without going in slow motion.  I am sure it’s user error. 

Thank you for your help on this.

**Comment by dermotduffy** [comment]
> but it is saying “Could not determine suitable engine for camera.  Check Troubleshooting.” I’m using a Reolink WiFi Doorbell cam.

Hmm. Are you using Frigate itself, or just the Frigate card with a generic camera? Would you mind posting your card config?

**Comment by raspman** [comment]
I’m using Frigate, but I think I have something set up wrong in the Frigate config file.  Would it help to see that?

**Comment by raspman** [comment]
Figured it out by going into the GUI and adding the camera. Main thing I'm trying to fix is the live view is in slow motion and the quality isn't the same as the recording.  Do you need to see my frigate config file?

**Comment by xcymax** [comment]
I was having the same issue, unable to find the installed frigate card. Just started with HA today using the docker container.

Tried clearing browser cache, different browser etc. nothing worked.

Couldn't navigate to the `"Manage resources" -> "Add Resource"` part at all (maybe I'm just blind).

Solution for me was to use the redownload option in HACS for Frigate Card (use the three dots). Now it shows up.

**Comment by raspman** [comment]
I'm still trying to figure out the live view issue.  Absolutely can't get the MSE feed to work, yet recordings are awesome....

**Comment by dermotduffy** [comment]
[Issue cleanup] Please update to the latest build and let me know if you still have this issue:

https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.3
