### ISSUE TITLE
Allow camera to start with predefined pan/zoom settings

### ISSUE THREAD

**Issue by Lockie85** [dermotduffy/frigate-hass-card#1427]
**Is your feature request related to a problem? Please describe.**
Im uncertain if this feature already exists but I'd like to be able to define a Frigate Card to be zoomed to a specific level by default. Right now you can zoom manual on a camera via scroll. However, I'd like to be able to predefine the setting so on loading a camera view it's already zoom on the area I want at the level I want.

**Describe the solution you'd like**
Within the Frigate Card settings I can define a zoom level and a point of the screen to define the centre. I assume this is roughly how the manual zoom works.

Many Thanks

**Comment by Lockie85** [comment]
Can anyone help define if this is an enhancement (feature request) or already possible?

**Comment by dermotduffy** [comment]
> Can anyone help define if this is an enhancement (feature request) or already possible?

This does not already exist and is an enhancement that needs prioritization. I have been thinking about how to do it ...

It's related to https://github.com/dermotduffy/frigate-hass-card/issues/1393 . If implemented the way I had intended in that issue, we wouldn't be able to "zoom back out" from the "pre-zoomed position" -- so now thinking maybe this way is the better choice.

**Comment by dermotduffy** [comment]
This is now implemented, and will be in the next build. As a nice side effect, [you can now do things like this](https://card.camera/#/examples?id=automatically-zoom-based-on-state).

**Comment by Lockie85** [comment]
Amazing, thanks very much!

**Comment by Lockie85** [comment]
@dermotduffy out of interest, when will the next build be released?

**Comment by dermotduffy** [comment]
When [this milestone is complete](https://github.com/dermotduffy/frigate-hass-card/milestone/6). It's slow going, but I'm hoping it won't be too long, really want to get this out the door...
