### ISSUE TITLE
HA: Sections support

### ISSUE THREAD

**Issue by ncodee** [dermotduffy/frigate-hass-card#1435]
I know Sections is experimental, but it would be nice if the Frigate card have support for it since this will become the default layout forthcoming. 

I noticed a few bugs, when using Sections; The card can be moved around in non edit mode, small image size on mobile, menu buttons not loading (mic, expand, fullscreen), and a few other bugs I have missed.

Thanks

**Comment by dermotduffy** [comment]
I haven't played with sections at all. Do you have a dashboard config you can share with me to showcase some of the bugs you spotted?

**Comment by dermotduffy** [comment]
Started looking into this: I'm using the latest card release (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4) and on quick glance this appears to JustWork(TM). Renders fine on browser and companion app, menu buttons look fine, media size is what I expect...

What am I missing?

HA version: `2024.9.3`
Card version: `v6.0.0-beta.4`

![image](https://github.com/user-attachments/assets/a27eb24f-5dfb-4a72-979a-0ca804e118be)

**Comment by dermotduffy** [comment]
Please re-open if you have specifics with Section support that are not working.
