### ISSUE TITLE
Media Gallery / Clips dimensions, allow # of rows setting.

### ISSUE THREAD

**Issue by ns-mglaske** [dermotduffy/frigate-hass-card#1436]
Problem:
I'd like to show a view of a camera live video, with the recent clips below it, but I don't want it to take up the whole screen.

**Describe the solution you'd like**
Allow the Media Gallery / Clips section dimensions to show # of rows of clips.  The ultimate solution for this would be a unified view that showed the live video and clips, and when you clicked on a clip, it would replace the live video with the clip and show controls, and a exit button to return to the live view.

**Describe alternatives you've considered**
I can somewhat do this now, by setting the dimensions to 10vh, but it doesn't always line up.

**Additional context**
Might be useful to also tell the media galllery / clips how many clips to pull from the server, although it looks like maybe it already does this dynamically?

**Comment by dermotduffy** [comment]
> I'd like to show a view of a camera live video, with the recent clips below it, but I don't want it to take up the whole screen.

Thanks for the issue request. I'm struggling to understand though -- how is what you're describing different from just enabling thumbnails underneath the live view, like this:

```yaml
live:
  controls:
    thumbnails:
      mode: below
```

Gets you something like [this](https://raw.githubusercontent.com/dermotduffy/frigate-hass-card/main/images/live-thumbnails.gif).

**Comment by dermotduffy** [comment]
[Issue cleanup] Closing this issue. Please re-open if there's a specific issue with the card that needs to be addressed. Thanks and good luck.
