### ISSUE TITLE
I am unable to get 2 way audio working with my reolink cameras

### ISSUE THREAD

**Issue by shwarnock** [dermotduffy/frigate-hass-card#1446]
**Release with the issue:**
v5.2

**Browser and Operating System:**
Android HA App

**Description of problem:**

**Frigate card diagnostic information**

```json
{
  "ha_version": "2024.4.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "date": "2024-04-19T19:42:35.722Z",
  "frigate_version": {
    "171d821a2557c42e2e6c1bd05709be46": "5.1.0/0.13.2-6476f8a"
  },
  "lang": "en",
  "timezone": "America/Chicago",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front_doorbell_camera",
        "live_provider": "go2rtc"
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "enabled": true,
          "type": "toggle"
        }
      }
    }
  }
}
```

**Comment by dermotduffy** [comment]
Getting 2-way audio working can be challenging since it depends on so many factors. Start here: https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#using-2-way-audio

**Comment by shwarnock** [comment]
I did follow that setup instructions, but it still isn't working

**Comment by dermotduffy** [comment]
> I did follow that setup instructions, but it still isn't working

At the very least your config (as pasted in this issue) does not match the instructions.

**Comment by shwarnock** [comment]
Sorry, I should have mentioned that I found that doc after posting the bug and have since updated my config to be ```type: custom:frigate-card
cameras:
  - camera_entity: camera.front_doorbell_camera
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
menu:
  buttons:
    microphone:
      enabled: true
      type: toggle
```

**Comment by dermotduffy** [comment]
Make sure you are accessing Home Assistant over `https`. Do you have 2-way audio working with [go2rtc](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#two-way-audio)? if you get it working with that, it should "just work" for the card. Make sure `go2rtc` supports 2-way audio for your camera.

**Comment by shwarnock** [comment]
I am trying to do this through the companion app. Does the companion app use https?

**Comment by shwarnock** [comment]
Ok @dermotduffy So I wasn't using https. I have now setup HA to use https. However, I still cannot get audio to work. Can you walk me through how to verify 2-way audio is working with go2rtc?

**Comment by elfux** [comment]
I've got E1 Pro audio working with rtsp protocol and using rtmp with reolink NVR.

I would be cool to get the 2 way audio working as well, if you managed to do it, share the configs

**Comment by DMedina559** [comment]
Just chiming in to say no the doorbell isn't the only reolink camera to support two way audio. 

I just recently installed the RLC-540A and have two way audio working with go2rtc and the frigate card. 

Same config as the doorbell but using aac instead of opus (according to VLC)

**Comment by skynet01** [comment]
Not to hijack a thread ... ... but we all should vote for the author to add Reolink camera recordings to media library feature https://github.com/dermotduffy/frigate-hass-card/issues/1027 😂

**Comment by dermotduffy** [comment]
[Issue cleanup] I'm not sure if there's anything else to implement here on the card side? I will say that getting 2-way audio working with Reolink seems to be both difficult but also common. If anyone wanted to submit a documentation PR describing their setup to help future users, that would be amazing!
