### ISSUE TITLE
Slow Loading of Frigate Card Live Feeds

### ISSUE THREAD

**Issue by thelefty** [dermotduffy/frigate-hass-card#145]
**Checklist:**

- [x ] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
1.2.0

**Browser and Operating System:**

- Home Assistant via any browser (tested Chrome & Safari)
- Home Assistant app for iOS

**Description of problem:**

Since updating to 1.2.0 and Frigate 9.2.1. When viewing the cards via Lovelace through the iOS app or a web browser the cards take forever to load the live feed (8-10 seconds), but before this update it would load the feeds in a matter of 1-2 seconds. Not sure why it takes so long. Is a Frigate thing or a Frigate-hass-card thing?

**Javascript errors shown in the web inspector (if applicable):**

The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
32207 @ styles.ts:367

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
[Closing due to insufficient information to debug]
