### ISSUE TITLE
New action `microphone_disconnect`

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1457]
**Is your feature request related to a problem? Please describe.**
I am trying to build a custom icon that actually looks like a hang up button. This hang up button will `camera_select` another camera but it must also disconnect microphone immediately when clicked.

**Describe the solution you'd like**
There are already actions like `microphone_mute` and `microphone_unmute`, so I think `microphone_disconnect` will be a good addition to the pair.

**Describe alternatives you've considered**
Unfortunately, I found no way around it. I was trying to play with `override` `disconnect_seconds` to `1` when switched back to the given camera, but it doesn't work.

**Additional context**

Here is how it would look like:

https://github.com/dermotduffy/frigate-hass-card/assets/29582865/2baf149e-1d50-4dec-a579-eb9c366a6a87

**Comment by felipecrs** [comment]
I found a clever workaround, which is limited to one device but it's the most important one in my case. I call the HA service to reload the URL through Fully Kiosk, which in turn will "disconnect" microphone.

**Comment by felipecrs** [comment]
@dermotduffy, do you think this is straightforward? I am thinking about doing it.

**Comment by dermotduffy** [comment]
> @dermotduffy, do you think this is straightforward? I am thinking about contributing this.

Yes, I think this should be quite easy.
 - Obviously, make sure you're on the `dev` branch to avoid serious heartache later!
 - Modify `config/types.ts` to update `FRIGATE_CARD_GENERAL_ACTIONS` to include `microphone_disconnect`.
 - Add a new entry in the action factory: `src/card-controller/actions/factory.ts`
 - Add a new action under `src/card-controller/actions/actions` (copy `microphone-mute.ts`)
 - Just have the action call `api.getMicrophoneManager().disconnect();`
 - Add test to `tests/card-controller/actions/actions` (you'll probably also need to update the factory test for code coverage)
 - Update the custom action docs `docs/configuration/actions/custom/README.md`

That should be it!

**Comment by felipecrs** [comment]
Awesome. Thanks a lot. Let this with me.
