### ISSUE TITLE
Microphone button stays on after microphone is disconnected via `disconnect_seconds`

### ISSUE THREAD

**Issue by UserGalileo** [dermotduffy/frigate-hass-card#1460]
**Is your feature request related to a problem? Please describe.**
When `live.microphone.disconnect_seconds` is set, the microphone correctly disconnects after some time. However, if the microphone button is a "toggle" type, it stays in the unmuted state even after it's disconnected, giving the illusion that tha microphone is still working.

**Describe the solution you'd like**
The button should automatically be toggled off when the microphone is disconnected.

**Describe alternatives you've considered**
Switching to a "momentary" button, however I don't particulary like it since there is some time between the tap and the activation of the microphone, so I'd have to keep the finger on the device for some seconds.

Thanks!

**Comment by dermotduffy** [comment]
At least with the new builds (e.g. https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.2) this does not appear to happen. When `disconnect_seconds` expires, I see both the browser and the card show me that the microphone has been toggled off.

Try out a new build and let me know if this is still an issue for you?

**Comment by dermotduffy** [comment]
Please re-open if this is still an issue with the new `v6` builds.
