### ISSUE TITLE
Can't get card to appear anywhere, I have no idea what to do next.

### ISSUE THREAD

**Issue by mjmeans** [dermotduffy/frigate-hass-card#1471]
New install on FreeNas SCALE. From TrueNAS catalog (home-assistant, version 2024.6.0, chart version 2.0.27), (frigate, version 0.13.2, chart version 1.2.6). From TrueCharts (mosquitto, version 2.0.18, chart version 10.0.10). HACS 1.34.0 is installed in home-assistant.

Before trying to install the frigate-hass-card: Frigate web portal working, recording, detecting and saving clips. Home-assistant web portal working, displaying cam count, occupancy sensors, camera images, etc.

The Home Assistant menu on the left shows: Overview, Logbook, History, HACS, Media, To-do Lists.

HASS > HACS shows HACS, Frigate and Frigate Card installed.

NOTE: The frigate-hass-card installation instructions that say "Home Assistant > HACS > Frontend > "Explore & Add Integrations" > Frigate Card" is not the same as what I see. It is "Home Assistant > HACS, then enter Frigate Card in the Search box, select it, then click the Download button in the bottom right corner.

In Settings > Dashboards > [three dots menu] > Resources this is shown "/hacsfiles/config-editor-card/config-editor-card.js?hacstag=43357760347      Javascript Module".

When going to the shell for TrueNAS > Apps > home-asssistant, I don't see any directory called /hacsfile/ or /local/community/. However, I do see the file /config/www/community/frigate-hass-card/frigate-hass-card.js.

The frigate-hass-card readme installation instructions do not match what I'm seeing. Also, the instructions don't specify where or how to add cameras; at least not in this version HASS.

I have no idea what to do next.

**Comment by dermotduffy** [comment]
```
In Settings > Dashboards > [three dots menu] > Resources this is shown "/hacsfiles/config-editor-card/config-editor-card.js?hacstag=43357760347 Javascript Module".
```

... this would be the problem as the Frigate card is absent (i.e. your HA dashboard is not loading it). 

### Try this:

- Navigate:

```
Three dots menu -> "Edit Dashboard" -> Three dots menu -> "Manage resources" -> "Add Resource"
```

- URL: `/hacsfiles/frigate-hass-card/frigate-hass-card.js`
- Resource type: `JavaScript Module`


[The docs have been entirely rewritten for the next release, since the README file is pretty unfriendly. You could take a look here where this is covered: https://card.camera/#/advanced-installation?id=manual-resource-management . Note that as it's the docs for the _next_ release there may be some differences, but for installation the instructions should be valid]

**Comment by mjmeans** [comment]
Thanks for the response. I see there was already another resource containing "/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=394082552520" that I didn't notice. So, I deleted the resource for config-editor since I have uninstalled that now (and for some reason the resource remained even though I uninstalled it. However, the HA dashboard is still not showing after a reset of HA. So, I then tried changing the URL to not include the part from the "?hacstag=394082552520" part and reset HA. I was expecting to see the card right under Overview in the left navigation pane.

The advanced installation instructions say to add the card, but I don't see anywhere in HA a button to (+ Add Card), much less anywhere to add an initial configuration. Here is the main dashboard and some other pages:

![image](https://github.com/dermotduffy/frigate-hass-card/assets/3971751/fc9d5566-238d-4e22-98ad-ce0e197c67bc)

![image](https://github.com/dermotduffy/frigate-hass-card/assets/3971751/2b1e6971-4d1e-4592-a435-4a7d284bdc42)

![image](https://github.com/dermotduffy/frigate-hass-card/assets/3971751/5da1abae-98bb-431b-b0be-4739c3f0daf3)

**Comment by mjmeans** [comment]
I even tried updating HA to 2024.6.1_2.0.28. No joy.

**Comment by mjmeans** [comment]
Could my problem have anything to do with the TrueNAS app version being Home Assistant Core?

**Comment by mjmeans** [comment]
I think I found it. I had to manually add a new Dashboard. The Frigate Card could not be added to any of the default dashboards. Once I added a new dashboard, I as able to add the frigate card.
