### ISSUE TITLE
Run without entity and without NVR frigate directly from go2rtc

### ISSUE THREAD

**Issue by Bobbik1** [dermotduffy/frigate-hass-card#1480]
I heard a rumors that  dev version  runs without actual Frigate , but could it run without a camera entity? Just with go2rtc stream name?

**Comment by dermotduffy** [comment]
> I heard a rumors that dev version runs without actual Frigate , but could it run without a camera entity? Just with go2rtc stream name?

Correct.

**Comment by zessi001** [comment]
Hello,

i like this card. its perfectly for video doorbells.
I use it with go2rtc directly, and it works mostly fine.
But sometimes, Video will not open. When i open the webrtc page in parallel, then video stream in Frigate Hass Card will appaer.

Is it possible, that there is a certificate validation somewhere, which prevents the card from opening the go2rtc stream by using https with self signed certificates? HA and go2rtc run with https and self signed certificates.

If yes, is it possible, to disable the verify SSL checks?

best regards

**Comment by zessi001** [comment]
> I heard a rumors that dev version runs without actual Frigate , but could it run without a camera entity? Just with go2rtc stream name?

You can configure it like this:

  - title: <free title name>
    id: <internal ID for HA>
    live_provider: go2rtc
    go2rtc:
      url: <your webRTC URL for example https://192.168.0.xxx:1985>
      stream: <Stream Name as configured in go2RTC>
      modes:
        - webrtc

best regards

**Comment by dermotduffy** [comment]
[Issue cleanup] As described this should just work straight out of the box. There is no need for Frigate to be used at all.
