### ISSUE TITLE
Need advice on layout optimization 

### ISSUE THREAD

**Issue by JohannCR** [dermotduffy/frigate-hass-card#1481]
Hi,
This is an awesome card, and the only one that works flawlessly to show live cameras in HA, so thanks a lot !

I'm trying to find the best way to handle multiple feeds without it being too heavy on home assistant. I have 5 cameras, and loading all of them in a dashboard makes it quite slow to load, cumbersome to use and the feeds lag, which doesn't surprise me^^
Right now the best method I found is to show feeds on condition using an input_boolean that triggers a state-switch card, and combining cameras. So I have
-  one switch to show interior cameras (2 of them in one frigate card)
- one switch to show exterior cameras (3 of them in one frigate card).

But I'm wondering : when showing a frigate card that contains multiple feeds, do they all use bandwidth ? Do they also use bandwidth when the card is hidden using the state-switch card ? I'm not sure how to test this...

Also I automatically switch between interior/exterior when a person is detected by frigate, and I'd love to show precisely the cameras on which there is a person (or other). Does anyone have ideas on how to do that ? 
- already tried frigate's birdseye view, it's too resource hungry for my setup unfortunately...
- only other option I can think of is using one card per camera, with state-switch on each to show only the pertinent ones, but I'm not sure this is an optimal way to do this, all the more if the feeds still use bandwidth when hidden by the switch card...

Anyone has ideas on how to do that efficiently ?
Thanks

**Comment by dermotduffy** [comment]
> But I'm wondering : when showing a frigate card that contains multiple feeds, do they all use bandwidth ? Do they also use bandwidth when the card is hidden using the state-switch card ? I'm not sure how to test this...

It depends on how you have the card configured. If you have the cameras in a carousel, with lazy-loading enabled (the default), only the "current" camera should be loaded and consuming bandwidth. You can use the `lazy_unload` option to optionally unload cameras when you unselect them. If you do this, you would only ever be "charged" the bandwidth for the camera you are currently looking at, which sounds like what you want. Docs: https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#live-options

> Also I automatically switch between interior/exterior when a person is detected by frigate, and I'd love to show precisely the cameras on which there is a person (or other). Does anyone have ideas on how to do that ?

You should be able to use "Scan mode" to do this, as long as the camera is configured with "person" as a required label. Docs may help: https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#view-scan-mode-configuration . The idea is that when something triggers the camera (e.g. the occupancy sensor), it can take an action.

Scan mode is considerably improved in the `dev` version of the card, but even the released version may meet your needs.

**Comment by JohannCR** [comment]
Forgot about lazy load... I've added it and am trying out the scan mode, it works pretty well so far. Thanks for the tips !
