### ISSUE TITLE
Cast Delay

### ISSUE THREAD

**Issue by Lockie85** [dermotduffy/frigate-hass-card#1482]
Hey,

I'm trying to understand if this is a "how it is", a bug or perhaps an incorrect setup on my part. But when using the Frigate Card and then casting a camera to a device like a Google Display. The difference between the live view on my PC and the Cast view on my Google is about 20 seconds.

I.E. there is a 20 second delay (for me) when casting a camera.

Is this a known issue or is there a known solution to this? Given everything is local I'd have expected delay to be minimal. I've had a quick search but the issues I've seen don't sound quite the same.

Many Thanks

**Comment by dermotduffy** [comment]
So with the very same card config, when casted it "lags" by 20s vs when uncasted and just viewed on a PC? Cannot say I have ever noticed this, but I also don't use HA casting regularly (the casting itself is not something the card is doing, it's asking HA to cast, so I would imagine casting anything else from HA would likely also show you 20s delay even without the card being involved).

**Comment by Lockie85** [comment]
> So with the very same card config, when casted it "lags" by 20s vs when uncasted and just viewed on a PC? Cannot say I have ever noticed this, but I also don't use HA casting regularly (the casting itself is not something the card is doing, it's asking HA to cast, so I would imagine casting anything else from HA would likely also show you 20s delay even without the card being involved).

Yes within the same card. I've modified the buttons which display like so:
![image](https://github.com/dermotduffy/frigate-hass-card/assets/7091582/0e1eb323-7a07-4d75-b7f8-4c22c285b3d1)

When selecting the cast button and a device the best I can achieve is a min of 10 seconds different from what's on my PC to what's on my display. It's the same when trying to cast from another device like my phone.

**Comment by dermotduffy** [comment]
@felipecrs I think you cast regularly, if I'm right have you experienced this latency?

**Comment by felipecrs** [comment]
It is expected to have ~10 seconds delay with the Home Assistant native casting approach, which is based on TLS.

It is theoretically possible to do casting through WebRTC, but Home Assistant doesn't support it yet.

What you can do however is to use the alternative casting method "dashboard".

https://card.camera/#/examples?id=cast-a-dashboard

I suggest you give it a try.

**Comment by felipecrs** [comment]
@dermotduffy, a `cast` profile would be nice to simplify this setup. Things such profile could have:

- No menu (assume casting to a TV with no touchscreen, users can still enable the menu if casting to something like Nest Hub)
- As performant as possible (extension of `low-performance`?)
- Auto-unmute enabled
- Force aspect ratio to 16:9 (fit content)

**Comment by dermotduffy** [comment]
@felipecrs Something like this perhaps? https://github.com/dermotduffy/frigate-hass-card/pull/1575

(I didn't combine with `low-performance` to allow people to choose, but since you can apply multiple profiles, that's trivial to include: added to profiles  doc)

**Comment by felipecrs** [comment]
That's exactly what I meant. I'll try it tomorrow too.

Feel free to merge though, any feedback can also be addressed later.

**Comment by felipecrs** [comment]
@Lockie85, @dermotduffy, casting the standard way is working fine. And such delay is expected.

However, casting a dashboard seems broken indeed.

I'd recommend to close this ticket, and track issues related to casting a dashboard in a different one (here or in HA core/frontend, unsure yet).
