### ISSUE TITLE
custom element doesn't exist : frigate-card on app HA in iphone

### ISSUE THREAD

**Issue by gypais** [dermotduffy/frigate-hass-card#1483]
**Checklist:**

- [X ] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
V5.2 with 
Core 2024.7.0
Supervisor 2024.06.2
Operating System 12.4
Interface utilisateur 20240703.0

**Last working release (if known):**

**Browser and Operating System:**

Everything is fine on the browser, but the problem is only on the phone application (iphone)

**Description of problem:**
https://github.com/dermotduffy/frigate-hass-card/assets/60287372/8707ffbd-1bc1-461b-afaa-b54d8c18cabb

custom element doesn't exist : frigate-card on app HA in iphone

**Frigate card diagnostic information**

On the card, hold down the Frigate menu button for a few seconds then paste the diagnostics below:

**Additional information:**

**Comment by gypais** [comment]
It works now, I don't know why ?

**Comment by dermotduffy** [comment]
Likely an iPhone frontend caching issue.
