### ISSUE TITLE
HA INPUT_BOOLEAN entity not working in Frigate Card Condition

### ISSUE THREAD

**Issue by projectdimpreza** [dermotduffy/frigate-hass-card#1485]
I searched the web for any solution about this issue but cannot find any example on how to make this work. I have a doorbell button that turn on/off HA input_boolean.switch. I use the boolean as  a condition in frigate card. below is the code of my automation.
`automations:
        - conditions:
            state:
              - entity: input_boolean.fullscreen_toggle
                state: 'on'
                state_not: 'off'
          actions:
            - action: custom:frigate-card-action
              frigate_card_action: microphone_unmute
          actions_not:
            - action: custom:frigate-card-action
              frigate_card_action: microphone_mute`

Whenever i press or manually turn ON the input boolean the microphone on camera is not unmuting.. i dont know what im missing here.. also im running HA Server on a mini pc and can access outside my network using cloudfare tunnel.. i also setup mqtt in frigate config.. i can see in  frigate integration that my cameras can detect motion via frigate motion and occupancy entity.

**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

 chrome browser

**Description of problem:**

**Frigate card diagnostic information**

Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.3.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
  "date": "2024-07-14T09:21:58.429Z",
  "frigate_version": {
    "6a6ea1b995f504a673c9b288660d7fc6": "5.2.0/0.13.2-6476f8a"
  },
  "lang": "en",
  "timezone": "Asia/Shanghai",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.hikvision_ch1",
        "live_provider": "go2rtc",
        "id": "ch1",
        "go2rtc": {
          "modes": [
            "webrtc"
          ]
        },
        "triggers": {
          "entities": [
            "switch.doorbell_2"
          ],
          "occupancy": false
        },
        "webrtc_card": {}
      }
    ],
    "menu": {
      "buttons": {
        "microphone": {
          "alignment": "matching",
          "icon": "mdi:microphone",
          "type": "toggle",
          "enabled": true
        },
        "mute": {
          "enabled": true,
          "alignment": "matching"
        },
        "snapshots": {
          "enabled": false
        },
        "expand": {
          "enabled": false,
          "alignment": "opposing"
        },
        "fullscreen": {
          "enabled": true,
          "alignment": "opposing"
        },
        "play": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        },
        "cameras": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "live": {
          "enabled": false
        },
        "clips": {
          "enabled": false
        },
        "download": {
          "enabled": false
        },
        "camera_ui": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        }
      },
      "style": "overlay",
      "position": "right",
      "alignment": "top",
      "button_size": 50
    },
    "live": {
      "auto_unmute": "all",
      "preload": false,
      "draggable": false,
      "microphone": {
        "disconnect_seconds": 0
      },
      "controls": {
        "title": {
          "mode": "none"
        },
        "builtin": false
      },
      "zoomable": false,
      "layout": {
        "fit": "fill"
      },
      "lazy_unload": "all"
    },
    "media_viewer": {
      "controls": {
        "builtin": false,
        "title": {
          "mode": "none"
        }
      }
    },
    "dimensions": {
      "aspect_ratio_mode": "static",
      "aspect_ratio": "4:4"
    },
    "automations": [
      {
        "conditions": {
          "state": [
            {
              "entity": "input_boolean.fullscreen_toggle",
              "state": "on",
              "state_not": "off"
            }
          ]
        },
        "actions": [
          {
            "action": "custom:frigate-card-action",
            "frigate_card_action": "microphone_unmute"
          }
        ],
        "actions_not": [
          {
            "action": "custom:frigate-card-action",
            "frigate_card_action": "microphone_mute"
          }
        ]
      }
    ]
  }
}

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Please update to the latest build and let me know if you still have this issue:

https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.1

**Comment by dermotduffy** [comment]
Please re-open if still an issue with the new releases. Thanks and good luck!
