### ISSUE TITLE
Full screen with HA mobile app

### ISSUE THREAD

**Issue by jagauthier** [dermotduffy/frigate-hass-card#1486]
Using the HA app on my android phone, I am trying to look at the video stream in full screen mode.

Upon opening the card I see this:
![Screenshot_20240723_121101_Home Assistant](https://github.com/user-attachments/assets/91c8b213-4ec4-4755-a9e5-9283a246af3e)

And then after hitting the full screen button just this:
![Screenshot_20240723_121109_Home Assistant](https://github.com/user-attachments/assets/6aa70c70-b7d6-493e-a801-829a738f0e54)

Doesn't seem to respect phone rotation.  Anything I can do?

**Comment by felipecrs** [comment]
@jagauthier this may be related:

- https://github.com/dermotduffy/frigate-hass-card/issues/590

**Comment by dermotduffy** [comment]
I believe this is an issue with the HA frontend, not with the card. The now stale issue @felipecrs created is here to prevent the frontend from re-rendering when the orientation changes:

https://github.com/home-assistant/frontend/issues/13726

Sadly, I think this is infeasible to make progress in, in the absence of HA frontend changes.
