### ISSUE TITLE
Only show XX hours in Snapshots Gallery

### ISSUE THREAD

**Issue by awilliams84** [dermotduffy/frigate-hass-card#1490]
Hopefully there is a way and I missed it, otherwise this might be a very useful feature. 

I monitor events mostly based on triggers, but it would be helpful to see only the day of events (or events in the last XX hours) when looking at the dashboard.

**Comment by dermotduffy** [comment]
> I monitor events mostly based on triggers, but it would be helpful to see only the day of events (or events in the last XX hours) when looking at the dashboard.

In the gallery there is a "When" filter in the drawer on the right hand side, that should let you narrow it down to the past day. Is that what you mean? If not, can you describe a little more the feature / usecase? Perhaps you mean in the thumbnail carousel on a non-gallery view?

**Comment by dermotduffy** [comment]
Please re-open with additional details if you'd like to pitch for a new feature!
