### ISSUE TITLE
Timeline does not move to match selected media

### ISSUE THREAD

**Issue by danishru** [dermotduffy/frigate-hass-card#1542]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

v6.0.0-beta.1

**Last working release (if known):**

**Browser and Operating System:**

Google Chrome 128.0.6613.120. Windows 10 pro 22H2 19045.3086

**Description of problem:**

When selecting a clip or recording from the clip or recording gallery, the timeline does not move to the time section of the selected video, but remains at the current time position, using the timeline in this form becomes inconvenient. It is necessary for the timeline to follow the time of the selected video.

**Comment by dermotduffy** [comment]
Confirmed as bug.
