### ISSUE TITLE
Audio only camera

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/frigate-hass-card#1559]
For baby monitoring for some reason unmuting the audio automatically is not working on some of my devices, so i would love a way to just use the audio stream in a media card that automatically plays when on dashboard.

**Comment by dermotduffy** [comment]
> For baby monitoring for some reason unmuting the audio automatically is not working on some of my devices, so i would love a way to just use the audio stream in a media card that automatically plays when on dashboard.

Do you mean a "audio only camera" effectively, i.e. the live view never plays video but does play audio?

**Comment by borgqueenx** [comment]
Yes, basically its like having a mp3 file opened in any browser, you get a play/pause button that its playing.
Ive noticed that when using frigate cards together with a popup card, when the popup card is automatically triggered due to a sensor/entity going on, audio on frigate cards is not working on my home assistant companion apps, but is working on desktop. I hope that specifically having a audio stream solves this.

**Comment by dermotduffy** [comment]
I suspect the user demand for an audio only camera is going to be very low. If there's an issue with the Frigate card not unmuting when you think it should, it might be better to try to fix that issue rather than implement something no-one else is going to use? Maybe you could describe the bug you have with the auto unmuting, and include card diagnostics (hold down the Frigate button in the menu for a few seconds and it'll give you diagnostics you can paste into this issue).

**Comment by borgqueenx** [comment]
I already discovered that when i use a automation to "touch" the screen(part of the video) of the android device running the home assistant app while the stream is loading, the audio works. 
Else it does not start. Could this be related to the companion app or a dependancy of the companion app, like web view or something?

**Comment by borgqueenx** [comment]
here is the code from the debug: 

`card_version: 6.0.0-beta.3
browser: >-
  Mozilla/5.0 (Linux; Android 8.1.0; Lenovo StarView Build/OPM7.181205.001; wv)
  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.70 Mobile
  Safari/537.36 Home Assistant/2024.7.3-13278 (Android 8.1.0; Lenovo StarView)
date: 2024-09-25T19:09:43.412Z
frigate_versions:
  a7191c8d59b0d181b8932ca5cc64e16b: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: Europe/Berlin
git:
  hash: 9c68b30
  build_date: Mon, 23 Sep 2024 02:47:19 GMT
  commit_date: Sun, 22 Sep 2024 19:39:40 -0700
ha_version: 2024.9.3
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.living_room_2
      live_provider: webrtc-card
    - camera_entity: camera.poolpole_cam
      live_provider: webrtc-card
    - camera_entity: camera.backyard_tree
      live_provider: webrtc-card
    - camera_entity: camera.naelis_place
      live_provider: webrtc-card
  live:
    auto_unmute:
      - selected
      - microphone
      - visible
`

**Comment by dermotduffy** [comment]
Ah, it might be the browser engine preventing the card for unmuting when there hasn't been user interaction. If this happens on the PC too, you would be able to see a message on the Javascript console (F12 in Chrome) when this happens. This makes sense, as we don't want random web pages to be able to unmute audio -- would be pretty spammy -- so browsers won't let Javascript unmute unless there's been some user interaction with the source of the audio (e.g. video).

**Comment by dermotduffy** [comment]
If this is the issue, an audio only camera would very likely have the same restriction...

**Comment by borgqueenx** [comment]
ah, thats too bad but fair enough. this does not happen on PC, but happens on the android companion app i am using.
Would this be something fixable to request as feature at the home assistant development team? or is it something external that the companion app uses?
Thanks for the clarification!

**Comment by dermotduffy** [comment]
> ah, thats too bad but fair enough. this does not happen on PC

If my theory is right, it should _also_ happen on the PC. Although perhaps the PC browser has a different threshold for the video having been interacted with. I can certainly reproduce this on Chrome if I haven't interacted with the page meaningfully.

You should be able to connect a USB cable to your device, and attach your chrome debugger to the app. It would log something in the console at the moment it tries to unmute. Without seeing that message, I'm afraid I'm just guessing at what the issue might be -- it could well be something else. Generally this behavior is not a bug though -- it's on purpose to avoid automation spamming the user with audio, so I don't think there really is a "fix".

**Comment by borgqueenx** [comment]
thanks for the explanation, its probably a difference then between the threshold! then this can be closed. I kinda hacky solved the issue by simulating a touch on the screen using automate for android, this is enough for audio to start loading.
