### ISSUE TITLE
Request: resizing cards or changing to portrait.

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/frigate-hass-card#1561]
I would love a feature to stretch cards to make them more visible. This could be achieved by stretching the cameras and cards. For example if we take a 16:9 camera we can turn it into 9:16 to fit portrait devices if we could zoom in and/or stretch the camera pixels. I dont know is either is possible to make, but would love such a feature.
As of now, we can zoom in, but the card remains the format of the camera's aspect ratio. Also tried playimg around with aspect ratio settings but not getting a portrait card out of a landscape aspect ratio camera. Maybe im doing something wrong, that is also entirely possible!

**Comment by dermotduffy** [comment]
Depends on what you want to do, this is likely possible already. See this example:

https://card.camera/#/examples?id=convert-a-landscape-camera-to-a-portrait-live-view

The full documentation is here, and includes quite a few permutations out of the box (see diagrams):

https://card.camera/#/configuration/cameras/README?id=layout-configuration

**Comment by borgqueenx** [comment]
thanks, that works, although the menu of pause/play and volume is then not visible anymore and i have to scroll to go there.
