### ISSUE TITLE
Page Freezes when Camera becomes unavailable.

### ISSUE THREAD

**Issue by oerix** [dermotduffy/frigate-hass-card#1599]
**Checklist:**
- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:** 
5.2.0

**Last working release (if known):** 
Unknown, always had this issue with prior version

**Browser and Operating System:** 
Safari, Chrome / macOS 14 & 15.1, Frigate 14

**Description of problem:**
When the camera becomes unavailable/goes offline in my case the Reolink camera connected via Frigate, the whole page freezes and becomes unresponsive. The frigate card just displays a blank white space, with no error messages or anything, after a while the whole page crashes.

**Frigate card diagnostic information**
Unfortunately, I can't post any diagnostic information or logs, as the whole page freezes and nothing renders on the Frigate card. I'm also not able to post any information from the browser console due to this. If there is any other way, please do let me know?

**Javascript errors shown in the web inspector (if applicable):**
As above

**Additional information:**
I'm not sure how Frigate card handles when devices go offline, but something doesn't seem right, it should in theory show an error/warning message saying the 'device is offline' and not freeze the whole page and then crash.

**Comment by dermotduffy** [comment]
Please try the new beta: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4

It changes how unavailable cameras are handled, so it may help.
