### ISSUE TITLE
Buttons don't render properly with most recent Home Assistant dev image

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#160]

**Comment by dermotduffy** [comment]
Fixed. The underlying Home Assistant button component changed. Fix will be in the next build.

**Comment by thundergreen** [comment]
Is it already in dev?

**Comment by dermotduffy** [comment]
Do you mean is it already part of a pre-release build? Not yet, this weekend.

**Comment by thundergreen** [comment]
OK i wait then :) thanks for the info.

**Comment by dermotduffy** [comment]
This fix is present in the new v2.0.0 pre-release: 
https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1602062
