### ISSUE TITLE
Cameras button should not show up by default if there's only one camera

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1603]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 6.0.0-beta.4

**Last working release (if known):** 5.2.0

**Browser and Operating System:** N/A

**Description of problem:**

When working on https://github.com/dermotduffy/frigate-hass-card/pull/1602, I realized that the _Select camera_/_cameras_ button is enabled by default even when there's only one camera in the card.

I think it should be disabled by default in such case, unless explicitly enabled by the user. Don't you think?

**Frigate card diagnostic information**

N/A

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

N/A

**Comment by dermotduffy** [comment]
> I think it should be disabled by default in such case, unless explicitly enabled by the user. Don't you think?

Or just disabled entirely? Doesn't serve any function with a single camera.

**Comment by felipecrs** [comment]
Yes, that's true. I agree.
