### ISSUE TITLE
Video stops shortly after zooming in on WebRTC Card on Android

### ISSUE THREAD

**Issue by bikemike** [dermotduffy/frigate-hass-card#1614]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Android 15 (AP41.240823.009)
Chrome version 129.0.6668.81

**Description of problem:**
On my android phone, after zooming in on a stream that uses WebRTC Card provider, the stream will soon stop playing. It seems to work on my Linux computer.

To get the stream to play again I must zoom out. Clicking the screen while zoomed in will not resume it.

The go2rtc provider seems to work fine.

https://github.com/user-attachments/assets/aecce2a7-ee28-44c8-8137-cb7f15c89f6e

**Frigate card diagnostic information**

card_version: 6.0.0-beta.5
browser: >-
  Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/129.0.0.0 Mobile Safari/537.36
date: 2024-10-04T18:14:28.590Z
frigate_versions:
  2fc97ec23d4ebf918965a8977d7b7723: 5.4.0/0.14.1-f4f3cfa
lang: en
timezone: America/Vancouver
git:
  hash: 21b4687
  build_date: Thu, 03 Oct 2024 03:34:25 GMT
  commit_date: Wed, 2 Oct 2024 20:28:13 -0700
ha_version: 2024.9.3
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.birdseye
      live_provider: go2rtc
      go2rtc:
        modes: []
    - camera_entity: camera.front_yard
      go2rtc:
        modes:
          - webrtc
        stream: front_yard_high
      live_provider: webrtc-card
      webrtc_card:
        url: front_yard_high
    - camera_entity: camera.doorbell
      go2rtc:
        stream: doorbell_high
        modes:
          - webrtc
      live_provider: webrtc-card
      webrtc_card:
        url: doorbell_high
    - camera_entity: camera.coopcam
      live_provider: webrtc-card
      go2rtc:
        modes:
          - webrtc
        stream: coopcam_high
      webrtc_card:
        url: coopcam_high
    - camera_entity: camera.violetcam
      live_provider: go2rtc
      capabilities:
        disable_except:
          - substream
  menu:
    buttons:
      media_player:
        enabled: false
        priority: 50
      mute:
        enabled: true
  live: {}
  cameras_global:
    dimensions:
      layout: {}

```yaml

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
I think I can reproduce this with a simple card using the `webrtc-card` provider:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
    live_provider: webrtc-card
```

If I zoom in and wait a few seconds (5-10) the whole video display appears to go black. It does not resume playing until I zoom back out again (the video appears to need to reload).

Sound like the same issue?

**Comment by bikemike** [comment]
Nice, thanks!
