### ISSUE TITLE
Zooming and panning bug, cannot zoom out completely.

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/frigate-hass-card#1618]
send a video showing the problem to the developer personally.
frigate card remembers the position when you zoom in or pan around etc. sometimes when this position is set, and you return later, frigate card does not allow you to zoom out to view the full camera view anymore. also panning around is sometimes buggy, it always resets to a initial position when you put your finger on screen.
The camera has a 1440p resolution.

**Comment by dermotduffy** [comment]
@borgqueenx I'm struggling to reproduce this. Would you mind holding down the Frigate menu button in the card and paste the diagnostics here, so I have the config and correct version.

Here's what I tried to use to reproduce the issue:

 - Setup a card with a camera
 - Zoom in
 - (Leave the card alone for some period of time?)
 - (At this point I should not be able to zoom back out?)

Are these the correct steps?

**Comment by dermotduffy** [comment]
Please re-open with requested information if this is still an issue, thanks!
