### ISSUE TITLE
Logs with depreciated variable

### ISSUE THREAD

**Issue by HomeBotOtto** [dermotduffy/frigate-hass-card#1621]
Logger: homeassistant.components.media_player.const
Source: helpers/deprecation.py:197
integration: Media player (documentation, issues)
First occurred: 12:37:56 PM (6 occurrences)
Last logged: 12:37:56 PM

MEDIA_CLASS_IMAGE was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.IMAGE instead, please report it to the author of the 'frigate' custom integration
MEDIA_CLASS_MOVIE was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.MOVIE instead, please report it to the author of the 'frigate' custom integration
MEDIA_CLASS_VIDEO was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.VIDEO instead, please report it to the author of the 'frigate' custom integration
MEDIA_TYPE_IMAGE was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.IMAGE instead, please report it to the author of the 'frigate' custom integration
MEDIA_TYPE_VIDEO was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.VIDEO instead, please report it to the author of the 'frigate' custom integration
**Additional information:**

**Comment by dermotduffy** [comment]
That's an integration problem, not a card problem. It's also already fixed, but probably needs a new build:

https://github.com/blakeblackshear/frigate-hass-integration/pull/726
