### ISSUE TITLE
No audio via Home Assistant intergration after switching from Addon to standalone server

### ISSUE THREAD

**Issue by jtricerolph** [dermotduffy/frigate-hass-card#1653]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
**Only just installed**
- Please try clearing your browser cache.
**Tried and tested on multiple machine/device**

**[REQUIRED] Card diagnostic information:**

**Sorry, not sure what this is asking me to do, there is no frigate menu button on the card?**

**[REQUIRED] Description of problem:**

had the card working well with the frigate addon inhome assistant but wanted tomove frigate over to my more powefull NAS that runs the workshop/garage as HA pc is lighter weight in the house for Zigbee stuff etc.
After changing to standalone frigate on my unraid server and reconfiguring the HA intergration to the server ip etc the cards show video but no sound and mic has disapeared.
The frigate proxy addon to bridge between them UI wise shows the cams in the companion app etc fine with sould localled and externally.
Not sure what to try next.

**Comment by dermotduffy** [comment]
> Sorry, not sure what this is asking me to do, there is no frigate menu button on the card?

In the card, there's a Frigate icon on the menu. Hold it down for a few seconds, let it go, and diagnostics information will appear. Paste that here.

**Comment by dermotduffy** [comment]
Please re-open with the required details if you still have an issue.
