### ISSUE TITLE
Cannot mute live feeds on camera load  for `webrtc-card` provider

### ISSUE THREAD

**Issue by ziptbm** [dermotduffy/frigate-hass-card#1654]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**
```
{
  "ha_version": "2024.10.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
  "date": "2024-10-22T11:37:16.320Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "America/Detroit",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.front_porch_webrtc",
        "webrtc_card": {
          "entity": "camera.front_porch_webrtc"
        },
        "live_provider": "webrtc-card"
      },
      {
        "camera_entity": "camera.doorbell_webrtc",
        "webrtc_card": {
          "entity": "camera.doorbell_webrtc"
        },
        "live_provider": "webrtc-card"
      },
      {
        "camera_entity": "camera.circle_drive_webrtc",
        "webrtc_card": {
          "entity": "camera.circle_drive_webrtc"
        },
        "live_provider": "webrtc-card"
      },
      {
        "camera_entity": "camera.driveway_webrtc",
        "webrtc_card": {
          "entity": "camera.driveway_webrtc"
        },
        "live_provider": "webrtc-card"
      }
    ],
    "live": {
      "auto_mute": "all"
    }
  }
}
```

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_porch_webrtc
    webrtc_card:
      entity: camera.front_porch_webrtc
    live_provider: webrtc-card
  - camera_entity: camera.doorbell_webrtc
    webrtc_card:
      entity: camera.doorbell_webrtc
    live_provider: webrtc-card
  - camera_entity: camera.circle_drive_webrtc
    webrtc_card:
      entity: camera.circle_drive_webrtc
    live_provider: webrtc-card
  - camera_entity: camera.driveway_webrtc
    webrtc_card:
      entity: camera.driveway_webrtc
    live_provider: webrtc-card
live:
  auto_mute: all
```

**[REQUIRED] Description of problem:**

Within the UI for this card, there's an option for Automatically Mute Live Cameras to be "All Opportunities" which puts this setting as "all" in the YAML.  Shouldn't this option automatically set the live camera feeds to a muted state?  If not, how do you accomplish this?  I do not want the audio on unless I tap the unmute button for any of the camera feeds.

<img width="1021" alt="Screenshot 2024-10-22 at 07 39 40" src="https://github.com/user-attachments/assets/0f765763-223c-47c3-98ff-04ec1a24691a">

What's interesting is the [configuration documentation for live auto_mute](https://card.camera/#/configuration/live) does not even show the "all" option available or provide any instruction that's clear to accomplish this goal.  

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by tm8** [comment]
Same here!

**Comment by dermotduffy** [comment]
Please try the latest beta release and let me know if the issue persists: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.8

**Comment by dermotduffy** [comment]
> Shouldn't this option automatically set the live camera feeds to a muted state?

It should! This may have been fixed already, give the beta release a shot.

**Comment by ziptbm** [comment]
> > Shouldn't this option automatically set the live camera feeds to a muted state?
> 
> It should! This may have been fixed already, give the beta release a shot.

I’ve upgraded to the beta, but haven’t been able to fully test due to network connectivity (cellular issues at the moment).  But the all option is no longer in it and breaks the current config.  What’s the recommend setting to have them muted by default?

**Comment by dermotduffy** [comment]
> UPDATE - it looks like the "all" option is no longer available with the beta. And I've now tried all three options available (individually and all together), but none of those configurations start the live camera feeds in a muted state.

OK -- that sounds like a bug. What you are trying to do should definitely be possible (in fact should be the default). Can you hold down your Frigate button again and paste your diagnostics with the new beta version. I will attempt to reproduce.

**Comment by ziptbm** [comment]
> > UPDATE - it looks like the "all" option is no longer available with the beta. And I've now tried all three options available (individually and all together), but none of those configurations start the live camera feeds in a muted state.
> 
> OK -- that sounds like a bug. What you are trying to do should definitely be possible (in fact should be the default). Can you hold down your Frigate button again and paste your diagnostics with the new beta version. I will attempt to reproduce.

Here you go.  PLMK what else I can provide to help or test.  Thanks! @dermotduffy 

card_version: 6.0.0-beta.8
browser: >-
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
  like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
date: 2024-10-23T16:23:02.730Z
lang: en
timezone: America/Detroit
git:
  hash: a869109
  build_date: Mon, 14 Oct 2024 00:01:23 GMT
  commit_date: Sun, 13 Oct 2024 16:50:47 -0700
ha_version: 2024.10.2
config:
  type: custom:frigate-card
  cameras:
    - camera_entity: camera.garage_webrtc
      live_provider: webrtc-card
      webrtc_card:
        entity: camera.garage_webrtc
  live:
    auto_mute:
      - microphone

**Comment by ziptbm** [comment]
> > > UPDATE - it looks like the "all" option is no longer available with the beta. And I've now tried all three options available (individually and all together), but none of those configurations start the live camera feeds in a muted state.
> > 
> > 
> > OK -- that sounds like a bug. What you are trying to do should definitely be possible (in fact should be the default). Can you hold down your Frigate button again and paste your diagnostics with the new beta version. I will attempt to reproduce.
> 
> Here you go. PLMK what else I can provide to help or test. Thanks! @dermotduffy
> 
> ```
> card_version: 6.0.0-beta.8
> browser: >-
>   Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML,
>   like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
> date: 2024-10-23T16:23:02.730Z
> lang: en
> timezone: America/Detroit
> git:
>   hash: a869109
>   build_date: Mon, 14 Oct 2024 00:01:23 GMT
>   commit_date: Sun, 13 Oct 2024 16:50:47 -0700
> ha_version: 2024.10.2
> config:
>   type: custom:frigate-card
>   cameras:
>     - camera_entity: camera.garage_webrtc
>       live_provider: webrtc-card
>       webrtc_card:
>         entity: camera.garage_webrtc
>   live:
>     auto_mute:
>       - microphone
> ```

@dermotduffy is there anything I can do in the meantime to force a mute by default?

**Comment by ddanielww** [comment]
same issue here, is this resolved ?

**Comment by ddanielww** [comment]
v5.4.0

**Comment by ddanielww** [comment]
The go2rtc option does not work well on mobile.

The webrtc card works nicely but i can not mute it :(

**Comment by doctorkb** [comment]
> v5.4.0

That doesn't seem to be a defined release... at least it isn't visible to me, or in HACS.

**Comment by ddanielww** [comment]
![Capture -2024-11-04](https://github.com/user-attachments/assets/463a3949-b517-42e4-ac2e-759dd83e7545)
downloaded from hacs

**Comment by doctorkb** [comment]
That's a different repo / fork: 
![image](https://github.com/user-attachments/assets/9bf27015-4a57-45a9-8a2f-149da05ea99f)

This one is:
![image](https://github.com/user-attachments/assets/46849d7e-89a7-4a32-8e6e-f1bb8d423898)

**Comment by ddanielww** [comment]
not sure how that happened.

Downlaoded from hacs, just removed and re-downloaded but still same issue on latest beta.

![Capture -2024-11-04](https://github.com/user-attachments/assets/c236a50f-6b00-4865-9455-a486c2c4d5e8)

**Comment by dermotduffy** [comment]
I believe this is now fixed. The issue was very simple, `webrtc-card` starts unmuted, `frigate-card` always starts (and assumes things start) muted. This should be in the next build. In this case though, you should be able to manually tell `webrtc-card` to start muted by passing parameters through to it like this:

```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.back_yard
    live_provider: webrtc-card
    webrtc_card:
      muted: true                      <-- This parameter gets passed through
```
