### ISSUE TITLE
Make the swipe feature optional

### ISSUE THREAD

**Issue by Mincka** [dermotduffy/frigate-hass-card#167]
**Is your feature request related to a problem? Please describe.**
I like the new swipe feature but it could be incompatible with swipe-card or lovelace-swipe-navigation.

**Describe the solution you'd like**
Allow enabling / disabling the swipe action in the card options.

**Describe alternatives you've considered**
I requested to ignore this card for [lovelace-swipe-navigation](https://github.com/maykar/lovelace-swipe-navigation/issues/63).

**Comment by dermotduffy** [comment]
Did you try out the new functionality? Or you are predicting the conflict will be an issue? I'm don't use either of those, so I'm interested to know what happens if you have tried: implementing this is also not trivial and will involve separate codepaths to maintain, so want to make sure it's worth it (i.e. there's an actual problem to work around).

**Comment by Mincka** [comment]
I use lovelace-swipe-navigation on mobile and I run 12cee94d49d1f3fa516c4dcd0158cc7914530aba.
I built it myself to test the latest version.

If I swipe on the card (which is my original intent), the dashboard view is swiped because of lovelace-swipe-navigation. 
That's why in my case, I would be happy if the card is ignored in lovelace-swipe-navigation.

Actually, that's not an issue with this card in the end since the swipe feature doesn't prevent me to swipe between the views. I am closing this issue for now and will wait for lovelace-swipe-navigation to ignore this card, I think it's a better approach.

**Comment by dermotduffy** [comment]
I had a look at the carousel API, and I think this is actually trivial to expose. The carousel would remain, but it would no-longer be swipeable. Maybe that's better than having the other card ignore this one in a locked fashion, as users could just tweak a parameter in this card if they're having problems?

**Comment by dermotduffy** [comment]
Verified that this is trivial to expose, and fits nicely post the configuration rework in #169 . Re-opening to implement.

**Comment by Mincka** [comment]
I can confirm it's working as intended. Thank you.
