### ISSUE TITLE
Full Screen -  Mobile Browser

### ISSUE THREAD

**Issue by ddanielww** [dermotduffy/frigate-hass-card#1673]
The latest build V6.0.0 Beta 8.

When you use the frigate menu in the card, full screen works on desktop but does not work in IOS browser or home assistant app.

**Comment by dermotduffy** [comment]
This is a known (and likely intentional) limitation of one phone manufacturer:

See: https://card.camera/#/troubleshooting?id=fullscreen-doesn39t-work-on-iphone

You may wish to vote on this issue to implement a workaround: https://github.com/dermotduffy/frigate-hass-card/issues/1444
