### ISSUE TITLE
Frigate card for non-existent camera DDoSing HA server making UI and server unresponsive

### ISSUE THREAD

**Issue by hiteshsharma** [dermotduffy/frigate-hass-card#1674]
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**
I can't get this because HA is becoming unresponsive on the dashboard where the card is. Bug report is for this issue which is making HA unresponsive

**/api/camera_proxy/ is being requested at 100+ qps at load (in a loop without any throttling), making entire HA unresponsive**

I'm using frigate Lovelace card in HA. Frigate is running outside of HA and is integrated via frigate integration. The card works fine but yesterday I disconnected my camera (powered it off) and now when I open HA, the card is calling /api/camera_proxy endpoint at 100+ qps. It's like running in a loop without any throttling. This blocks the entire HA UI entirely.

I believe there should be some throttling backed into this call with some upper bound after which an error is displayed on UI.

Even weirder thing is that all the requests (10000+ within a few seconds) are waiting for response which implies that next request is being dispatched even without waiting for the first one.

This is like a DDos on my HA server

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment]
Well that sounds bad. You don't specify which version of the card you're using, but try one of the latest betas if you haven't already (it fixes some issues related to this, and has per-camera engine request concurrency limit support):

https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.8

**Comment by hiteshsharma** [comment]
This fixed it. Thanks!
