### ISSUE TITLE
 Problem after updating to home assistantt 2024.11

### ISSUE THREAD

**Issue by primevisionservices** [dermotduffy/frigate-hass-card#1677]
On my devices with Chrome, after updating to the new version of Home Assistant, the event videos are no longer loading. 
In the Home Assistant app it works normally, the problem is on all devices that run the home assistant in chrome

**Comment by jeffreyrdubois** [comment]
Seems to be a common issue with the latest Home Assistant Versiom

**Comment by dermotduffy** [comment]
Duplicate: https://github.com/dermotduffy/frigate-hass-card/issues/1678
