### ISSUE TITLE
Add entity buttons on top of Video

### ISSUE THREAD

**Issue by SteveLobdell** [dermotduffy/frigate-hass-card#1683]
I'd like the ability to add entity buttons on top of the video (like any other frigate card button).  For example, when viewing a camera feed and it's too dark, I could quickly tap the light button for that room.  Great card guys!

**Comment by dermotduffy** [comment]
Do you mean add a button to the menu?

If yes: https://card.camera/#/examples?id=menu-state-icons

**Comment by SteveLobdell** [comment]
Yep!  Thanks!
