### ISSUE TITLE
Does this work with remote Frigate server?

### ISSUE THREAD

**Issue by SteveLobdell** [dermotduffy/frigate-hass-card#1688]
**[REQUIRED] Card diagnostic information:**

```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.11.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
  "date": "2024-11-22T01:27:49.305Z",
  "frigate_version": {
    "01JD7ZX1VDQGMCF4PYVEDKT3XR": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "America/Chicago",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.steve_office",
        "live_provider": "go2rtc",
        "go2rtc": {
          "modes": [
            "webrtc"
          ],
          "stream": "steve_office"
        }
      }
    ],
    "menu": {
      "style": "overlay",
      "alignment": "right",
      "position": "bottom",
      "buttons": {
        "cameras": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "download": {
          "enabled": false
        },
        "frigate": {
          "enabled": true
        },
        "clips": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        },
        "microphone": {
          "enabled": true
        },
        "mute": {
          "enabled": true
        }
      }
    },
    "live": {
      "controls": {
        "builtin": false
      }
    }
  }
}
```

**[REQUIRED] Description of problem:**

This is not really a bug, but I just set up a Frigate server outside of HomeAssistant.  Everything works great except in the card now I can no longer use go2Rtc as the live provider because all it asks for is the stream name but it's on a remote server.   Does this card only work if Frigate is installed as an addon?  I searched online but couldn't find anything addressing my specific issue.  I know I could use a different card to load up a remote stream but I do really like the frigate card.  Thanks

Steve

**Comment by dermotduffy** [comment]
Yes, this should work fine. As long as the Frigate integration is installed, it doesn't matter if you're using the HA Frigate Addon or a remote Frigate server (I'm using a remote Frigate server myself).

**Comment by SteveLobdell** [comment]
Hmm, any idea where this could go wrong?  I can view the streams fine in the go2rtc web interface.  Are there any other ports that need to be exposed on the Frigate server for go2rtc besides 1984?  How does the Frigate card find the go2rtc stream?  Using the same server ip as Frigate but different port?

**Comment by SteveLobdell** [comment]
I think that was left over from trying to get 2way audio to work back when I had Frigate installed as an add-on.  I just tried adding a new Card, and just selecting my camera.  The video is really choppy, like it updates once a second.  This is the camera entity that the Frigate integration created for me.  I'm sure I'm missing something stupid.

**Comment by SteveLobdell** [comment]
Looking at the Frigate logs, I see this every second when I'm viewing the camera, so it's obviously not able to find the livestream for some reason.

frigate  | 2024-11-23 15:41:21.821617951  192.168.0.67 - - [23/Nov/2024:15:41:21 +0000] "GET /api/front_door/latest.jpg HTTP/1.1" 200 75738 "-" "HomeAssistant/2024.11.3 aiohttp/3.10.11 Python/3.12" "-"

**Comment by dermotduffy** [comment]
Do you definitely have a go2rtc stream with the name "steve_office" configured?

**Comment by owaismai** [comment]
Try this trick, 
Under
Live view provider for this camera, choose **JSMpeg**
Disable **Show still image while the live stream is loading**

![frigatecard1](https://github.com/user-attachments/assets/485271da-e898-434d-836c-6658c8a72999)

**Comment by SteveLobdell** [comment]
Wow, oddly without changing anything else I unselected that option and it works now.  Thanks a lot!

**Comment by dermotduffy** [comment]
> Wow, oddly without changing anything else I unselected that option and it works now. Thanks a lot!

Ah, you're on HA `2024.11`, and I suspect maybe you're caught up in [Issue 1](https://github.com/dermotduffy/frigate-hass-card/issues/1678#issuecomment-2466489875). Since you have a satisfactory workaround, suggest we consider this closed and that other issue can get the real fix in...
