### ISSUE TITLE
Threshold / squelch for audio activation

### ISSUE THREAD

**Issue by ministryofsillywalks** [dermotduffy/frigate-hass-card#1700]
**[REQUIRED] Describe the feature you'd like:**

I have a few cameras I like to monitor live. They have sound enabled but the environment has some background noise (wind, cars driving by, etc) 
These are mostly very "quiet" noises but can still be annoying/distracting so I would love to have the option of an audio threshold level as of which audio would activate on the card.
So for example if there is a loud noise above a certain db-level like a scream audio would enabled, otherwise audio would be muted.

**[OPTIONAL] Describe alternatives you've considered:**

Tinycam app on android has this feature and it works great, however I want to implement this in home assistant as well.
https://www.tinycammonitor.com/manual/camera_audio.html

Thanks a lot for your work!

**[OPTIONAL] Additional context:**

**Comment by dermotduffy** [comment]
Thanks for the request. I don't think it would make sense for the _card_ to implement this. The card is not actively processing the video or audio at all. I think this is something that should happen on the Frigate backend, and when Frigate decides there is an event, the card reacts to that.

In fact, this might already work, have you played with [https://docs.frigate.video/configuration/audio_detectors/](audio detectors). The card can already react to Frigate events.
