### ISSUE TITLE
[Deprecation] -ms-high-constrast is in the process of being deprecated. 

### ISSUE THREAD

**Issue by pressurejets** [dermotduffy/frigate-hass-card#1709]
[Deprecation] -ms-high-constrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.

**Comment by dermotduffy** [comment]
I'm afraid I have no idea what this refers to / what usage you're referring to. The only reference I can find to this is in the theme for the card documentation, is that what you mean?
