### ISSUE TITLE
Setting default view other then live view gives error

### ISSUE THREAD

**Issue by euro2** [dermotduffy/frigate-hass-card#171]
![01](https://user-images.githubusercontent.com/6632948/139941392-333f02f0-1d3a-4b03-811a-cd0c2f0f191c.PNG)

Ive been messing with Frigate a lot, reinstalling over and over. Recordings didnt work. Finally i changed mqqt prefix and client_id to something else and recordings started working.

Now (after removing and adding this card in hacs, also tried beta 1.2.1) i get this error.

**Comment by dermotduffy** [comment]
Have you set the client_id in the card config to match the client_id you ended up with? It's an option under "Optional" in the card editor. The error message just means that Home Assistant does not recognize the Frigate instance with the default client_id ("frigate").

**Comment by euro2** [comment]
bingo! must have overlooked that. thank you.

**Comment by dermotduffy** [comment]
No problem!
