### ISSUE TITLE
How to use the frigate card?

### ISSUE THREAD

**Issue by Xa4-J** [dermotduffy/frigate-hass-card#1712]
A have always used the cusom gallery-card as slideshow for my images and videos. This card doesn't work anymore. Hacs pointed to frigate card, but how to set it up? It's not clear how to configure it to present the images and videos in the media folder.

**Comment by dermotduffy** [comment]
> A have always used the cusom gallery-card as slideshow for my images and videos. This card doesn't work anymore. Hacs pointed to frigate card, but how to set it up? It's not clear how to configure it to present the images and videos in the media folder.

What is your goal? Frigate card cannot show arbitrary media in a gallery, but can show media of supported camera engines (e.g. Frigate, motionEye or [experimental] reolink), then it can help. If you're only interested in media from those types of cameras, this card can help. Otherwise, it cannot.

**Comment by Xa4-J** [comment]
> > A have always used the cusom gallery-card as slideshow for my images and videos. This card doesn't work anymore. Hacs pointed to frigate card, but how to set it up? It's not clear how to configure it to present the images and videos in the media folder.
> 
> What is your goal? Frigate card cannot show arbitrary media in a gallery, but can show media of supported camera engines (e.g. Frigate, motionEye or [experimental] reolink). If you're only interested in media from those types of cameras, this card can help. Otherwise, it cannot.
> 
> Full documentation is at: https://card.camera/

Thanks for your answer. In that case I can not use this card. Goal is to have a slideshow of photos and videos. The custom gallery card in hacs pointed to the frigate card but that looks like its only for cameras.

**Comment by dermotduffy** [comment]
> Goal is to have a slideshow of photos and videos. 

If your camera is a Frigate camera, that would work. If it's any arbitrary photos/videos, I'm afraid this is not the card for you.
