### ISSUE TITLE
`hover-card` menu style is broken

### ISSUE THREAD

**Issue by Maddin1684** [dermotduffy/frigate-hass-card#1721]
Hover menu (Card-wide) doesn‘t come up when tapping the Card. It only works when tapping the Menu area.

**Comment by dermotduffy** [comment]
Please follow the new issue template, as I need diagnostics information to help you further. Minimally, please hold down the Frigate menu button in the card for a few seconds and then paste me the result here.

**Comment by dermotduffy** [comment]
... having said that, I can easily reproduce this, so never mind :-) Thanks for the report.
