### ISSUE TITLE
Option to remove native video controls from live stream

### ISSUE THREAD

**Issue by paco-atiiienza** [dermotduffy/frigate-hass-card#1722]
**[REQUIRED] Describe the feature you'd like:**

Configuration parameter to disable native video controls that come from the 'controls' attribute of the video tag.

**[OPTIONAL] Describe alternatives you've considered:**

I'm unaware if there's a workaround to accomplish this right now.

**[OPTIONAL] Additional context:**

I don't want to see the default video controls while hovering over the live feed, but from what I'm able to tell, there's no option to disable it.

![image](https://github.com/user-attachments/assets/720b5f6a-6f3f-411d-a722-825440ae7452)

**Comment by conorlap** [comment]
The option is there in the card.

Live > Live Controls > Built-in video controls

```
live:
  controls:
    builtin: false
```
