### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Welsyntoffie** [dermotduffy/frigate-hass-card#1727]
**Checklist:**

Using latest version
- Please try clearing your browser cache. -> Cleared

**[REQUIRED] Description of problem:**

Camera initialization failed: API error whilst subscribing to events for unknown Frigate instance frigate. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).

**[OPTIONAL] Last working release (if known):** Never could get it to work

I have the frigate integration working. From the integration I use the camera entity for the frigate card but get an error about API.
Frigate is running on port 5005 and go2rtc is running on port 1984.
I have deleted the card and redownloaded.

Using bare minimum for the frigate card...
type: custom:frigate-card
cameras:
  - camera_entity: camera.back_yard
  
Runnign on Debian 12 via docker.

**Comment by dermotduffy** [comment]
Please include the diagnostic information the new issue template requests -- that information is needed so I can help you.

In this case (guessing), you might be setting a custom value in your frigate config (not the card config, but Frigate itself) for:

```
mqtt:
  client_id: <SOMETHING>          <---------------- Are you setting this value?
```

The default of that value is `frigate`. In this case, it seems that the card cannot find an instance with that value, is it possible you set it to something else? If yes, you need to tell the card like this:

```
type: custom:frigate-card
cameras:
 - camera_entity: camera.back_yard
  frigate:
    client_id: <VALUE HERE>
```

**Comment by Welsyntoffie** [comment]
You nailed it. Thanks.
I had 2 pc's running frigate and testing which one did better. I ended up using the one with...
  client_id: frigate_mint
  
  Adding the non default mqtt client ID on the card solved the problem.
  Thanks a million
