### ISSUE TITLE
Low Performance Mode Gone Since 6.0.0 update - Breaking Echo Show Usage

### ISSUE THREAD

**Issue by sircoynie** [dermotduffy/frigate-hass-card#1735]
Missing Low Performance Mode option since update 6.0.0

Hi all, not sure if anyone can help advise if there's a workaround or if this is a bug.

I have been using the frigate card with multiple devices for a while now. 2 such devices being Echo Show devices. I had the frigate card transitioning from camera to camera with lazy load on and in low performance mode. This would work and not crash silk.

Since the update Low performance mode has disappeared as an option and i can't seem to figure out the new options and how to get them to work and not overload the memory of the echo devices causing silk to crash.

I have looked at the new options but can't find any info on what chunk size actually does and how it relates to low/high performance modes which were there before?

Thanks.

**Comment by dermotduffy** [comment]
> Since the update Low performance mode has disappeared as an option

No it hasn't :-) It is pretty much unchanged. What leads you to the conclusion it's been removed? What behavior are you seeing on your device.

Enable it like this:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.office
profiles:
  - low-performance
```

> I have looked at the new options but can't find any info on what chunk size actually does and how it relates to low/high performance modes which were there before?

Documentation should help, PRs welcome to improve it: https://card.camera/#/configuration/performance

**Comment by dermotduffy** [comment]
Please re-open with more details if you'd like further support.
