### ISSUE TITLE
Does not render correctly with `rtl` languages

### ISSUE THREAD

**Issue by niro-zz** [dermotduffy/frigate-hass-card#1740]
hi hello 
There is a small problem when homeassistant is configured in the Hebrew language 
It does not display videos or images 

If I add to the card
the following code 

 card_mod:
  style: |
    ha-card {
      direction: initial;
    }
It displays the video and images 

But there is still a frigate-card-submenu problem edge in the menu  

thanks

**Comment by dermotduffy** [comment]
The issues are not super clear. Lets make sure I understand.

> It does not display videos or images

So without that styling, you see nothing? OK, I can test this.

> But there is still a frigate-card-submenu problem edge in the menu

Can you include a screenshot of what you mean?

**Comment by niro-zz** [comment]
Hi, I've been trying to fix this all day with cardmod, thank you very much, it works great and wonderful.
