### ISSUE TITLE
Live view freezes and jerks with Reolink

### ISSUE THREAD

**Issue by copa80** [dermotduffy/frigate-hass-card#1745]
Since 6.0.0 release the live view does Not work. It stucks freeze and jerks. 10 cameras all the same. Worked brilliant before.

**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml

```

**[REQUIRED] Description of problem:**

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by Gamso** [comment]
@copa80 Can you confirm that it's the same problem as this issue #1741 ?

**Comment by copa80** [comment]
> @copa80 Can you confirm that it's the same problem as this issue #1741 ?
Yes seems to be the same

**Comment by dermotduffy** [comment]
Closing as duplicate of #1741
