### ISSUE TITLE
Icons are gone in menu

### ISSUE THREAD

**Issue by Thom-x** [dermotduffy/frigate-hass-card#175]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

1.2.0 (also master)

**Last working release (if known):**

I don't know

**Browser and Operating System:**

Chrome Version 95.0.4638.69 (Build officiel) (64 bits)
Firefox 94.0 (64 bits)
Windows 10

I tried with private navigation and without

**Description of problem:**

Icons are blank on menu

![image](https://user-images.githubusercontent.com/6797195/140313176-64ef3a23-dd15-4124-b973-b1a9d5be854d.png)

Not sure this is linked but I get this error:

**Javascript errors shown in the web inspector (if applicable):**

![image](https://user-images.githubusercontent.com/6797195/140313217-06c7b369-d791-4b4d-8293-c111b9b484da.png)

**Additional information:**

**Comment by dermotduffy** [comment]
This is already fixed in code (see [pinned issue](https://github.com/dermotduffy/frigate-hass-card/issues/160)), there'll be a build this weekend. If you'd rather not wait, rolling  back your HomeAssistant version would also work .

**Comment by dermotduffy** [comment]
This fix is present in the new v2.0.0 pre-release: 
https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1602062

**Comment by Thom-x** [comment]
Thanks 👍
