### ISSUE TITLE
Onvif is not setup for XXX

### ISSUE THREAD

**Issue by speakradmin** [dermotduffy/frigate-hass-card#1753]
https://github.com/blakeblackshear/frigate/discussions/14056 refers

Seems like the latest card update is probing cameras for onvif controls that do not exist. I have tried adding PTZ to the list of disabled camera capabilities but the frigate log keeps filling up with these errors. I would not have thought to post this here if not for the comment made by @hawkeye217
![image](https://github.com/user-attachments/assets/ac770c74-5be5-4f6a-bec6-a76a024753fa)

**Comment by dermotduffy** [comment]
Please update your Frigate instance.

**Comment by dermotduffy** [comment]
Please re-open if the problem persists with the most recent Frigate (not the card) releases.

**Comment by speakradmin** [comment]
Thanks for the reply,

I have been on Frigate 14.1 for a while now without seeing these errors and they only started when updating the integration and card. They're harmless so I'm happy to wait until version 15 stable release.
