### ISSUE TITLE
Card Disappears when Resizing Browser or Switching Lovelace Tabs When Using JSMPEG

### ISSUE THREAD

**Issue by Fredrick-III** [dermotduffy/frigate-hass-card#176]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.2.0

**Last working release (if known):**

**Browser and Operating System:**
Windows 10 / Chrome 95.0.4638.69 / Firefox 94.0.1

**Description of problem:**
When using `live_provider: frigate-jsmpeg`, the card disappears when resizing the browser or switching between lovelace tabs. The log entry appears everytime the card disappears.

**Javascript errors shown in the web inspector (if applicable):**

```
http://10.0.0.5:8123/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=X Uncaught TypeError: this._elementResized is not a function
http://10.0.0.5:8123/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=X TypeError: this._elementResized is not a function
```

**Additional information:**
Running Home Assistant 2021.11.0 in Docker.

**Comment by dermotduffy** [comment]
I suspect this will help: https://github.com/dermotduffy/frigate-hass-card/issues/170#issuecomment-957694336

**Comment by Fredrick-III** [comment]
> I suspect this will help: [#170 (comment)](https://github.com/dermotduffy/frigate-hass-card/issues/170#issuecomment-957694336)

It works! Thank you, I didn't see there was a beta earlier.
