### ISSUE TITLE
Submenu truncated with `permanent` buttons

### ISSUE THREAD

**Issue by niro-zz** [dermotduffy/frigate-hass-card#1761]
Hi

custom:frigate-card-menu-submenu does not display all content

When the card is not in full screen mode, the menu is displayed and everything works properly

When the card is in full screen, I have a condition that the menu will be hidden and only display what I selected in the settings

<img src="https://github.com/user-attachments/assets/d466b95b-bb30-4960-8699-da213de2299e" width=50% height=50%>

<img src="https://github.com/user-attachments/assets/6d22e8bf-4ffe-4534-8122-2ec29e14a045" width=50% height=50%>

**Comment by dermotduffy** [comment]
Please use the new issue template and include the requested diagnostics so I can attempt to reproduce.

**Comment by dermotduffy** [comment]
I tried this with the cast submenu and the camera submenu, in fullscreen, with עִברִית as my language, and the menu seems to render fine. Might depend on the browser, so I'll try to reproduce with your exact config when I have the diagnostics.

**Comment by niro-zz** [comment]
hi 
I don't think the problem is related to Hebrew "rtl" because I changed homeassitant to English and it still happens 

After many attempts in the settings of 
 frigate-card 
I learned to understand that this happens when you select the menu in "style: hidden"

And it also happens in full screen and not full screen mode

I also tried in other browsers

**Comment by dermotduffy** [comment]
> Please use the new issue template and include the requested diagnostics so I can attempt to reproduce.

I cannot help you further without these diagnostics. From the new issue template:

```
<!-- =================================================================
***               PLEASE DO NOT IGNORE THIS TEMPLATE
***
*** This is the smallest amount of information needed to help you!
====================================================================== -->

**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

<!--
On the card, hold down the Default/Frigate menu button for a few seconds then paste the diagnostics below. No help can be provided without this
-->
```
