### ISSUE TITLE
Question: Browse ha's media folder

### ISSUE THREAD

**Issue by oeiber** [dermotduffy/frigate-hass-card#1772]
Hi,
is it possible to add a media folder as gallery source even when frigate is not installed?

thank you!

**Comment by dermotduffy** [comment]
@oeiber . No. It can show `frigate`, `motioneye` or `reolink` media -- and any other camera if someone would implement it, but it cannot show a general media folder of some other kind currently.

Recommend you chime in on #1748 with your usecase, as we're discussing just such a feature.
