### ISSUE TITLE
No icons using 2021.11 version

### ISSUE THREAD

**Issue by r11a** [dermotduffy/frigate-hass-card#178]
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Already fixed. New beta build will be this weekend. 

See: https://github.com/dermotduffy/frigate-hass-card/issues/160

**Comment by dermotduffy** [comment]
This fix is present in the new v2.0.0 pre-release: 
https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1602062
