### ISSUE TITLE
Card stops showing Camera after 5 Seconds.

### ISSUE THREAD

**Issue by awptechnologies** [dermotduffy/frigate-hass-card#1780]
Core 2024.12.4
Frontend 20241127.8

card_version: 6.1.0
browser: Mozilla/5.0

In this release of homeassistant as soon as page refreshes i can view cameras just fine. After about 5 seconds camera goes out and it displays an error.
request:
  type: frigate/events/get
  instance_id: frigate
  cameras:
    - living-room
  limit: 50
  id: 66
response:
  code: frigate_error
  message: >-
    API error whilst retrieving events for cameras ['living-room'] for Frigate
    instance frigate

As soon as you refresh page it works then stops again.

**Comment by dermotduffy** [comment]
https://card.camera/#/support?id=diagnostics-missing-in-issue
