### ISSUE TITLE
Discuss: Are there too many releases?

### ISSUE THREAD

**Issue by petervk** [dermotduffy/frigate-hass-card#1781]
There has been a recent change to this card where releases happen automatically, but they are happening so incredibly often. Can you change it to at least max one release per day, or maybe only one per week? There were four releases on Dec 16th alone which seems unnecessary.

**Comment by dermotduffy** [comment]
@petervk I agree it's a dramatic change to go from no stable release for more than a year, to fully automated releases. However, it's _much_ better this way -- new features and fixes get immediate testing, I don't have to repeatedly tell people to "try the latest beta", we don't accumulate any "untested debt" in the codebase and we can exactly pinpoint which change breaks things for people.

Can you explain why too many releases is a bad thing? What is the problem this is causing you?

**Comment by AndyGJ** [comment]
I don't think its a major issue, but I do agree with petervk - from my perspective a a user, the notification from HA saying there is an update is currently nearly always the frigate card. I would prefer some buffering of releases personally - it seems out of step with the other components of HA to me in terms of frequency.

No doubt this is a better release strategy technically, but I don't (in my view) need as a user to be notified to update so frequently.

**Comment by Delta1977** [comment]
Cou can allways install the Update automatically  with a backup

**Comment by roverpixel** [comment]
Different users certainly have different levels of what they may consider noise.  Could this be a matter of adding a shush period for dismissals in HA? 
No matter the approach, I have lower interest in a stream of updates, as long as I am not waiting for a fix.  It is definitely a personal preference.

**Comment by dermotduffy** [comment]
> need as a user to be notified to update so frequently.

To make sure I understand: When we say "notified" here, do we just mean "If we navigate to HACS, we see an update is available", or is there some more active/disruptive notification you're referring to?

**Comment by AndyGJ** [comment]
Its not disruptive, nor particularly active but I get a notification in settings (the same as if HA itself was requiring an update).

**Comment by haforme** [comment]
I kind of thought the same thing concerning the number of releases on December the 16th but then again, I received a fix that was in a released version during that time period that solved a problem for me. I appreciated that thanks to the developer.

**Comment by dermotduffy** [comment]
In practice, the number of releases is throttled by how many PRs are merged, and the number of PRs is throttled by the time I have available, e.g. there's been no release in the last 5 days (busy!), but there might be multiple over the holiday period (less busy!).

I think it breaks down like this:
 - For me: Hugely beneficial to release every PR.
 - For some users: Somewhat beneficial to release every PR.
 - For some users: Annoying to release every PR.

I think that's positive on balance and honestly (sorry!), this does not sound especially disruptive when I think the workaround is "just ignore the little notification to update" :-)

Feel free to re-open this or request a reconsider if this becomes too annoying! Thanks.
