### ISSUE TITLE
Icons Missing in latest version of Home Assistant Core

### ISSUE THREAD

**Issue by Shermer321** [dermotduffy/frigate-hass-card#186]
I just updated to the latest Home Assistant core and now my icons are gone. Browser cookies cleared, restarted. All that jazz. I have the circles but no icon. Can't upload a picture but it is self explanatory. 

core-2021.11.1

**Comment by dermotduffy** [comment]
This is a known issue with any custom card that uses the HA provided button component, and the very latest HA release.

It's already fixed in a pre-release version of this card, see [this thread](https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1602062). 

Good luck!

**Comment by Shermer321** [comment]
I seen that when I went back to the issues page. So sorry for double
asking. Appreciate the email. Great work!
