### ISSUE TITLE
Fetch events via integration websocket/proxy, not directly

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#19]
* Necessary to support Nabu Casa.
* Would make setup easier for addon users.

**Comment by Haloooch** [comment]
Adding my comments here as I think they are related. I have HA running on SSL through a domain: https://home.mydomain.net:8123/

Frigate however is not on SSL: http://192.168.1.166:5000

Both are accessible on my browser (at least internally), but when the card tries to pull in content, I get the 'Failed to fetch' error. When checking the console, I can see the browser is flagging a warning of trying to load mixed content (http & https) and blocks the http (frigate) content.

Accessing frigate content through the integration should resolve this issue.

(Side note, amazing addition to HA. I used the Aarlo custom card prior to switching my camera's over to Unifi & frigate. This is exactly what I was looking for, thank you!)

**Comment by s24dor** [comment]
thanks dermot, this would defiantly helps a lot, btw the card is great, exactly what i was looking for.

**Comment by dermotduffy** [comment]
Hi all, I have a fairly complete fix for this ready. I hope to have a pre-release in the next few days.

**Comment by dermotduffy** [comment]
FYI: [The new pre-release is available for testing](https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1283669)

[Please open new bugs/requests as appropriate](https://github.com/dermotduffy/frigate-hass-card/issues/new/choose)
