### ISSUE TITLE
Show Clips and Snapshots without a reverse proxy

### ISSUE THREAD

**Issue by corgan2222** [dermotduffy/frigate-hass-card#20]
**Describe the solution you'd like**
It would be great if the card could use the clips and snapshot that already exists in HA (Media Browser). ATM i could only use the live view from the frigate camera entity. The clips and Snapshots can't be displayed.
I don't want to expose the frigate URL to the internet (as I'm using haproxy on pfsense) only to show the latest clips, or install a seperate proxy. 

**Additional context**
I'm running frigate as an unraid docker container and use the integration in HA.
HA running via haproxy on pfsense on ha.mydomain.url
The frigate URL is http://192.168.x.x:5005

**Comment by corgan2222** [comment]
As the request was posted at the same time, I think this is the same request 
https://github.com/dermotduffy/frigate-hass-card/issues/19

**Comment by dermotduffy** [comment]
I think it's different. #19  one is about fetching the event metadata via HA, this one is about fetching the event _contents_ via HA media browser. I had the same idea! I couldn't immediately find a way to extract the media out of the media browser to play via another means (i.e. NOT the media browser), but I'll try harder as it's a good idea.

**Comment by corgan2222** [comment]
Thanks a lot! Hit me, if I can help to test!

**Comment by dermotduffy** [comment]
Hi all, I have a fairly complete fix for this ready. I hope to have a pre-release in the next few days.

**Comment by dermotduffy** [comment]
FYI: [The new pre-release is available for testing](https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1283669)

[Please open new bugs/requests as appropriate](https://github.com/dermotduffy/frigate-hass-card/issues/new/choose)
