### ISSUE TITLE
HomeAssitant Stream support LL-HLS

### ISSUE THREAD

**Issue by hcgonzalezpr** [dermotduffy/frigate-hass-card#200]
**Is your feature request related to a problem? Please describe.**
Could we leverage HomeAssistant LL-HLS support for better low latency videos?

**Describe the solution you'd like**
https://www.home-assistant.io/integrations/stream/#ll-hls

**Comment by hcgonzalezpr** [comment]
Closing this issue, I just tried the LL-HLS settings and I see it does work. Lowering the segment_duration option to 2 managed lower delay to 2 seconds.

**Comment by dermotduffy** [comment]
Hi @hcgonzalezpr Would you mind sharing the settings/config you used? We may want to include this in the documentation (for the integration, don't think this is a card issue really).

**Comment by dermotduffy** [comment]
Thanks. Added a link to LL-HLS from the card README.
