### ISSUE TITLE
Download clip works in browser; does not work in companion apps

### ISSUE THREAD

**Issue by irakhlin** [dermotduffy/frigate-hass-card#202]
**Description of problem:**
After updating and upgrading the configuration to frigate card 2.0 release I am seeing the following behavior when attemping to download a clip:

Navigating to a specific clip; I have the option to download the clip via the new download button...
**In Chrome (Windows)**
Clicking the download button will download the clip without prompt and works as expected. No additional page is launched.
**In Firefox (Windows)**
Clicking the download button will present a prompt to download the clip. No additional page is launched.
** iOS Companion App ** 
Clicking the download button has no response.
**iOS Safari Browser (Firefox/Chrome in iOS works the same)**
Clicking the download button presents a prompt to download the clip. No additional page is launched.

I do not have a great deal of front end dev experience especially when it comes to iOS apps but looking at the code it;
https://github.com/dermotduffy/frigate-hass-card/blob/e99a5a5ef7fd9ed998528cb9f0558cee64dbccb1/src/card.ts#L610

This is used to initiate the download without opening a new window which is great but it seems it may not be possible in the iOS app? I do not have access the Android version of the app to check if this works in there. 

Doing some basic investigation I was able to make this work by changing the launch to using:
window.open(link, "_blank")

I guess this is a bit of a hack as it simply launches a new window using the default browser set in the companion app. Seemed to work regardless of which browser was set but of course it changes the app screen to the new window.

I am not sure if there are other ways to trigger the download from the iOS companion app but if not would it be possible to construct the command depending on the client? This could allow to not have to open a new window in most cases but still allow iOS app to function.

**Comment by dermotduffy** [comment]
[Same behavior on Android, thanks for the report!]

**Comment by irakhlin** [comment]
Let me know if I can be of any assistant on this.
I fixed this in a hackish way by detecting iOS and changing launch mechanism based on it; 
`if (this._iOS()) {
      window.open(response,'_blank');
    } else {
      link.setAttribute('download', '');
      link.href = response;
      link.click();
      link.remove();
    }`

Curious if this is really a bug/intended feature of the iOS/Android app itself?
