### ISSUE TITLE
Issue with the Frigate 0.10 beta

### ISSUE THREAD

**Issue by MrAnonymous722** [dermotduffy/frigate-hass-card#204]
**Checklist:**

- [X] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**V2.0.0

**Last working release (if known):**V2.0.0

**Browser and Operating System:**Google Chrome, Windows 10. Also shows up on Google Chrome on my iPhone.

**Description of problem:**When an 'in progress' event is occurring, the card breaks for the duration of that event. 
![image](https://user-images.githubusercontent.com/26932670/142731616-0dc1f0d6-9f54-4bd4-b167-531f9e5187de.png)

**Javascript errors shown in the web inspector (if applicable):**None that I can see.

**Additional information:**Not sure if this is even a valid bug, since its a beta release of Frigate, but I hadn't seen it in the open bugs here so I decided to let y'all know.

**Comment by dermotduffy** [comment]
[That's annoying. I can't transfer to `blakeblackshear/frigate-hass-integration/`, I'll just leave it here]

**Comment by dermotduffy** [comment]
Successfully reproduced. Working on the fix.
