### ISSUE TITLE
Live providers for external and internal use

### ISSUE THREAD

**Issue by Wism** [dermotduffy/frigate-hass-card#206]
Thank you for your great card!

Maybe not for everyone, but for me it would be a nice addition to be able to use different live providers for external and internal use.

**Comment by dermotduffy** [comment]
Hi @Wism , thank you for the request!

> Maybe not for everyone, but for me it would be a nice addition to be able to use different live providers for external and internal use.

Can you explain a little more what the usecase is (why you want different live providers)?

I think by "external and internal use" you mean on home work vs external network -- am I right? I'm not sure there's a way for a Lovelace card to know the difference (?), and for some users (e.g. me!) they'll be the same. But I'll dig into whether it's feasible or not once I understand the usecase a little more.

**Comment by Wism** [comment]
Hi @dermotduffy, thanks for your prompt reply.

Maybe posted too quickly. WebRTC seems to be forwarded when on mobile data. Is that correct?

**Comment by dermotduffy** [comment]
Yes, WebRTC can be accessed externally -- although that is not related to this card per se. See [WebRTC external access](https://github.com/AlexxIT/WebRTC#webrtc-external-access for how to set that up.
