### ISSUE TITLE
Support cycling cameras on card update

### ISSUE THREAD

**Issue by chvvkumar** [dermotduffy/frigate-hass-card#221]
**Is your feature request related to a problem? Please describe.**
I have one display that I show the card on fullscreen. As you can see below, it is too small to display multiple cameras at once and be legible.  It would be really nice if I can list multiple cameras and objects and the card rotate through the latest snapshot from each camera.

**Describe the solution you'd like**
Play a slideshow of most recent snapshots from each specified camera at specified interval.

**Describe alternatives you've considered**
Multiple displays but this does not scale well. Also exploring surveilance card for this purpose but it shows all cameras at once:

https://github.com/custom-cards/surveillance-card

**Additional context**
This is the display I am using. A 5 inch waveshare LCD with RPi 3B on my desk. 

![image](https://user-images.githubusercontent.com/16548147/143691326-75bca3ac-9e9b-4a67-a135-4c6ccb845d9a.png)

**Comment by dermotduffy** [comment]
I like this idea in general, but implementing it would incur fairly massive complexity in the card -- as everything would need to support multiple cameras. If only the latest snapshot supported multiple cameras, it would be pretty confusing I think.

How about something like https://github.com/igloo15/slideshow-card (from a quick search)? You'd configure multiple Frigate cards, and that would cycle through them for you.

**Comment by chvvkumar** [comment]
I will try the slideshow card. What about a 'latest snapshot' MQTT message from Frigate itself with the latest snapshot from all cameras and all objects? Would that be too much change to the codebase?

**Comment by dermotduffy** [comment]
It's the change from 1 camera to multiple cameras that's the issue, as it changes a fundamental underpinning of the card (that everything is based around a single camera). I think the only real feasible way around that is to move the N-to-1 outside the card, by either using a slideshow card (as linked), by having something in the integration itself (e.g. combines multiple MQTT images as you describe) or something on the Frigate backend (e.g. something like the birdseye view, except it cycles through the cameras).

**Comment by dermotduffy** [comment]
I'm going to close this out as I think implementing this outside of this card is the right way forwards -- but let me know if the slideshow doesn't work and/or you have other ideas.

**Comment by chvvkumar** [comment]
> I'm going to close this out as I think implementing this outside of this card is the right way forwards -- but let me know if the slideshow doesn't work and/or you have other ideas.

Sorry for the late reply, appreciate your time in looking into this request! Do you want me to submit this as a feature request on the main Frigate repo?

**Comment by dermotduffy** [comment]
No, that won't help either. There's only one Frigate card, and this is the repo for it. The main Frigate repo does not involve itself with Home Assistant at all.

Try the slideshow and let me know how it goes? If for some reason that doesn't work maybe we need a different _kind_ of Frigate card entirely or something else creative, but lets try the easier path first?

**Comment by chvvkumar** [comment]
I will try the slideshow. 

Also, I should have been clearer, I meant open a feature request in the main Frigate repo for a 'latest snapshot from all cameras scope' MQTT topic, not enhancements to the card.

**Comment by dermotduffy** [comment]
> Also, I should have been clearer, I meant open a feature request in the main Frigate repo for a 'latest snapshot from all cameras scope' MQTT topic, not enhancements to the card.

Oh, sorry. If Frigate had such a snapshot, it would result in a `camera` entity in HA that could show the latest snapshot from any camera, but you still wouldn't be able to use it fully in the card nor would it "cycle" in the way I think you want (i.e. the cameras would be able to overwrite each other, you'd only see the camera that wrote the last snapshot). Probably not a high-demand feature, I'd guess.

I linked to another bug that someone opened today, which I think is also asking for multiple camera support. Let me also see where that bug goes, as (from my reading of the description) I don't think it is solvable with the slideshow option.

**Comment by chvvkumar** [comment]
Awesome, appreciate your thoughts!

**Comment by chvvkumar** [comment]
The slideshow card works well for this purpose. I will add my config for that card for any one looking for an example:

```
type: custom:slideshow-card
fill: false
auto_play: true
auto_delay: 20
style:
  object-fit: cover
cards:
  - type: picture-entity
    entity: camera.frontyard_car
    show_name: false
    show_state: false
  - type: picture-entity
    entity: camera.frontyard_person
    show_name: false
    show_state: false
```

**Comment by dermotduffy** [comment]
**Update**: As it came up a few times simultaneously from different users, I am in the midst of implementing multiple camera support (as some usecases could not be solved with the slideshow idea that appears to have worked for you). This 'cycling' proposal would (afterwards) make sense to implement -- so re-opening this bug to track.

**Comment by Welsyntoffie** [comment]
> > Oh, sorry. If Frigate had such a snapshot, it would result in a camera entity in HA that could show the latest snapshot from any camera, but you still wouldn't be able to use it fully in the card nor would it "cycle" in the way I think you want (i.e. the cameras would be able to overwrite each other.
> 
Your reply here was exactly what I was trying to get. My tablet is slow in loading images, so I wanted only one image with the latest snapshot of my 6 cameras. 

I used a python script...



```
import datetime
import io
import json
import requests
import sys
from PIL import Image
FRIGATE_HOST = "http://IPHERE:PORTHERE"
event_id = sys.argv[1]
json = requests.get(f"{FRIGATE_HOST}/api/events/{event_id}").json()
camera = json["camera"]
img_bytes = requests.get(f"{FRIGATE_HOST}/api/events/{event_id}/snapshot.jpg").content
img = Image.open(io.BytesIO(img_bytes))
img.save("/config/www/cloud_plate/camera_image/last_detected.jpg")
```

In configuration yaml...
```
shell_command:
  last_detected_snap: python3 /config/bashscript/last_detect_snap.py "{{ event_id }}"

camera:
  - platform: local_file
    file_path: /config/www/cloud_plate/camera_image/last_detected.jpg
    name: "trigger shot"
```

Automation file...
```
alias: Last_detection_snap
description: ""
trigger:
  - platform: mqtt
    topic: frigate_mint/events
    variables:
      camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
      id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
condition:
  - condition: template
    enabled: true
    value_template: "{{trigger.payload_json[\"type\"] == \"new\" }}"
  - condition: template
    enabled: true
    value_template: "{{trigger.payload_json[\"after\"][\"camera\"] != \"pcroom\" }}"
  - condition: template
    enabled: true
    value_template: "{{trigger.payload_json[\"after\"][\"label\"] == \"person\" }}"
action:
  - service: shell_command.last_detected_snap
    data_template:
      event_id: "{{id}}"
      camera: "{{camera}}"
trace:
  stored_traces: 20
mode: queued
max: 3
```

If any 1 camera detects a person the file is overwritten and I always only have 1 file instead of 6 images.
