### ISSUE TITLE
Support showing thumbnails from multiple cameras in one single thumbnail carousel

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#233]
Just tried your new Beta release - great work as always!  Thought I would describe how I use your card, and what (in my opinion) would make it even better.  To begin with, I am a minimalist :)   I have only one view (which I display without the menu bar), but within that view I have multiple buttons which can configure the display.  My main display includes the Birdseye view - but I can selectively display all cameras (4 in total) via a toggle button.  So the default is Birdseye, which now displays live video if there is motion detected on any of the cameras.  I also love the idea of being able to display the latest snapshot or clip, but that means I have to display all 4 cameras.  Is it possible that you could add the option to display an optional carousel below the Birdseye view?  This way I can always see active motion, I can also see and play the most recent clips (for all cameras), and then after a timeout, go back to Birdseye.  Hope I explained this well enough.

**Comment by dermotduffy** [comment]
> I have only one view (which I display without the menu bar), but within that view I have multiple buttons which can configure the display. My main display includes the Birdseye view - but I can selectively display all cameras (4 in total) via a toggle button.

I don't quite follow this. The card currently doesn't support dynamically changing the underlying camera entity, so I must be missing something. Outside of the birdseye view, how are you displaying multiple cameras? Is it just having 4 buttons that open the camera entities perhaps?

If you're comfortable doing so, maybe pasting your card config would help me understand what you mean.

> Is it possible that you could add the option to display an optional carousel below the Birdseye view? This way I can always see active motion, I can also see and play the most recent clips (for all cameras), and then after a timeout, go back to Birdseye. Hope I explained this well enough.

Right now, the carousel is (not surprisingly) tied to the camera the card is configured with. Displaying clips for >1 cameras (or doing anything for >1 camera) isn't supported directly, i.e. you cannot view media from 2 cameras.

Coincidentally, in https://github.com/dermotduffy/frigate-hass-card/issues/221 this topic is also coming up (right now).

**Comment by felipecrs** [comment]
Having a way to use multiple cameras would be awesome, because then I could set as a full size card in a "Cameras" view, and supposedly it would render beautifully on both smartphone and desktop.

Also, as opposed to adding 16 frigate cards to the Cameras view, which makes it barely usable because of network consumption or whatever.

**Comment by dermotduffy** [comment]
I've just start experimenting with very basic multiple camera support (it's more in line with what @felipecrs is describing).

@tbrausch Would you mind clarifying your original request so I can understand if what I have in mind would address that  too?

> I also love the idea of being able to display the latest snapshot or clip, but that means I have to display all 4 cameras. Is it possible that you could add the option to display an optional carousel below the Birdseye view? This way I can always see active motion, I can also see and play the most recent clips (for all cameras), and then after a timeout, go back to Birdseye.

I think this is just displaying a _single_ camera in live mode (birdseye), but having the event carousel underneath display events from multiple cameras. Is that right?

**Comment by tbrausch** [comment]
That's it exactly!

**Comment by kbrouder** [comment]
+1 on this. Is there another solution folks are using for this functionality? My frigate endpoint is not accessible to the extranet but my hass is, so when I am away from home and get a few notifications I don't have a great way to pop open hass and see what happened. Would be ideal to just have a view with recent thumbnails from all cameras so I can click on whichever is most relevant.  I agree with the OP that having that thumbnail carousal below with the birdseye live would be the perfect starting page for my mobile dashboard.

**Comment by kbrouder** [comment]
Going to respond to my own comment here....
I missed in the Frigate docs about the Proxy add-in -> https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate_proxy/

Using this card and then being able to hop over to the frigate event interface is a good workaround for this requirement. Would still love to see a more robust solution but the proxy add-in solves a ton of workarounds I tried while still allowing you to keep your ports closed on your router.

**Comment by dermotduffy** [comment]
Just FYI: That's a fine work-around -- but I _absolutely_ still plan to work on this, as it's needed for multiple things I'd like to do (it's just not trivial to implement).

**Comment by dermotduffy** [comment]
Will be in the v4 release.
