### ISSUE TITLE
A way to toggle the Fullscreen mode with a service.

### ISSUE THREAD

**Issue by maxi1134** [dermotduffy/frigate-hass-card#237]
**Is your feature request related to a problem? Please describe.**
I currently switched to using this card to stream on multiple displays.
And in many instances, I want those displays to display the fullscreen mode in certain moments.
For instance when someone is at the door, or motion is detected at the back door!

I currently use conditionals cards, but with the initial loading time, the use is not ideal.

**Describe the solution you'd like**
A way to trigger the fullscreen action from somewhere else.
Or even based on conditions using [templating](https://www.home-assistant.io/docs/configuration/templating/)

```
view_mode: >
    {% if is_state('sensor.front_persons', '0') %}
      normal
    {% else %}
      fullscreen
    {% endif %}
```

**Describe alternatives you've considered**
The use of the Conditional card was acceptable until the introduction of the "disableWebAssembly" fix, [which seems to add an initial loading time](https://github.com/dermotduffy/frigate-hass-card/issues/189#issuecomment-974525138)

**Additional context**
Nothing more, but amazing work, and thanks a lot for the support!

**Comment by dermotduffy** [comment]
I'm afraid I think this is technically not feasible. The Javascript fullscreen API can only be activated by a human action. You can imagine the amount of abuse/spam there'd be if this protection was not present (e.g. visit a site and the spam/ad is instantly fullscreen).

I did a quick test of going to fullscreen without a human interaction, and Chrome logs:

```
Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
```

A [totally untested] trick could be to make a new dashboard in panel mode with a single instance of the  card. That could be independently navigated to, and you could use something like  [browser-mod](https://github.com/thomasloven/hass-browser_mod#available-commands) to control the navigation.

**Comment by dermotduffy** [comment]
Closing as not implementable for the reasons described.

**Comment by maxi1134** [comment]
Sorry! Thought my answer has been sent.
I understand why it is not possible. Thanks for trying!

I will try to find a way to keep a conditional card pre-loaded!
