### ISSUE TITLE
Request: Tap action to quickly/easily mute/unmute audio from camera feed.

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#238]
**Is your feature request related to a problem? Please describe.**
It would be great to have the ability to mute/unmute the audio from camera feeds with a single tap action on the card.

**Describe the solution you'd like**
Tap action to quickly/easily mute/unmute audio from camera feed.

**Describe alternatives you've considered**
At the moment (on Android companion app) I have to long hold the card to show the regular HA video controls (pause/mute/fullscreen) to mute/unmute. However it seems to only allow me to do this once, after the first 'press+hold 'I can't get those controls to pop up again unless I tap into the recordings display then back to live feed.

**Comment by dermotduffy** [comment]
> At the moment (on Android companion app) I have to long hold the card to show the regular HA video controls (pause/mute/fullscreen) to mute/unmute. However it seems to only allow me to do this once, after the first 'press+hold 'I can't get those controls to pop up again unless I tap into the recordings display then back to live feed.

That's strange. In the Android companion app, I get the mute/unmute buttons when the video first loads and if I short tap on the video feed (which I don't think qualifies as undue burden?).

What live provider are you using where you're seeing the behavior you describe?

This is probably implementable, but I think it's better handled in the video player itself if at all possible rather than at the card level.

**Comment by conorlap** [comment]
I'm using WebRTC for live provider.

I see https://github.com/dermotduffy/frigate-hass-card/issues/242 has been raised too which sort of relates to this issue - where by the WebRTC/video controls aren't always easily accessible on companion app, I have to press and hold the card to get the mute button to pop up. But it seems to only allow me to do this once, after the first 'press+hold 'I can't get those controls to pop up again unless I tap into the recordings display then back to live feed.

**Comment by conorlap** [comment]
Hey @dermotduffy , as of yesterday's update to 'main' i think this issue can be closed. With the fix in place where the video control UI comes up on every tap now I'm pretty happy muting/unmuting that way! 
Thanks so much for this amazing card!!
