### ISSUE TITLE
Request: Pinch to zoom on companion app

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#239]
**Is your feature request related to a problem? Please describe.**
Having the ability to 'pinch to zoom' into the live camera feed on the companion apps would be great. I understand this might be something that the HA devs will have to implement on the companion apps themselves, but figured I'd submit this request incase you can figure it out within the card / have any other suggestions.

**Describe the solution you'd like**
Pinch to zoom on companion apps. This may already work on iOS - I'm not sure, I'm on Android.

**Describe alternatives you've considered**
An alternative I've considered is to install HA as a web app via Chrome browser on my phone, I can then pinch to zoom on the entire lovelace dashboard then but it's a little buggy.

**Comment by dermotduffy** [comment]
As you guessed, not much that can be done at the card level. This needs to be implemented in the companion app, which I think is this issue (which you also found!): https://github.com/home-assistant/android/issues/1117

**Comment by conorlap** [comment]
Thanks for confirming @dermotduffy  - and thanks so much for this amazing card, super useful! I'll close this issue and hope that we can get some traction on [home-assistant/android#1117 ](https://github.com/home-assistant/android/issues/1117) :)
