### ISSUE TITLE
Bug: WebRTC component not found (Android Companion app)

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#240]
**Checklist:**

- [ yes ] I updated to the latest version available
- [ yes ] I cleared the cache of my browser

**Release with the issue:**
HA: 2021.12.1
frigate-hass-card: v2.1.0 
AlexxIT/WebRTC card: v2.2.0

**Last working release (if known):**
Not known

**Browser and Operating System:**
Android companion app - beta-1776-8c5149dd-full (issue is also happening on latest Play Store version)

**Description of problem:**

Occasionally when I open the HA companion app I get the below error, this issue doesn't occur when I use the regular WebRTC camera card on it's own (https://github.com/AlexxIT/WebRTC). Please note it's only an occasional error and only happens sporadically (approx 1 or 2 times out of 10). 
The card loads fine if I close the app and open it again, or tap the clips/recordings button and then go back to live view.

<img width="412" alt="Screenshot 2021-12-14 at 13 36 54" src="https://user-images.githubusercontent.com/57415184/146008680-078b1aa6-adf0-402e-ae34-92bacad5541f.png">

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

N/A

**Comment by dermotduffy** [comment]
Thanks for the report @conorlap ! I have not seen this before. Perhaps some sort of race condition between the Frigate card loading and the resources for the rest of the page loading. If the Frigate card loaded before WebRTC, it wouldn't be able to find the `webrtc-camera` element and you'd probably get that error.

**Comment by cappiel** [comment]
I've been also getting this error since upgrading to the following, I've also uninstalled and reinstalled the card. Dermotduffy did you solve?

HA: 2021.12.1
frigate-hass-card: v2.1.0
AlexxIT/WebRTC card: v2.2.0

**Comment by dermotduffy** [comment]
@cappiel didn't even get a chance to investigate yet ;-) 

When you say "since upgrading", do you mean it used to not be a problem -- then you upgraded the card -- then it was a problem? If yes, do you know what version you were previously on?

**Comment by cappiel** [comment]
@dermotduffy all good! sorry that came across bad haha

Yea, so I upgraded HA to 2021.12.1 on Sunday. That broke WebRTC I know. AlexxIT fixed that with 2.2. and installed that earlier today.

I'm pretty sure I upgraded your card on Sunday also to 2.1 through HACS. Seeing similar issue as Conor above. (Not Android though, web and/or iOS HA app)

Any logs I can pull for ya?

**Comment by dermotduffy** [comment]
Thanks @cappiel , no worries! So sounds like you did a big upgrade of HA, WebRTC and the Frigate card -- so can't really pin it down :-(

@conorlap was this triggered by a recent upgrade for you also, or "always" been this way?

**Comment by conorlap** [comment]
@dermotduffy I've only setup Frigate and this card within the past week so not sure how long this issue has been present.

**Comment by NickM-27** [comment]
I'm having this issue as well, just downloaded the last couple days as well so I have not had it working. Happy to test any custom builds or anything else to figure it out though. It is happening to me on all devices (desktop, android, ios)

**Comment by dermotduffy** [comment]
With a caution that I could never reproduce this bug on any device (and so cannot test it has fixed the issue), I think the merged PR fixes at least one race condition I could imagine during loading that may cause the described behavior. If someone has this issue reliably, would love your feedback after the next release to determine if it's really fixed correctly.
