### ISSUE TITLE
WebRTC UI not clickable in Android

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#242]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

2.1.0

**Last working release (if known):**

I don't know

**Browser and Operating System:**

Android 11 with HA Companion App

**Description of problem:**

The buttons exposed by the card works fine, but the buttons exposed by WebRTC does not. In a browser it works normally.

**Additional information:**

https://user-images.githubusercontent.com/29582865/146305182-d786600d-a059-49b0-85bb-caf93e70dff0.mp4

**Comment by conorlap** [comment]
I'm experiencing this also, I've noticed if you press and hold the card you can get access to the video controls like pause/mute etc. But this only seems to work once and then no matter how many times I press and hold, I can't get to those controls unless I close the app or tap into the recordings tab on the card and then back to live view for example.

**Comment by dermotduffy** [comment]
Ouch. Thanks @felipecrs for the quality bug  report & demo. 

I have an unverified hunch this is caused by https://github.com/dermotduffy/frigate-hass-card/issues/172 , the work for which is causing the click event to be "swallowed" on _touch_ devices. I'll need to either find a way to prevent that from happen,  or roll back that feature.

If that hunch is correct, going back to v2.0.0 would probably fix this.

**Comment by conorlap** [comment]
Yep I just rolled back to v2.0.0 and tapping is working fine!

**Comment by felipecrs** [comment]
> Ouch. Thanks @felipecrs for the quality bug report & demo.

You are doing all the work, it's the least I can do. :)

> If that hunch is correct, going back to v2.0.0 would probably fix this.

I also confirm that rolling back to v2.0.0 solves the issue.

**Comment by felipecrs** [comment]
I was not able to confirm that the latest main version solves the issue because when I try to upgrade to it, HACS fails for some reason:

https://user-images.githubusercontent.com/29582865/146622995-3c4b6083-09bb-49c2-aec4-e9cfcb312096.mp4

(you can pause at 00:08 to see the error message -> no content to download)

When switching to any other version it works fine, and I remember that using main as the version used to work in the past.

But anyway, I'm not in rush to test or anything like that because 2.0.0 works for me for now until the next version gets released.

**Comment by peledzius** [comment]
Thanks, I can confirm that https://github.com/dermotduffy/frigate-hass-card/pull/244 solves the issue in iOS.
