### ISSUE TITLE
Add recording viewing (separate from events)

### ISSUE THREAD

**Issue by Mincka** [dermotduffy/frigate-hass-card#246]
**Is your feature request related to a problem? Please describe.**
I would be interested to have some kind of support for playback recording at any point in time.

I would like to start the stream based on Frigate recording at a specific point in time.

Currently, I am able to use the VOD feature of Frigate to start the stream at a point in time until the end of recording.
http://10.0.0.9:5000/vod/Frigate_Maison_Avant/start/1639929600/end/9999999999/index.m3u8
But I cannot use it on mobile through my Nabu Casa instance.

Based on specific detection methods (not related to Frigate events), I would like to be able to have a clickAction in a notification to start the playback of the recording when the notification was sent, so a few seconds or few minutes in the past.

It would mean to be able to use an interface similar to the one of the Frigate addon to browse recording hours AND specify in argument a timestamp to start the playback at a specific time.

**Describe alternatives you've considered**
Maybe record a clip based on the stream, 
or trim the recording based on the files, 
or use the with the 10 minutes segment where my timestamp is, eg. /root/media/frigate/recordings/2021-12/19/19/Frigate_Maison_Avant/09.09.mp4 if I want something "starting" at 9h12.
and / or use the HA Media Player with the previous point.

**Additional context**
My request maybe would be better split into different issues, with one or many in the integration repo. Let me know if I need to create more specific issues.

**Comment by dermotduffy** [comment]
Thanks for the feature request @Mincka . I figured doing something with recordings was ~inevitable in the card, but didn't really get to think about it yet. For your specific usecase though (a URL to navigate to from a notification clickAction) I'm not sure the card is the right answer anyway -- you perhaps reached the same conclusion as per your 'Additional context'.

For you, the bottom line seems to be that the Frigate backend already offers what you need when you're on your local network, but when you're away your phone presumably doesn't have access to that backend (but it does have access to HA).

**Something to experiment with**: The integration already offers a proxy of `/vod/` which is used by the HA media browser -- maybe you could use that? It would be something like this (below is untested, for you to hack around with):

```
http://YOUR_HA/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1639929600/end/9999999999/index.m3u8
```

(The second 'frigate' should be your MQTT client_id, the default is `frigate`)

[Code that does the proxying](https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/views.py#L215)

**Comment by Mincka** [comment]
Thank you for your quick reply. :)
I wasn't aware that the VOD endpoint was also proxified, which is great!

I tried to mimic what is done in the Frigate notification blueprint:
https://gist.github.com/hunterjm/23c1588a9f2b8b9c2a62ffc364e17f8c#file-frigate_notification-yaml-L179

```
service: notify.mobile_app_telephone_julien
data:
  title: Motion Detected in Backyard
  message: Someone might be in the backyard.
  data:
    clickAction: https://xxx.ui.nabu.casa/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1639983620/end/9999999999/index.m3u8
```

I am prompted to open the link in VLC or Edge, but in both cases, I get `401: Unauthorized`.
That's the same when I am connected though NabuCasa on desktop and I try to browse this URL.

I saw that in some cases, the authentication headers are not passed with clickActions:
https://github.com/home-assistant/android/issues/1672

Could it be related to the `authSig` parameter which is used when you initiate the WS connection?

Hum, looking a bit further, I compared the endpoints and saw this trick:
https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/views.py#L195

Also for the notification endpoint. So indeed, I could access the segment but I am missing the access to the playlist. :-p
I tried to hack my way out by adding `requires_auth = False` to `VodProxyView` and I managed to get acccess to the m3u8 file.

However, I hit a new wall since the video does not start. I did not manage to download a `ts` segment. From what I see in the code, it's more complicated to get an authentication token for this.

`m3u8` direct access from the addon API:
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
seg-1-v1.ts
#EXTINF:10.000,
seg-2-v1.ts
```

When downloaded from the API proxy:
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
seg-1-v1.ts?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiNGY2MDQwYzQ2ZmI0OWNhYTJhMGQ5NGIxMzA2MjBhMyIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9qc21wZWcvRnJpZ2F0ZV9KYXJkaW5fQXZhbnQiLCJpYXQiOjE2Mzk5ODcyNTMsImV4cCI6MTY0MDA3MzY1M30.4Ydh6Ozcd9m0ild5lXy32A9_H5SURSXcuq_Ji3ORx4s
#EXTINF:10.000,
seg-2-v1.ts?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiNGY2MDQwYzQ2ZmI0OWNhYTJhMGQ5NGIxMzA2MjBhMyIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9qc21wZWcvRnJpZ2F0ZV9KYXJkaW5fQXZhbnQiLCJpYXQiOjE2Mzk5ODcyNTMsImV4cCI6MTY0MDA3MzY1M30.4Ydh6Ozcd9m0ild5lXy32A9_H5SURSXcuq_Ji3ORx4s
```

From VLC on desktop:
```
adaptive error: Failed reading https://i09wik436d0bpvm3h7el09k9hpcwpwkq.ui.nabu.casa:443/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1639983620/end/9999999999/seg-1-v1.ts: HTTP/1.1 401 Unauthorized
adaptive error: Failed to create demuxer 0000000000000000 Unknown
adaptive error: Failed reading https://i09wik436d0bpvm3h7el09k9hpcwpwkq.ui.nabu.casa:443/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1639983620/end/9999999999/seg-2-v1.ts: HTTP/1.1 401 Unauthorized
adaptive error: Failed to create demuxer 0000000000000000 Unknown
adaptive error: Failed reading https://i09wik436d0bpvm3h7el09k9hpcwpwkq.ui.nabu.casa:443/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1639983620/end/9999999999/seg-3-v1.ts: HTTP/1.1 401 Unauthorized
adaptive error: Failed to create demuxer 0000000000000000 Unknown
adaptive error: Failed reading https://i09wik436d0bpvm3h7el09k9hpcwpwkq.ui.nabu.casa:443/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1639983620/end/9999999999/seg-4-v1.ts: HTTP/1.1 401 Unauthorized
access error: HTTP 401 error
```

**Comment by dermotduffy** [comment]
Ah yes, it's authenticated. Ignore the unauthenticated segment proxy, you won't be able to get that to work as it requires the request to have gone via the authenticated manifest.

Two things to try [not sure either will work though]

* Have you tried the URL in a browser that's already logged into HA?
* [If you use the Android companion app] Have your notification use an absolute path without the hostname (i.e. just `/api/frigate/frigate/...`), so that (maybe) the Android companion app will sign the request and send it to the HA backend it's connected to.

**Comment by Mincka** [comment]
**Browser**

- Without `requires_auth = True` on `VodProxyView` I get 404 without being authenticated and 401 when I am.
- With `requires_auth = True` on `VodProxyView` I can download the m3u8 but not the referenced ts file.

**Companion App**

- If I use the absolute URL, I can *download* the playlist it through VLC or Edge but not play the video.
- If I use the relative URL, the HA companion app will show the player without being able to start the video.

Maybe I can still download the playlist without  `requires_auth = True` and the relative URL. I don't think it could break something to "force it" in my patched code.

I don't know what I changed from my earliest tests but I am now unable to get a playlist with `authSig` segments using
https://xxx.ui.nabu.casa/api/frigate/frigate/vod/Frigate_Maison_Avant/start/1640026800/end/9999999999/index.m3u8

I am not sure why you say
> Ignore the unauthenticated segment proxy, you won't be able to get that to work as it requires the request to have gone via the authenticated manifest.

Since the `m3u8` is only a playlist referencing `ts` files (the segments), the player will try to download them right after the playlist is loaded.

Other random attempts:
1) /api/frigate/frigate/jsmpeg/Frigate_Maison_Avant
Message in webview in app:
`No WebSocket UPGRADE hr: None
Can "Upgrade" only to "WebSocket"
2) https://xxx.ui.nabu.casa/api/frigate/frigate/jsmpeg/Frigate_Maison_Avant
Same, but in browser

**Comment by dermotduffy** [comment]
> I am not sure why you say
> 
> > Ignore the unauthenticated segment proxy, you won't be able to get that to work as it requires the request to have gone via the authenticated manifest.
> 
> Since the `m3u8` is only a playlist referencing `ts` files (the segments), the player will try to download them right after the playlist is loaded.

Yes, I meant that even though the requests for the segments themselves are unauthenticated, a signature from the manifest is [still verified here](https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/views.py#L241).

**Comment by Mincka** [comment]
I am experimenting by fiddling with the code.
I "disabled" the `_async_validate_signed_manifest` check by returning `True` without any check.
Using `/api` relative URL the stream will load in the HA Companion app for the whole duration. The only thing is that every few seconds (I guess for each `ts` file, the app throw a pop-up "Unable to connect to HA".
Using the absolute NabuCasa URL, nothing shows up in VLC despite a progress bar that looks correct.
Finally, I can load the recording in Edge without any error, which is great.
Now I need to revert all my changes and see how I can manage to do the same thing but with a little bit more security.

**Comment by Mincka** [comment]
Just a quick note for anyone attempting to use the VOD, its seems limited to about 3 hours (about 2h55) of video for a run so my idea of using `9999999999` for ending timestamp only works if the recording starts less that 3 hours ago, 10790 +/- 300 seconds depending of the segment. In my case, I will add 10000 seconds for the maximum ending timestamp.

**Comment by dermotduffy** [comment]
Updating bug name as the new build will feature a timeline, but not the ability to view records that are not events. Implementing that will likely require Frigate backend changes.

**Comment by dermotduffy** [comment]
The timeline view which will be in the v4 build allows access to arbitrary recordings. Closing this as complete.
