### ISSUE TITLE
JSMPEG live view quickly passes through all frames when resuming

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#252]
Disclaimer:

1. I'm sorry for the title, I'm really not sure if I used the right words to describe what my video below will show (or even if what I said is true)
2. I'm also not sure if this is the correct repository where this should be reported (despite I have an idea on how it could be solved here anyway)
3. Idk if this is rather a bug or a feature request, or something else. I started with bug, but feel free to change it...

So, the following is happening when I switch back to a tab which was previously in background:

https://user-images.githubusercontent.com/29582865/147297965-4e5194a4-a70a-434e-9052-042b9ae58db5.mp4

The more time it stays in background, more time it stays like this.

Despite of the weird (didn't find a better word) experience of seeing this happening, I wonder if this does not cause an unnecessary use of bandwidth, because if the frames are being displayed quickly after I resume the tab, it means they were downloaded.

Even if this issue is not caused by the card itself, I think it would be reasonable to stop the JSMPEG streaming when the card is not visible (like when the tab is in background). Reasonable because, at least for me, JSMPEG is always reasonably quick to load, and because it may worth more to wait a second for it to load than spending unnecessary bandwidth (like when using 4G).

Or, if the current behavior exists for good reasons (that I'm may not know), a new option like _Stop live view when card is not visible_ would be helpful.

Worths mention, I think, that I'm not using the _Preload_ live view option.

**Comment by dermotduffy** [comment]
Yeah, I've seen the same behavior although it never bothered me enough to explore more. It's a property of the underlying player, not the card -- although it could be how I'm configuring the player: In the card I configure JSMPEG with `pauseWhenHidden` to false, as I think it sped up the load times when I was initially writing it.

Maybe flip that option and see if it does anything for you:

```yaml
live:
  jsmpeg:
    options:
      pauseWhenHidden: true
```

**Comment by felipecrs** [comment]
That sounded exactly what I was seeking for. But unfortunately, it does not do anything:

https://user-images.githubusercontent.com/29582865/147361854-5d517d86-1032-4ea0-9ed1-3a1a52035e1e.mp4

**Comment by dermotduffy** [comment]
I think this can be (approximately!) closed now:

* Lazily loaded cameras can be lazily *UN*loaded: #285
* Cameras will pause (or unload if lazy *UN*loading is enabled) when the document visibility changes, i.e. when the user changes to a different tab: #289

The net effect is that the user can have the cameras unload when not seen (thus eliminating all streaming overheads) and automatically reload them when they're back visible again (with a loading delay). 

So, whilst I didn't find a way to eliminate the "fast-forward" type behavior that JSMPEG exhibits, I think the above combination delivers on the spirit.

[Of course, love to hear it if the above is not an acceptable solution to the issue]

**Comment by felipecrs** [comment]
Amazing! Can't wait to test and report back.

**Comment by felipecrs** [comment]
Lazy unloading works very well! Thanks a lot for this! I even think is a good thing to have it enabled by default.

But the second thing, however, to automatically pause the stream does not seem very reliable (lazy unloading disabled):

https://user-images.githubusercontent.com/29582865/154349241-be32dbf1-ac7c-4f16-b04e-41e62fa2df58.mp4

In the example above I left the first camera with lazy unload disabled, and the other two in the right side of the screen  with lazy unload enabled.

I then, minimized the browser window (Chrome + Windows) and waited for 30 seconds. After switching to the browser window again, the same effect described in this issue happened again for the camera which had lazy unload disabled.

PS: none of them have lazy LOAD enabled.
