### ISSUE TITLE
Full screen icon not showing for iOS?

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#254]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

On chrome desktop and android mobile app the fullscreen button shows but on iOS the icon is missing. Does iOS not support full screen?

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by blakeblackshear** [comment]
It is an iOS limitation. It does work on the iPad. https://caniuse.com/fullscreen

**Comment by dermotduffy** [comment]
That's right. Related [troubleshooting entry](https://github.com/dermotduffy/frigate-hass-card#fullscreen-button-does-not-appear-on-iphone).
