### ISSUE TITLE
Add option to hide arbitrary buttons

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#26]
[Breaking #16 into multiple issues]

> Add option to remove 'View Frigate UI' button (reduce button clutter)

I think there should be a way to hide arbitrary buttons (except the 'F' button), e.g. some people do not use snapshots and that could be hidden.

**Comment by kylegordy** [comment]
Looking forward to this addition, thanks! Quick question, how do you enable this? Sorry, I'm new to HA and Frigate…

**Comment by dermotduffy** [comment]
Hi @kylegordy, this is already live in the beta version of the card, so you could use this right now! You can either use the GUI card editor `[3 dots menu] -> Edit dashboard -> Edit on the Frigate card` and you'll find toggle switches under the 'Appearance' menu. Or, in the card YAML configuration:

```yaml
menu_buttons:
  live: false
```

(This would hide the `live` button, for example, valid values are covered in the [documentation](https://github.com/dermotduffy/frigate-hass-card#appearance)).

**Comment by kylegordy** [comment]
@dermotduffy  Awesome! Thanks so much for the reply and example!
