### ISSUE TITLE
Support favorite icon on clips to indicate which clips are favorited

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#264]
**Is your feature request related to a problem? Please describe.**
I have written [a PR for frigate](https://github.com/blakeblackshear/frigate/pull/2643) which allows the user to favorite certain clips so they are not deleted during the normal retention settings. I think it would be nice to indicate which clips are favorited in the UI of this card as well.

**Describe the solution you'd like**
I'm considering a simple addition of a star or some other icon in a corner of the image to indicate that it is favorited.

**Additional context**
I am happy to work on this PR but would need some guidance on if this is possible in the `mdc_image_list__image` class or how it would best be implemented. The information is the `retain_indefinitely` property of each `Event` so I believe that the card should have easy access to the property to show this.

**Comment by dermotduffy** [comment]
Nice idea. I fear this is much more involved than you expect, though. Home Assistant integrations are the abstraction for Lovelace cards, so cards can't (i.e. shouldn't) talk directly to backends. This makes sense because many people only expose HA to the internet, or use Home Assistant Cloud -- and will still want their cards to work.

So the Frigate card does not directly communicate with Frigate, and does not have access to the `Event` properties.

The card uses the Home Assistant media browser API -- this has the benefit of getting the nice breakdowns the integration supports (e.g. "Person", "Last month", etc) in the card too. 

=> So to get what you want here, you'd need to somehow attach the new metadata to the media that Home Assistant returns from the Frigate integration ([here](https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/media_source.py#L799)). That in itself will be hard, as that API seems fairly locked down/standardized, it might be difficult/impossible to add new fields.

**Comment by NickM-27** [comment]
@dermotduffy I see, I agree that seems very involved and I appreciate the context as I was not aware that these cards worked in that way. 

Switching gears, would it be more feasible for the frigate integration to provide a `favorited` filter like it does for people and other items?

**Comment by dermotduffy** [comment]
> > => So to get what you want here, you'd need to somehow attach the new metadata to the media that Home Assistant returns from the Frigate integration (here). That in itself will be hard, as that API seems fairly locked down/standardized, it might be difficult/impossible to add new fields.

Actually -- it might be worth experimenting with making a new media class that inherits from `BrowseMediaSource` and attaching the event. I don't know how HA serializes the objects, but if that could be made seamless it would be very useful in the card to have the Event (both for this and other usecases -- right now even getting the event timestamp is a pain).

> Switching gears, would it be more feasible for the frigate integration to provide a favorited filter like it does for people and other items?

Yes, that would also work. We could certainly add a new Drilldown for 'Favorites'. Probably a less slick UX than your little star idea (as with that, you get the drilldowns and the favorite markings together, vs just grouping all the favorites together).

**Comment by NickM-27** [comment]
Awesome! I'll start experimenting with that and see what I can figure out.

**Comment by NickM-27** [comment]
@dermotduffy Time to close this now or once 4.0.0 is merged?

**Comment by dermotduffy** [comment]
Now. Will leave the honors to you :-)

**Comment by NickM-27** [comment]
> Cool feature guys, just wondering if it's feasible to have the ability to favorite clips directly in the event gallery & media viewer?
> 
> Eg. Tapping on a 'star-outline' icon to favorite the clip directly within the card

Like was discussed above, the card shouldn't circumvent the media browser API and talk to frigate directly, that being the case it's not really feasible currently as that's not something home assistant media browser supports.

**Comment by dermotduffy** [comment]
> Like was discussed above, the card shouldn't circumvent the media browser API and talk to frigate directly, that being the case it's not really feasible currently as that's not something home assistant media browser supports.

@NickM-27 Is there an MQTT endpoint for "starring", or could there be? It would be non-trivial for sure, but if there was we could implement a websocket endpoint in the integration that just proxies (websocket->MQTT) to Frigate. The read path for favorites could stay the same, and the card could call the websocket to star the favorite.

**Comment by NickM-27** [comment]
> @NickM-27 Is there an MQTT endpoint for "starring", or could there be? It would be non-trivial for sure, but if there was we could implement a websocket endpoint in the integration that just proxies (websocket->MQTT) to Frigate. The read path for favorites could stay the same, and the card could call the websocket to star the favorite.

There isn't, probably nothing stopping it technically but I'm not sure how I feel about it. There's not any other MQTT topics for adjusting non-camera items so I'd have to think about how that would look. 

That being said, if we're okay with that approach, is there any reason a websocket to the integration which proxied to http wouldn't also work?

**Comment by NickM-27** [comment]
> Nope, that would work fine too (and if it already exists is much easier!)

Yeah the front end already uses the http API to toggle this so should be ready to go except integration support

**Comment by dermotduffy** [comment]
SGTM. Separate bug filed to at least try that: https://github.com/dermotduffy/frigate-hass-card/issues/743
