### ISSUE TITLE
Image does not refresh in iOS

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#269]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** `main` branch

**Last working release (if known):** 

**Browser and Operating System:** Home Assistant Companion iOS 2021.12.1, iOS 15.2

**Description of problem:** Picture in `image` view does not update after `refresh_seconds`

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:** If you refresh in app or switch from other view to `image` view, picture is updated one time. Refreshing works in Safari.

**Comment by dermotduffy** [comment]
[Note: I have no iOS device to test]

That's odd. It works fine on the Android companion app. I think you're saying it works fine in Safari on iOS -- just not the Home Assistant Companion on iOS?

Is it possible that it is caching the JS content from the old version? Certainly with the Android companion I need to force it to clear its cache when testing changes or it'll happily continue to cache the old content.

**Comment by peledzius** [comment]
Yes, you are right, it was caching old version. I had to reset frontend cache inside Companion app(Configuration > Companion App > Debugging > Reset frontend cache) and just after that image started to refresh. Closing.
