### ISSUE TITLE
Multiple camera_entity view not working

### ISSUE THREAD

**Issue by maddeuce** [dermotduffy/frigate-hass-card#278]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
chromes, HA app

Can not render name if use multiple camera entities.  I'm running on card version 2.1.0
![card4](https://user-images.githubusercontent.com/54375636/150695321-17c83eee-d9ed-44f1-b090-9e85656304ef.JPG)

As you can see below on basic single camera setup both camera.name is good.  But once try multiple camera entities it does not work.
![card1](https://user-images.githubusercontent.com/54375636/150695169-f090b82d-2d94-463b-aa3e-313880bc2044.JPG)
![card2](https://user-images.githubusercontent.com/54375636/150695171-6317271c-7777-4e07-a226-28d63288d431.JPG)
![card3](https://user-images.githubusercontent.com/54375636/150695172-125a1af5-523c-4c27-bad7-477042c553ef.JPG)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Hello @maddeuce , the support for multiple cameras is not yet part of any release -- so unless you built a version of the card yourself, this won't work and you'll need to wait for the v3.0.0 build which should shortly be coming.

**Comment by dermotduffy** [comment]
Going to close this for now, but please let me know if I'm missing anything. Otherwise, stay tuned, the v3 release should be fairly soon!

**Comment by maddeuce** [comment]
👍 👍.  Thx
