### ISSUE TITLE
Switching between cameras pop-ups more-info dialog

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#291]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** `main`

**Last working release (if known):** [commit 6119423b41813be8a832ba8122653c7edd303fd2](https://github.com/dermotduffy/frigate-hass-card/commit/6119423b41813be8a832ba8122653c7edd303fd2)

**Browser and Operating System:** 

Firefox 96.0, Ubuntu 20.04
Home Assistant Companion 2021.12.1, iOS 15.2

**Description of problem:**

Noticed it yesterday, didn't have time to fill the report. It has something to do with January 27 commits.

![frigate-card-issue](https://user-images.githubusercontent.com/24360494/151511380-28d255a8-e8c4-4c85-86e4-8584413d179e.gif)

By the way, it would be nice addition to switch on live camera view after you press appropriate camera name in the menu(for example if you are currently looking image view), so you don't need to press on Live view button again.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Yes -- I can reproduce it too, only on use of the menu, but not the camera carousel. My suspicion is: #286 . Thanks for flagging.

> By the way, it would be nice addition to switch on live camera view after you press appropriate camera name in the menu(for example if you are currently looking image view), so you don't need to press on Live view button again.

My idea was you're looking at clips for camera A, when you select camera B in the menu, it should take me to clips for camera B, i.e. I can imagine this being annoying in the opposite direction.

Could make it configurable, choice would be:
* Takes you to the current view for the different camera.
* Takes you to the default view for the different camera.

??

**Comment by peledzius** [comment]
I think if you're currently in image view and select any camera in the menu it should switch view to live. For other views keep the same behaviour.

**Comment by dermotduffy** [comment]
> I think if you're currently in image view and select any camera in the menu it should switch view to live. For other views keep the same behaviour.

Not sure. Perhaps better to make the image src overridable, so you can set a different image per camera -- and then keep the behavior the same for all views.

**Comment by dermotduffy** [comment]
FYI: Broken out the sub-request to:

* #293 
* #294
