### ISSUE TITLE
Add timestamp to events for mobile devices

### ISSUE THREAD

**Issue by ansarowsky** [dermotduffy/frigate-hass-card#297]
Afaik there is no way to show time of the event while mobile. You can get time of the event by hovering your mouse on event in events viewer and it's only available on PC, no way to get it mobile. I think it's an important feature to add.

**Comment by dermotduffy** [comment]
Thanks for the feature request @ansarowsky , I think you're right on the feature gap for mobile devices

Did you have something in mind on how you'd like to see this?

**Comment by ansarowsky** [comment]
In my opinion, a good way to solve this problem would be showing time below the event in event viewer. I also believe that list event viewer will be great to have too, so you can choose between tiles and list.

**Comment by ansarowsky** [comment]
Another option could be showing events spotify-like, but I'm sure you can do better than me.
![image](https://user-images.githubusercontent.com/51420809/151669389-c893b80b-9b08-4b63-8e9c-ea96b45bde88.png)

**Comment by dermotduffy** [comment]
I had also been watching the development of https://github.com/blakeblackshear/frigate/pull/2633 and wondering if there's a card equivalent of that possible in future. I think there's probably three feature requests buried in here:

[Easier] Get the time rendered on the event somehow so you can see it on mobile devices.
[Medium] An option to configure the gallery as a list view instead.
[Much harder] A full recording navigation system with timeline.

**Comment by dermotduffy** [comment]
Easy option implemented. Please follow the dedicated bugs shown above for updates on the other ideas proposed.
