### ISSUE TITLE
Fullscreen doesn't use entire screen for video

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#312]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

`main` branch

**Description of problem:**

On both mobile and desktop, it seems the size of the video displayed is still the same as the card itself. Going fullscreen expands the card buttons UI but leaves the video feed in the center.

![image](https://user-images.githubusercontent.com/14866235/152076928-528eb6c8-5bf4-495a-b5a0-ba9bb61f0003.png)

**Comment by dermotduffy** [comment]
Thanks! I noticed this on Android companion app and have a theory, but never saw it on desktop.. what browser? Is it reproducible?

**Comment by NickM-27** [comment]
This is on chrome desktop (I think I have stable on this computer but not 100% sure, might be chrome beta), I have hard refreshed cache and it happens every time. 

One thing I just found: 
1. Go to fullscreen and it is small
2. Go to clips and clips are shown in fullscreen
3. Go back to live and it is now full size

**Comment by dermotduffy** [comment]
Do you have live preload turned on out of curiosity?

**Comment by NickM-27** [comment]
I do have live preload turned on, I tried turning off live preload and live lazy loading (together and separately) and none of them had an effect on this behavior.

**Comment by NickM-27** [comment]
@dermotduffy unrelated but do you have a discord or something more conducive to chatting (hope it's okay to ask)? A have a camera question as well as some thoughts from my looking into #264

**Comment by dermotduffy** [comment]
@NickM-27 Let me know if that works for you?

**Comment by NickM-27** [comment]
@dermotduffy yep looks good after latest commits!
