### ISSUE TITLE
Rounded corners gone on v3.0.0-rc.1 

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#334]
**Checklist:**

- ✅ I updated to the latest version available
- ✅ I cleared the cache of my browser

**Release with the issue:**
v3.0.0-rc.1 

**Last working release (if known):**
v2.0.1

**Browser and Operating System:**
Chrome on Android 12

**Description of problem:**

The nicely styled rounded corners on this card are gone in v3.0.0-rc.1, is there a way to get these back? The card looks out of place on my dashboard without the rounded corners. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Ps. This latest release (v3.0.0-rc.1 ) is killer, love the new features!! 🚀

**Comment by dermotduffy** [comment]
Not intentional. Will investigate. You get the same behavior regardless of theme? (Which theme do you use?)

**Comment by conorlap** [comment]
Yeah I've changed themes and still got the squared off corners.  I'm using kibibit-dark-cards theme.
I notice when I click in and out of the dashboard page, for the first split second the corners are rounded and then very quickly morphs to squared. 

https://user-images.githubusercontent.com/57415184/152813646-e90db134-166f-496d-b883-b3febafe8da0.mov

**Comment by dermotduffy** [comment]
Huh. That's very weird. Thanks for the video clip, really helps. Let me look into it and get back to you!

**Comment by tbrausch** [comment]
I have the same issue
