### ISSUE TITLE
Add new carousel effect: instant (no sliding)

### ISSUE THREAD

**Issue by scooper1** [dermotduffy/frigate-hass-card#337]
currently view slides in from the right when switching cameras  on a timed loop

is there an option not to slide in, instead change the frame without the amination

could not find an option to do this

Great card thanks

**Comment by dermotduffy** [comment]
So I understand: you want an option for the camera to just instantly appear instead of sliding?

**Comment by scooper1** [comment]
correct 
nice to have 
the slide action gives me slight motion sickness

**Comment by dermotduffy** [comment]
Makes sense. Leave it with me.
