### ISSUE TITLE
Cards don't span to new columns

### ISSUE THREAD

**Issue by deosrc** [dermotduffy/frigate-hass-card#34]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 0.1.4

**Last working release (if known):**

**Browser and Operating System:** Firefox, Pop!_OS 21.04

**Description of problem:**

Cards are extending the page using a scroll bar instead of spanning to new lovelace columns.

To reproduce:

1. Create a new lovelace dashboard/view with the default layout (equal width columns)
2. Add a frigate card with a valid configuration
3. Duplicate the card multiple times so that when the cameras load, the cards extend off the screen.

The cards remain in a single column rather than splitting across multiple columns (depending on screen space).

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Any chance you have a screenshot you could attach of the behavior? Thanks for the report, much appreciated!

**Comment by deosrc** [comment]
![image](https://user-images.githubusercontent.com/50599779/131380447-b632ee24-00e8-4e8c-979f-c8108a5f301f.png)

Hope this is ok
