### ISSUE TITLE
Streams won't load in Wall Panel

### ISSUE THREAD

**Issue by bjammin** [dermotduffy/frigate-hass-card#35]
I'm using a Samsung Galaxy A7 tablet, fully updated.

This card works great when viewed in the Home Assistant app, or directly in the Samsung Browser or Chrome (thanks so much, it's awesome).

However I'm using HA embedded in the WallPanel app, and the live stream or clips just won't load.  WallPanel uses the WebView component).

Anything I should try?  I haven't tried setting up WebRTC yet, is that more likely to work?

**Comment by dermotduffy** [comment]
Hi @bjammin, thanks for the feedback!

Do other Home Assistant cameras (outside of this card) render their live view okay on the tablet? i.e. is your problem specific to this  card?

**Comment by bjammin** [comment]
> Hi @bjammin, thanks for the feedback!
> 
> Do other Home Assistant cameras (outside of this card) render their live view okay on the tablet? i.e. is your problem specific to this card?

Good question.  At best they load inconsistently - sometimes they load, sometimes they don't.  However the frigate card never loads any stream or clip.

So I don't think it's necessarily a problem with the card, more likely something to do with the way the Webview component works.  Is it worthwhile trying WebRTC?

**Comment by dermotduffy** [comment]
Ah. You could try WebRTC yes, it uses a different video technology so it's possible, but as Webview is (AIUI) a fairly generic web rendering component, I wouldn't get my hopes up. 

Other (more adventurous) options include trying to update Webview on your tablet, or install [LineageOS](https://lineageos.org/).

**Comment by bjammin** [comment]
Thanks, I'll do some experimenting over the next week or so.

**Comment by dermotduffy** [comment]
Going to close this issue as this does not actually sound linked to this card itself. Good luck with the experimentation!
