### ISSUE TITLE
Rename live providers to avoid inevitable 'webrtc' confusion

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#353]
* See https://github.com/dermotduffy/frigate-hass-card/issues/335#issuecomment-1032223985 for why this is advisable.

Proposed new names:

* "ha" (formerly: "frigate"): Home Assistant streams (includes anything "native" HA, e.g. HLS, LL-HLS, WebRTC)
* "frigate-jsmpeg": JSMPEG from the Frigate server.
* "webrtc-card" (formerly: "webrtc"): https://github.com/AlexxIT/WebRTC

Proposed new configuration stanzas:

* "ha": _No configuration stanza currently supported._
* "frigate-jsmpeg": "jsmpeg" (unchanged)
* "webrtc-card" (formerly: "webrtc")

**Comment by thundergreen** [comment]
great! I would just like to test if it works .. Do you think it is possible to push a beta?
