### ISSUE TITLE
Issue viewing clips gallery and snapshot gallery

### ISSUE THREAD

**Issue by millie75** [dermotduffy/frigate-hass-card#355]
On the frigate hass card when I click on either the snapshots gallery or the clips gallery I get the following message

Could not find client for frigate instance id: frigate. Check troubleshooting

When I click on troubleshooting the webpage appears but with no help with this error.

I am running hass-card v2.2.2 Frigate 0.94 on a seperate docker server and run HA on a raspberrypi

Is this not possible when running frigate on a different device?

Many thanks

**Comment by dermotduffy** [comment]
Do you have the Frigate integration installed and working: https://github.com/blakeblackshear/frigate-hass-integration

Is there anything interesting in the Home Assistant logs pertaining to Frigate?

Did you change the default MQTT client_id as configured here: https://docs.frigate.video/configuration/index/

If yes, you have to set the client_id configuration value in the card to match.

**Comment by dermotduffy** [comment]
(HA and Frigate on different machines is absolutely supported, in fact the card exclusively talks to HA)

**Comment by millie75** [comment]
Thanks for your super quick response.
here was me struggling and I thought I had copied the default config, but I had changed the client_id when I setup frigate months ago. Now I have added the change all is working perfectly

Very much appreciate all you work
