### ISSUE TITLE
Hide Frigate button when menu bar mode is `hover`, `overlay`, `above`, or `bottom`

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#383]
Because in that case, the Frigate button does barely anything as all the buttons will be expanded by default.

It does change back to the default view if not in it already, but that's also what the other buttons does like "Live" if you click on it.

What do you think?

**Comment by dermotduffy** [comment]
Hi @felipecrs -- thank you as always!

Putting `hidden` menu modes aside (where it is obviously useful), the Frigate button does the following:

* Update with the default view

I agree that is not super useful, but have you considered:

* ... when `update_cycle_camera` is true, the Frigate button effectively updates to the default view of the **_next_** camera.
* ... even if people hate it, they can disable it easily
* ... it looks pretty good (IMO -- quite a bit of inkscape pain ...) and carries some tiny value of brand recognition for Frigate :-)

All in all, think it maybe falls on the side of 'keep it'. Does the above help convince you?

**Comment by felipecrs** [comment]
It does! Thank you for the elaboration!

And actually I should have concluded that by myself because otherwise you would have made it hidden already. 

So, sorry about it.
