### ISSUE TITLE
RTSP streams don't load when navigating dashboard tabs

### ISSUE THREAD

**Issue by jdehlin** [dermotduffy/frigate-hass-card#384]
**Release with the issue:**
Build from head

**Browser and Operating System:**
Windows and OSX
Chrome

I'm using the new 'ha' live mode along with the [RTSPtoWeb](https://community.home-assistant.io/t/add-on-rtsptoweb-and-rtsptowebrtc/387846) add-on. Using this makes the streams load amazingly fast. Everything is working great, except when navigating between dashboard tabs. When navigating away from the dashboard to e.g. the Configuration section of Home Assistant and back, the streams load up no problem. However, when navigating to another tab of the dashboard and then back to the tab with the Frigate cards, the streams don't load and the cards are blank other than the buttons.

This behavior is also experienced when using the streams with the Picture Glance card, so it may be more of an underlying issue with RTSPtoWeb or the new native HA WebRTC support.

**Comment by jdehlin** [comment]
Looks to have been reported in HA repo: https://github.com/home-assistant/frontend/issues/11540

**Comment by dermotduffy** [comment]
The Frigate card just re-uses a [very slightly modified](https://github.com/dermotduffy/frigate-hass-card/blob/main/src/patches/ha-web-rtc-player.ts) version of the same HA frontend WebRTC player, so any bugs (or fixes) that that player gets will also be in the card, i.e. don't think this is a bug for the Frigate Card.
