### ISSUE TITLE
Unique camera ids not regenerated after changing camera entity

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#385]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v3.0.0-rc.1

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

https://user-images.githubusercontent.com/29582865/154343063-2f83902a-03dd-4492-b7e4-499b404e20c1.mp4

1. Have camera 1 added to camera list already
1. Add camera 1 again to the list (it seems to work)
1. Now change the camera entity of the camera added in 2, it will trigger the error that camera 1 does not have a unique ID. I guess IDs should be re-evaluated every time the camera entity changes (unless one has explicitly defined one ID - which I didn't do)

**Comment by dermotduffy** [comment]
Thanks for the report @felipecrs !
