### ISSUE TITLE
Can you add support to have custom menu functions like a relay for enabling lights in house.

### ISSUE THREAD

**Issue by Tuurkevg** [dermotduffy/frigate-hass-card#401]
![image](https://user-images.githubusercontent.com/77327545/154842682-5062216e-9781-4935-abfe-50a5824c50bc.png)
like here I want to add a menu button to open the gate. Is this possible? I don't find any documentation about it.
In the readme i find a gif where you can manage an light 
![image](https://user-images.githubusercontent.com/77327545/154842736-f67d3442-5f96-48e0-ade4-d3f96ba91573.png)

**Comment by dermotduffy** [comment]
> like here I want to add a menu button to open the gate. Is this possible? I don't find any documentation about it.

Yes this is possible, and is covered extensively in the documentation:

https://github.com/dermotduffy/frigate-hass-card#special-elements
https://github.com/dermotduffy/frigate-hass-card#adding-menu-icons
https://github.com/dermotduffy/frigate-hass-card#configuring-a-submenu

Those documents are for release v3.0.0-rc.1, if you're using an older version of the card please read the documentation that corresponds to that version (see the 'heart' note at the top of the documentation).
