### ISSUE TITLE
Default view should also set default (first) camera

### ISSUE THREAD

**Issue by maxi1134** [dermotduffy/frigate-hass-card#406]
Describe what you are trying to accomplish and why in non technical terms
I would like for my live view to return to the preset camera after a certain amount of time.

Describe the solution you'd like
A time out option for the camera view ( Like the timeout for the views )

Describe alternatives you've considered
I tried using the view time out, but it doesn't seem to trigger when I change camera while remaining on "live"

**Comment by dermotduffy** [comment]
I think it may be simpler to just have the existing timeout set both the view and camera (to the first in the list), as long as they camera cycle option is not set. Would that work for you?
