### ISSUE TITLE
Boolean Inputs as icon no longer blue when enabled.

### ISSUE THREAD

**Issue by maxi1134** [dermotduffy/frigate-hass-card#409]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
v3.0.0-rc.1
**Last working release (if known):**
Pre 3.0
**Browser and Operating System:**
Tablet and Chrome browser

**Description of problem:**

Previously, when I turned on a boolean input, the icon would turn to blue, which was very usefull to know if it was on or off.
In the new version, it stays white no matter the state.

It is not possible to use icon_template with boolean inputs.
I tried that as it was my first path of resolution
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
This was already fixed in https://github.com/dermotduffy/frigate-hass-card/pull/362 (will be in the next release).
