### ISSUE TITLE
Event fetching does not work with bleeding edge HA 2022.3

### ISSUE THREAD

**Issue by joselito11** [dermotduffy/frigate-hass-card#413]
Get this error on new betas: `Received invalid response from Home Assistant for request: {"type":"media_source/browse_media","media_content_id":"media-source://frigate/frigate/event-search/snapshots////cesta//","id":56}. Invalid keys: 'children'. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).`

**Comment by joselito11** [comment]
![Uploading F5865819-4C13-4340-9BF0-C7C1DB606A45.jpeg…]()

**Comment by thundergreen** [comment]
same issue here Thanks for filing the issue

**Comment by NickM-27** [comment]
I believe this is fixed in the early release version, I have no issues with 2022.3 and that version.

**Comment by thundergreen** [comment]
@NickM-27  which version exactly? Will try that too

**Comment by NickM-27** [comment]
> @NickM-27  which version exactly? Will try that too. Running 2.22 atm and it doesn't work U mean beta 3 ha?

I'm talking about the release candidate 3.0 for this card.

**Comment by thundergreen** [comment]
@NickM-27 how did u install this card? i do not see this version ata ll .  :(

**Comment by NickM-27** [comment]
> @NickM-27 how did u install this card? i do not see this version ata ll .  :(

Go to HACS, open up the card, then press the checkbox that says beta versions, select 3.0.0

**Comment by thundergreen** [comment]
updated to 3.0.0. rc1 but still same issue.. lates ha beta 2022.3 beta 3

**Comment by NickM-27** [comment]
Interesting, I see it now with the events tab.

**Comment by thundergreen** [comment]
i have previews of events under the live stream.. so that why i saw it directly.. has something to do as they changed something with media.. the added DLNA and radio to media and even more. @dermotduffy  should have a look at it i think

**Comment by dermotduffy** [comment]
Thanks all. I've just updated my HA instance and I can reproduce it. Will investigate.

**Comment by dermotduffy** [comment]
Fixed on my local instance, feel free to build your own if you want it now -- otherwise it'll be in v3.0.0-rc.2 .

**Comment by thundergreen** [comment]
I built it myself and replaced old file with new built one.. but is it really necessary to follow manual install? can I not just replace existing file? seems like not working :(

**Comment by joselito11** [comment]
> I built it myself and replaced old file with new built one.. but is it really necessary to follow manual install? can I not just replace existing file? seems like not working :(
> 
> EDIT: manual install worked for me :) Thanks fellow!

Can you give more info how to do this correct? Want try it out. Or can you share the files?

**Comment by thundergreen** [comment]
@joselito11  I deninstalled the card via hacs and installed it manually like in the wiki here. Please find below the working built file
[frigate-hass-card.zip](https://github.com/dermotduffy/frigate-hass-card/files/8148438/frigate-hass-card.zip)

**Comment by dermotduffy** [comment]
@scooper1 I will meet that deadline.

**Comment by dermotduffy** [comment]
FYI: The cause of this breakage is being reversed on the HA side (https://github.com/home-assistant/core/pull/67409) so there should be no need for a new card build by Wednesday. As such, I'll release v3.0.0-rc.2 decoupled from that date, but hopefully still soon (e.g within the next week or so).

**Comment by thundergreen** [comment]
New built card will also work for latest beta release so I let it this way
