### ISSUE TITLE
Card editor dropdowns don't work with bleeding edge HA

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#421]

**Comment by Joeviocoe** [comment]
Does this bug present as this?:
![Screenshot 2022-03-07 at 18-45-55 Screenshot_2022-03-07_18-44-04 png (PNG Image, 6880 × 1440 pixels) — Scaled (24%)](https://user-images.githubusercontent.com/16479297/157149563-ffb27208-6ec6-47d9-9e92-bc78f84eca08.png)

If so 3.0.0-rc.2 still has this bug.

**Comment by dermotduffy** [comment]
@Joeviocoe Something like that, but I am going to guess maybe you are running an older version of Home Assistant perhaps, one that doesn't have the new frontend widgets.

Here is what the new widgets look like:

![Screenshot from 2022-03-07 19-04-58](https://user-images.githubusercontent.com/1136829/157158363-3cdd4b16-8951-41b8-bb36-ebd886c69225.png)

**Comment by Joeviocoe** [comment]
Yep, I was on core-2022.2.5, which I thought would be recent enough for 3.0.0-rc.2
Upgrading to core-2022.3.2 fixed it.
