### ISSUE TITLE
Clips and Frigate .90

### ISSUE THREAD

**Issue by pavlov70** [dermotduffy/frigate-hass-card#43]
Hi, just discovered this amazing card at the same time I upgraded to Frigate .90. Currently everything is working great (awesome webrtc!) except I can't play clips created in Frigate .90 in the card. Clips created under previous version of Frigate play fine. Both show up, except clicking on a .90 clip just returns the spinny wheel. Reading through closed issues it looks like perhaps the version in HACS doesn't fully support .90 yet? Should I sit tight for a new release or continue troubleshooting?

**Comment by dermotduffy** [comment]
Sit tight! This is actually already fixed/merged, just no new release yet. I'm cramming some new features in, hopefully a new release this weekend!

**Comment by dermotduffy** [comment]
[Closing this, as I'm trying to clear out as many bugs as I can pre-release. More feature requests / bugs welcome!]

**Comment by dermotduffy** [comment]
@pavlov70 FYI: The new pre-release is available for testing: https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1283669
