### ISSUE TITLE
Add native cast support

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#439]
A cast button to leverage the [recently introduced Home Assistant Play Media action](https://www.home-assistant.io/blog/2022/03/02/release-20223/#media-selector-and-the-new-play-media-action) to show a camera stream in a Chromecast enabled media player.

When clicked, it would open a dropdown menu allowing to select which media player to cast the current camera stream to.

When selected, the card can then trigger the Play Media action passing in the current camera entity as input, in the selected media player.

It would be disabled for birdseye, by the way.

I haven't tried to build my own custom buttons yet (and I wonder how far it would be possible), but the following are the reasons why I'm opening this suggestion:

1. I believe it's a quite common and generic use case. It would be nice to support it out-of-the-box, as HA now also does.
3. I don't think the current `tap_action` syntax provides the means to call a _Play Media_ action (which is not a service, by the way). But I suppose the card can do it, though.
2. If provided by the card, it can automatically decide to hide the button in case no suitable media players are found.
3. If provided by the card, I suppose it can also color the icon based on the media_player state (whether it has started to stream the given camera or not), although this can come as an enhancement later (if possible at all).

What do you think?

**Comment by dermotduffy** [comment]
Hi @felipecrs , sounds like a good suggestion.

> When selected, the card can then trigger the Play Media action passing in the current camera entity as input, in the selected media player.

I think it hinges on this: whether or not / how a custom card can _actually do this_ . It has to be via HA in order to get the HA media devices, which means it depends on HA having externalized that support somehow. The HA frontend is an enormous Javascript blob, and it is tricky -- and in some cases not possible -- for custom cards to get access to parts of it ([here's an example of where the card needs to fake load a picture glance card to get access to the editor widgets](https://github.com/dermotduffy/frigate-hass-card/blob/main/src/editor.ts#L994)). 

i.e. more research required on whether this is feasible right now.

**Comment by dermotduffy** [comment]
Hmm. Maybe this is less of a big deal than I was thinking:

* Can get the media players from the entities in the provided HA state.
* Can call `select_source` and `play_media` services.

UX:

* A cast icon appears in the menu on camera streams (and ideally clips)
* Clicking the icon drops down a list of media players (similar to the submenu used to choose cameras)
* Clicking a media player calls the set source and play media services behind the scenes.

There'd be no way to actually control the media playing on the device, though. But maybe that's okay.

**Comment by felipecrs** [comment]
> There'd be no way to actually control the media playing on the device, though. But maybe that's okay.

Maybe, just maybe, the `media_player` reports the media currently being shown (which can be checked against the media used to start the stream). And there is the `media_player.media_stop` service.

**Comment by dermotduffy** [comment]
Start playing around with this, a few things:

* I'm having initial difficulty getting Frigate media to play via HA remote playing _at all_ (see bug above). If this is a real issue (and not just a problem on my side), that will become a required fix for this work.
* There'll be limitations: I expect these things will work with it when it's done:
   * Clips
   * Snapshots
   * The camera entity ('HA' provider).
* These things will not work with it:
   * Casting the card itself beyond the media (would need [this](https://www.home-assistant.io/blog/2019/08/06/home-assistant-cast/) instead).
   * Casting the `jsmpeg` (e.g. birdseye) or `webrtc_card` providers.

**Comment by dermotduffy** [comment]
Will be in v4.0.0 .
