### ISSUE TITLE
URL is not passed to WebRTC

### ISSUE THREAD

**Issue by chrisevans1001** [dermotduffy/frigate-hass-card#446]
- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** 3.0.0-rc.1 & Home Assistant v2022.3.1

**Last working release (if known):** Not used before

**Browser and Operating System:** Firefox 97 & Safari 15.3 / Mac OS

**Description of problem:**

Utilising WebRTC-Card. First created the WebRTC-Card and ensured it functioned. This displayed fine. Then created the Frigate card and set it to use WebRTC-Card with the same URL configuration underneath webrtc_card. On saving, an error appears stating that:

`WebRTC component reported an error: Missing `url` or `entity``

Password is fake for the purposes of this report.

![image](https://user-images.githubusercontent.com/4400074/156892902-1f02a339-2fe0-4a09-abc7-ee107b7a5b65.png)

I have tried enclosing the URL either in "" or '' but the visual editor strips these regardless. I have viewed the lovelace stored configuration and it matches that used when WebRTC is used directly.

There are no errors showing in the javascript console.

**Comment by dermotduffy** [comment]
Try:

```yaml
webrtc:
  url: foo
```

The 'webrtc_card' naming was introduced after rc.1 to avoid confusion with other sources of WebRTC, and you're probably referring to the documentation associated with head rather than rc.1 ?

**Comment by chrisevans1001** [comment]
You're right! I was reading the wrong docs but I didn't even know that was a feature in GitHub. Just learnt something new. Thanks for your help - and excellent project. Working really well. :)
