### ISSUE TITLE
Card menu buttons does not react to touch events

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#497]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 3.0.0

**Last working release (if known):**

**Browser and Operating System:**

HA Companion App, Android
HA Companion App, iOS

**Description of problem:**

Sometimes you need to touch a button 2-3 to make it work. 

I noticed this on submenus and thought at first it was happening because my card-mod modifications, but I was able to reproduce this behaviour with minimal configuration.

Recorded on Android:
![Peek 2022-03-27 16-42](https://user-images.githubusercontent.com/24360494/160285467-db903352-562e-4f24-96ec-1345862de0b7.gif)

**Comment by dermotduffy** [comment]
Huh. I have never experienced this. The ripple effect still happens on the failed` clicks, so it is being registered by the button -- but somehow the action is not triggering. You've seen this on both Android & iOS -- but never browser?

**Comment by peledzius** [comment]
> You've seen this on both Android & iOS -- but never browser?

Yeah. AFAIR, never saw this behaviour in browser.

**Comment by peledzius** [comment]
All good after upgrading HA to 2022.3.
