### ISSUE TITLE
Make `view` configuration overridable

### ISSUE THREAD

**Issue by tytlau** [dermotduffy/frigate-hass-card#529]
Hi all, thanks a lot for the work in making this card. I have recently incorporated Frigate and this lovelace card into my HA and it is working well. Thanks!

If not already possible, can I use HA template syntax within frigate lovelace card?

My camera gets its power through a smart switch (which is integrated with HA as well). What I would like to achieve is, if the switch (and hence the camera) is on, the default view of frigate lovelace card is 'live'. If switch is off, the default view is 'image'. This way, when my camera is off (such as when I am at home), HA would not keep trying to get a live stream (and therefore keep showing a spinning icon).

If this can already be acheived by existing funtionality of the card, would be great to hear some advice!

Thanks

(PS sorry not sure if this is the right place to post this - please feel free to move this to somewhere else in the forum)

**Comment by dermotduffy** [comment]
Hi @tytlau , thanks for the feature request.

**Short answer**: This is not currently possible.

**Longer answer**: I'm currently (yesterday!) working on https://github.com/dermotduffy/frigate-hass-card/issues/418 . With that, it would allow overrides to apply to the card based on HA state. I'd also need to make the `view` configuration section overridable, but I think with both of those you'd have what you need.

I'll keep this bug open to refer to the second half of this feature request. So leave it with me ...

**Comment by dermotduffy** [comment]
OK -- everything required for this should now be in. I have this working in my test environment, and have added this exact situation as an [example in the README for the 4.0.0 branch](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#overriding-card-behavior). 

Note that you won't be able to use this until the 4.0.0 branch is released (unless you do your own test build in the meantime).

**Comment by tytlau** [comment]
@dermotduffy  thanks for the reply! I will eagerly wait for the release!
