### ISSUE TITLE
WebRTC Frigate camera stream

### ISSUE THREAD

**Issue by mishoboss** [dermotduffy/frigate-hass-card#532]
Hello, I'm fighting with streaming a WebRTC stream in this card without using [AlexxT WebRTC Camera card](https://github.com/AlexxIT/WebRTC). I have performance issues using AlexxIT implementation and everyone recommends this new native Go implementation - RTSPtoWeb.

So, I have installed [Home Assistant Add-on: RTSPtoWeb - WebRTC](https://github.com/allenporter/stream-addons/tree/main/rtsp-to-web) and its Integration. Apparently camera entities generated by the Frigate Integration don't support WebRTC streaming, so I created General Camera entities for that. They work like a charm when used in Picture Glance card. However I can't find a way how to use them in the Frigate card.

The end goal is to have latency-free live stream in the Frigate card and all the other Frigate related things actually work too - show recordings, screenshots, etc. for that camera.

Any help and ideas are highly appreciated.

**Comment by dermotduffy** [comment]
Hi @mishoboss -- thanks for using the card and providing feedback!

What happens why you just use the general camera entity in the card configuration? You'd need to _also_ set the `camera_name` parameter to tell the card what the matching Frigate camera name is, but otherwise what you describe should just work ...

If I'm missing something, please include your card configuration so I can take a look!

Thanks again.

**Comment by mishoboss** [comment]
Huge thanks, it was a stupid miss - I didn't thought that the **camera_name** parameter is actually the linking to the Frigate. Apparently when used with a Frigate generated camera entity it works out of the box, but when used with non-Frigate camera it needs the Frigate camera name to make the link. Makes sense once you realise it. :)

**Comment by dermotduffy** [comment]
> Apparently when used with a Frigate generated camera entity it works out of the box, but when used with non-Frigate camera it needs the Frigate camera name to make the link.

Yup, exactly! Sounds like you got it working -- enjoy!
