### ISSUE TITLE
Default Full screen View feature request

### ISSUE THREAD

**Issue by limitless-code** [dermotduffy/frigate-hass-card#540]
**Is your feature request related to a problem? Please describe.**
frigate-hass-card is running on a raspberry pi 4 on bullseye, I shutdown the machine at night time and and start it up in the morning. frigate-hass-card starts up automatically in chromium (full screen mode) using a custom service  but I have to set the live camera full screen option every morning.

**Describe the solution you'd like**
Not sure if it is already possible? I don't think it is in the live camera view options currently, but "a set live camera to full screen" option by default view or just have a default full screen option for any view, so when the card is loaded it loads as full screen by default regardless of initial view?

**Describe alternatives you've considered**
Have looked at Custom actions but doesn't look like I can use that. Have looked at [browser-mod](https://github.com/thomasloven/hass-browser_mod#available-commandsl) but feel this should be part of the "view settings" for frigate-hass-card.

**Additional context**
I am using chromium browser on Raspbian OS (Bullseye)

Thank you

**Comment by dermotduffy** [comment]
I'm afraid this is just not possible to implement in the card. The Javascript fullscreen API can only be activated by a user gesture. Here's a demo of me activating it from the Javascript console on a 5 second delay:

<img width="694" alt="Screen Shot 2022-05-03 at 9 23 17 PM" src="https://user-images.githubusercontent.com/1136829/166622919-148cae67-ae1d-4442-a046-9371ac3b452b.png">

This makes sense if you think about it, just imagine the user experience if random websites could put your browser into fullscreen mode without your permission.

My only suggestion is browser-mod, perhaps with a new dashboard in panel mode which ends up being quite close to fullscreen.

**Comment by dermotduffy** [comment]
I'm closing this as (unfortunately) I believe it is unimplementable. Please re-open if you have a better idea!

**Comment by limitless-code** [comment]
@dermotduffy Thank you for taking the time to explain. I see the issue with 'requestFullscreen' API element after your explanation. Pity there's no way to 'trust' the local network/ serving host for example so this can work in certain scenarios by turning off the security feature, not sure if this would be client side/ browser.

I tried looking into browser_mod but looks like it can't do the 'requestFullscreen' gesture/ action? So as you say would have to create a new dashboard in panel mode. Unfortunately have not been able to get browser_mod working as i am hitting a recent bug that has been reported.

I have therefore tried using [xdotool](https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html) in a script to automate and fake 'user interaction and gestures' (mouse), this is working well for the moment as a service starting after the 'frigate-hass-card' page has loaded as I only need it at startup. 

Not sure if this comment will re-open the ticket. If so you are welcome to re-close if I haven't already.
