### ISSUE TITLE
Allow next/prev controls to be disabled

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#56]
Requested by @pavlov70 in https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1283952

> While I like the next/previous buttons on clip playback, an option to turn them off would be nice as well.

**Comment by s24dor** [comment]
Although the preview icon for previous and next image are cool, they do take up a bit of screen real estate. Maybe change or option to use left/right chevrons, to take up less space.

**Comment by dermotduffy** [comment]
@s24dor PR just merged supports thumbnails, chevrons or off entirely.
