### ISSUE TITLE
Refactor `supportsFeature` out of the icons directory

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#566]
As discussed in https://github.com/dermotduffy/frigate-hass-card/pull/565 .

**Comment by felipecrs** [comment]
BTW, the original source of the function is from [here](https://github.dev/home-assistant/frontend/blob/5754f4463d8a5cf40c369028d1491dbe95f3c58a/src/common/entity/supports-feature.ts#L3).
