### ISSUE TITLE
Filter out media players only capable of audio?

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#567]
This is only a question, for now.

For example, I've got two Nest Minis. They support Media Browser, but Media Browser won't let me play a camera stream:

https://user-images.githubusercontent.com/29582865/167517073-14001684-2fc7-483b-814c-aeaad21a4135.mp4

But, funnily enough, if I cast the camera from the Frigate Card to one of them, they play it (the audio only, of course).

So... I'm not sure, should we filter them out or not? Other players, like Youtube, do not let me select my Nest Mini as cast target. But Youtube Music does. So, if we were to follow the same rule (show casting for devices that makes sense), we should filter them out.

PS: I'm willing to implement it if we come up to a yes.

**Comment by dermotduffy** [comment]
Good question. The only usecase is for someone who wants to cast the audio of a recording, and that feels like that really won't be most people -- but then why take that opportunity away? The only benefit is less clutter in the media_player list, and wouldn't have thought that'd be an issue for most people.

At the very least I think we could do a filter with `view.isSnapshotRelatedView()`. If that returns true, we certainly cannot cast an image to an audio-only player.

But no real strong feelings I guess.

**Comment by felipecrs** [comment]
Ok, agreed. Thank you!
