### ISSUE TITLE
Scrollbars / "Shimmering" in Chrome in Windows

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#57]
Reported by @pavlov70 in https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1283952

> Installed 1.0 and it looks great! I'm able to hide unwanted menu items and most importantly I'm able to play Frigate .90 clips. Clips play fine on my Fire tablets which are my main devices but in Windows browsers (Chrome/Edge) on mouseover they get a scrollbar and playback "shimmers" like 2 misaligned projectors playing the same movie. Focusing mouse on another part of the page generally restores correct playback. This goes for both Frigate .90 clips and previous ones. The prior version of this card played pre-.90 Frigate clips just fine on Windows browsers.

@pavlov70 -- is it a particular part of the card that you mouseover to cause this "shimmering" or just any of it? Is it only when there's a clip playing? If you could give me the Windows & Chrome version that'd be great too, so I can try to exactly reproduce.

PS: If you have the means to take an animated gif of the shimmering, that'd be fantastic.

Thanks.

**Comment by dermotduffy** [comment]
@pavlov70 Some mild testing in Windows did not show the error you're talking about (no scrollbars, or shimmer). Can you share the Chrome and Edge versions you are using?

**Comment by pavlov70** [comment]
Hi, I’m attaching an animated gif I took. I had to lower the FPS to make the file smaller and to show you clearly what's happening. In reality, what I’m seeing is happening 30 times a second so it looks like 2 misaligned images  playing at once. It only occurs during playback of a clip, not in the gallery or live camera. During playback if I move the mouse to the menu above the effect stops. In overlay mode if I move the mouse to the menu, the effect continues. When the clip ends, the effect continues in whatever state it was in at the time. If it was shimmering and playback ends, moving the mouse away doesn’t make a difference. Only switching to live view or going back to clip gallery fixes it. Works fine on my Fire tablets, does not work fine on the following Windows browsers. If I’m the only one having this issue no need to pursue it as it's a minor nuisance. Hope this helps!

Windows 10 20H2 ATI graphics
Edge: 93.0.961.38 (Official build) (64-bit)

Windows 10 20H2 Intel graphics
Edge: 93.0.961.38 (Official build) (64-bit)

Windows 10 20H2 ATI graphics
Chrome: Version 93.0.4577.63 (Official Build) (64-bit)


![CPT2109060915-497x322](https://user-images.githubusercontent.com/29015046/132223305-17af8366-96c3-489f-bf87-fa5790b33797.gif)

**Comment by dermotduffy** [comment]
Maybe we should add some background music and call it disco mode? ;-)

Thanks @pavlov70 , that's really helpful. I have not seen that behavior before, I'll see if I can reproduce it. Final request, can you give me the YAML configuration of your card so I have the exact same test case, in the same versions of Chrome/Edge.

**Comment by dermotduffy** [comment]
@pavlov70 I have not been able to reproduce this so it's very hard to debug, however I did a CSS refactor and would love if you would try the new build out and see if the disco effect continues: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v1.0.1

**Comment by pavlov70** [comment]
You solved it! Playback of clips now play flawlessly for me in both Chrome and Edge. Thanks!

Sent from Mail for Windows

**Comment by dermotduffy** [comment]
Hurray! Thats a relief 😜 Thanks for testing.
