### ISSUE TITLE
Menu alignment not working

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#580]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 3cea188c400f62e60c0ab562d35194d20d9a7129

**Description of problem:**

https://user-images.githubusercontent.com/29582865/167878695-e2ec8530-bd0b-4b85-a8b7-be1984714eee.mp4

**Comment by dermotduffy** [comment]
Nevermind, tried to reproduce, got it. Quick check seems to suggest issue is only with the outside style menu.
