### ISSUE TITLE
Switching to a non-frigate camera when in clips view should return to live view

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#594]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Description of problem:**

Because otherwise it errors out.

**Additional information:**

https://user-images.githubusercontent.com/29582865/168481904-e6bd1511-8421-402d-ac38-ab650285523d.mp4

**Comment by felipecrs** [comment]
PS: I'm trying to implement it.

**Comment by dermotduffy** [comment]
Fixed courtesy of @felipecrs !
