### ISSUE TITLE
Card beta clips not playing

### ISSUE THREAD

**Issue by s24dor** [dermotduffy/frigate-hass-card#60]
Using frigate V8 alongside the v1 beta card

I can confirm that snapshots and clips (cover image only) display when accessing via local and nabu casa, the problem is when trying to view the video clip, it displays a broken link symbol then a spinning icon that never loads.

The clips do play from the media browser directly

![Screenshot_20210906-100700](https://user-images.githubusercontent.com/87673731/132193545-cc4d5ae4-c832-48e3-8547-6bd2410b2804.png)

![Screenshot_20210906-101201](https://user-images.githubusercontent.com/87673731/132193587-6347adad-3c77-455f-8db8-4371f544de6a.png)

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Thanks @s24dor -- this is very likely a duplicative of https://github.com/dermotduffy/frigate-hass-card/issues/55 . It's already fixed, and I'll do a new build later today for you to test out.

**Comment by dermotduffy** [comment]
Please try the new build (v1.0.1), it should resolve this issue: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v1.0.1

Please re-open if not, thanks!
