### ISSUE TITLE
Frigate streams don't render on iOS browsers

### ISSUE THREAD

**Issue by friendodevil** [dermotduffy/frigate-hass-card#605]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
3.0

**Last working release (if known):**
Never worked on iOS browsers but works flawlessly on PC or tablet browsers

**Browser and Operating System:**
both Chrome & Safari on iOS don't render Frigate streams

**Description of problem:**
I’ve been happily using Frigate and displaying the streams via the [Frigate NVR Custom Component](https://github.com/blakeblackshear/frigate-hass-integration) for Home Assistant and with the [Frigate Lovelace Card](https://talnet-ha.duckdns.org:9433/hacs/frontend). I’m running four cameras and everything/all cards are displaying well when accessed via a browser on the PC or a tablet. 

When I'm accessing the Frigate Lovelace Cards via Chrome or Safar (the same cards which render well on the PC/tabet), I get the following:

![Image 2022-05-22 at 7 47 53 PM](https://user-images.githubusercontent.com/40683291/169713654-3c4e5f9c-0999-4c93-9b74-d9322de20a5f.jpeg)

Expecting that Frigate card renders the stream on IOS browsers as well as it does on the PC and tablet

**Comment by dermotduffy** [comment]
Thanks for the report! I don't have access to an iOS device, so this is a little tricky for me to test.

There was a somewhat similar sounding bug here: https://github.com/dermotduffy/frigate-hass-card/issues/505

Would you mind trying what I [describe here](https://github.com/dermotduffy/frigate-hass-card/issues/505#issuecomment-1092385882) and see if that helps?

I assume the streams work fine when viewing them in HA through some other means? (e.g. a picture glance card?)

**Comment by friendodevil** [comment]
I cleared the cache on both chrome and safari iOS browsers but did not see any change

Viewing them in HA on PC/tablet browsers works great via Frigate or Picture/Glance cards but I get the same negative result when viewing in iOS browsers

**Comment by dermotduffy** [comment]
Closing as it does not seem related exclusively to the card. Let me know if this works with a picture/glance card, but doesn't work for this card (that would indicate a problem here).
