### ISSUE TITLE
Hover menu no longer seems to work in 4.0

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#620]
**Checklist:**

- [x ] I updated to the latest version available Yes, built V4.0 on 5/31
- [x ] I cleared the cache of my browser 

**Release with the issue: 4.0

**Last working release (if known): 3.0

**Browser and Operating System: Chrome Browser on Windows 11

**Description of problem:**
First of all, thanks Dermot for your help the other day - I was able to build V4.0 after your comments.  The release looks fantastic, but I have a couple minor issues having to do with the menu display.  First of all, I typically use hover mode for menus so the card does not look too cluttered.  I saw in your code that hover should now only work when the cursor is over the menu itself rather than the card (great idea!).  However, when I select hover mode the menu is "always" displayed - identical to if I had selected overlay mode. 

The second issue is minor - my cards always have rounded corners based on my theme, but when the menu is displayed it causes the top left corner of the card to be square.  The other three corners are OK.  With no menu displayed it displays OK.

I should probably note that if I set hidden mode, the Frigate button does not cause this issue.  But clicking the Frigate button (and displaying the rest of the menus) causes the top left corner to be squared off.

**Comment by dermotduffy** [comment]
Thanks for the feedback to help make v4 a quality release! Do you have a screenshot you could provide for the rounded corners thing?

**Comment by tbrausch** [comment]
This is a screenshot when the menu mode is set to hidden.  Notice the corner is rounded:
![left_hidden](https://user-images.githubusercontent.com/45288916/171287084-275decb7-95ad-42d8-875f-12343f43a411.jpeg)

Still set to hidden, but the menu is expanded by clicking on the Frigate button - corner is not rounded.
![hidden_expanded](https://user-images.githubusercontent.com/45288916/171287594-f73b71ea-0da2-410f-ad69-670dc9c35e9b.jpeg)

And this is when the menu stye is set to hover:
![left_hover](https://user-images.githubusercontent.com/45288916/171287225-b01c5a88-a685-43e8-9d3e-b32c53aae5a0.jpeg)

**Comment by dermotduffy** [comment]
> The second issue is minor - my cards always have rounded corners based on my theme, but when the menu is displayed it causes the top left corner of the card to be square. 

I think it's actually the menu background (a linear gradient darker on the right side than the left) that is causing it to look like the corner is not rounded. Let me see if I can fix ...

**Comment by dermotduffy** [comment]
Thanks @tbrausch ! I believe both are now fixed. Really appreciate the early beta testing, please keep the issue reports coming.
