### ISSUE TITLE
Custom menu button

### ISSUE THREAD

**Issue by kongjudas** [dermotduffy/frigate-hass-card#625]
I have 10 Tapo cameras with a privacy switch (black-out). With a custom menu button function, it would be easy to control things like detection, on/off services and ie. night vision or in-camera alarm.

**Comment by dermotduffy** [comment]
If the goal is simply to add a custom menu icon that can perform Home Assistant actions (e.g. turn something on or off), then this is already possible. See: https://github.com/dermotduffy/frigate-hass-card#adding-menu-icons

**Comment by dermotduffy** [comment]
Closing for now, please re-open if it does not work as desired! Thanks.
