### ISSUE TITLE
Scroll button on mouse tries to scroll between cameras

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#626]
Not sure if this is intended operation or not, but the scroll button on a mouse causes the cameras to scroll if the mouse is positioned anywhere over the frigate-hass-card.  Even if only one camera is defined in the card, it tries to scroll (goes about a third of the way).  I have a view that displays 6 cameras, and when I try to scroll the entire window with the mouse it instead tries to scroll the individual frigate card to the next camera.  I have to click and drag on the windows scroll bar to be able to move down to see the bottom cameras.

**Comment by dermotduffy** [comment]
That is working as intended -- i.e. the scroll wheel can be used to scroll through the cameras in the carousel within one card.

A few questions:
* Do you think it should behave this way by default? If I have a card with >1 cameras in it, this feels useful?
* Should there be an option do disable this?
* What about the thumbnail carousels?

**Comment by tbrausch** [comment]
I can see where this would be useful, but is it possible to disable it if there is only 1 camera defined in the card?  This would allow me to scroll the window when I am using a card for each camera (versus multiple cameras in each card).

**Comment by dermotduffy** [comment]
> I can see where this would be useful, but is it possible to disable it if there is only 1 camera defined in the card? 

Done!

**Comment by Arjenlodder** [comment]
Great card! I was wondering if it is possible to completely disable this functionality, then I found this issue. Looking at the code, I guess it can't be disabled completely, right? Is there a possibility this could be configurable in an upcoming release?

**Comment by dermotduffy** [comment]
> @dermotduffy Great card! I was wondering if it is possible to completely disable this functionality, then I found this issue. Looking at the code, I guess it can't be disabled completely, right? Is there a possibility this could be configurable in an upcoming release?

Yes, this could be done easily I suspect. File a feature request if this is something you'd like me to explore. Please be clear in the feature request whether or not you'd expect it to apply to the main media only (e.g. live video streams), or the thumbnails carousel, or both.
