### ISSUE TITLE
Custon Sub Menus do not Display in the Correct Location

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#649]
I created a submenu for the frigate-hass-card but the dropdown portion does not display in the correct location if I specify the menu location with style.  For example:

```
  - type: custom:frigate-card-menu-submenu
    icon: mdi:menu
    style:
      position: relative
      left: 150px;
    items:
      ...
```
This casues the pulldown menu to be displayed as if no style position was specified - as shown below.
![menu](https://user-images.githubusercontent.com/45288916/172693843-828bc645-d1c3-48cb-b12c-b63fb2d3662e.jpg)

**Comment by dermotduffy** [comment]
It is correct that this is not supported. Sadly getting the menu to appear in the right place has already cost a significant amount of time ([I described it here](https://github.com/dermotduffy/frigate-hass-card/issues/447#issuecomment-1059821014)), and I'd rather not open this can of worms again!

Fundamentally, the menu icons themselves cannot be user positioned reasonably. The buttons are context sensitive, so some buttons will appear/disappear depending on what the card is doing. So we cannot really use user positioned menu icons (they'd end up continually wrong!). Here you are talking about the position of the menu itself, but the menu just appears anchored on wherever the icon is (the three horizontal lines in your screenshot).

It might help to understand why you want to move the menu in the first place?

**Comment by tbrausch** [comment]
Understood - not a big deal.  This is a complicated card with lots of options, I was just playing around to understand it a little more.  Thanks again for all your efforts!
