### ISSUE TITLE
Prevents Screen Sleep on Android

### ISSUE THREAD

**Issue by bluegizmo83** [dermotduffy/frigate-hass-card#65]
Can't speak to other devices, but on my Android device this card prevents the screen from sleeping when the card is in view on the screen. The stock Picture Entity card does the same thing though when it's set to view a camera in Live mode, so I don't know if there is anything you could do to fix this...

**Comment by dermotduffy** [comment]
I think it's just that any video at all will do so on Android, i.e. is not really related to this card. A way to test would be to put the card in clips mode so it's showing the gallery:

```yaml
view_default: clips
```

... the Android device will  probably go to sleep (as there's no video playing, even though the card is loaded).

Some people reportedly [use this video trick to intentionally keep their android screens on](https://stackoverflow.com/questions/11529247/in-html5-how-can-i-keep-an-android-device-s-screen-on/29796071#29796071). If this is for a tablet, you might have more look at https://www.fully-kiosk.com/en/ which may be able to blank the screen at least.

**Comment by dermotduffy** [comment]
Going to close this as I'm not sure what else the card can/should do to help, please re-open if you have an idea!
