### ISSUE TITLE
frigate jsmpeg

### ISSUE THREAD

**Issue by dpomnean** [dermotduffy/frigate-hass-card#686]
I am using the Frigate JSMpeg live feed and more times than not, I will receive this error. If I just wait long enough or close the app and re-open it, it will start streaming. Using the webrtc live feed option I do not have this issue.

Home Assistant Core 2022.6.1

card v3.0.0
frigate HACS version 2.3
frigate version 0.10.1

```
http://192.168.1.65:8123/lovelace-cameras/0:0:0 Uncaught
:0:0 Script error.
http://192.168.1.65:8123/lovelace/default_view?external_auth=1:0:0 Uncaught
http://192.168.1.65:8123/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=394082552300:14944:28 Uncaught RangeError: offset is out of bounds
http://192.168.1.65:8123/lovelace-cameras:0:0 Uncaught
```

**Comment by dermotduffy** [comment]
Some more details that may help right now: https://github.com/dermotduffy/frigate-hass-card#console-shows-offset-is-out-of-bounds--out-of-bounds-memory-access

This should be fixed fully in the upcoming imminent v4 build, as it includes a new JSMPEG player version that (I believe) fixes this problem -- so just waiting for that build would also work.

I'm going to close this as I don't think there's anything else to be done on this end, but let me know if you think I'm mistaken!
