### ISSUE TITLE
"ERROR: Support only RTSP-stream" on all cameras when using WebRTC (but direct camera URLs work with WebRTC Card)

### ISSUE THREAD

**Issue by oramirite** [dermotduffy/frigate-hass-card#69]
**Checklist:**
- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
v1.0.1 (also occurred on v0.1.4)

**Last working release (if known):**
None

**Browser and Operating System:**
All (Windows/Chrome, Android app)

**Description of problem:**
Whenever I specify a camera entity using WebRTC playback, I immediately get this error on the top of the player:
"ERROR: Support only RTSP-stream"

**Debug steps taken:**
This issue also occurs if I use the WebRTC card directly, and specify the camera via `entity:` instead of `url:`. Ultimately, using the WebRTC card with 'url:' directly to any camera works, so the cameras are compatible.

**Javascript errors shown in the web inspector (if applicable):**
```
mediaSource.onsourceopen @ webrtc-camera.js?v2.0.2:158 WebSocket is already in CLOSING or CLOSED state.
```

**Additional information:**
I suspect this problem is occuring because Frigate re-streams cameras as RTMP, not RTSP. This is all very confusing, because the Readme for this project implies that Frigate cameras should work with WebRTC playback without a problem. The WebRTC plugin recommended in the readme does not support RTMP... therefore, specifying the camera entity will always be broken. Yet, the Readme implies that this setup works and I should be able to view Frigate cameras now. Am I missing a step?

**Comment by dermotduffy** [comment]
I think you may be misunderstanding how this is supposed to work, or more likely, the documentation is unclear. 

When you're using WebRTC as your live provider, the Frigate card is little more than a wrapper around the WebRTC card that adds some Frigate fanciness such as events. You must have WebRTC already working & configured, and WebRTC fundamentally requires an RTSP stream. If you want to avoid using the `url` argument in the webrtc configuration, you must provide an `entity` argument (under `webrtc:`) but that must be independently configured as a separate RTSP camera in HA by you manually.

e.g. you must configure "raw" RTSP entries in Home Assistant with something like this:

```yaml
  - platform: generic
    stream_source: !secret rtsp_path_cam_back_yard
    name: Back Yard RTSP
    still_image_url: [path to some still]
```

... and then use that RTSP entity in your WebRTC configuration. This is all a requirement of WebRTC, not of the Frigate card.

General advice: Get WebRTC working exactly as you want it first, _then_ just copy that card configuration into the `webrtc` section of your Frigate card, and it should all work.

**Comment by oramirite** [comment]
Okay, yes, the docs are unclear. After combing over them multiple times I finally figured out that I must go in and edit the card in YAML mode and add the url: parameter to get working operation. This is sorta hidden in the middle of your steps, when it's really the ONLY step that matters :P 

You should state this clearly: "Live streams from Frigate camera entities are not supported with this card. One must bypass the Frigate camera by adding the direct URL of a camera via yaml mode."

Just to clarify, I DID mention in my original post that I had WebRTC working fully. I think your docs just need to be clearer about YOUR card actually using the same params from the WebRTC card.

I would not qualify this plugin as "Working" with Frigate cameras in this case, at least not for live streaming. When you say something like that, it implies I should just be able to reference the entity directly. Especially since the URL field is the only field missing from the GUI configuration. You just mention that one should "set up "WebRTC and you link to the other pluygin, but this is confusing as there isn't really a "set up" process for that plugin... there is just configuration of the actual card itself, which I didn't expect would apply to an entirely different card (your card).

You could probably reduce this confusion by adding a "URL" field in the GUI of the WebRTC section of your card. I was actually pleasantly surprised to see that GUI, but I think it's what started to throw me off too :)

**Comment by dermotduffy** [comment]
@oramirite Thanks again for the valuable feedback. Please take a look through the merged PR, I hope (?) it's clearer now on the limitations and utility. I also added editor support from `webrtc.url` since you suspected that may also have reduced confused.
