### ISSUE TITLE
Select entities not displaying state anymore

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#699]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** latest 4

**Last working release (if known):** I don't know, sorry! But I know it worked before.

**Browser and Operating System:**

**Description of problem:**

Select entities stopped being colored according to their states:

https://user-images.githubusercontent.com/29582865/174462371-01729645-9b32-4db8-8046-78dc223facfb.mp4

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

**Comment by dermotduffy** [comment]
This seems to still work for me.

![submenu-state](https://user-images.githubusercontent.com/1136829/174471631-cb1f3f2c-07ef-4d46-a1e7-c2616f9cb0c0.gif)

Can I see the config? 

Code near this did change recently (https://github.com/dermotduffy/frigate-hass-card/pull/684) so a bug may have sneaked in ...

**Comment by dermotduffy** [comment]
Ah, I think it's broken if the options are overridden. Would guess you are doing that. Still investigating.

**Comment by dermotduffy** [comment]
Confident I got it. Try it out and re-open if not!

**Comment by felipecrs** [comment]
@dermotduffy it worked, thank you so much!
