### ISSUE TITLE
Full Screen View

### ISSUE THREAD

**Issue by utkarshjain00** [dermotduffy/frigate-hass-card#70]
**Is your feature request related to a problem? Please describe.**
I use the cards to fit many cameras on the phone screen for a view at a glance. Once something of interest happen, I want to look at a particular camera in full screen mode.

**Describe the solution you'd like**
Add a full-screen view button on the card. 

**Describe alternatives you've considered**
With multiple clicks, this can be solved, but the whole point is to get to the full view in 1 click. 

**Additional context**

**Comment by dermotduffy** [comment]
Do the video controls rendered on the card when live, or a clip is playing, not already contain a fullscreen button for that purpose? Or do you mean something else?

**Comment by utkarshjain00** [comment]
There's no full screen button when live. 

![image](https://user-images.githubusercontent.com/81548490/132798119-8fafb330-9430-4cf3-b7cc-a637ec24d312.png)

**Comment by dermotduffy** [comment]
- What browser / OS are you using?
 - Is that the default live via or WebRTC?
 - Do you expect the fullscreen button on the menu? [Depending on the menu configuration, that may not be 1-click, but is certainly "neater"]

**Comment by utkarshjain00** [comment]
Windows 10 / Microsoft Edge
Default Live View
Button on menu would be great! I keep the menu on all times anyways.

**Comment by utkarshjain00** [comment]
Repro on Pixel Android Phone / Home Assistant App
Repro on Pixel / Chrome browser too.

**Comment by dermotduffy** [comment]
Huh, that's weird. Chrome/Android are certainly giving me a full screen button on live, any chance you can grab a screenshot?

**Comment by utkarshjain00** [comment]
Here you go. 
![Screenshot_20210910-115033](https://user-images.githubusercontent.com/81548490/132903113-32aad106-ee5b-419b-851a-c2abce1dd78b.png)
![Screenshot_20210910-114613](https://user-images.githubusercontent.com/81548490/132903119-f12437ef-9b86-41b2-b66e-ffdc24380b0c.png)

**Comment by dermotduffy** [comment]
When you click on the video feed, don't the video controls show up including a fullscreen button?

**Comment by utkarshjain00** [comment]
No controls whatsoever. Tried clicking on video, live view button etc. From menu, I can go to clips and when I play a clip, I get controls.

**Comment by dermotduffy** [comment]
FYI: This functionality is now pre-released as part of [v1.1.0](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v1.1.0) . Any help to test and report bugs is much appreciated!

**Comment by utkarshjain00** [comment]
Any instructions on how to install this pre-release? I don't see this in the HACS card info, I guess by design being a pre-release.

**Comment by dermotduffy** [comment]
See the "instructions" at the top of: https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1399806

**Comment by utkarshjain00** [comment]
Thank you, that worked! 

I can confirm the Full-screen button works on my Pixel/HA App.  Thank you very much!

Minor issue: if I make the camera full -screen, then rotate my phone, the full-screen view is exited. Ideally, it should just rotate and fit screen.

**Comment by dermotduffy** [comment]
Excellent!

Sadly on your minor issue I think that's the browser/phone, not the card. On my Pixel, I can open a regular camera fullscreen in HA (i.e. not in the card) and when I rotate the fullscreen mode is exited -- same as in the card. I'm not sure there's a way to influence that behavior from what's running in the web browser.
