### ISSUE TITLE
Improve connection lost UX

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#711]
**Is your feature request related to a problem? Please describe.**

When the card cannot communicate with HA for fetching the JSMPEG stream, it displays a message of:

```
Could not retrieve or sign JSMPEG websocket path. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
```

But when HA backend is simply unavailable (like during restarts), the error message above isn't helpful (and a little ugly).

![chrome_dmVHWodBnx](https://user-images.githubusercontent.com/29582865/174674959-101a1e6c-db4b-4f9e-96c0-fd3dfd5a920b.png)

**Describe the solution you'd like**
Home Assistant frontend can properly detect whether connection to backend was lost or not (that's why it shows a `Connection lost. Reconnecting...` toast message below).

If we could reuse that part of the frontend for detecting such a situation, we could improve the error message (by not displaying an error at all).

How about showing a "Connection"-like icon like `mdi:connection`, centralized:

![image](https://user-images.githubusercontent.com/29582865/174674675-2b580b8d-e395-4d5b-ac04-e24311546a05.png)

Another suggestion, which perhaps should be tracked in a different issue, would be to keep the aspect ratio of 16:9 (if the user has defined such a 16:9 fixed aspect ratio) even in such scenarios to avoid breaking the screen layout.

**Describe alternatives you've considered**

N/A.

**Additional context**

What do you think? Happy to hear opinions.

**Comment by felipecrs** [comment]
Found one reference in the frontend:

[hassDisconnected](https://github.com/home-assistant/frontend/blob/3ef2912b60485b0dd1302b8d6a14c573eeda1567/src/state/disconnect-toast-mixin.ts#L75)

**Comment by dermotduffy** [comment]
> How about showing a "Connection"-like icon like mdi:connection, centralized.

How about just an error with that as the icon and "Connection lost. Reconnecting..." as the message. We can tell we're disconnected if `this._hass.connected` goes to false, then we show that message. This would happen ~immediately, so would almost certainly happen before the card otherwise shows an error like the one you include.

> Another suggestion, which perhaps should be tracked in a different issue, would be to keep the aspect ratio of 16:9 (if the user has defined such a 16:9 fixed aspect ratio) even in such scenarios to avoid breaking the screen layout.

Yeah, different issue -- but right now the card intentionally doesn't bother with such constraints if there's a message to display. This may be because messages were being truncated -- can't remember exactly why I did this, but I agree if the user specifically sets a static set of dimension, respecting those makes sense to me.

**Comment by felipecrs** [comment]
Sounds great! But maybe the "Connection lost. Reconnecting..." message is still too verbose (considering that the frontend itself would already make sure you acknowledged this information). And that you may have multiple cards in the screen.

If only there were a better (more self-explanatory) icon than the one I suggested... I'm sure I saw one somewhere, but it does not seem to be part of the MDI.

**Comment by dermotduffy** [comment]
Yeah. Maybe just "Reconnecting..."?

Could also modify the existing message component (that does the error messages) to just center the icon (and maybe make it a bit bigger) if there is not a message otherwise specified.

**Comment by felipecrs** [comment]
Some icon ideas:

`mdi:connection`:

![image](https://user-images.githubusercontent.com/29582865/174678412-bd4810e5-a9e6-4692-8974-5366aa2eb4a3.png)


`mdi:lan-disconnected`:

![image](https://user-images.githubusercontent.com/29582865/174678375-54c8ad9b-e9ab-4ac7-801d-a5734a1cea72.png)

`mdi:image-broken-variant`
![image](https://user-images.githubusercontent.com/29582865/174678494-7389ff6e-03d2-4673-ad6e-2adc087094c6.png)

👆 This was the one I thought.

`mdi:image-broken`

![image](https://user-images.githubusercontent.com/29582865/174678582-7b3515cc-0249-4abf-89f8-a9025da784de.png)

**Comment by dermotduffy** [comment]
`mdi:connection` or `mdi:lan-disconnected` get my vote, although zero strong preference. The latter two are more suggestive of a broken image format to me, rather than a connectivity one.

**Comment by felipecrs** [comment]
> Yeah. Maybe just "Reconnecting..."?

A million times better than _Could not retrieve or sign JSMPEG websocket path. Check troubleshooting_, but I still have the impression that the text-less (icon only) variant would look better (and I'm totally okay if you prefer the message).

> Could also modify the existing message component (that does the error messages) to just center the icon (and maybe make it a bit bigger) if there is not a message otherwise specified.

Sounds like a good idea.

**Comment by felipecrs** [comment]
I think `mdi:lan-disconnected` is the best of them. It immediately shows that something is wrong (because of the little X).

**Comment by dermotduffy** [comment]
@felipecrs How about this? I tried the large icon without text and it looks worse (IMO), as it clashes with the menu icons, so here is my proposal:

![reconnecting](https://user-images.githubusercontent.com/1136829/175217055-78479a65-98f2-4b99-8f8b-fc798edb886c.gif)

**Comment by felipecrs** [comment]
It looks amazing!

**Comment by dermotduffy** [comment]
Closing this one, other sub-issues tracked separately.
