### ISSUE TITLE
Unconfirmed incompatibility between card/integration and `2022.7.0b0`

### ISSUE THREAD

**Issue by tkdrob** [dermotduffy/frigate-hass-card#745]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
HA 2022.7.0

**Last working release (if known):**
HA 2022.6.7
Card 4.0.0-rc.1

**Browser and Operating System:**
Windows 10 21H2 Chrome

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2022.7.0b0",
  "card_version": "4.0.0-rc.1",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
  "date": "2022-06-29T22:25:37.143Z",
  "frigate_version": {
    "cd579cef6171f523784444ce93c975a4": "3.0.0-rc.2/0.10.1-83481af"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-rc.1-HEAD+ge936521",
    "build_date": "Mon, 27 Jun 2022 02:41:57 GMT",
    "commit_date": "Sun, 26 Jun 2022 16:47:08 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "live_provider": "webrtc-card",
        "camera_entity": "camera.front_door",
        "webrtc_card": {
          "url": "rtsp://nunya:beeznes@10.1.3.12:554/stream0"
        }
      },
      {
        "camera_entity": "camera.walkway",
        "live_provider": "webrtc-card",
        "webrtc_card": {
          "url": "rtsp://nunya:beeznes@10.1.3.15:554/mode=real&idc=1&ids=1"
        }
      },
      {
        "camera_entity": "camera.front_yard",
        "live_provider": "webrtc-card",
        "webrtc_card": {
          "url": "rtsp://nunya:beeznes@10.1.3.16:554/mode=real&idc=1&ids=1"
        }
      },
      {
        "camera_entity": "camera.driveway",
        "live_provider": "webrtc-card",
        "webrtc_card": {
          "url": "rtsp://nunya:beeznes@10.1.3.13:554/stream0"
        }
      },
      {
        "camera_entity": "camera.south_side",
        "live_provider": "webrtc-card",
        "webrtc_card": {
          "url": "rtsp://nunya:beeznes@10.1.3.14:554/mode=real&idc=1&ids=1"
        }
      },
      {
        "camera_entity": "camera.shop",
        "live_provider": "webrtc-card",
        "webrtc_card": {
          "url": "rtsp://nunya:beeznes@10.1.3.17:554/mode=real&idc=1&ids=1"
        }
      }
    ],
    "live": {
      "preload": true,
      "controls": {
        "next_previous": {
          "size": 30
        }
      },
      "lazy_unload": "all",
      "auto_unmute": "never"
    },
    "menu": {
      "buttons": {
        "image": {
          "enabled": true
        },
        "download": {
          "enabled": true
        },
        "frigate_ui": {
          "enabled": true
        },
        "fullscreen": {
          "enabled": true
        }
      }
    },
    "view": {
      "default": "live"
    },
    "media_viewer": {
      "lazy_load": true,
      "draggable": true,
      "auto_unmute": "all"
    }
  }
}
```

![Screenshot 2022-06-29 155511](https://user-images.githubusercontent.com/21083073/176555451-937b72e3-d09f-4a1f-909c-d45010cf6d6a.png)

**Additional information:**

https://rc.home-assistant.io/blog/2022/06/29/release-20227/
Python 3.9 has been dropped so this may have caused the issue.

**Comment by dermotduffy** [comment]
Please hold down the Frigate menu icon and paste the resulting text. Thanks!

**Comment by tkdrob** [comment]
![Screenshot 2022-06-29 183002](https://user-images.githubusercontent.com/21083073/176556578-9d177d1c-7b07-4a91-af7d-11e65470179f.png)

**Comment by dermotduffy** [comment]
@tkdrob `2022.7.0b0` works fine with the integration and card for me (same versions as you). The only difference between our setups is that you are using an older version of Frigate itself (you are using v0.10, and I am using v0.11). Can you upgrade your Frigate instance, then restart HA, and see if the issue persists:

https://github.com/blakeblackshear/frigate/releases/tag/v0.11.0-beta4

PS: That log message is not related, but I'll bet there is a different exception in the logs from Frigate. If you can't see anything in the HA log viewer, try looking at the file raw and the exception will be more apparent.

**Comment by dermotduffy** [comment]
@tkdrob I'm going to close this for now since the main issue is the WebRTC card issue (https://github.com/AlexxIT/WebRTC/issues/318). Please re-open if you think there's something in the card to fix. Thanks.
