### ISSUE TITLE
Not available via Internet?

### ISSUE THREAD

**Issue by joaovitoriasilva** [dermotduffy/frigate-hass-card#75]
Hello,

So I have the latest version of frigate docker image, latest version of HA and latest version of this lovelace integration.
Both frigate and the card integration are installed using HACS.

I have Homeassistant published to the world using the old port forwarding + reverse proxy combo.
Frigate is not published to the world, only internally.

When I am via Internet using the mobile app, the card does not show live view or captures and clips. Sometimes it even displays an error.

Thank you.

![IMG_6497](https://user-images.githubusercontent.com/8648976/133076839-b7a60d1f-6cd4-4b9b-bdda-07d78e1bedc8.PNG)
![IMG_6498](https://user-images.githubusercontent.com/8648976/133076844-00455659-fc98-4c98-ae63-93757fa14ef8.JPEG)

**Comment by dermotduffy** [comment]
I don't think you're using the most recent version of the card, based on clues in your config.

There is a v1.0.1 pre-release which is the very latest. There are substantial changes to how media metadata & data are loaded which I believe will help, or entirely resolve, this issue.

Try that pre-release? You'll need to tell HACS to show you beta versions by clicking the 'Reinstall' option and then choosing v1.0.1.

**Comment by joaovitoriasilva** [comment]
Hello,

Thanks for the quick help. In fact I was using the lateste stable release. Updated the version to v1.0.1 but I am still unable to stream the live view from the Internet.

**Comment by dermotduffy** [comment]
Make sure you have cleared your cache on your device, e.g. try to do it via an Incognito Chrome window? (Common problem)

Are you using the Frigate or WebRTC live provider? If the former can you see any camera live view from your HA instance (without use of the card) from outside your home network? If the latter, can you see the WebRTC live view using the native WebRTC card? (Trying to see if you have a general issue or something specific to this card)

**Comment by joaovitoriasilva** [comment]
Using Incognito Window does not fix it. I have the same issue.
Using a "normal" picture entity with the live view from the Firgate entity, it works okay. It was like this before trying this card.

Using a webrtc card also does not work. I am using the url to the camera RTSP feed that only works on the internal network. Can this be the issue?

**Comment by dermotduffy** [comment]
If the WebRTC card doesn't work (which I think is what you're saying), your issue is not with the Frigate card as the Frigate card just 'wraps' the WebRTC card when you use WebRTC as your live provider.

Either:

* Try to get the WebRTC card itself to work, then when it's working move the configuration into the Frigate card (see [this section](https://github.com/AlexxIT/WebRTC#webrtc-external-access), or seek support from the authors of WebRTC itself).
* OR: Don't use WebRTC as your live provider, just use 'Frigate' in the configuration for this card.

**Comment by joaovitoriasilva** [comment]
Hello,

First thank you so much for the tips and quick response.
The problem is solved. I was not aware the limitation of WebRTC on iOS when no ports were open. https://github.com/AlexxIT/WebRTC#webrtc-external-access

Awesome work. I am really loving this card.
