### ISSUE TITLE
Improve instructions to cast card

### ISSUE THREAD

**Issue by Tyrian81** [dermotduffy/frigate-hass-card#750]
In the release notes it says possible to cast the card directly ,but I'm only able to cast stream directly without the controls to my nest hub ?

Do i need to use the HA integrated Google Cast: Show lovelace view ? this shows the whole lovelace view though ?

**Comment by dermotduffy** [comment]
> Do i need to use the HA integrated Google Cast: Show lovelace view ? this shows the whole lovelace view though ?

Yes, you're not really casting the card itself -- you're casting a dashboard with the card on it. Best bet is probably to make a new dashboard with a single card on it and cast that. This is [briefly mentioned in the docs](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#casting-the-card), and suggests using [cast.homeassistant.io](https://cast.home-assistant.io/).

PRs to improve the documentation are very welcome if you think it can be made clearer.
