### ISSUE TITLE
Spinner on JSMPEG not vertically centralized

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#752]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

v4.0.0-rc.2

**Last working release (if known):**

I'm sure this didn't use to happen in the past. If you need, I can try to find the latest version which it worked.

**Browser and Operating System:**

N/A

**Description of problem:**

The JSMPEG spinner/loading icon is not vertically centralized.

**Additional information:**

![chrome_MFdVpPzNRd](https://user-images.githubusercontent.com/29582865/177047973-e3e27f51-8366-4171-8580-4fb2c45678dd.png)

https://user-images.githubusercontent.com/29582865/177047975-47460566-8685-461e-9a83-35f1a96d559a.mp4

**Comment by dermotduffy** [comment]
Think that should do the trick, let me know if you spot a case it's not right!
