### ISSUE TITLE
Hide custom elements until stream is loaded

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#758]
**Is your feature request related to a problem? Please describe.**
To prevent PTZ buttons like these to show up when the camera is yet loading:

https://user-images.githubusercontent.com/29582865/177878965-7af9b142-5679-4c8f-8fc2-dfd2a98c0537.mp4

**Describe the solution you'd like**
Hide those custom elements during the spinner. Just like they are hidden during an error message, and I believe.

- Refs https://github.com/dermotduffy/frigate-hass-card/issues/717

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dermotduffy** [comment]
Makes sense, but may be irritating/awkward to implement as the element display are done at the 'top level' of the card, whereas the many different kinds of media loads (e.g. webrtc, images, hls clips, jsmpeg, etc) are done "down" in the relevant component. I have an idea though ...

**Comment by felipecrs** [comment]
Interesting... unless you have a better idea, we can start by the jsmpeg perhaps.
