### ISSUE TITLE
Refactor camera unavailable message

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#759]
**Is your feature request related to a problem? Please describe.**
Cameras can become unavailable frequently depending on their setup. This is how the card handles it currently:

![image](https://user-images.githubusercontent.com/29582865/177879373-48c8dbdc-ad49-4490-8dee-6c1d2fea2364.png)

It states that there may be something wrong with the configuration, while there is not.

**Describe the solution you'd like**
I believe it could be said: 

```
mdi:cctv-off Camera unavailable.
```

As in the "Reconnecting" message.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dermotduffy** [comment]
I would suggest we keep the existing message if the state is not found at all (e.g. typo in the config), but a much smaller message if it's found but unavailable. Make sense to you?

**Comment by felipecrs** [comment]
Yes. That's what I meant too. Only if the entity is there, but its state is unavailable.

**Comment by dermotduffy** [comment]
<img width="488" alt="Screen Shot 2022-07-23 at 11 09 17 PM" src="https://user-images.githubusercontent.com/1136829/180634711-78a023bf-6f06-4a46-b1f0-80b02bd8c860.png">

**Comment by felipecrs** [comment]
Looks great! I would just suggest to use the camera's friendly name instead of the entity's id.
