### ISSUE TITLE
Clips and captures not available on the mobile app

### ISSUE THREAD

**Issue by joaovitoriasilva** [dermotduffy/frigate-hass-card#76]
Hello,

So I have the latest version of frigate docker image, latest version of HA and latest version of this lovelace integration.
Both frigate and the card integration are installed using HACS.

I have Homeassistant published to the world using the old port forwarding + reverse proxy combo.
Frigate is not published to the world, only internally.

On the mobile app clips and captures does not get displayed, displaying an circle with a ! icon. This happens both using internal or internet connections.

Thank you.

![IMG_6503](https://user-images.githubusercontent.com/8648976/133077149-024d6ede-154d-4bb3-a09b-c2c3eeb3541d.JPEG)

**Comment by dermotduffy** [comment]
As on the other bug report, I'd suggest you try the latest pre-release. I'd guess this issue will be resolved in it (v1.0.1).

**Comment by joaovitoriasilva** [comment]
Hello,

Thanks for the quick help. In fact I was using the lateste stable release. Updated the version to v1.0.1 and this was fixed.
