### ISSUE TITLE
Live view only half screen

### ISSUE THREAD

**Issue by McPaHa** [dermotduffy/frigate-hass-card#763]
Home Assistant 2022.7.3
Supervisor 2022.07.0
Käyttöliittymän versio: 20220707.0 - latest

Frigate card v 3.0.0

![image](https://user-images.githubusercontent.com/36406452/178467585-2dfb009a-11cf-4267-9da7-95c663aa5ad4.png)

After clicking full screen and then esc (back to normal view) then live view is normal:

![image](https://user-images.githubusercontent.com/36406452/178467778-33edbb49-969d-4e99-b3ad-1ad59b6412b3.png)

**Comment by dermotduffy** [comment]
[Quick comment] This was likely already fixed, try the beta build: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.2

**Comment by jemershaw** [comment]
I just tested it and it seems to be working with the v4 version.

**Comment by dermotduffy** [comment]
Thanks for verifying. Will close this bug, please re-open if you think there's more to do here.
