### ISSUE TITLE
Issue with Frigate Card in HA

### ISSUE THREAD

**Issue by millie75** [dermotduffy/frigate-hass-card#777]
I set the card up yesterday and all was working fine, camera entity and frigate ID all entered correctly, I could see the camera and the clips/recordings etc, then after rebooting HA a couple of times on install other HACS updates I get the below in the Frigate card, as you can see from the image I have frigate typed in the frigate ID, but the message says can't find client instance id frigat  (without the e), is there something I've missed - running version v4.0.0-rc.2

Failed to receive response from Home Assistant for request. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigat/event-search/clips////front_door//",
    "id": 442
  },
  "response": {
    "code": "unknown_error",
    "message": "Could not find client for frigate instance id: frigat"
  }
}

![image](https://user-images.githubusercontent.com/51971269/181788075-cac942bb-fde7-43ca-b436-8a16091e1084.png)

**Comment by dermotduffy** [comment]
Hi @millie75 , that's odd. Can you hold down the Friagate icon in the menu and post  the resulting text?

**Comment by dermotduffy** [comment]
Please re-open with additional debugging information if this is still a problem. Thanks!
