### ISSUE TITLE
Added translation support

### ISSUE THREAD

**Issue by elax46** [dermotduffy/frigate-hass-card#781]
I open this request to ask for support in inserting the translation if you need help I'm available

**Comment by dermotduffy** [comment]
Hi @elax46 , the card already supports translations -- but it only has English and Brazilian Portuguese language data. If you are able to contribute language data for other languages, that would be very welcome!

Localization files live here: https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0/src/localize/languages 

You'd just need to copy the `en.json` file and make a new version for whatever language you are able to speak and verify the translations for.

Please let me know if I misunderstand the request. Thanks!

**Comment by elax46** [comment]
I'm sorry I hadn't looked at the folders in depth, of course I proceed!
