### ISSUE TITLE
Great work! Some challenges on Mobile.

### ISSUE THREAD

**Issue by scottjjr** [dermotduffy/frigate-hass-card#789]
Hi, have started using v4 and really loving where this is heading it’s great work!  

Am having some challenges on mobile though unfortunately.

I may have missed it, but is it possible to swap the pull-out event tab from the left side to the right? The left side tab is difficult to get as 9/10 times touching that side of the screen opens the HA left menu instead.  Also the cards that do pop out are massive and the scroll space is limited to the video height so only two show (see image) below is the same for the event image list also (image below also).  Is there some way of making those full height and not limited to the video height?

thanks!

![B2178B56-D0F1-4B06-86CB-D8FD19EF6FC4](https://user-images.githubusercontent.com/57744283/183278551-015eaee4-3445-4bdd-8387-a9e53405d739.jpeg)
![FC4E5822-58FF-4E44-B777-F283166A0223](https://user-images.githubusercontent.com/57744283/183278552-0aaae9db-3020-4157-8f30-b447ee7e3aca.png)
![6C5376CD-F2B7-4745-960B-38FAAC347897](https://user-images.githubusercontent.com/57744283/183278553-494a6201-17c6-4f59-84fe-29619b0526aa.png)

**Comment by dermotduffy** [comment]
> I may have missed it, but is it possible to swap the pull-out event tab from the left side to the right? The left side tab is difficult to get as 9/10 times touching that side of the screen opens the HA left menu instead. 

Yes, you can put the drawer to the right, or instead have the thumbnails above / below. See [documentation](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#media-viewer-controls-thumbnails).

> Also the cards that do pop out are massive and the scroll space is limited to the video height so only two show (see image) below is the same for the event image list also (image below also). Is there some way of making those full height and not limited to the video height?

You can vary what is shown in the thumbnail drawer (e.g. remove details, reduce size), which will alter the amount of space consumed. See the same documentation linked to above.

By default the card expands to the size of the media shown.

Fundamentally I think the issue you are having here is with the card height is smaller than you want -- and everything is fitting within that height. If this is the only card on the dashboard, you can set the HA dashboard to `Panel mode` (see [HA documentation](https://www.home-assistant.io/dashboards/panel/)) which will cause the card to consume all available space.

Another option is to force a particular aspect ratio (see [documentation](https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#dimensions-options)) to create more vertical space.

Let me know if the above does not resolve what you're getting at.

**Comment by scottjjr** [comment]
Hi, I have managed to move the draw to the other side now thanks, I'd missed that in the UI config options.  Unfortunately now it thinks i'm selecting the last event anytime I try and touch it, feels like a mouse-over click problem.  I have set to the bottom which presents the cards outside of the display bounds, which is more workable on a phone but requires scrolling left/right for events (when adding in text it takes up most of phone width).

I do have the card in panel view and have tried aspect ratios.  Have had some win with setting unconstrained ratio and all details on event gallery for a nice vertically scrollable list.

Yes agree, fundamental issue appears to be trying to use a phone in portrait mode, which has a low height in a tall screen.  The changes above have made it workable though - thanks for your help!

**Comment by dermotduffy** [comment]
> Unfortunately now it thinks i'm selecting the last event anytime I try and touch it, feels like a mouse-over click problem.

Hmm. I'm not following this -- can you describe in more detail how I can try to reproduce and what you're seeing? This sounds like a potential bug if the event carousel is somehow unusable.

> The changes above have made it workable though - thanks for your help!

Is there's a feature request that could make it _excellent_ rather than workable in your opinion? At the very least having the drawer start on the right feels like it might be a safer default, but I'm curious if there's anything you'd like to see.

**Comment by scottjjr** [comment]
Sure, almost every timeI touched the draw handle with my finger it would pull the draw out and then slide the carousel to the previous video. Assume the touch was registering for both. On the pc when i mouse however the drawer handle it would pop out, so wondering it both hover and touch register on the phone when using a finger.

What would be a stellar option is the timeline view under the camera window, simliar to what I have on the last pic above. 
Not sure on others, but I record 24x7 and would love a way to 'scrub' through the video based on the timeline.  Am almost there with the single row of events, but the timeline from the other tab would be amazing.

**Comment by dermotduffy** [comment]
Thanks @scottjjr . Opened two separate issues for the two items discussed, follow along there, I'll close this one. Thanks again.
