### ISSUE TITLE
Instructions for a manual install

### ISSUE THREAD

**Issue by kbmetz** [dermotduffy/frigate-hass-card#79]
There's no option for manual install. I prefer not to run HACS and install everything by hand. The install instructions mention a 'frigate-hass-card.js' but this is not anywhere in the source code when you do a git clone. Can there be some brief instructions on how to install this without using HACS?

**Comment by dermotduffy** [comment]
Thanks for filing the issue!

Tactical answer: It's automatically compiled as part of the release process, you'll find it attached to an individual release ([example](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v1.0.1)).

May I ask why you don't use HACS? The answer is not directly pertinent to your reasonable request for instructions, but ... I guess I'd like to generally discourage manual installs as it's more work for the user, and the maintainer ;-) So understanding your usecase may soften that stance...

**Comment by kbmetz** [comment]
Ah, I was not aware that it was possible to just download it as a release.

I don't use HACS because I want to see everything that is installed. And, in my opinion when HACS breaks that will be just one more thing that I have to troubleshoot in my system. Also, I want to see what's being downloaded, installed, versions, etc. I'm one of those guys who NEVER runs the 'wget blah | /bin/bash' and in fact I'll do the wget first and then have a look at the code. Yes, I realize that overall its more work for the user to install, and I take on that burden by asking for this. And while I'm sorry it makes more work for you, its just something I'd like to have because I'm enjoying Frigate and I'd like to be able to try this out without being forced to run HACS.

Thanks

**Comment by dermotduffy** [comment]
Thanks for the usecase @kbmetz . Despite my fondness for HACS, I can absolutely relate. Added instructions.
