### ISSUE TITLE
Apply custom style based on "hovering" for custom elements

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#797]
**Is your feature request related to a problem? Please describe.**
I have the PTZ control arrows in my card (as custom elements as in the README). But some times the PTZ arrows covers parts of the image, while it didn't need to.

**Describe the solution you'd like**
Something similar to the PTZ controls in the WebRTC card: when I hover the mouse on the card, or tap on it (in touch screen), the PTZ controls pops up with less transparency. When idle, the PTZ cards are almost 100% transparent. It would be nice to be able to apply custom effects/styles in the custom elements based on such situation too.

**Describe alternatives you've considered**
N/a

**Additional context**
If this is possible already, please let me know, but no need to come up with an example (I can find my way if so). But I would say that the PTZ example in the README would be nicer to come with such a thing in it too.

**Comment by dermotduffy** [comment]
Don't think this is possible today (and figured it would eventually be requested)!

**Comment by dermotduffy** [comment]
Oh, hmm. The styling for **stock** HA elements is applied by Home Assistant frontend code, not by the card. So it may actually be non-trivial to apply custom `:hover` styles on stock elements unless we implement that in the HA frontend code. It would be easy with native (implemented by the card) elements.

**Comment by felipecrs** [comment]
Perhaps it can be implemented in the "frigate-card-custom-element" first? That should cover a good amount of the needs already.

**Comment by dermotduffy** [comment]
Current thinking: I am going to close this without merging the implementation:

* It's deceptively complex to implement dynamic hover styling, and I ended up resorting to a JS solution rather than CSS, which is just awkward and inflexible.
* I can't actually see many -- or any -- practical use cases (see my [comment](https://github.com/dermotduffy/frigate-hass-card/pull/805#issue-1338385712)).

**Comment by felipecrs** [comment]
I agree, you are right.
