### ISSUE TITLE
Native PTZ controls

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#798]
**Is your feature request related to a problem? Please describe.**
Apart from https://github.com/dermotduffy/frigate-hass-card/issues/797, I think some "native" PTZ controls would be good for the following reasons:

1. No need to calculate the pixels for each arrow. This is boring, but the problematic part is that they get displayed differently based on the device's DPI. It would be better if all the buttons were grouped and aligned centrally or something like that (instead of based on pixels only).
2. Difficult to apply fancy styles for each button, or something like the one in the WebRTC card which looks like a wheel (single image but clickable in 4 different areas).
3. Reduce a lot of YAML code duplication. Let's say you have 3 cards with such PTZ controls, if you want to keep them all the same, it would start to be a pain.

**Describe the solution you'd like**
This should be a rather popular use case. Having native support would simplify the people's setup, and would unlock the ability to make it fancier. I believe if the code from WebRTC could be borrowed, it should, because I think it works really well.

**Describe alternatives you've considered**
To use custom elements and customize them by myself. 

**Additional context**
If you disagree, I totally respect. The current approach isn't bad at all.

**Comment by dermotduffy** [comment]
Yeah, makes sense. The amount of YAML it takes to implement this yourself is pretty unpleasant.

**Comment by felipecrs** [comment]
https://github.com/dermotduffy/frigate-hass-card/pull/807
