### ISSUE TITLE
Investigate clash of drawer opening and carousel dragging

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#801]
Broken out of: https://github.com/dermotduffy/frigate-hass-card/issues/789
Requested by: @scottjjr

> Sure, almost every timeI touched the draw handle with my finger it would pull the draw out and then slide the carousel to the previous video. Assume the touch was registering for both. On the pc when i mouse however the drawer handle it would pop out, so wondering it both hover and touch register on the phone when using a finger.

**Comment by dermotduffy** [comment]
@scottjjr I cannot reproduce this. On the device that has this problem, can you hold down the Frigate icon in the menu then paste the diagnostics into this bug?

**What I'm doing**: Single touch the side-drawer handle on the side of the live view.
**Result**: The drawer pops open. The carousel does NOT activate.

**Comment by scottjjr** [comment]
Hi Dermot, have just finished a fresh re-install of everything. Here’s a screen recording of what I experience on an iPhone 13 in the HA mobile app.

 https://youtube.com/shorts/m4RnmRfY8SQ?feature=share

**Comment by scottjjr** [comment]
Just tried it on my android wall tablet and it’s not the same and works as expected. Where you trying on an apple or android device?

**Comment by dermotduffy** [comment]
I am only testing on Android, so this explains why there's a difference.

> @scottjjr I cannot reproduce this. On the device that has this problem, can you hold down the Frigate icon in the menu then paste the diagnostics into this bug?

Can you paste these diagnostics so I can attempt to reproduce?

Rather than scrolling the carousel, it looks like touching the drawer button is causing one of the clips _in the carousel_ to play.

**Comment by dermotduffy** [comment]
Update: I can reproduce this on an Apply device on Browserstack.

**Comment by dermotduffy** [comment]
Think I have this figured out. iOS Safari is treating the touch as first a 'hover' (which opens the drawer) then subsequently as a 'click'. But as the drawer has already opened on the 'hover', the 'click' lands not on the drawer control but on the carousel -- causing a clip to play. IMHO this is broken Safari behavior -- a single interaction should not be able to 'hover' over one element but instantaneously 'click' on a different element.

I think there'll be a straightforward fix.

**Comment by dermotduffy** [comment]
Fixed, and confirmed working on BrowserStack, so optimistic this will work for you @scottjjr . Fix will be in the next release of the card.

**Comment by scottjjr** [comment]
Awesome thanks! So you don't need the diagnostics anymore?

**Comment by dermotduffy** [comment]
> Awesome thanks! So you don't need the diagnostics anymore?

That's right! Pretty sure I got it, so just wait for the next build and re-open if it still doesn't work. Thank you again for the video, that was what hinted to me at what was going on.
