### ISSUE TITLE
Add mini-timeline view

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#802]
Broken out of: https://github.com/dermotduffy/frigate-hass-card/issues/789
Requested by: @scottjjr

> What would be a stellar option is the timeline view under the camera window, simliar to what I have on the last pic above.
Not sure on others, but I record 24x7 and would love a way to 'scrub' through the video based on the timeline. Am almost there with the single row of events, but the timeline from the other tab would be amazing.

**Comment by dermotduffy** [comment]
@scottjjr Just to confirm, you mean if we could have a timeline for a given camera load under the `live` view for the same camera. Is that what you mean?

**Comment by scottjjr** [comment]
Yes correct, if you can see the live view with timeline underneath and drag left/right to scrub through the recordings that would be awesome.

**Comment by dermotduffy** [comment]
> drag left/right to scrub through the recordings that would be awesome.

What does this mean exactly? Can you describe what you want to happen when you drag the timeline left / right?

**Comment by scottjjr** [comment]
Something like this with ring, milestone xprotect is similar as well

https://youtube.com/shorts/yQk5g55K9Wo?feature=share

**Comment by scottjjr** [comment]
Might help if I explain the use case a little more sorry.  What I’m keen to do is have access to all the recorded video and see the timeline with events marked, and move forward and backward through the video by dragging the timeline bar left or right.  Sometimes to events, other times just scrubbing through the video to see what’s happening/changing (or not). 

The timeline underneath the full recorded video is super useful doing this as I can see  when things are happening/finishing, or look either side for things that may not have captured as an event. As awesome as frigate’s recognition is, I have a lot of misses where something has happened and is obvious in the recording but it wasn’t tagged as an event (either not registering the object or not a tracked object).

**Comment by dermotduffy** [comment]
Quick update: This is the current feature I am investigating (i.e. this is not forgotten, just also not easy to implement!).

**Comment by bagobones** [comment]
I really like this idea as it would better give context to the current recording being played as well if this ALSO appeared when you launched a recording from the timeline.. I was going to suggest something else but if all playback live or recording just had a timeline under it that would just solve the context issue completely.

As for examples Surveillance station mobile has a really great UI for this including snapping / jumping to events as an option https://www.synology.com/en-ca/surveillance/feature/mobile

I just migrated off of surveillance station but could fire it back up if wanted more examples.

**Comment by bagobones** [comment]
![mock mini](https://user-images.githubusercontent.com/1587701/190708645-2f29ba53-b7f2-449a-a2af-f302f37d91f2.png)

A quick mockup using the current cards elements, ideally you could swipe and zoom the timeline part under it and when you tapped on an event or recording area it would start playing.
A LINE or indicator showing your current selection would also be needed.

**Comment by dermotduffy** [comment]
This will be in the next build.

**Comment by scottjjr** [comment]
Brilliant thanks! Looking forward to seeing it
