### ISSUE TITLE
Thumbnail images not working (shows broken image link)

### ISSUE THREAD

**Issue by ehosch** [dermotduffy/frigate-hass-card#812]
I can't seem to get thumbnail images working properly.  Everything else seems to work.  Here is a screenshot:

![image](https://user-images.githubusercontent.com/6679181/185839188-9a031144-4941-4363-961d-a0bbd85bc432.png)

I can respond with settings, but my setup is pretty straight forward so any help is appreciated.

**Comment by dermotduffy** [comment]
There are changes in how thumbnails are loaded in both the unreleased code of the integration & card, but this should work fine with the released version of both. They'll both be released in sync to keep this working -- is there a chance you are using one of the card or integration built from head, rather than an official pre-release/release?

If not, you'll need to provide the version numbers of card & integration so I can investigate further. A simple way to do this is to hold down the Frigate button on the card, then paste the resulting diagnostics information.

Thanks!

**Comment by ehosch** [comment]
Thanks for the quick response!

Card diagnostics. Please review for confidential information prior to
sharing
{
  "ha_version": "2022.8.6",
  "card_version": "4.0.0-rc.2",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "date": "2022-08-22T04:58:41.717Z",
  "frigate_version": {
    "92e3b33d5048b858ba32a3d2449f979c": "3.0.0-rc.3/0.10.1-83481af"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-rc.2-HEAD+g771943c",
    "build_date": "Sun, 03 Jul 2022 02:25:09 GMT",
    "commit_date": "Fri, 1 Jul 2022 19:57:20 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "frigate-jsmpeg",
        "frigate": {
          "url": "https://<REDACTED>"
        },
        "dependencies": {
          "all_cameras": true
        },
        "triggers": {
          "occupancy": false
        },
        "icon": "mdi:cctv"
      }
    ],
    "event_gallery": {
      "controls": {
        "thumbnails": {
          "show_details": true,
          "show_controls": true,
          "size": 75
        }
      }
    },
    "view": {
      "default": "live",
      "camera_select": "live"
    },
    "media_viewer": {
      "auto_play": "all",
      "transition_effect": "slide"
    },
    "image": {
      "mode": "camera"
    },
    "timeline": {
      "show_recordings": true,
      "controls": {
        "thumbnails": {
          "size": 100
        }
      }
    },
    "dimensions": {
      "aspect_ratio_mode": "dynamic"
    },
    "live": {
      "preload": true,
      "lazy_unload": "all",
      "auto_play": "all"
    }
  }
}

**Comment by dermotduffy** [comment]
Hmm, that version of the integration & card should work well together. Perhaps it's the older Frigate server version, can you try upgrading to v11:

https://github.com/blakeblackshear/frigate/releases/tag/v0.11.0-rc1

The pre-release card & integration that you're using both assume a bleeding edge Frigate server. Give it a try, and if it still doesn't work, I'll do a test using those exact versions ...

**Comment by ehosch** [comment]
Still no joy.  There has got to be something I'm missing.  Do I have to
have zones configured?

New card diags...

Card diagnostics. Please review for confidential information prior to
sharing
{
  "ha_version": "2022.8.6",
  "card_version": "4.0.0-rc.2",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "date": "2022-08-22T05:15:00.194Z",
  "frigate_version": {
    "92e3b33d5048b858ba32a3d2449f979c": "3.0.0-rc.3/0.11.0-37325c7"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-rc.2-HEAD+g771943c",
    "build_date": "Sun, 03 Jul 2022 02:25:09 GMT",
    "commit_date": "Fri, 1 Jul 2022 19:57:20 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "frigate-jsmpeg",
        "frigate": {
          "url": "https://<REDACTED>"
        },
        "dependencies": {
          "all_cameras": true
        },
        "triggers": {
          "occupancy": false
        },
        "icon": "mdi:cctv"
      }
    ],
    "event_gallery": {
      "controls": {
        "thumbnails": {
          "show_details": true,
          "show_controls": true,
          "size": 75
        }
      }
    },
    "view": {
      "default": "live",
      "camera_select": "live"
    },
    "media_viewer": {
      "auto_play": "all",
      "transition_effect": "slide"
    },
    "image": {
      "mode": "camera"
    },
    "timeline": {
      "show_recordings": true,
      "controls": {
        "thumbnails": {
          "size": 100
        }
      }
    },
    "dimensions": {
      "aspect_ratio_mode": "dynamic"
    },
    "live": {
      "preload": true,
      "lazy_unload": "all",
      "auto_play": "all"
    }
  }
}

**Comment by dermotduffy** [comment]
> Do I have to have zones configured?

No.

I'm out of ideas for tonight. With those versions, the thumbnail picture data should be _literally_ included in the event information that is being correctly fetched, so I'm not sure why it's not working for you. Let me think about it (this code changed a bunch, so I may be mis-remembering, I'll have to do a test run to verify ....). Stay tuned, in the mean time let me know if you figure it out.

**Comment by ehosch** [comment]
No worries, I'll get fresh eyes on it tomorrow too.  Great work BTW.
Awesome product all around.
FYI I removed the card and added back with defaults and still no
thumbnails...
Card diagnostics. Please review for confidential information prior to
sharing

{
  "ha_version": "2022.8.6",
  "card_version": "4.0.0-rc.2",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0
Safari/537.36",
  "date": "2022-08-22T05:32:00.145Z",
  "frigate_version": {
    "92e3b33d5048b858ba32a3d2449f979c": "3.0.0-rc.3/0.11.0-37325c7"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-rc.2-HEAD+g771943c",
    "build_date": "Sun, 03 Jul 2022 02:25:09 GMT",
    "commit_date": "Fri, 1 Jul 2022 19:57:20 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.doorbell"
      }
    ]
  }
}

**Comment by dermotduffy** [comment]
BTW: Can you use the visual card editor to change the thumbnails to be under/above the media (i.e. not left/right in a drawer), then use the developer tools (press F12 in Chrome), and select this icon:

![Screenshot from 2022-08-21 22-36-56](https://user-images.githubusercontent.com/1136829/185846843-4f3dbfa5-1664-43fd-81ab-f53e0eba2ba5.png)

... and click on a broken thumbnail.

Then tell me what the `src` attribute of the `img` element is. It should look something like this (if you're not familiar with devtools):

![Screenshot from 2022-08-21 22-38-05](https://user-images.githubusercontent.com/1136829/185846993-f3a1bd0b-c6f8-44b4-bc87-146c498034b1.png)

**Comment by dermotduffy** [comment]
Also tell me if you see anything interesting in your Javascript console (also F12 in Chrome) when you load the card with the broken thumbnails, i.e. an error messages show up?

**Comment by ehosch** [comment]
Thanks for the suggestions.  The src attribute is: "https://<REDACTED>/api/frigate/frigate/thumbnail/1661178226.57335-yfvqoz" and when I try to go to it directly I get 401: Unauthorized page.  I think there is an issue with either my NGINX proxy config, or the way Frigate is providing via api.  I am running my own NGINX proxy (I don't like using duckdns). I am also running Frigate in Docker and mapping the port 5050:5000 which would be a problem if ports are hardcoded in some source code.

**Comment by dermotduffy** [comment]
@ehosch That is a src attribute that was added in https://github.com/blakeblackshear/frigate-hass-integration/commit/f3afa88be68c0e65ad1858d2c54bf849daa57e45#diff-c0c9bfdb652d2f05cf484016f9d05d83d62418f56702111b9313f99f2d137a3dR866 , which is _after_ the [v3.0.0-rc.3](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v3.0.0-rc.3) build of the integration that you are running. Does not make sense.

Is it possible you built the integration from head yourself, or are otherwise not _actually_ running the `v3.0.0-rc.3` code?

Suggest removing the integration entirely, restarting HA to verify it's not there anymore, then specifically re-install ``v3.0.0-rc.3`  via HACS and try again.

**Comment by ehosch** [comment]
I guess the HACS install isn't clearing out the old version.  I tried removing and adding back with the same result. Can you tell me how to remove the files manually?  I have ssh access.

**Comment by ehosch** [comment]
Okay, I finally figured it out.  Just removing the Frigate Integration did not make a change.  I had to remove it, then upgrade via HACS, then re-add the integration.  All is well (sheesh!) finally.  Thank you for your assistance.  Once again, excellent product. Kudos!

**Comment by dermotduffy** [comment]
Fantastic, delighted you figured it out. Enjoy!
