### ISSUE TITLE
Menu buttons overlap with Android notification and buttons bar

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#817]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 4.0.0-rc.3

**Last working release (if known):**

**Browser and Operating System:** Android (companion app)

**Description of problem:**

The following screenshot explains better. Happens when in full screen, and more noticeable when in portrait mode.

![ha](https://user-images.githubusercontent.com/29582865/188486805-9bb75add-fda2-42a2-b0e4-a26cccab694e.jpg)

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

None.

**Comment by dermotduffy** [comment]
Is that different than prior versions? I'm not sure this is something I can control directly. At least on my Android devices, the Android system icons (top & bottom) auto-hide when in fullscreen mode and then re-appear if I touch near the edge of the screen (tested on a Pixel device).

**Comment by felipecrs** [comment]
For me, only the bottom bar (the three buttons) is hidden (unless I drag, as you mentioned). But the top bar is always there colliding with the menu bar of the card.

I suppose the card should not render on top of both the top and bottom bar, especially when in portrait mode.

Or, when you drag the top or bottom bar, the card should re-draw to ensure it's not overlapping in the new layout.

However, I understand that it may be very difficult to resolve. Let me check how the picture glance card works... one sec.

**Comment by felipecrs** [comment]
The same issue happens in picture glance:


https://user-images.githubusercontent.com/29582865/188494573-156cb2ce-09c8-4e06-83cc-b6e826a471ce.mp4



And no, this behavior is not different than older versions, as far as I remember.

**Comment by dermotduffy** [comment]
I don't think this is reasonably fixable by the card (or picture glance) as it can't know that the phone OS will overlay controls, nor where it will draw them, nor even when it will draw them. The card simply asks for fullscreen, and expects to get full (not partial) use of the screen. This is not an unreasonable expectation (which is probably why at least some Android devices only show such control overlays temporarily).

**Comment by felipecrs** [comment]
Right. I agree, this is not fixable by the card.

But it should be fixable by the companion app, since there are APIs made for handling with such things in Android. I also found a library in npm for React Native for controlling such behavior.

Anyway, thank you for your time.

**Comment by felipecrs** [comment]
Refs: https://github.com/home-assistant/android/issues/2876

**Comment by felipecrs** [comment]
@dermotduffy I believe the following CSS attributes can be used to prevent the card from displaying on top of the notch/cutout (this is what happens currently when it enters in full screen).

**Comment by felipecrs** [comment]
Also, I found the following:

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#:~:text=The%20browser%27s%20navigation%20interface%20will%20be%20hidden%20and%20the%20entire%20dimensions%20of%20the%20screen%20will%20be%20allocated%20to%20the%20display%20of%20the%20element.

I wonder if setting `navigationUI` to `hide` can help.

**Comment by felipecrs** [comment]
> Also, I found the following:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#:~:text=The%20browser%27s%20navigation%20interface%20will%20be%20hidden%20and%20the%20entire%20dimensions%20of%20the%20screen%20will%20be%20allocated%20to%20the%20display%20of%20the%20element.
> 
> I wonder if setting `navigationUI` to `hide` can help.

It seems that the issue was confirmed in the HA Android app, so I suggest not to spend time on evaluating this option.

> @dermotduffy I believe the following CSS attributes can be used to prevent the card from displaying on top of the notch/cutout (this is what happens currently when it enters in full screen).
> 
> https://www.w3.org/TR/css-round-display-1/#viewport-fit-descriptor

This can still be useful though, as even when using Chrome on Android the card displays on top of the cutout and that's not desirable. A simple fix would be to simply add the CSS attributes that prevent it from showing on top of the cutout. A more advanced fix would be for the card to calculate whether there are any custom element, or menus that would get displayed on top of the cutout in portrait or landscape mode, and hide it when it should. Probably not worth to invest the time on this option.

**Comment by felipecrs** [comment]
Ok, the [preview APK](https://github.com/home-assistant/android/issues/2876#issuecomment-1245796048) fixed the issue for me.

> I believe the following CSS attributes can be used to prevent the card from displaying on top of the notch/cutout

![photo_2022-09-13_15-40-13](https://user-images.githubusercontent.com/29582865/189984062-7ea7976e-f06a-48db-9187-27263fb945b2.jpg)

This is how it looks like. Totally manageable in my case, but it can be much worse depending on the device, I guess.

**Comment by felipecrs** [comment]
The new default behavior of the Android companion app is to **never** draw on top of the notch. So, I don't think we need to do anything here.

While browsing through Chrome, it still displays on top of the notch, but I don't think this is worth tinkering with.
