### ISSUE TITLE
image thumbnail's are empty

### ISSUE THREAD

**Issue by ttadam** [dermotduffy/frigate-hass-card#818]
**Release with the issue: v3.0.0**

**Browser and Operating System: chrome, windows 10, also in IOS HA app**

**Description of problem:**

Basicly the title.  There should be small images about the event, but only empty frames shows up. 
![frigatebug2](https://user-images.githubusercontent.com/6552445/189373500-851f6fda-e9e5-45ff-9025-08ae71a6c4dd.gif)

**Comment by dermotduffy** [comment]
Please update to the latest v4 version and the latest version of the integration, then test again. There were considerable changes to how thumbnails were fetched and you probably are using incompatible card and integration versions. The latest pre-release versions of both should resolve this issue.
