### ISSUE TITLE
Make the card "stackable"

### ISSUE THREAD

**Issue by ragenhe** [dermotduffy/frigate-hass-card#82]
I've added four cameras using the Frigate card.

All four stayed horizontal.

Would it be possible to make the card "stackable" so it could be 2 x 2?

Thank you!

**Comment by dermotduffy** [comment]
This is working as intended -- Lovelace manages card layout, not cards themselves. If your goal is a 2x2 "block" of Frigate cards, you'd do that by combining two [horizontal stacks](https://www.home-assistant.io/lovelace/horizontal-stack/) in a single [vertical stack](https://www.home-assistant.io/lovelace/vertical-stack/) -- should work just fine, try it out?

**Comment by ragenhe** [comment]
Thank you!

I'm going to spend some additional time with lovelace now!!
