### ISSUE TITLE
Allow recordings to be accessible via a button

### ISSUE THREAD

**Issue by bagobones** [dermotduffy/frigate-hass-card#822]
**Is your feature request related to a problem? Please describe.**
Clips and snapshots are available but not recordings.

**Describe the solution you'd like**
In the native frigate UI it is possible to view recordings on a per camera basis, would be nice to have this option on each camera in addition to using the HASS media browser.

**Comment by dermotduffy** [comment]
With the v4 card pre-release you can access recordings via the timeline view, example:

https://github.com/dermotduffy/frigate-hass-card/tree/release-4.0.0#single-camera-recordings

I'm currently working on improvements to this, but that's available for now at least. Let me know if this is what you're looking for.

**Comment by bagobones** [comment]
Looks good (updated to beta releases via HACS), does showing recording also depend on the frigate backend being a beta version or the main HA integration? Looks like by default show recordings is enabled but I am not seeing anything visualized.

Sound like this SHOULD do what I want but at the moment it doesn't appear to be working for me. I will try to read all the beta docs...

**Comment by bagobones** [comment]
Had to upgrade the backend to 0.11.0, the integration to 3.0.0 in addition to the 4.0.0 card

Looks like the basics are covered.. Now I REALLY need to find a coral device.

**Comment by dermotduffy** [comment]
I think there are still some improvements I can do here! Re-opening so I remember. There's also major rework for recordings going on, so I'll try to work this in ...

**Comment by dermotduffy** [comment]
#1 is because it shades in any hour that has recording of any length. I figured out a way to address this that will be in my timeline rework I'm working on now. 

#2 is a bug, mind opening a separate issue?

**Comment by bagobones** [comment]
I have opened a separate bug for the download error.

Look forward to the improvements on the timeline.. It is looking good so far.

If there is a separate place I should give general feedback on the timeline let me know. Selecting days / going back and forth could maybe be improved at the moment all I see is the ability to drag and zoom out. Having a date / time picker to jump to a specific day at 2pm would be nice for example when going further back in time weeks.

**Comment by dermotduffy** [comment]
Recordings will now be accessible via an optional button in  the next build, although it's still fairly limited until the 'infinite list' idea is implemented. I'll close this one for now, and  we can track that over at #835 .
