### ISSUE TITLE
Support multiple zones for a single camera

### ISSUE THREAD

**Issue by luzik** [dermotduffy/frigate-hass-card#823]
It would be awesome to be able to specify multiple zones and labels. Please consider adding such a feature.

My personal use case is to filter 2 zones out of 3. 3rd is public area and I want to filter it out.

**Comment by dermotduffy** [comment]
In the [v4 pre-release](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.3) you can configure dependent cameras. You could configure two different cameras in the card (which are really the same Frigate camera, just with each of the two zones) -- the configure each camera as a dependent of the other.

This would mean that whenever you view these cameras, it also shows you the events of the "other" camera.

Maybe this is roughly the effect you are looking for? [Benefit of this approach is also that it can show events for entirely different cameras, or even different Frigate servers]

**Comment by luzik** [comment]
I will check this out after new frigate release. Thanks for the information. But yeah ..it sounds rough. Allowing selecting multiple zones and labels in place for that, seems to be much more natural way of achieving this, without workarounds like this one

**Comment by dermotduffy** [comment]
> without workarounds like this one

Perhaps I don't understand your usecase enough, but the whole point of the dependent camera feature is actually to allow one zone to be dependent on another (e.g. you are viewing the live stream of a front door, and you also want events for a zone related to that camera). 

Anyway, give it a shot and lets discuss how we can make it better! Thanks.

**Comment by luzik** [comment]
Ok, this works, dependency is quite usable, because I have two cameras that share some zones.
But this for my issue is still some kind of workaround ..I have two same cameras to switch.

My exactly use case is that I have 3 zones -entrance, place for my car and street. As I want to record clips for all cars on the street, I want to filter it out from frigate-card events, so it would be awesome be able to use
```
cameras:
 - frigate:
   - zone:
     - entrace
     - car_place

```

Support for array in zone and label params would be more intuitive and straightforward
If it's not a way You see it, just close issue.

**Comment by dermotduffy** [comment]
I agree this is more intuitive for a case when it's a single camera, and will keep it open for future work.

It may not be trivial to implement due to the integration only supporting searching for one zone per camera, but I can find ways around this or fix the integration.

Thanks for the continued feedback @luzik !

**Comment by dermotduffy** [comment]
Other unrelated refactoring work made this feature significantly easier to implement. It will be in the next build.
