### ISSUE TITLE
Snapshot\Clip icons not loading

### ISSUE THREAD

**Issue by simonyel** [dermotduffy/frigate-hass-card#825]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
Integration - v3.0.0-rc.4
frontend - Frigate Card v.3.0.0
server - Frigate v0.11.0-C461C9E

**Last working release (if known):**

**Browser and Operating System:**
Windows 10 / Android 11&13

**Description of problem:**
All icons within the Frigate card representing snapshots and clips aren't loading. At the same time whenever any of my devices with HA App installed (or browsers) navigate to Frigate Card in my lovelace, generate http access errors i.e:

Login attempt or request with invalid authentication from 192.168.xx.xx (192.168.13.10). Requested URL: '/api/frigate/frigate/thumbnail/1663086023.849525-n1nnjy'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
@simonyel If you use the  pre-release Frigate backend, you need to match it with the pre-release integration and pre-release  card. 

Try: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.3

**Comment by dermotduffy** [comment]
Very confident this is a version mismatch issue, please re-open if you still can't get it to work right!

PS: The official release of the new version of Frigate, the Integration and the Card should be fairly soon, after which this issue will be fully resolved.
