### ISSUE TITLE
Cannot download recordings

### ISSUE THREAD

**Issue by bagobones** [dermotduffy/frigate-hass-card#826]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
v4.0.0-rc.3
**Last working release (if known):**
N/A
**Browser and Operating System:**
Chrome Windows 11 

**Description of problem:**

The download button returns "Could not extract Frigate event id from media" if you are viewing a recording not an event.
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Will be in the next build (will also require a new integration build).
