### ISSUE TITLE
Allow a way to jump (not pan) back / forward in time

### ISSUE THREAD

**Issue by bagobones** [dermotduffy/frigate-hass-card#827]
**Is your feature request related to a problem? Please describe.**
At the moment in 4.0.0-rc.3 it appears that only zooming and scrolling are available

**Describe the solution you'd like**
I would like something like controls like the Home Assistant Energy dashboard (Today Day/Week/Month/Year) buttons

OR

A simple calendar date picker like the Home Assistant Log book to jump to a day and time.

Sometimes you find something changed or missing and you where not looking at the camera for days or there was a report of something happing in the past it would be nice to quickly JUMP through the days.

**Comment by dermotduffy** [comment]
The new v4.1.0 codebase (not yet released) already supports the described behavior for events (or very similar). I'd like to implement similar for the timeline view, so keeping this open for that.

**Comment by bagobones** [comment]
Looking forward to it.

Already running frigate 0.12 beta so many new features.
