### ISSUE TITLE
Timeline view should use vertical space better

### ISSUE THREAD

**Issue by bagobones** [dermotduffy/frigate-hass-card#828]
**Is your feature request related to a problem? Please describe.**
When using the Frigate menu option of over lay it covers part of the screen which is fine for camera feeds but it is very obstructive in timeline view.
Timeline view also does not use vertical space very well.

**Describe the solution you'd like**
Maybe timeline view should auto offset it self from the menu always when the menu is set to overlay? The name of the first camera in the top right is always covered by default in overlay mode.

Timeline view should maybe attempt to stretch to the whole  screen size available? It seems to do so when zooming out and more objects are in the timeline, but maybe it should just default to using the virtical space?

Outside menu mode avoids the overlay issue but on mobile uses up extra screen space.

**Comment by dermotduffy** [comment]
Would you mind attaching a screenshot that shows the kind of thing you'd like to look different, and I can use that as a reference?

**Comment by bagobones** [comment]
For the Timeline view only overlay mode should shift the timeline down so it isn't covering it
![Overlay](https://user-images.githubusercontent.com/1587701/190548998-12b024fe-a418-4356-a361-b6cb289968ae.png)
so that all elements of the Timeline are visible like in outside mode
![Outside](https://user-images.githubusercontent.com/1587701/190549006-e22a427e-54fd-429d-b842-e5bf9809b28f.png)

The reason being that when looking at a video overlay is the only UI clickable item, but the Timeline has elements to read and click on, so it would make sense that the timeline is aware of the overlay position and just shift it self down or up as needed to not be covered.

As far as vertical space goes I am using the hass card on View in Panel (1 card) mode.  On mobile and desktop this is great as video fills as much screen as possible.

The Timeline view not as tall as a normal video, at least if there are not many events / depending on zoom level

The area in green illistrates the amount of screen a 16:9 video takes up vertically vs the Timeline.. Keeping the timeline virtical space as tall as possible (as tall as a 16:9 video or the screen) would allow the slide out on the right to show more things.
![Tall](https://user-images.githubusercontent.com/1587701/190550230-a8767454-cc80-4cc7-8032-1410694efc16.png)

**Comment by bagobones** [comment]
FYI just wanted to comment and say that your HASS card is amazing and the timeline is really what pushed me to take Frigate seriously . 

Great work..

I hope my suggestions are useful to improve on an already great start.
