### ISSUE TITLE
Unable to load camera's snapshot

### ISSUE THREAD

**Issue by weitheng** [dermotduffy/frigate-hass-card#844]
Try to make the card show a static image of the camera's snapshot, but got this error: 
```
The image could not be loaded. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "mode": "url",
  "url": "https://admin:XXXX@i192.168.XX.XX/cgi-bin/snapshot.cgi?1",
  "refresh_seconds": 1
}
```
What I intend to do is make the card show a static image of the camera's snapshot before the live view is ready to view (usually takes a longer time to load under low internet speed). It seems that the card is unable to accept the url without the file type, even though I have checked it with multiple browsers and it works.
**Checklist:**

- [x] I updated to the latest version available
- [X] I cleared the cache of my browser

**Comment by dermotduffy** [comment]
> It seems that the card is unable to accept the url without the file type, even though I have checked it with multiple browsers and it works.

This error is shown if the browser fails to load the provided URL. Are you sure the URL works exactly as written in the card config, in another browser window? 

> It seems that the card is unable to accept the url without the file type

Can you clarify what you mean by `file type` here?

> What I intend to do is make the card show a static image of the camera's snapshot before the live view is ready to view 

This is actually a native feature offered by the card, try the `show_image_during_load` option. No need to set the URL yourself, the card will try to get it from HA as long as you are setting a camera entity. If you are using the visual editor, it's the option near the bottom under `Live`:

![show_image](https://user-images.githubusercontent.com/1136829/193048915-c20f2094-028a-4aae-96b2-fec59df1ceb6.png)

**Comment by weitheng** [comment]
> Are you sure the URL works exactly as written in the card config, in another browser window?
Yes, It works on multiple works using the same exact url that is in the config.

> Can you clarify what you mean by `file type` here?
By file type, I mean the url has to end with `.jpg` etc.

> This is actually a native feature offered by the card, try the `show_image_during_load` option. No need to set the URL yourself, the card will try to get it from HA as long as you are setting a camera entity. If you are using the visual editor, it's the option near the bottom under `Live`:
> 
> ![show_image](https://user-images.githubusercontent.com/1136829/193048915-c20f2094-028a-4aae-96b2-fec59df1ceb6.png)
Yeap, I am aware of this feature, but as I am unsure if the static image is working, I have temporarily put it to show the static image only just for testing. 

Have you managed to test it with url similar to the one I have above, that doesn't end with `.jpg`, `.png` etc.

**Comment by dermotduffy** [comment]
> Yes, It works on multiple works using the same exact url that is in the config.

Ah. I think I know what's happening. Your browser is rejecting the image URL for security reasons, as this is cross-origin image request and it will not allow you to pass credentials when it is sourced from a script. If you take that same URL, and put it into a Home Assistant Picture Glance card -- I bet you will see exactly the same behavior.

There is no way around this [unless you own and can configure the webserver, which you ~cannot do when it's a camera].

I think the right thing is for me to add a README entry explaining this limitation.

> Yeap, I am aware of this feature, but as I am unsure if the static image is working, I have temporarily put it to show the static image only just for testing.

Does it load instantly? It's working :-) You could also use developer tools to inspect the element and verify it's a `<img>` tag.

**Comment by dermotduffy** [comment]
I've updated the README, and I don't think there's anything left to do here (as this is effectively a browser restriction). Please re-open if you see otherwise. Thank you!
