### ISSUE TITLE
Forbidden media source identifier

### ISSUE THREAD

**Issue by vmannoor** [dermotduffy/frigate-hass-card#845]
Card fails show the camera live view with following error:

```
Failed to receive response from Home Assistant for request. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////entrance_camera//",
    "id": 55
  },
  "response": {
    "code": "unknown_error",
    "message": "Forbidden media source identifier: frigate/event-search/clips////entrance_camera//"
  }
}
```
I've frigate nvr running as as a docker container and frigate hass integration set up and running.

Both google chrome and companion app show the same message.

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Comment by dermotduffy** [comment]
Hmm. Are you sure you have the integration working correctly? Can you view Frigate media from the sidebar of Home Assistant (ignoring the card for now):

![media](https://user-images.githubusercontent.com/1136829/193172154-da788819-842d-4a93-b477-da09219b1ce6.png)

Please check your Home Assistant log, there'll probably be an exception or error shown?

**Comment by dermotduffy** [comment]
New theory, you have this option disabled:

![option](https://user-images.githubusercontent.com/1136829/193177635-1c5d6709-fe2b-499a-95e3-7cf7d72b7a37.png)

The card requires this to be enabled in order to fetch media. If you don't want to fetch media and just want to see live events, you could disable the media thumbnails in the controls section of the live options.

**Comment by vmannoor** [comment]
I've the media browser option turned on:

![image](https://user-images.githubusercontent.com/65083692/193194908-caf5b79d-9e78-4a19-91a9-71c0c68cf4fd.png)

And I can access my media files from the media library:
![image](https://user-images.githubusercontent.com/65083692/193195006-8808cb51-e808-4f73-960c-03167aedb9b5.png)

**Comment by dermotduffy** [comment]
Anything of note in your HA logs?

**Comment by dermotduffy** [comment]
Please also hold down the Frigate menu button in the card and paste the diagnostics that show up.

**Comment by vmannoor** [comment]
HA log entry:
`[140278097898432] Error handling message: Forbidden media source identifier: frigate/event-search/clips////entrance_camera// (unknown_error)
`

Card diagnostics:
```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2022.9.7",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "date": "2022-09-30T17:26:49.674Z",
  "frigate_version": {
    "e6bf47291c1aa9ec34dcf61c14900194": "3.0.0/0.11.0-3846a13"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.entrance_camera",
        "live_provider": "auto"
      }
    ],
    "view": {
      "update_force": true,
      "update_cycle_camera": false
    }
  }
}
```

**Comment by dermotduffy** [comment]
@rjlee reports the same issue, pulling them in here. Can you confirm you have [this setting enabled](https://github.com/dermotduffy/frigate-hass-card/issues/845#issuecomment-1263033781).

@vmannoor How can see actual media in your HA media browser, right? (i.e. not just the 'Clips' / 'Recordings' folders, but actually get the snapshots & clips)

**Comment by rjlee** [comment]
@dermotduffy - yes the setting is enabled.

Card diagnostics:

```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2022.9.7",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "date": "2022-10-01T14:58:32.793Z",
  "frigate_version": {
    "019e80ddc49f8f613bd153207ddb866e": "3.0.0/0.11.0-3846a13"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.lounge_camera"
      }
    ]
  }
}
```

**Comment by dermotduffy** [comment]
Are either of you overriding the client_id value in your `frigate.yml` configuration file ? [The frigate backend configuration file].

**Comment by rjlee** [comment]
@dermotduffy in my case, yes I am (required for running multiple instances).

Checking with vi, no python stacktraces, just a number of these:

,,,
2022-10-01 14:58:10.211 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139776833861568] Error handling message: Forbidden media source identifier: frigate/event-search/clips////lounge// (unknown_error)
```

**Comment by dermotduffy** [comment]
@rjlee In your case at least I think this is the issue. You are using a custom client_id but not telling the card about it. Try this setting to that it matches your backend configuration value for the `client_id` flag.

![cleint_id](https://user-images.githubusercontent.com/1136829/193416016-81aac5d0-23fc-4514-83de-bd8e88419a99.png)

**Comment by rjlee** [comment]
Confirmed, that fixes my issue thanks, sorry should have RTFM.

**Comment by dermotduffy** [comment]
@rjlee Fantastic, no problem at all.

@vmannoor Any chance this is the same issue for you?

**Comment by vmannoor** [comment]
Yes, I too had a custom client id. Thank you such for your help.

**Comment by dermotduffy** [comment]
Fantastic! I'll add this to the troubleshooting section of the README for future users who may have the same issue.
