### ISSUE TITLE
Hide side-drawer - is it possible?

### ISSUE THREAD

**Issue by pejotigrek** [dermotduffy/frigate-hass-card#846]
**Is your feature request related to a problem? Please describe.**
while side-drawer is useful on bigger thumbnails, I've got HomeAssistant's dashboard with small camera previews and sometimes accidentaly open the side-drawer which covers whole preview. I just want to hide it but couldn't find any option for that

**Describe the solution you'd like**
it would be great to have an option to enable/disable this on demand

**Describe alternatives you've considered**
tried to hide it with CSS styling, but without luck - probably I can't address the selector correctly

**Additional context**
just to be clear - this is the element I'm talking about:
![image](https://user-images.githubusercontent.com/10796588/193156312-1731f20d-794c-447d-a42e-28f479ac54e2.png)

**Comment by dermotduffy** [comment]
Yes this is possible:

![thumbnails](https://user-images.githubusercontent.com/1136829/193171692-db04231b-3839-4ccb-b630-db6eb4780dd6.png)

You may want to also hide it in the media viewer, if you don't want it at all (the control for that is in a similar place under the media view item in the editor).

See also: [Related documentation](https://github.com/dermotduffy/frigate-hass-card#live-controls-thumbnails)

**Comment by pejotigrek** [comment]
> See also: [Related documentation](https://github.com/dermotduffy/frigate-hass-card#live-controls-thumbnails)

great, thank you! seems I'm blind - I thought I've tried all switches [I'm using pure yaml mode] but accidentally skipped this one. sorry for bothering!
