### ISSUE TITLE
A new menu style `hover-card` 

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A new menu style called `hover-all` that would function exactly as `hover`, except that it would activate while hovering (or tapping, while in touch-screen) in any position of the card and not just through the menu position. Similar to how the built-in player works:

![chrome_rENze6rLB3](https://user-images.githubusercontent.com/29582865/193465470-ab793d3e-dbf2-458d-9aa8-7dfb94553d05.gif)

**Describe alternatives you've considered**
Switching between `hover` and `overlay` depending on some conditions.

**Additional context**
PS: `hover-all` may not be the best name.

What do you think about this feature request? Perhaps you have considered it before, I would like to hear opinion.

**Comment by dermotduffy** [comment]
> Perhaps you have considered it before, I would like to hear opinion.

This is actually the behavior I previously had implemented as `hover`, I changed it because it was a bit annoying and consumed card space when you were interacting with other things in the card (e.g. gallery). Adding a separate menu mode makes sense.

Maybe `hover-card` ?

**Comment by felipecrs** [comment]
> This is actually the behavior I previously had implemented as hover, I changed it because it was a bit annoying and consumed card space when you were interacting with other things in the card (e.g. gallery)

Got it.

> Maybe hover-card ?

Yeah, much better than `hover-all` lol
