### ISSUE TITLE
Is it possible to prevent the built-in player controls from appearing if not hovered or tapped?

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#856]
For example, if I refresh my page, this is what happens:

https://user-images.githubusercontent.com/29582865/193465677-1eccacb3-2031-42c3-a3b4-ddd981a594d3.mp4

As you can see, as soon as the live stream is loaded and the stream starts, the player controls are shown for some moments.

The downside of it is that it kind of breaks the otherwise seamlessly transition between "use still images while loading" and the actual live stream.

This is more a question than a feature request or a bug report, since I don't know whether this is possible or not.

**Comment by felipecrs** [comment]
Hey @dermotduffy, thanks a lot for this. But for some reason, I still observe the same behavior as before:

https://user-images.githubusercontent.com/29582865/195103965-63c2ae43-6701-4040-b2b0-c5e3adbebdbc.mp4

**Comment by dermotduffy** [comment]
@felipecrs On the old version, do the controls show up for longer time wise? Right now it's hiding them for `2s` (fairly arbitrary value), perhaps it needs to be longer to be effective.

**Comment by felipecrs** [comment]
I increased to 5 seconds, and I still don't quite get the expected result. My theory is that the media control UIs are always automatically shown once they are unhidden.

**Comment by dermotduffy** [comment]
> I increased to 5 seconds, and I still don't quite get the expected result. My theory is that the media controls are always automatically shown once they are unhidden.

But it works for me! (TM)

Mind including your card config and I'll try and exact reproduction?

**Comment by dermotduffy** [comment]
https://github.com/dermotduffy/frigate-hass-card/pull/867

**Comment by dermotduffy** [comment]
@felipecrs OK, I entirely neglected to add the controls hiding to the native webrtc player which I  think you are using. Oops. Fixed now. Try again? [It works for me on your instance if I override with local source, so I'm hopeful!]

**Comment by felipecrs** [comment]
It works surprisingly well now, much cleaner!!!
