### ISSUE TITLE
Failed to receive response from Home Assistant for request

### ISSUE THREAD

**Issue by harambe88** [dermotduffy/frigate-hass-card#860]
I'm getting an error message "Failed to receive response from Home Assistant for request." and don't get live view from my cameras.

WebRTC is showing live view.

This configuration used to work before Frigate NVR 0.11.0

--------------------------------------------------------------

Complete error message:

Failed to receive response from Home Assistant for request. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////7Links-Cam1//",
    "id": 78
  },
  "response": {
    "code": "unknown_error",
    "message": "Forbidden media source identifier: frigate/event-search/clips////7Links-Cam1//"
  }
}

--------------------------------------------------------------

frigate.yml:

mqtt: 
  host: 192.168.xx.xx
  user: xxxx
  password: xxxx
              
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  7Links-Cam1:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxx@192.168.88.112:80/videoMain
          roles:
            - detect
            - record
            #- rtmp
            
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
            
    detect:
      width: 360
      height: 240
      fps: 5
      max_disappeared: 15

    objects:
      track:
        - person
        #- bicycle
        #- dog
        #- cat
        
    motion:
      threshold: 15

    record: 
      enabled: True 
      retain:
        days: 0
      events:
        retain:
          default: 20
          mode: motion
          objects:
            person: 20
          
    #live:
      #height: 360
      #quality: 8
      #preload: true

    snapshots:
      enabled: true
      timestamp: False
      bounding_box: false
      crop: false
      #height: 175
      retain:
        default: 20
        objects:
          person: 20

--------------------------------------------------------------

**Comment by dermotduffy** [comment]
@harambe88 

* Can you hold down your Frigate menu button for a few seconds and paste the diagnostics that show up?
* After you get the above message, can you check your `home-assistant.log` file and see if you see exceptions from Frigate?

**Comment by dermotduffy** [comment]
Please re-open with the requested information if this is still an issue. Thanks!

**Comment by harambe88** [comment]
Sorry for late response. I needed to restore a previous version which is running fine now. I haven't installed Frigate NVR 0.11.0 so far. If problem comes back I'll catch up with you.
