### ISSUE TITLE
Frigate NVR proxy supported?

### ISSUE THREAD

**Issue by jirimissbach** [dermotduffy/frigate-hass-card#87]
Hello, great card, love it!  I'm running frigate on another server than the HA with this card.  Both servers are in the same network.

All works fine, including the media browser on the HA where the frigate-hass-card is, however, I'm having a problem displaying the Clips Gallery / Snapshots gallery using this card.  It always displays "No CLips" / "No galery". Live view works fine.

I'm not sure, based on the documentation, whether this is supposed to work? Can you advise, please? I can provide more details from my environment but I have tested the latest HA/latest Frigate plugins.

Thanks

**Comment by dermotduffy** [comment]
Glad you're enjoying the card!

To confirm: You have a single HA instance, and a single Frigate server running on a different machine. You have the Frigate integration working correctly in HA, including the media browser. And your question is whether or not the card just work and show media in this case?

If I understand you correctly => then absolutely this should work. In fact, the card uses the very same HA APIs as the media browser does. 

If it's not working, here is a theory:
 - The card does not know the correct name of your camera in Frigate. With the currently released version, it guesses based on the entity name but that may well be incorrect. In this case, you should set the `frigate_camera_name` ([docs](https://github.com/dermotduffy/frigate-hass-card#optional)) option in the card to the correct value. (I actually improved this code a lot yesterday, but it hasn't been released yet -- the "guessing" is now significantly more accurate, but setting the configuration option may help for now)
 - The other possibility is if you're using a non-standard client-id in your Frigate server, you'd need to specifically set that in the options too (see same docs above). This is only usually the case if you're running multiple Frigate servers (and `frigate_client_id` tells Home Assistant which one you want the card to talk to).

Good luck!

**Comment by jirimissbach** [comment]
Thank you,
it is all as you described.  I had the client_ID set correctly (otherwise the card was complaining about missing ID) but I have missed the part around the frigate_camera_name in the documentation. After setting this ti the exact name in frigate.yml, all is working properly as expected. I have the camera names as a single world so was not thinking about this being a problem. My bad.


Thanks, for the detailed explanation, I'll test this further when the updated version is released

**Comment by dermotduffy** [comment]
Excellent! I'll close out this bug. FWIW: I did a pre-release yesterday of [v1.1.0](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v1.1.0), so you could try updating to that, removing your `frigate_camera_name` and it will probably  work correctly as long as you have a Frigate camera entity selected.
