### ISSUE TITLE
Ability to enlarge video (not full-screen)

### ISSUE THREAD

**Issue by chelming** [dermotduffy/frigate-hass-card#877]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I'm trying to watch for my kids' bus but my only option to make the video larger is to make it full screen. I'd like the video to fill the browser tab so I can still do other things on my screen.

**Describe the solution you'd like**
Instead of pausing the video when clicked, I'd like it to switch to a "modal" view that fills the browser tab, similar to the action that happens when you click on a **Picture Entity Card.**

Alternatively, a button just to "zoom" the video to fill the tab.

**Describe alternatives you've considered**
Using "Ctrl + Plus" to zoom in.

**Comment by dermotduffy** [comment]
Suggestion for right now:

* Add a separate dashboard to your Lovelace display in `panel` mode, this will cause the card fill the whole tab. You could also configure a tap action on your regular card to navigate to this new dashboard to show it `full tab`.

The feature request is valid, so keeping this open for consideration. Thanks for the feedback!

**Comment by chelming** [comment]
great workaround with the panel mode. thanks!

**Comment by dermotduffy** [comment]
Added a new button to expand the card on the lovelace dashboard. Will be in the next build.
