### ISSUE TITLE
Thumbnails not loading 

### ISSUE THREAD

**Issue by primski** [dermotduffy/frigate-hass-card#880]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```
styles.ts:370 
       Uncaught (in promise) TypeError: Failed to fetch
    at I (styles.ts:370:1)
    at Object.fetchWithAuth (styles.ts:370:1)
    at frigate-hass-card.js?hacstag=394082552400:165:70942
    at new Promise (<anonymous>)
    at frigate-hass-card.js?hacstag=394082552400:165:70917
    at jy.t (frigate-hass-card.js?hacstag=394082552400:165:71125)
    at jy.run (frigate-hass-card.js?hacstag=394082552400:165:70114)
    at jy.performTask (frigate-hass-card.js?hacstag=394082552400:165:69778)
    at jy.hostUpdated (frigate-hass-card.js?hacstag=394082552400:165:69656)
    at frigate-hass-card.js?hacstag=394082552400:11:5253
```

Where it is trying to connect and how do i give it correct URL ?

**Additional information:**

Hello sir,

Ive set it all up but thumbnails aren't loading ... not sure why. Frigate is up and running ,live view works, if i click media it will also load ... just thumbnails won't load.

what can i check?

many thanks

adding to favourites also doesn't work
log entry:

home-assistant   | 2022-10-19 09:49:53.402 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://myfrigateurl/api/events/1666100393.412405-1d1yk7/retain: 405, message='METHOD NOT ALLOWED', url=URL('https://myfrigateurl/api/events/1666100393.412405-1d1yk7/retain')

my URL is https:// and not http so i'm not sure where it's getting this from?

I've removed the integration from HACS and from Settings -> Devices&Information and reinstalled and still doesn't work.

**Comment by primski** [comment]
well that's a shame

**Comment by primski** [comment]
I have this:

3.0.0/0.11.1-2eada21
by Frigate

**Comment by primski** [comment]
default settings dont work

**Comment by primski** [comment]
wait ... it works now but only for newly generated clips ... not the existing ones. good enough for me, thanks!

**Comment by skynet01** [comment]
I think it's cause of the caching? It happens to me too from time to time, I just pull down inn the app or shift+ reload the page and they usually all populate. But yes seems a bit annoying :)

**Comment by dermotduffy** [comment]
[Bug sweep] Sounds like this was resolved to ~satisfaction, so closing for now.
