### ISSUE TITLE
Media player icons are no longer automatically updated

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#881]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

4.1.0

**Last working release (if known):**

It was working before, I'm pretty sure. I just don't remember when, because of:

- https://github.com/home-assistant/core/issues/79494

**Browser and Operating System:**

N/A

**Description of problem:**

Continuing the title... I have to change to another camera before the icon gets updated.

**Additional information:**

https://user-images.githubusercontent.com/29582865/196823987-e043f199-901c-4c90-9d1c-b2c68f35dd8b.mp4

**Comment by felipecrs** [comment]
Just to update that I tested with the latest sources of 4.1.0 and this seems to still occur.

**Comment by felipecrs** [comment]
Thanks a lot! I verified here that it works.

This was the last issue I had (so far) with the 4.1.0 codebase.

With this issue ironed out I'd say that 4.1.0 looks pretty much stable.

Maybe you could consider releasing some beta/rc version so more people get to test it before the final release as well.

**Comment by felipecrs** [comment]
Oh, and BTW, if it were me, I'd call the new version 5.0.0 instead of 4.1.0. There are so many great changes after all!

**Comment by dermotduffy** [comment]
> Maybe you could consider releasing some beta/rc version so more people get to test it before the final release as well.

I'd like to complete everything on the [4.1 milestone](https://github.com/dermotduffy/frigate-hass-card/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.1) and then do the release, or at least make an explicit decision to punt them.

> Oh, and BTW, if it were me, I'd call the new version 5.0.0 instead of 4.1.0. There are so many great changes after all!

Yup! That's exactly my plan, since there's also backwards incompatible changes. I'll swap everything from "4.1.0" to "5.0.0" when it's release time.
