### ISSUE TITLE
View Clips gallery should remember previous scroll position when exiting / entering the view.

### ISSUE THREAD

**Issue by spacebares** [dermotduffy/frigate-hass-card#885]
_Current behavior on small browser window / mobile device:_
1. Open up a camera's Clip gallery that contains a large number of items that you must scroll, and click to view one. Try the one at the most bottom of the list.
2. Now go back to clip gallery, you have to start at the top again, without no visual aid showing what clip you clicked on.

_New behavior:_
1. Open up a camera's Clip gallery that contains a large number of items that you must scroll, and click to view one. Try the one at the most bottom of the list.
2. Now go back to clip gallery, the clip you have previously selected is highlighted, and scroll-to-center'ed for you.

This behavior already exists for "Media Player". Clicking on a clip in Clip Gallery with any of "Media player's" thumbnail options enabled highlights the clip and scrolls it for you, it would be great to see this behavior also implemented into Clip Gallery.

**Comment by dermotduffy** [comment]
**Clarification**: Should it remember the scroll position specifically, or just make sure the selected item (if present in the gallery -- which it make not be!) is selected? I think it's more about the selection that the scrolling, per se?

When the gallery is loaded, it fetches the last 50 items (roughly, it's more complicated!). What should happen if you had previously drilled down (e.g. Month -> Day -> Person) in the gallery, then viewed one of those clips? Would you expect the gallery to subsequently show you the same 'drilldown folder' you were previously looking at, or start from the 'top' of the folder hierarchy and just select the media if it happens to still be in the most recent?

> This behavior already exists for "Media Player". Clicking on a clip in Clip Gallery with any of "Media player's" thumbnail options enabled highlights the clip and scrolls it for you, it would be great to see this behavior also implemented into Clip Gallery.

I don't quite follow what you mean here, can you give me a screenshot or something to illustrate? (If I understood correctly above, it's fine!)

**Comment by spacebares** [comment]
In the following video i have the Clips Gallery open _(pretend its a big list of say 50 items)_ :
- scroll down to the last card and select it to view the video
- after viewing the video i click back to the Clip Gallery, i have to scroll and find the item again.
https://user-images.githubusercontent.com/57186372/198859419-982b482e-ae21-4197-8ab5-63825621cb4e.mp4

In this video it shows that auto select & scroll behavior is already implemented for sidebar clips:
https://user-images.githubusercontent.com/57186372/198859528-5f5c34f0-4b32-4c2e-8719-e15998ae2d7b.mp4


I feel like it would be nice to have this behavior for the Clips Gallery menu too.

**Comment by dermotduffy** [comment]
[Finally get around to this]

Maybe there's a choice here:

- Implement as described. When you click to go to the events gallery in the menu, it remembers the previous query and positions the view where you were. This has the disadvantage (IMO) that it does not necessarily show up the fresh events that just happened, i.e. it's not a clean fresh query and may leave you in the "middle" of a load of old events.
- Add a new button that renders on top of the media (e.g. above the next or previous chevrons) that when clicked returns to the gallery with that same media centered. And in _this_ case, it would scroll to the selected item.
- Maybe there are other ideas ...

@spacebares What do you think?
@felipecrs may also have an opinion.

**Comment by felipecrs** [comment]
How about a mix of option 1 and 2?

Instead of rendering yet another button, if clicking the media gallery button WHEN the media is already visible, it shows the media gallery with the media highlighted (or as you suggested in option 2).

Wherever other situation, like when in the media gallery itself, clicking its button would return to a fresh view.

**Comment by dermotduffy** [comment]
Good idea! Done.
