### ISSUE TITLE
[Feature QOL] Double tapping some views will auto fullscreen.

### ISSUE THREAD

**Issue by spacebares** [dermotduffy/frigate-hass-card#888]
QOL Ease of use. Would help out alot of cards that have menu disabled. As currently they need the fullscreen button shown to have this functionality.

**Comment by dermotduffy** [comment]
This should already work via a card-wide action -- [see this example](https://github.com/dermotduffy/frigate-hass-card#adding-card-wide-actions), or let me know if you mean something else.

**Comment by spacebares** [comment]
https://github.com/dermotduffy/frigate-hass-card#triggering-card-actions
