### ISSUE TITLE
Can't download clips not associated with events

### ISSUE THREAD

**Issue by pjennings** [dermotduffy/frigate-hass-card#889]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
v4.0.0

**Last working release (if known):**
NA

**Browser and Operating System:**
Firefox 106.0.3/MacOS Big Sur
107.0.5304.87/MacOS Big Sur

**Description of problem:**
I have Frigate set for 24/7 recording. When I click on the timeline view, I get a clip in the media player centered at the time that I clicked. If I click the download button on that clip, I get the following message:

Could not extract Frigate event id from media. Check troubleshooting.

I would like to be able to download the clip as shown in the media player.

**Comment by dermotduffy** [comment]
This is already fixed in https://github.com/dermotduffy/frigate-hass-card/pull/852 and will be in the next build.
