### ISSUE TITLE
Mutliple zones

### ISSUE THREAD

**Issue by dpomnean** [dermotduffy/frigate-hass-card#89]
I was wondering if the card supports multiple zones? I currently have two zones in my front yard, 'driveway' and 'frontyard'. It seems like I can specify one or the other but could not figure out how to add multiples. Is this supported? If it is, I was not able to determine it from the readme. Love the card by the way!

**Comment by dermotduffy** [comment]
Glad you're enjoying the card!

Yes, right now, the card only supports a single camera and _specifying_ a single zone. If you just specify _no_ zone for a given camera, you should get the events for all zones for that camera. If you specify (a single)  zone, it'll only show events for that zone.

Does that work for your usecase?

**Comment by dpomnean** [comment]
@dermotduffy Ah I see, yeah that makes sense. I think there will be a couple events every now and then that don't fall into that the two zones but I think this will be fine not setting the zone. Thanks for the quick reply!
