### ISSUE TITLE
Options around handling of offline cameras

### ISSUE THREAD

**Issue by nibagit** [dermotduffy/frigate-hass-card#891]
Options around handling of offline cameras, we turn off inside of the house cameras when we are at our home, however this means we either have cameras with an old time stamp (which one might not notice) and/or an blank camera. It would be great if there is some way to either have a 1. standard image indicating status 2. last camera image with an overlay status 3. have the cameras not appear in the list....currently using a switch to turn off power to camera, future might use API to switch off (no change to feature request) or use it to switch off recording (feature to state NOT RECORDING in an overlay). Anyways thank you for creating this card it works great as-is already!!!

**Comment by dermotduffy** [comment]
Thanks for the request. Does Home Assistant itself notice that the camera is offline? i.e. does the camera state change to `unavailable`? I'm guessing not, because otherwise I think the card would throw an error when you try to look at the camera.

Reason I ask: Unless Home Assistant knows the camera is offline, there's no way the card can do anything different.

**Comment by nibagit** [comment]
HA would only know that the zwave device (switch) is off that powers the camera, actually no error in the frigate or the card nor an unavailable messafe I have seen two states either just blank OR solid green (most common) OR a picture from the last time it was connected (not sure how I got that as I have been unable to reproduce it).  Current "work around" is that I have both cameras listed as the last ones, so they don't show up directly.  Guess having some way to make the camera conditional in HA either through a device tracker OR through the state of the switch would be an option, maybe?

**Comment by felipecrs** [comment]
The Frigate Hass Card has already a nice handler for camera entities in unavailable states, now the only pending thing is to make the Frigate integration turn cameras into unavailable when they stop sending frames to ffmpeg:

- https://github.com/blakeblackshear/frigate-hass-integration/issues/406

I would suggest closing this issue in favor of the one above.

**Comment by dermotduffy** [comment]
Agree -- it makes much more sense to implement this on the integration side (and then it will "just work" in the card). Closing this for now and we can track progress on the other bug. Thanks!
