### ISSUE TITLE
Large amount of clips causes the card to error

### ISSUE THREAD

**Issue by austindetzel** [dermotduffy/frigate-hass-card#897]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
3.0.0
**Last working release (if known):**
Unknown (Sorry)
**Browser and Operating System:**
Chrome, Home Assistant, Windows, Edge, and Others

**Description of problem:**

I have run through a lot of troubleshooting to try to help out. I have narrowed it down to either a large amount of clips and/or their side. Theyre linked so im thinking its the size. I have about 400GB of Clips and over 8TB of recordings so loading can be slow. The card steams fine but will crash with this error after a few seconds.

`{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////Living_Room//",
    "id": 434
  },
  "response": {
    "code": "unknown_error",
    "message": "Unknown error"
  }
}`

This happens for all of my cameras on frigate but not all at the same time (usually within a few seconds though)

**Javascript errors shown in the web inspector (if applicable):**
(I have one camera offline right now, Its a blizzard and I cannot get to it to reboot it, I belive the errors are caused by this not the described issue)

`
 FRIGATE-HASS-CARD  Version 4.0.0 
26/hacs:1 Uncaught (in promise) DOMException: The play() request was interrupted because the media was removed from the document. https://goo.gl/LdLk22
/api/hls/c0876bfc6b70aa89a838da588816d4f55b6428200358af0b60ef5d35c4f6db47/master_playlist.m3u8:1          Failed to load resource: the server responded with a status of 504 ()
master_playlist.m3u8:1          Failed t`

**Additional information:**

This happens across all platforms but more often on phones through the home assistant app. Attached is a screenshot from the app, its on 4 phones all doing the same thing.

![Screenshot_20221120-112751](https://user-images.githubusercontent.com/13470242/202916624-8da80549-b3ef-4f68-a3af-159428481b42.png)

**Comment by blakeblackshear** [comment]
The playlist endpoint is timing out. We are hoping to remove most of the processing that happens on that endpoint in a future release.

**Comment by HHUBSS** [comment]
I also experience this. If I choose the camera entity (not the frigate camera entity) it's working fine but I cannot access the clips and snapshots.

![image](https://user-images.githubusercontent.com/89816305/210193313-88b491cd-62f6-467d-a00d-5b63e61c7959.png)

**Comment by Heisenberg2980** [comment]
I am getting the same error. Just talking from a complete ignorance of how frigate works, but if the number of events is the issue does that mean either the card or frigate backend are trying to retrieve all events and failing when there are to many events? in that case could this be fixed with some type of pagination or limitation in the amount of events retrieved?

**Comment by dermotduffy** [comment]
> I am getting the same error pretty often (but not always, which is weird). Just talking from a complete ignorance of how frigate works, but if the number of events is the issue does that mean either the card or frigate backend are trying to retrieve all events and failing when there are to many events? in that case could this be fixed with some type of pagination or limitation in the amount of events retrieved?

There are already limits, i.e. the card is not requesting every event. The backend is likely just doing too much processing to be able to keep up with the requests, despite the limits in place. Today, the card is requesting events via the HA media browser interface (the same API that gets used when you click 'Media' in HA). The next major card build will make these calls on a separate API, which introduces the ability for the card to do much more clever things -- but ultimately that still could cause the backend to timeout if the quantity / size of requests is such that the processing time necessary to serve them exceeds the timeout.

**Comment by HHUBSS** [comment]
See my update here #911 originally I have 60 days of retention after configuring to only 15 days of retention, I'm not getting the error anymore. In my opinion, it is better for the card to pull only xxx of days and retain longer periods of records in the frigate server.

**Comment by dermotduffy** [comment]
Yes, that could be a workaround (right now the limit is on quantity of events returned, rather than the quantity of time searched for events -- which is probably more expensive). However the real issue remains as the performance of the backend -- the requests the card is making are reasonable / correct, and I'd rather this be fixed on the backend than hack workarounds into the card.

**Comment by Heisenberg2980** [comment]
> See my update here #911 originally I have 60 days of retention after configuring to only 15 days of retention, I'm not getting the error anymore. In my opinion, it is better for the card to pull only xxx of days and retain longer periods of records in the frigate server.

When you say you updated the retention are you talking about frigate backend or the frigate card? I would like to keep the maximum retention my storage allows in the frigate backend, even if the frigate card is just able to retrieve the last 15 days

**Comment by HHUBSS** [comment]
> When you say you updated the retention are you talking about frigate backend or the frigate card? I would like to keep the maximum retention my storage allows in the frigate backend, even if the frigate card is just able to retrieve the last 15 days

The frigate backend/server. As far as I know, you cannot define the number of days for the card to pull from the server. Please correct me if I'm wrong.

**Comment by blakeblackshear** [comment]
> However the real issue remains the performance of the backend -- the requests the card is making are reasonable / correct, and I'd rather this be fixed on the backend than hack workarounds into the card.

Which API endpoint are we talking about here?

**Comment by dermotduffy** [comment]
> Which API endpoint are we talking about here?

Released version of the card gets events only through the HA media browser -- i.e. it's the media browser in the integration that is timing out. In turn, that is calling both `async_get_events`  and `async_get_event_summary` (it calls other things for recordings, but that's not in question here). So it maps to these on the backend:
 - `/events/summary`
 - `/events`

**Comment by Heisenberg2980** [comment]
@dermotduffy do you think those changes will fix the timeout issue when retention is high (i.e. 60 days). 

To be honest I don´t understand why the amount of retention days affect these calls to the HA media browser, is the frontend trying to retrieve all events? can´t the data retrieve be restricted to one day for example (and then if the user scrolls to a different day another call is done to retrieve the events for that day), so no matter how many days are stored the backend never reaches the 10s timeout?

**Comment by dermotduffy** [comment]
@Heisenberg2980 I don't know. I absolutely could imagine the card caching will help, since it'll reduce any parallel queries hitting the backend.
