### ISSUE TITLE
<feature request> Input Select styled option for sub/main stream

### ISSUE THREAD

**Issue by Bod1985** [dermotduffy/frigate-hass-card#898]
First of all -  thank you for thework on this card - each update brings great features and it's one of my most comprehensive and usable cards in my HomeAssistant.

I have my cameras configured as follows:

camera.frontdoor
camera.frontdoorsub
camera.backdoor
camera.backdoorsub

or 

rtsp://ipaddress:8554/frontdoor
rtsp://ipaddress:8554/frontdoorsub
rtsp://ipaddress:8554/backdoor
rtsp://ipaddress:8554/backdoorsub

I'd love to be able to toggle sub/main stream for the WebRTC camera input. I port forward WebRTC integration and find the substream is smooth and live remotely but the main stream is too much for my upload speed.

Being able to toggle to main stream when viewing on LAN and sub stream on WAN (not automatically ofc) would be a huge upgrade over my current LQ and HQ pages or having all streams in one card to swipe through.

Currently I have to reconfigure 2 locations if I prefer a different layout or buttons. I'd like to handle this with a button in the card or perhaps the WebRTC camera entity could be 'overidable' and then I can script around it with input selects or something?

**Comment by spacebares** [comment]
Like a highquality / lowquality button? The options in the card would be choose highquality camera entity and low quality camera entity. Or RTSP urls.

**Comment by spacebares** [comment]
I would check to see if the "automatically pause" feature of the card works since mainstream uses more cpu & network. You can just check to see if cpu&network usage goes down properly.
