### ISSUE TITLE
Error in HA logs: play is not a function

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#899]
Hi there, I'm using the latest version of the card (branch 4.1.0), and recently I noticed the following issue in my HA logs:

```
Logger: frontend.js.latest.202211080
Source: components/system_log/__init__.py:256
First occurred: 12:10:08 AM (6 occurrences)
Last logged: 9:51:15 AM

https://home.felipecrs.com/local/custom/frigate-hass-card/live-8d5f3a37.js:85:757 Uncaught TypeError: this._providerRef.value?.play is not a function
https://home.felipecrs.com/frontend_latest/core.0e377a7a.js:1:9578 Uncaught Error: Suspend promise not set
```

I didn't notice any side effect, but I suppose it's something to be aware of to be corrected when have time.

**Comment by dermotduffy** [comment]
@felipecrs Have you seen this recently? If yes, would you mind syncing the 4.1 branch (which includes https://github.com/dermotduffy/frigate-hass-card/pull/953 ) and see if it makes any difference?

**Comment by felipecrs** [comment]
Actually I have not seen this since a long time. I'll close it, and if I notice something I get back.

Thanks!
