### ISSUE TITLE
Full on arbitrary aspect-ratio cameras doesn't work as intended on PC/browser

### ISSUE THREAD

**Issue by utkarshjain00** [dermotduffy/frigate-hass-card#90]
**Release with the issue:**
pre-release v1.1.0

**Browser and Operating System:**
Edge  / Windows 10

**Description of problem:**

Full on arbitrary aspect-ratio cameras in the browser opens a partial view with a scroll bar. 

View in a card in lovelace:

![b4](https://user-images.githubusercontent.com/81548490/135212807-952d3bb4-db84-456a-9512-5b72f181bd25.jpg)

View when full screen is clicked:

![af](https://user-images.githubusercontent.com/81548490/135212852-63ecb106-9bca-4e53-9171-29782eba3fcb.jpg)

**Comment by dermotduffy** [comment]
Thank you! Would you mind posting the card config?

My theory is that the media dimensions aren't properly recognized in Edge, which would cause both the fullscreen behavior (for media taller than wide) and explain why the `dynamic` aspect ratio doesnt work for you.

**Comment by utkarshjain00** [comment]
`      - type: custom:frigate-card
        frigate_url: http://192.168.X.Y:5000
        menu_mode: below
        webrtc: {}
        view_default: live
        frigate_camera_name: GateYard
        controls: {}
        menu_buttons:
          frigate_ui: false
          frigate: false
          snapshots: false
        dimensions:
          aspect_ratio_mode: unconstrained
        camera_entity: camera.gateyard`

**Comment by dermotduffy** [comment]
Fixed in https://github.com/dermotduffy/frigate-hass-card/pull/95 .
