### ISSUE TITLE
Frigate labels from double take do not show in lovelace card

### ISSUE THREAD

**Issue by atv2016** [dermotduffy/frigate-hass-card#900]
So double take has the option to send recognised sublabels back to Frigate. This shows in frigate, but doesn't seem to show in the lovelace card.

Not sure why, seems to pull the same event log?

**Comment by bagobones** [comment]
frigate calls them sublabels, it would be a great feature to have

**Comment by dermotduffy** [comment]
Quick clarification: Do you just want to see them on events, or be able to search by them, or both?

**Comment by bagobones** [comment]
In the frigate ui you can do both... if you want to see when "x" got home it is nice to put in their name and the doorbell cam to find the answer quickly.

**Comment by dermotduffy** [comment]
Will be in the next build (requires new builds of Frigate itself, the integration, and the card).
