### ISSUE TITLE
Error streaming video from Android tablet

### ISSUE THREAD

**Issue by jegestee** [dermotduffy/frigate-hass-card#902]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Android Companion App & Chrome

**Description of problem:**
I'm having some issues displaying the Frigate card on a Samsung Galaxy Tab A8. It initially loads in the video, and plays it briefly for a few seconds, then it throws an error saying "Error with media stream contents".  The same issue occurs in both the Android app, and in a browser (Chrome). I can see the existing recording/images, but I cannot play the videos as it just shows a grey screen. The images are displayed without any problem. However, I'm able to play the videos if I go directly to Frigate. The card is working fine on every other device, including an android phone and an iPhone, so it really puzzles me what is causing the problem. Seeing that I don't face any issue in Frigate itself using the mentioned tablet, I suspect that something goes wrong with the card. Could you please help me address this issue? Please let me know if I can assist in any way.

Many Thanks!

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I have retrieved the Android app logs as I don't see anything related in the other log files. 
I've observed several errors relating to MediaCodec which might just be the root cause?

12-05 18:52:36.204 22537 25542 I MediaCodec: Codec shutdown complete
12-05 18:52:36.215 22537 22537 E cr_MediaCodecBridge: MediaCodec.onError: android.media.MediaCodec.error_neg_2147479520
12-05 18:52:36.259 22537 22546 D InputTransport: Input channel destroyed: 'ClientS', fd=181
12-05 18:52:36.326 22537 22537 I ViewRootImpl@14a65af[SettingsActivity]: ViewPostIme pointer 0
12-05 18:52:36.327 22537 22537 I GestureDetector: obtain mCurrentDownEvent. id: 178975701 caller: androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent:484 androidx.core.view.GestureDetectorCompat.onTouchEvent:548 io.sentry.android.core.internal.gestures.SentryWindowCallback.handleTouchEvent:68 
12-05 18:52:36.353 22537 22537 I GestureDetector: obtain mCurrentMotionEventRaw. action: 2 id: 1048164044
12-05 18:52:36.462 22537 22537 I ViewRootImpl@14a65af[SettingsActivity]: ViewPostIme pointer 1
12-05 18:52:38.110 22537 22537 I ViewRootImpl@14a65af[SettingsActivity]: ViewPostIme pointer 0
12-05 18:52:38.111 22537 22537 I GestureDetector: obtain mCurrentDownEvent. id: 72874946 caller: androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent:484 androidx.core.view.GestureDetectorCompat.onTouchEvent:548 io.sentry.android.core.internal.gestures.SentryWindowCallback.handleTouchEvent:68 
12-05 18:52:38.136 22537 22537 I GestureDetector: obtain mCurrentMotionEventRaw. action: 2 id: 319472512
12-05 18:52:38.879 22537 22537 I ViewRootImpl@14a65af[SettingsActivity]: ViewPostIme pointer 1
12-05 18:52:39.322 22537 22677 I cr_MediaCodecBridge: create MediaCodec video decoder, mime video/avc
12-05 18:52:39.324 22537 22677 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
12-05 18:52:39.324 22537 22677 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
12-05 18:52:39.326 22537 22677 I ACodec  :  [] Now uninitialized
12-05 18:52:39.327 22537 25555 I ACodec  : [] onAllocateComponent
12-05 18:52:39.328 22537 25555 I OMXClient: IOmx service obtained
12-05 18:52:39.336 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Loaded
12-05 18:52:39.338 22537 25553 I MediaCodec: MediaCodec will operate in async mode
12-05 18:52:39.339 22537 25553 D SurfaceUtils: connecting to surface 0xb4000075f9e6f010, reason connectToSurface
12-05 18:52:39.339 22537 25553 I MediaCodec: [OMX.sprd.h264.decoder] setting surface generation to 23078229
12-05 18:52:39.339 22537 25553 D SurfaceUtils: disconnecting from surface 0xb4000075f9e6f010, reason connectToSurface(reconnect)
12-05 18:52:39.339 22537 25553 D SurfaceUtils: connecting to surface 0xb4000075f9e6f010, reason connectToSurface(reconnect)
12-05 18:52:39.339 22537 25555 I ACodec  : app-pid(22537)
12-05 18:52:39.340 22537 25555 E ACodec  : [OMX.sprd.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
12-05 18:52:39.344 22537 22677 D MediaCodec: keep callback message for reclaim
12-05 18:52:39.345 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Loaded->Idle
12-05 18:52:39.349 22537 25555 D SurfaceUtils: disconnecting from surface 0xb4000075f9e6f010, reason setNativeWindowSizeFormatAndUsage
12-05 18:52:39.349 22537 25555 D SurfaceUtils: connecting to surface 0xb4000075f9e6f010, reason setNativeWindowSizeFormatAndUsage
12-05 18:52:39.349 22537 25555 D SurfaceUtils: set up nativeWindow 0xb4000075f9e6f010 for 2688x1520, color 0x15, rotation 0, usage 0x402933
12-05 18:52:39.349 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] configureOutputBuffersFromNativeWindow setBufferCount : 15, minUndequeuedBuffers : 7
12-05 18:52:39.350 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Allocating 15 buffers from a native window of size 6128640 on output port
12-05 18:52:39.363 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Idle->Executing
12-05 18:52:39.363 22537 25553 I MediaCodec: setCodecState state(0), called in 6
12-05 18:52:39.364 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Executing
12-05 18:52:39.364 22537 22677 I cr_MediaCodecBridge: create MediaCodec video decoder, mime video/avc
12-05 18:52:39.364 22537 22677 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
12-05 18:52:39.365 22537 22677 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
12-05 18:52:39.366 22537 22677 I ACodec  :  [] Now uninitialized
12-05 18:52:39.366 22537 25560 I ACodec  : [] onAllocateComponent
12-05 18:52:39.367 22537 25560 I OMXClient: IOmx service obtained
12-05 18:52:39.370 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Loaded
12-05 18:52:39.373 22537 25555 E ACodec  : [OMX.sprd.h264.decoder] ERROR(0x80001020)
12-05 18:52:39.373 22537 25555 E ACodec  : signalError(omxError 0x80001020, internalError -2147483648)
12-05 18:52:39.373 22537 25553 E MediaCodec: Codec reported err 0x80001020, actionCode 0, while in state 6/STARTED
12-05 18:52:39.373 22537 25553 D SurfaceUtils: disconnecting from surface 0xb4000075f9e6f010, reason disconnectFromSurface
12-05 18:52:39.373 22537 25553 E Surface : freeAllBuffers: 8 buffers were freed while being dequeued!
12-05 18:52:39.373 22537 25559 I MediaCodec: MediaCodec will operate in async mode
12-05 18:52:39.374 22537 22687 E cr_MediaCodecBridge: Failed to queue input buffer
12-05 18:52:39.374 22537 22687 E cr_MediaCodecBridge: java.lang.IllegalStateException
12-05 18:52:39.374 22537 22687 E cr_MediaCodecBridge: 	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
12-05 18:52:39.374 22537 22687 E cr_MediaCodecBridge: 	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2634)
12-05 18:52:39.374 22537 22687 E cr_MediaCodecBridge: 	at org.chromium.media.MediaCodecBridge.queueInputBuffer(chromium-TrichromeWebViewGoogle.aab-stable-530414133:8)
12-05 18:52:39.374 22537 25559 D SurfaceUtils: connecting to surface 0xb4000075f9e71010, reason connectToSurface
12-05 18:52:39.374 22537 25559 I MediaCodec: [OMX.sprd.h264.decoder] setting surface generation to 23078230
12-05 18:52:39.374 22537 25559 D SurfaceUtils: disconnecting from surface 0xb4000075f9e71010, reason connectToSurface(reconnect)
12-05 18:52:39.374 22537 25559 D SurfaceUtils: connecting to surface 0xb4000075f9e71010, reason connectToSurface(reconnect)
12-05 18:52:39.375 22537 25560 I ACodec  : app-pid(22537)
12-05 18:52:39.376 22537 25560 E ACodec  : [OMX.sprd.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
12-05 18:52:39.380 22537 22677 D MediaCodec: keep callback message for reclaim
12-05 18:52:39.382 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Loaded->Idle
12-05 18:52:39.387 22537 22537 E cr_MediaCodecBridge: MediaCodec.onError: android.media.MediaCodec.error_neg_2147479520
12-05 18:52:39.388 22537 25560 D SurfaceUtils: disconnecting from surface 0xb4000075f9e71010, reason setNativeWindowSizeFormatAndUsage
12-05 18:52:39.388 22537 25560 D SurfaceUtils: connecting to surface 0xb4000075f9e71010, reason setNativeWindowSizeFormatAndUsage
12-05 18:52:39.388 22537 25560 D SurfaceUtils: set up nativeWindow 0xb4000075f9e71010 for 2688x1520, color 0x15, rotation 0, usage 0x402933
12-05 18:52:39.389 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] configureOutputBuffersFromNativeWindow setBufferCount : 15, minUndequeuedBuffers : 7
12-05 18:52:39.389 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Allocating 15 buffers from a native window of size 6128640 on output port
12-05 18:52:39.428 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Idle->Executing
12-05 18:52:39.429 22537 25559 I MediaCodec: setCodecState state(0), called in 6
12-05 18:52:39.430 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Executing
12-05 18:52:39.430 22537 22677 W cr_MediaCodecBridge: Releasing: OMX.sprd.h264.decoder
12-05 18:52:39.431 22537 22677 W cr_MediaCodecBridge: Codec released
12-05 18:52:39.431 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Executing->Idle
12-05 18:52:39.435 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078d22e5500
12-05 18:52:39.435 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 16 to native window
12-05 18:52:39.435 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078d22e5300
12-05 18:52:39.435 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 15 to native window
12-05 18:52:39.436 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078d22e5100
12-05 18:52:39.436 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 14 to native window
12-05 18:52:39.437 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835807200
12-05 18:52:39.437 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 13 to native window
12-05 18:52:39.437 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078c6db0f00
12-05 18:52:39.437 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 12 to native window
12-05 18:52:39.438 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078c6db0d00
12-05 18:52:39.438 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 11 to native window
12-05 18:52:39.440 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078c6db0b00
12-05 18:52:39.440 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 10 to native window
12-05 18:52:39.441 22537 25555 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000078c6db0900
12-05 18:52:39.441 22537 25555 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 9 to native window
12-05 18:52:39.442 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Idle->Loaded
12-05 18:52:39.442 22537 25555 I ACodec  : [OMX.sprd.h264.decoder] Now Loaded
12-05 18:52:39.443 22537 25560 E ACodec  : [OMX.sprd.h264.decoder] ERROR(0x80001020)
12-05 18:52:39.443 22537 25560 E ACodec  : signalError(omxError 0x80001020, internalError -2147483648)
12-05 18:52:39.443 22537 25559 E MediaCodec: Codec reported err 0x80001020, actionCode 0, while in state 6/STARTED
12-05 18:52:39.443 22537 25559 D SurfaceUtils: disconnecting from surface 0xb4000075f9e71010, reason disconnectFromSurface
12-05 18:52:39.443 22537 25559 E Surface : freeAllBuffers: 8 buffers were freed while being dequeued!
12-05 18:52:39.444 22537 25555 I ACodec  :  [OMX.sprd.h264.decoder] Now uninitialized
12-05 18:52:39.444 22537 25555 I ACodec  :  [] Now kWhatShutdownCompleted event : 8101
12-05 18:52:39.444 22537 22687 E MediaCodec: getBufferAndFormat - not executing
12-05 18:52:39.444 22537 25553 I MediaCodec: Codec shutdown complete
12-05 18:52:39.444 22537 22687 E cr_MediaCodecBridge: Failed to get input buffer
12-05 18:52:39.444 22537 22687 E cr_MediaCodecBridge: java.lang.IllegalStateException
12-05 18:52:39.444 22537 22687 E cr_MediaCodecBridge: 	at android.media.MediaCodec.getBuffer(Native Method)
12-05 18:52:39.444 22537 22687 E cr_MediaCodecBridge: 	at android.media.MediaCodec.getInputBuffer(MediaCodec.java:3993)
12-05 18:52:39.444 22537 22687 E cr_MediaCodecBridge: 	at org.chromium.media.MediaCodecBridge.getInputBuffer(chromium-TrichromeWebViewGoogle.aab-stable-530414133:20)
12-05 18:52:39.444 22537 22687 E chromium: [ERROR:media_codec_bridge_impl.cc(697)] GetInputBuffer failed
12-05 18:52:39.446 22537 22677 W cr_MediaCodecBridge: Releasing: OMX.sprd.h264.decoder
12-05 18:52:39.447 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Executing->Idle
12-05 18:52:39.447 22537 22677 W cr_MediaCodecBridge: Codec released
12-05 18:52:39.454 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb4000075fe9e2100
12-05 18:52:39.454 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 16 to native window
12-05 18:52:39.454 22537 22537 E cr_MediaCodecBridge: MediaCodec.onError: android.media.MediaCodec.error_neg_2147479520
12-05 18:52:39.454 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875f00
12-05 18:52:39.454 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 15 to native window
12-05 18:52:39.455 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875d00
12-05 18:52:39.455 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 14 to native window
12-05 18:52:39.455 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875b00
12-05 18:52:39.455 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 13 to native window
12-05 18:52:39.456 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875900
12-05 18:52:39.456 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 12 to native window
12-05 18:52:39.456 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875700
12-05 18:52:39.457 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 11 to native window
12-05 18:52:39.457 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875500
12-05 18:52:39.457 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 10 to native window
12-05 18:52:39.457 22537 25560 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb400007835875300
12-05 18:52:39.457 22537 25560 W ACodec  : [OMX.sprd.h264.decoder] can not return buffer 9 to native window
12-05 18:52:39.458 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Idle->Loaded
12-05 18:52:39.458 22537 25560 I ACodec  : [OMX.sprd.h264.decoder] Now Loaded
12-05 18:52:39.460 22537 25560 I ACodec  :  [OMX.sprd.h264.decoder] Now uninitialized
12-05 18:52:39.460 22537 25560 I ACodec  :  [] Now kWhatShutdownCompleted event : 8101
12-05 18:52:39.460 22537 25559 I MediaCodec: Codec shutdown complete

**Comment by jegestee** [comment]
Hi,

I have narrowed down the issue to a possibly missing codec on the tablet. It seems like Samsung's default player is unable to play the recorded mp4 files. Strangely it can play other (h264) mp4 files. Anyways, this can be closed as it's not related to the card - Sorry for creating the issue unnecessarily.

**Comment by Morphy99** [comment]
I'm seeing the same issue with an Echo Show 15 and using the companion app or Fully Kiosk Browser. I'm now using Amazon's Silk browser which works better but when it switches to another camera (with Scan Mode) it stops with the same "Error with media stream contents". Refreshing enables it to play again.

I've tried disabling OpenGL for JSMPEG live views as suggested in troubleshooting.

**Comment by dermotduffy** [comment]
I've slightly increased the robustness of the HA player to only show errors if HA believes they are fatal. The "Error with media stream contents" is not fatal. Will be in the next build.
