### ISSUE TITLE
Cannot enable back smooth still images while loading when Low performance preset is enabled

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#904]
I guess the title says everything. I tried to tweak all the parameters to bring it back but it's not possible. Low performance is great, but I'd like to keep this feature enabled.

**Comment by felipecrs** [comment]
I think this was fixed as well. :)

**Comment by felipecrs** [comment]
@dermotduffy, when testing https://github.com/dermotduffy/frigate-hass-card/pull/982, I realized that this issue is still valid.

The following:

```yaml
cameras_global:
  image:
    refresh_seconds: 1
```

Were supposed to give me smooth images even when low perf profile is set, but even in that case the images are only updated on every 10s. On high perf profile it seems to work fine.

**Comment by dermotduffy** [comment]
@felipecrs I see this too. Investigating...

**Comment by felipecrs** [comment]
Awesome!

**Comment by felipecrs** [comment]
Tested here too, working fine. 🎉
