### ISSUE TITLE
Camera going blank on HomeAssistant app

### ISSUE THREAD

**Issue by MelvinSnijders** [dermotduffy/frigate-hass-card#906]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v4.0.0

**Browser and Operating System:**
Android HomeAssistant companion app `beta-3020-efc4f0af-full`

**Description of problem:**
Camera loads, then flickers and goes blank with a small icon in the top left corner.
It doens't happen all the time, and switches between the camera (not one specific one that has the issue, can be multiple cameras at once).
Only happens when using JSMpeg.
Screenshot:

![](https://i.imgur.com/qcg5klz.png)

**Comment by dermotduffy** [comment]
Huh. Can you hold down your Frigate button and paste the diagnostics that appear?

Can you check your Javascript console log and tell me if you see anything unusual when this happens (F12 in Chrome).

Thanks.

**Comment by MelvinSnijders** [comment]
Yes, only in the app, haven't seen it happen on desktop.

Here's the diagnostic information:
```json
{
  "ha_version": "2022.11.2",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (Linux; Android 13; SM-F936B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/beta-3020-efc4f0af-3020 (Android 13; SM-F936B)",
  "date": "2022-12-24T21:39:48.519Z",
  "frigate_version": {
    "9ffacdb0940503f2b89755a983634d11": "3.0.0/0.11.0-3846a13"
  },
  "lang": "en",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.voortuin",
        "live_provider": "frigate-jsmpeg"
      }
    ],
    "view": {
      "dark_mode": "off"
    },
    "live": {
      "preload": true
    }
  }
}
```

Is there a possibility to open the developer console on mobile?

**Comment by dermotduffy** [comment]
> Is there a possibility to open the developer console on mobile?

Enable [remote debugging](https://companion.home-assistant.io/docs/integrations/android-webview/#remote-debugging) on the HA app, enable USB debugging on your Android system, plug your device into a PC and then you can visit `chrome://inspect` and get a remote developer console for the HA app.

Are you still having this issue? It's not really going to be possible to debug further without remote debugging access to the console.

**Comment by dermotduffy** [comment]
Recommend trying the new build and see if this changes the situation: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v5.0.0-beta.1

**Comment by dermotduffy** [comment]
Please re-open if still an issue.
