### ISSUE TITLE
Fullscreen mode iOS

### ISSUE THREAD

**Issue by StanESmith** [dermotduffy/frigate-hass-card#907]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
Running version 4.0.0
**Last working release (if known):**
Not known
**Browser and Operating System:**
iOS 16, Firefox and Safari, HA-Companion App

Full screen mode does not work on iOS. I have tested this through setting up the fullscreen button, adding a "tap to go fullscreen" and neither of these work. The fullscreen button fails to load on iOS on all browsers tried and the companion app. On the desktop browser for firefox everything works as expected. 

How it should behave is similar to the desktop browser. The fullscreen button should be visible and allow to go full screen on the companion app and the mobile browser. No method of triggering fullscreen works on iOS mobile in the current version.

**Comment by dermotduffy** [comment]
Unfortunately, this is not possible from iOS. See [documentation](https://github.com/dermotduffy/frigate-hass-card#fullscreen-button-does-not-appear-on-iphone). Complaints to your Phone OS manufacturer ;-)
