### ISSUE TITLE
Underway: Major card refactor

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#908]
* Allow media to come from sources other than the HA media browser
* Move Frigate specific logic into Frigate contained areas
* Better support non-Frigate engines (e.g. other camera related integrations)
* Abstracts much more of the code to support unittesting.

Required for:
* https://github.com/dermotduffy/frigate-hass-card/issues/835
* https://github.com/dermotduffy/frigate-hass-card/issues/884
* https://github.com/dermotduffy/frigate-hass-card/issues/837

**Comment by felipecrs** [comment]
@dermotduffy I think you can unpin this now. :)
