### ISSUE TITLE
Allow us to define a custom image to use for show_image_during_load

### ISSUE THREAD

**Issue by owenfiscus** [dermotduffy/frigate-hass-card#919]
It would be nice to use a static image of our choice as the `show_image_during_load` image rather than a snapshot of the camera. I have created an image that would make it clear the camera is loading while remaining aesthetically pleasing and I would love to be able to use it. Thanks!

**Comment by NickM-27** [comment]
This is already possible using https://github.com/dermotduffy/frigate-hass-card#image-options

**Comment by felipecrs** [comment]
Are you sure that's the same image using during load? I think it's not.

**Comment by NickM-27** [comment]
> Are you sure that's the same image that's used during load? I think it's not.

yes, that is a way to define a static image and the option mentioned above just shows the static image while the stream is loading.

**Comment by owenfiscus** [comment]
Hm, perhaps I'm doing something wrong then, that option is defined but not working for me.

``` yaml
image:
  mode: url
  url: https://my.hassinstance.url/local/assets/camera-backdrop.png

```

**Comment by dermotduffy** [comment]
This actually is not possible right now. The image `url` parameter will set the image for the`image` view, but that's not the same as the temporary loading image used in the `live` view. I've just implemented this, it will be in the next official build (`v4.1.0`).
