### ISSUE TITLE
Allow to set webrtc_card options for each camera

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#920]
It's good to have a global one, so that I don't have to duplicate the webrtc_card config for all cameras, however, I'd like to set some options specifically for each camera. For example, I may want to enable the PTZ buttons (from WebRTC card) for a single camera, or have audio unmuted/ui shown for a single camera, etc.

**Comment by dermotduffy** [comment]
Right now you can override that, search for `Expand: Enable WebRTC Card UI only for a selected camera` in the [docs](https://github.com/dermotduffy/frigate-hass-card#config-expanded-overrides) for an example.

**Comment by felipecrs** [comment]
Oh, that makes sense! I keep forgetting that I can do pretty much everything with the override feature.

Thank you!
