### ISSUE TITLE
WebRTC card never shows up if `live.show_image_during_load` is enabled

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#923]
As found in https://github.com/dermotduffy/frigate-hass-card/issues/917.

**Comment by dermotduffy** [comment]
Guess: The media detection of the new WebRTC card is failing, i.e. Frigate card does not correctly identify that WebRTC has loaded the stream and so continues to show the image indefinitely.

**Comment by felipecrs** [comment]
That's must be it... because my conditional elements that has `mediaLoaded` condition also never shows up.

**Comment by dermotduffy** [comment]
Easy fix. Will be in the next build.

**Comment by felipecrs** [comment]
@dermotduffy this issue is back for me. Maybe it's because of the new update from WebRTC?

**Comment by dermotduffy** [comment]
Will upgrade to the new WebRTC version and see ...

**Comment by dermotduffy** [comment]
@felipecrs Give the (now merged) #976 a shot? The underlying card had changed structure again.

**Comment by felipecrs** [comment]
#976 fixed the issue. Thanks a lot!
