### ISSUE TITLE
Live view cannot mute (always play sound no matter what.)

### ISSUE THREAD

**Issue by MopGitHub** [dermotduffy/frigate-hass-card#925]
**Checklist:**

- [ yes] I updated to the latest version available
- [yes ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
Happened around a week or two
**Browser and Operating System:**

HA Core  2023.1.7 
go2rtc V 1.1.1
Frigate in Docker

**Description of problem:**

When open live view on frigate card even if I set live view options for (Automatically mute : All opportunities) It's always play sound
It's never happened and I didn't change any settings ( I think it's play sound for about a week or 2 weeks ago ) 

( I want it to always mute )

![1675413191193](https://user-images.githubusercontent.com/56420566/216551253-99c6129a-d8e8-4a21-996c-ad50ae3cdd96.jpg)

![1675413213350](https://user-images.githubusercontent.com/56420566/216551288-820e2431-dafc-4d12-b6b7-f47ba597a50e.jpg)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by felipecrs** [comment]
Are you using webrtc card?

**Comment by MopGitHub** [comment]
> Are you using webrtc card?

No, it's frigate card

**Comment by MopGitHub** [comment]
> Are you using webrtc card?

![1675426248635](https://user-images.githubusercontent.com/56420566/216600612-166ef4cd-1941-45cb-b6d4-647ff1b6bf1e.jpg)

**Comment by felipecrs** [comment]
The Frigate card won't unmute the webrtc card. You should unmute it yourself. Example: https://github.com/dermotduffy/frigate-hass-card/issues/917#issuecomment-1402687760

**Comment by MopGitHub** [comment]
> The Frigate card won't unmute the webrtc card. You should unmute it yourself. Example: [#917 (comment)](https://github.com/dermotduffy/frigate-hass-card/issues/917#issuecomment-1402687760)

I see. But I did not change any configuration for the card. It's start unmute about 1-2 weeks ago (maybe frigate card got an update ?)

**Comment by felipecrs** [comment]
My friend, you are using WebRTC card and you are blaming the Frigate card. There was no update to the Frigate card, but I bet you upgraded the WebRTC card.
