### ISSUE TITLE
Go2rtc live source failing with invalid header

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#958]
This is the dev console error I get when trying to use it:

```
live-go2rtc-c899dab0.js:1 WebSocket connection to 'ws://192.168.50.106:8123/api/frigate/frigate/mse/api/ws?src=birdseye&authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0YzYzM2Q5MTk1YmQ0NWU1YWUzM2Q2NzE2ZGRmNTIwYyIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9tc2UvYXBpL3dzIiwicGFyYW1zIjp7InNyYyI6ImJpcmRzZXllIn0sImlhdCI6MTY3NjkwNzA3OSwiZXhwIjoxNjc2OTkzNDc5fQ.ks9qy-CSg-yhgf_aQKbWQSWYpARL8uKHfNRuGIyPQ2Q' failed: Invalid frame header
```

**Comment by NickM-27** [comment]
This is happening to me every time right now

**Comment by NickM-27** [comment]
Okay, I can pin this issue down to the `show_image_while_loading` variable. When this is set to false, go2rtc live source does not work. As soon as I set it to true it does work as expected

**Comment by dermotduffy** [comment]
Can't figure out why this is happening nor even what is producing that error message (it is coming from below the go2rtc player layer itself). Would you mind trying a few different cameras / different go2rtc modes (configurable in the card visual editor) and see if you can get it to not happen?

**Comment by NickM-27** [comment]
I tried with 3 different cameras, they are all having the problem. Tried using the stream_name config which hasn't seemed to help. Also tried each mode individually which made no difference. Not really sure what would be affecting this which is weird

**Comment by NickM-27** [comment]
I just tried on an incognito tab and I am seeing the same thing

**Comment by dermotduffy** [comment]
[Silly questions]
 * You're using integration [v4.0.0-beta4](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-beta4)
 * You're using "stock" [0.12.0 Beta 8](https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0-beta8) ?

Anything else weird in the JS console, or network requests failing?

**Comment by NickM-27** [comment]
I think I may have found the error. Checked go2rtc logs and I see this:

`2023-02-26 15:54:29.522398188  15:54:29.522 ERR github.com/AlexxIT/go2rtc/cmd/api/ws.go:66 > host=localhost origin=http://192.168.50.106:8123 error="websocket: request origin not allowed by Upgrader.CheckOrigin"`

**Comment by NickM-27** [comment]
However, I don't understand why that error would be happening given that the origin and the requested resource are the same ip/port

**Comment by NickM-27** [comment]
adding

```
  api:
    origin: "*"
```

to my go2rtc config fixed it. 

I saw this issue when I was working on the webUI for frigate but it was fixed after adding the nginx proxy and working through that (which you already are) so it is confusing to me why that would not be allowed here.

**Comment by dermotduffy** [comment]
Why _would_ it work? Your HA instance (from which the card is making the request) presumably has a different domain / ip than your go2rtc instance. Perhaps it's fine on the Frigate frontend, if the whole thing is served by the same IP & port (same nginx instance?) -- but that definitely won't be the case for Home Assistant.

Maybe `/mse/` and `/rtc` proxies should be more permissive, e.g. [ref](https://michielkalkman.com/snippets/nginx-cors-open-configuration/).

```
        add_header 'Access-Control-Allow-Origin' '*' always;
```

**Comment by NickM-27** [comment]
The HA instance and frigate / go2rtc are running on the same machine, though frigate is not running in host mode so that could be the issue. 

Also, seeing as go2rtc is the one with errors in the logs (instead of frigate nginx) I believe the frigate part is proxying along as expected

**Comment by NickM-27** [comment]
Okay so I enabled trace logs for go2rtc and it is odd. 

When I view in frigate this is what it shows: `origin=192.168.50.106:5000, host=192.168.50.106`

however viewing in HA shows: `host=localhost origin=http://192.168.50.106:8123 error="websocket: request origin not allowed by Upgrader.CheckOrigin"`

**Comment by NickM-27** [comment]
The current nginx config for these is:

```
        location /live/mse/ {
            proxy_pass http://go2rtc/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location /live/webrtc/ {
            proxy_pass http://go2rtc/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
```

perhaps somewhere in the frigate card -> frigate integration -> frigate chain the host header isn't being set? Or maybe I am misunderstanding how this is supposed to work and localhost is expected as the host in this case

**Comment by dermotduffy** [comment]
> Also, seeing as go2rtc is the one with errors in the logs (instead of frigate nginx) I believe the frigate part is proxying along as expected

Sure, but then go2rtc is rejecting it. I think my question is: Are the `/mse/` and `/rtc/` proxy endpoints ever useful without the user also setting the go2rtc origin [Which to be clear, I am also setting], or having nginx specifically work around?

> perhaps somewhere in the frigate card -> frigate integration -> frigate chain the host header isn't being set?

Do you have the integration configured to talk to localhost or `192.168.50.106:5000`?

**Comment by NickM-27** [comment]
> Do you have the integration configured to talk to localhost or 192.168.50.106:5000?

ah wow can't believe I missed that, you are correct. I moved the integration over to 192.168.50.106:5000 and it started working immediately without any CORS necessary

**Comment by dermotduffy** [comment]
> ah wow can't believe I missed that, you are correct. I moved the integration over to 192.168.50.106:5000 and it started working immediately without any CORS necessary

OK -- great. Think we're done here then, let me know if not!

**Comment by nabheet** [comment]
My two cameras are working perfectly and recording all events that I care about. But I can't get the birdseye view to work. 

I am getting this error: 

```
frigate-hass-card.js:1155  FRIGATE-HASS-CARD  Version 4.0.0 
frigate-hass-card.js:276 WebSocket connection to 'ws://myserver.local:8123/api/frigate/frigate/jsmpeg/birdseye?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwZWU4OGRkZjc4ZmM0MGM1ODllMzk1YmM2MDIyMWUyNCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9qc21wZWcvYmlyZHNleWUiLCJwYXJhbXMiOnt9LCJpYXQiOjE2Nzg0MjQ4MDEsImV4cCI6MTY3ODUxMTIwMX0.QenXvxIw6JRQkMVBhYn8UoqLaLYw4PbhDDrZc8TYO0E' failed: Invalid frame header
e.start @ frigate-hass-card.js:276
e.startLoading @ frigate-hass-card.js:276
(anonymous) @ frigate-hass-card.js:276
:8123/developer-tools/state:1 Autofocus processing was blocked because a document already has a focused element.
frigate-hass-card.js:276 WebSocket connection to 'ws://myserver.local:8123/api/frigate/frigate/jsmpeg/birdseye?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwZWU4OGRkZjc4ZmM0MGM1ODllMzk1YmM2MDIyMWUyNCIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9qc21wZWcvYmlyZHNleWUiLCJwYXJhbXMiOnt9LCJpYXQiOjE2Nzg0MjU1NTEsImV4cCI6MTY3ODUxMTk1MX0.4mO8-YYOKSG_qOBRKkRfbqdSLYCoNLSni9qCvLd0AO8' failed: Invalid frame header
e.start @ frigate-hass-card.js:276
```

I have the birdseye configured as:

```
  - title: Home
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: birdseye
            frigate:
              camera_name: birdseye
              url: http://myserver.local:5000/
            live_provider: frigate-jsmpeg
          - camera_entity: camera.garage
...
```

I am using these images:

```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED       STATUS          PORTS                                                                                  NAMES
db832ae7a55e   ghcr.io/home-assistant/home-assistant:stable   "/init"                  3 hours ago   Up 3 hours                                                                                             HomeAssistant
c4b7789ce37f   ghcr.io/blakeblackshear/frigate:dev-e8d8cc4    "/init"                  3 hours ago   Up 43 minutes                                                                                          frigate
```

I am not sure how to resolve this issue. Please let me know if I need to share additional information.
