### ISSUE TITLE
Allow to hide media player interface and provide a mute/unmute button in menu bar

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#973]
**Is your feature request related to a problem? Please describe.**
One of the features that I like about the WebRTC card is that it allows me to disable Chrome's embedded player UI and instead provide a very minimal interface that I can interact with.

This is my WebRTC config:

```yaml
webrtc_card:
  muted: true
  ui: true
  mode: webrtc
  style: >
    .mode {display: none}
    .fullscreen {display: none}
```

As you can see, the only button left is the mute/unmute one:

https://user-images.githubusercontent.com/29582865/221747451-484da914-92ac-4dc8-8cd3-c2961b2b8bf6.mp4

**Describe the solution you'd like**
It would be great if I could achieve a similar effect without having to use WebRTC Card for it. If I could place the mute/unmute button in the menu bar, it would look so much better (at least in my mind).

**Describe alternatives you've considered**
I can keep using the WebRTC card, but currently my main issue is https://github.com/dermotduffy/frigate-hass-card/issues/923 (I really enjoy `show_image_during_load`'s smoothness), and I feel like it can break very frequently.

For some reason I believe that not using it would make Frigate Card has a better control of the live view, and I like this idea.

**Additional context**
Let me know what you think. Maybe I'm overthinking? Also, I don't know how difficult it would be to implement such a feature.

Some suggestions I have around the mute/unmute button though:

- It should be colored if unmuted, uncolored if muted
- It should only show up if media is loaded
- It could also appear for the media browser if users want, although I think it should not appear by default (the player UI is intended there by most users, I guess)
- Perhaps a new query param to allow to control this? Useful for doorbell automations like: show doorbell cam in full screen with audio unmuted.
- It should be detected from the media (some cameras hasn't audio), but if that's too difficult, maybe it should be configurable per camera?

**Comment by dermotduffy** [comment]
[Example in documentation](https://github.com/dermotduffy/frigate-hass-card/tree/dev#using-menu-based-video-controls-instead-of-browser-builtin-controls).

Will be in the next build.

**Comment by felipecrs** [comment]
This is awesome!!!
