### ISSUE TITLE
ERROR in HA logs: `Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')`

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#994]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

4.1.0 latest

**Last working release (if known):**

N/A

**Browser and Operating System:**

Chrome Windows

**Description of problem:**

I noticed this error in my HA logs:

```
Logger: frontend.js.latest.202303020
Source: components/system_log/__init__.py:254
First occurred: 4:13:48 PM (8 occurrences)
Last logged: 10:42:57 PM

https://<ha>/local/custom/frigate-hass-card/live-go2rtc-22be1b6b.js:1:3206 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
https://<ha>/frontend_latest/core.e355b7ab.js:1:9854 Uncaught Error: Suspend promise not set
```

So, I'm just wondering if there is something that can be done about it. I notice that sometimes the go2rtc player can't pick up after resuming an idle page, maybe this error is related.

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

**Comment by dermotduffy** [comment]
Thanks.

The card itself is not adding any event listeners in go2rtc code, so it might be coming from the library underneath.

> I notice that sometimes the go2rtc player can't pick up after resuming an idle page, maybe this error is related.

i.e. you leave the page alone for a while, come back, and it doesn't resume / reset into a useful state?

**Comment by felipecrs** [comment]
https://user-images.githubusercontent.com/29582865/223010596-82ec2af2-fb01-494f-80cd-fc8301b18094.mp4

Here is an example. I can trigger it ~somewhat easily when moving the window across different monitors.

**Comment by dermotduffy** [comment]
Don't suppose you can get more of a stacktrace, or at least what line the `addEventListener` call is on?

**Comment by felipecrs** [comment]
Well, in fact this error didn't show up im my HA logs while recording and showing the video in live, thus I believe the error has no relationship to the symptom that I mentioned.

But yes, I'll build the card with development as environment and let it run for some time.

**Comment by felipecrs** [comment]
Ok, the error originally reported didn't show up anymore so far, so I will close this issue and reopen if necessary.

However the separate problem of the media player not loading sometimes still happens, but I'll open a separate issue.
