### ISSUE TITLE
Detected integration that calls media_source.async_resolve_media without passing an entity_id

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#995]
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 01:59:03 (1 occurrences)
Last logged: 01:59:03

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")
```

_Originally posted by @felipecrs in https://github.com/dermotduffy/frigate-hass-card/issues/941#issuecomment-1435871154_

This issue appeared back in my logs, so I'm reporting it. There is no direct mention of the Frigate Card, but to the best of my guessing abilities, I think it comes from here.

**Comment by dermotduffy** [comment]
This is an actually an issue with HA core itself. Right now there is no way to pass the entity_id in via websocket, despite it complaining that it's not passed in! On a fresh HA restart, you can just use the media browser (no card) and you'll get the same message.

Once the websocket supports passing the target entity_id in, we can do something on this end.

Related PR on the HA side: https://github.com/home-assistant/core/pull/87458

**Comment by dermotduffy** [comment]
Related PR: https://github.com/home-assistant/core/pull/90897

**Comment by dermotduffy** [comment]
This was fixed on the HA side in a way that requires no change to the card \o/
