### ISSUE TITLE
go2rtc and webrtc-card providers do not correctly handle DOM disconnection

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#996]
https://user-images.githubusercontent.com/29582865/223010596-82ec2af2-fb01-494f-80cd-fc8301b18094.mp4

Here is an example. I can trigger it ~somewhat easily when moving the window across different monitors.

_Originally posted by @felipecrs in https://github.com/dermotduffy/frigate-hass-card/issues/994#issuecomment-1455369261_

---

Absolutely nothing shows up in any logs about it.

**Comment by dermotduffy** [comment]
[As discussed on discord this is almost certainly related to incorrect player behavior when the DOM is disconnected and reattached. This bug can be triggered by changing Home Assistant dashboard 'tabs', which uses disconnection/reattached of DOM]
